### ISSUE TITLE
IMP - SDD for Purchase and Subcontracting

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#10]
Dear Team,

Purchase and Subcontracting *Solution Definition Document*(SDD) Preparation Process.

Thanks and Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Dear Sir,

Purchase and subcontracting SDD ver 1.0 for your reference.

SDD :[01_JCIPL_Purchase and Sub contracting SDD_Ver 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3328822/01_JCIPL_Purchase.and.Sub.contracting.SDD_Ver.1.0.docx)

Thanks and Regards,
M.Maheshwran

**Comment by astpl1998** [comment]
In Currency include EUR
Include GMBH Purchase as seperate section
Try the solution suggested for Pre gr, Suggest only base reports to a maximum extent

**Comment by maheshwaran-m** [comment]
Dear Sir,

Above mentioned Points are modified and added In Purchase and Subcontracting SDD V 1.0. Pre-GR function its there once i ll check and Provide comment in Updated SDD.

SDD : [01_JCIPL_Purchase and Sub contracting SDD_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3349043/01_JCIPL_Purchase.and.Sub.contracting.SDD_V.1.0.docx)

regards,
M.Maheshwaran.

**Comment by maheshwaran-m** [comment]
Dear Team,

Updated SDD for Purchase and Sub contracting V 1.0 for your reference.

SDD : [01_JCIPL_Purchase and Sub contracting SDD_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3375787/01_JCIPL_Purchase.and.Sub.contracting.SDD_V.1.0.docx)

@raju sir: Kindly Review Open points in SDD.

Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Dear Team,

Updated SDD for Purchase and Sub contracting V 1.0 for your reference.

**SDD :** [01_JCIPL_Purchase and Sub contracting SDD_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3389516/01_JCIPL_Purchase.and.Sub.contracting.SDD_V.1.0.docx)

Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Dear Team,

Updated SDD for Purchase and Sub contracting all Version for your reference.

SDD : [01_JCIPL_Purchase and Sub contracting SDD_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3476790/01_JCIPL_Purchase.and.Sub.contracting.SDD_V.1.0.docx)
[02_JCIPL_Purchase and Sub contracting SDD_V 1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3476791/02_JCIPL_Purchase.and.Sub.contracting.SDD_V.1.1.docx)
[03_JCIPL_Purchase and Sub contracting SDD_V 1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3476788/03_JCIPL_Purchase.and.Sub.contracting.SDD_V.1.2.docx)
[04_JCIPL_Purchase and Sub contracting SDD_V 1.3.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3476789/04_JCIPL_Purchase.and.Sub.contracting.SDD_V.1.3.docx)

Regards,
M.Maheshwaran

**Comment by raju-kurup** [comment]
SDD issued waiting for Sign-off
