### ISSUE TITLE
IMP - Opening Balance Uploading - MFG OU

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#105]
Opening   Balance Uploading
Please furnish the details of   Opening balance

**Comment by raju-kurup** [comment]
Seperate ticket for collection, so closing this ticket.

**Comment by AkashGleen** [comment]
@raju-kurup Sir,

[MFG Live Uploaded File.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6391598/MFG.Live.Uploaded.File.zip)

**Comment by raju-kurup** [comment]
Opening Balance uploaded, so closing this ticket.
