### ISSUE TITLE
IMP - Opening Balance Uploading - ZEICON

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#107]
Opening   Balance Uploading
Please furnish the details of   Opening balance

**Comment by AkashGleen** [comment]
@raju-kurup Sir,

[FOR SUBMISSION TO RAMCO ZIECON BALANCE 31012021.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6391604/FOR.SUBMISSION.TO.RAMCO.ZIECON.BALANCE.31012021.zip)
[Initial Balance ZIECON OU.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6391605/Initial.Balance.ZIECON.OU.zip)
[Initial Entry ZIECON OU.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6391606/Initial.Entry.ZIECON.OU.zip)
[Working File Ziecon.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6391607/Working.File.Ziecon.xlsx)

**Comment by raju-kurup** [comment]
Opening balance uploaded, so closing this ticket.
