### ISSUE TITLE
IMP - Opening Balance Uploading - GMBH

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#108]
Opening   Balance Uploading
Please furnish the details of   Opening balance

**Comment by raju-kurup** [comment]
Seperate ticket for collection, so closing this ticket.

**Comment by AkashGleen** [comment]
@raju-kurup Sir,

[Initial Balance.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6391613/Initial.Balance.zip)
[Initial Entry.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6391614/Initial.Entry.zip)

**Comment by raju-kurup** [comment]
Opening balance uploaded, so closing this ticket
