### ISSUE TITLE
SMO - Scenario Showcasing - SCM 

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#11]
Scenario   Showcasing - SCM 
--

**Comment by Prabakaran92** [comment]
Dear Team,
Sample data for Scenario showcasing
[Purchase flow.sample data. scenario showcasing.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3372890/Purchase.flow.sample.data.scenario.showcasing.xlsx)

Regards,
Prabakaran A

**Comment by maheshwaran-m** [comment]
**Scenario show casing Sample Data for All Module Final sheet**

Purchase : [02_Purchase Sample Data for Scenatio Showcasing V 1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3375749/02_Purchase.Sample.Data.for.Scenatio.Showcasing.V.1.1.xlsx)

Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Scenario Show casing has been completed.

Issue has been closed.
