### ISSUE TITLE
IMP - Master Data Collection for Tool Management 

### ISSUE THREAD

**Issue by basha123456** [astpl1998/Jyoti-Ceramic#110]
Dear Sujin,

As Discussed, please collect the master data for Tool management 
[Project Management Masters Collection Format.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3624839/Project.Management.Masters.Collection.Format.xlsx)

**Comment by sujin1708** [comment]
PMSC : [Project Management Masters Collection Format.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3626265/Project.Management.Masters.Collection.Format.xlsx)

**Comment by basha123456** [comment]
Dear Sujin,

As Discussed, kindly update the master data file once you collect from the customer.

**Comment by basha123456** [comment]
MDCF format is shared with the tool room dept.

**Comment by basha123456** [comment]
MDCF received from the tool room team.

[MDCF_Item Master_RM.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4052166/MDCF_Item.Master_RM.xlsx)

**Comment by basha123456** [comment]
MDCF given to patil for data in some fields.
[MDCF_Item Master_RM.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4052863/MDCF_Item.Master_RM.xlsx)

**Comment by basha123456** [comment]
Tool room person is preparing MDCF for all sizes of materials after discussion with patil & thorat. so finalized list will come.

**Comment by basha123456** [comment]
[MDCF_Item Master_RM_ jothi tool room.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4096274/MDCF_Item.Master_RM_.jothi.tool.room.xlsx)
Tool Room has given this MDCF.

**Comment by raju-kurup** [comment]
UAT is In-progress, so closing this ticket
