### ISSUE TITLE
PPD : Material stock  Report plant wise-DCUBE

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#111]
[Production Report 27.9.2019 (1).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4469087/Production.Report.27.9.2019.1.zip)
Kindly create the PFS Material stock  Report plant wise...Format will be attached once received form client

**Comment by sujin1708** [comment]
Dear Sir,

please find the attached pfs for material stock report ...kindly review 

PFS : [PFS.Material Stock Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3728082/PFS.Material.Stock.Report_v1.0.xlsx)
Test Data : [Test data for material stock report syslos.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3728083/Test.data.for.material.stock.report.syslos.xlsx)

regards,
Sujin.M

**Comment by raju-kurup** [comment]
Karthi- please start development in DCube

**Comment by karthikeyanamitysoft** [comment]
Allocated to Anand

**Comment by sujin1708** [comment]
@anand please find the material stock report revised PFS
PFS : [PFS.Material.Stock.Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3800194/PFS.Material.Stock.Report_v1.1.xlsx)

**Comment by karthikeyanamitysoft** [comment]
Development completed.

**Comment by karthikeyanamitysoft** [comment]
Development completed

**Comment by sujin1708** [comment]
anand report not open...please 

correction required  :

Process cell description not display in input search

**Comment by Nandhineedevi** [comment]
Hi sujin,
The report rework has been completed by Anand. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
values not fetching in this report ..please check

**Comment by Nandhineedevi** [comment]
@anand has been doing the rework correction

**Comment by karthikeyanamitysoft** [comment]
@sujin test data not available

**Comment by sujin1708** [comment]
1. values fetching for all item code ..kindly put the validation against process cell to be fetch
2. Input process stage in help icon --load process stage code and description

 
![image](https://user-images.githubusercontent.com/47313592/70136614-5b4d3e00-16b2-11ea-8cc6-a359bdaa400d.png)

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The rework has been completed. Kindly check and revert back.
There is no test data to validate.

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
[test data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4143698/test.data.xlsx)

**Comment by Nandhineedevi** [comment]
Hi Mani,
The rework has been completed. Kindly check and revert back.

[MATERIAL_STOCK_POP_v1.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4163364/MATERIAL_STOCK_POP_v1.4.zip)

regards
Nandhinee Devi

**Comment by sujin1708** [comment]
values not fetching

**Comment by Nandhineedevi** [comment]
Hi Sujin,
As we discussed, Kindly update the PFS 

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@Nandhineedevi as discuss please find the updated pfs
[PFS.Material.Stock.Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4186856/PFS.Material.Stock.Report_v1.1.xlsx)

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The rework has been completed. Kindly check and revert back.

[MATERIAL_STOCK_POP_v1.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4190020/MATERIAL_STOCK_POP_v1.5.zip)

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@srinivasanbaskaran  please find the test case for material stock report..testing one completed kindly move to next level
check with multiple items.
[Material Stock Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4190053/Material.Stock.Report.xlsx)

**Comment by srinivasanbaskaran** [comment]
Manivel,

Please start test this report with multiple data & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@Nandhineedevi values not fetching
![image](https://user-images.githubusercontent.com/47313592/74624728-9b7b7300-516f-11ea-8943-7ba73ff1202a.png)

**Comment by Nandhineedevi** [comment]
hi Sujin,
The rework has been completed. Kindly check and revert back.

Regards
Nandhinee devi

**Comment by sujin1708** [comment]
@Nandhineedevi 
refer the screenshot which is  marked as red color ..values not fetching
![image](https://user-images.githubusercontent.com/47313592/75088686-e255d800-5576-11ea-88b3-c6567ca8527f.png)

Regards,
sujin.M

**Comment by Nandhineedevi** [comment]
Hi Sujin,
Kindly create new formula and check.

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@Manimahat kindly do the testing...attach the test data

**Comment by sujin1708** [comment]
check with multiple datas

**Comment by sujin1708** [comment]
@ raju sir please do the changes
Date :15/03/2020
p/po/19-20/0200 - SDST7010001 -3000 Qty (Accepted qty)
P/po/19-20/0201 - INST7010001 - 2850

p/po/19-20/202 - SDST7010001 -9000 qty
p/po/19-20/203 - INST7010001 -5950 qty
p/po/19-20/204 - INST7010001 -2800 qty

1. Batch qty fetching wrong
2. issued to press shop values shown wrong
3.  consumed qty if null should be in blank
4. while generate excel ( Following field shown unwanted)
i) RTM Mode Flag
ii) Delete Flag
5. Process cell only 5 available in system --if they create new cell that should be automatically fetch 

 
[MTS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4336762/MTS.xlsx)

regards,
sujin. M

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The rework has been completed. Kindly check and revert back.

[MATERIAL_STOCK_POP_v1.6.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4358240/MATERIAL_STOCK_POP_v1.6.zip)

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@Nandhineedevi 
please find the same data consumed qty fetching wrong
[MStock report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4362479/MStock.report.xlsx)

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The rework has been completed. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@srinivasanbaskaran kindly assign this ticket for testing2

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@sujin1708 

Data mismatches are there..PFA refer test data sheet..please take care.
[PFS.Material.Stock.Report_v1.1 (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4391991/PFS.Material.Stock.Report_v1.1.1.xlsx)

![image](https://user-images.githubusercontent.com/47315921/77731144-5d078c80-7028-11ea-85dc-abedf51ea720.png)

**Comment by sujin1708** [comment]
@raju-kurup please do the changes

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : some of the values in columns are coming wrong and some are not fetching. Correct data details are also attached

**Comment by Nandhineedevi** [comment]
Hi Sujin,
Kindly provide test data.

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@basha123456  prepare multiple test data and  check with nandhini

**Comment by basha123456** [comment]
@raju-kurup 

Sir, Report is not generating data if i put data  2nd or 3rd time. for 1st time data only report is generating and in some fields data not generating
PFS updated and highlighted in yellow.PFA.
please assign to developers.
[PFS.Material.Stock.Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4419879/PFS.Material.Stock.Report_v1.1.xlsx)
[Material stock report output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4419881/Material.stock.report.output.pdf)

**Comment by raju-kurup** [comment]
@sujin1708 : As discussed please keep this ticket with you for testing, once 113 ticket resolved then transfer to me

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction in 2 points(Last consumed qty and Batch no used), it was hold due to the ticket no :113 now that ticket is resolved.

**Comment by Nandhineedevi** [comment]
Hi Basha,
Kindly test with fresh data with spray dried stage and revert back.

Regards
Nandhinee Devi

**Comment by basha123456** [comment]
@Nandhineedevi 

As Discussed, Please find test data..for any clarification please contact me.

[material stock report data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4491351/material.stock.report.data.xlsx)

**Comment by Nandhineedevi** [comment]
Hi Basha,
The rework has been completed. Kindly check and revert back.

[test2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4501601/test2.xlsx)

Regards
Nandhinee Devi

**Comment by basha123456** [comment]
@raju-kurup 

Sir, Total stock in plant, last day consumption is not coming correctly.
batch use for this product is not fetching.
kindly assign developer to solve this.

[material stock report errors.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4510036/material.stock.report.errors.xlsx)

**Comment by raju-kurup** [comment]
@basha123456 : please give me the test data with correct data.

**Comment by basha123456** [comment]
@raju-kurup 

Sir,as discussed PFS is updated & test data is attaached.

[material stock report test data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4516728/material.stock.report.test.data.xlsx)
[PFS.Material.Stock.Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4516732/PFS.Material.Stock.Report_v1.1.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per the PFS.

**Comment by Nandhineedevi** [comment]
Hi Basha,
Please find the test data. Kindly check and revert back.

[material.stock.report.test.data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4527083/material.stock.report.test.data.xlsx)

Regards
Nandhinee Devi

**Comment by basha123456** [comment]
@raju-kurup 

Data is not fetching correctly in the report..data as per format is attached

[#111 Material stock report Test data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4534688/111.Material.stock.report.Test.data.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Data is not  coming correctly, Test data is attached for reference.  PFS has no changes.  Contact Basha for clarification.

**Comment by Nandhineedevi** [comment]
Hi Basha,
The 3rd line you have provided in test data is not valid, because it is old transaction of feb month, which is deleted by someone. Kindly Provide new test data with new PO, new batch and new transaction.

Regards
Nandhinee Devi

**Comment by basha123456** [comment]
@Nandhineedevi 

PFA of the test data.
[Material Stock report as per format.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4551125/Material.Stock.report.as.per.format.xlsx)

**Comment by Nandhineedevi** [comment]
Hi Basha,
The rework has been completed. Kindly check and revert back.
The intermediate item and its batch and date is added 

[Material.Stock.report.as.per.format (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4567870/Material.Stock.report.as.per.format.1.xlsx)
[MATERIAL_STOCK_POP_v1.8.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4567874/MATERIAL_STOCK_POP_v1.8.zip)

Regards
Nandhinee Devi

**Comment by basha123456** [comment]
@raju-kurup 

Data is not feching correctly in the report.. Fields are marked in yellow in PFS..need to review and assign for development.
System output & the correct data is attached as per the format.

[PFS.Material.Stock.Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4580200/PFS.Material.Stock.Report_v1.1.xlsx)
[Material Stock report as per format.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4580216/Material.Stock.report.as.per.format.xlsx)

**Comment by sujin1708** [comment]
@raju-kurup sir as discuss kindly move to rework

1. Input item code Search filter not working
2. Values Fetching Zig Zag way.
[PFS.Material.Stock.Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4587978/PFS.Material.Stock.Report_v1.2.xlsx)

**Comment by srinivasanbaskaran** [comment]
Team,

PFA of latest point 

![1589451204998](https://user-images.githubusercontent.com/46194039/82185907-97462980-9907-11ea-957c-e2e7705f7890.JPEG)

**Comment by sujin1708** [comment]
Dear Sir,

Please find the revised PFS..kindly review
PFS : [PFS.Material.Stock.Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4661240/PFS.Material.Stock.Report_v1.2.xlsx)
Test Case : 
[Material Stock Report Test Case - .xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4661248/Material.Stock.Report.Test.Case.-.xlsx)

**Comment by raju-kurup** [comment]
@sujin1708 : please do the workings as per the Suresh sir suggestion.

**Comment by sujin1708** [comment]
@raju-kurup As Discuss Revised PFS attached kindly Review..

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do 1 correction in this report which is highlighted in yellow colour.

**Comment by Nandhineedevi** [comment]
Hi Sujin,
Kindly provide new test data. The test data you have provide on the period of date is not valid

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@basha123456 prepare one test data and share to nandhini on urgent basis.

**Comment by basha123456** [comment]
@Nandhineedevi 

Please find the test data in the sheet TD.

[PFS.Material.Stock.Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4723449/PFS.Material.Stock.Report_v1.2.xlsx)

**Comment by Nandhineedevi** [comment]
Hi Basha,
The rework has been completed. kindly check and revert back.

[MATERIAL_STOCK_POP_v1.9.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4739385/MATERIAL_STOCK_POP_v1.9.zip)
[test output.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4739388/test.output.xlsx)

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
Values Should Fetch all batch till date
![image](https://user-images.githubusercontent.com/47313592/83987644-903a9600-a95e-11ea-824d-e9adf21e794e.png)

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The rework has been completed. Kindly check and revert back.

[MATERIAL_STOCK_POP_v2.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4744068/MATERIAL_STOCK_POP_v2.0.zip)
[test output.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4744069/test.output.xlsx)

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@srinivasanbaskaran Testing 1 Completed..kindly move to next level
PFS : [PFS.Material.Stock.Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762415/PFS.Material.Stock.Report_v1.2.xlsx)
Test Case : [Material Stock Report Test Case - .xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762416/Material.Stock.Report.Test.Case.-.xlsx)
Test Result : [Test Result_MTS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762414/Test.Result_MTS.xlsx)

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start Testing 2

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2 copleted.

[Material.Stock.Report.Test.Case.-.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4764632/Material.Stock.Report.Test.Case.-.xlsx)
[Material Stock Report TR.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4764633/Material.Stock.Report.TR.xlsx)

**Comment by srinivasanbaskaran** [comment]
Sir, 

Material Stock Report Plant wise testing has been completed. Herewith I have attached testing documents for future references.

PFS: [PFS.Material.Stock.Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4774108/PFS.Material.Stock.Report_v1.2.xlsx)

DELIVERABLES: [MATERIAL_STOCK_POP_v2.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4774109/MATERIAL_STOCK_POP_v2.0.zip)

TESTCASE1: [Material.Stock.Report.Test.Case1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4774111/Material.Stock.Report.Test.Case1.xlsx)

TEST RESULT1: [Test.Result_MTS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4774114/Test.Result_MTS.xlsx)

TESTCASE2: 
[Material.Stock.Report.Test.Case2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4774116/Material.Stock.Report.Test.Case2.xlsx)

TEST RESULT2: [Material.Stock.Report.TR.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4774112/Material.Stock.Report.TR.xlsx)

**Comment by sujin1708** [comment]
@Nandhineedevi kindly apply the below mentioned logic

1) if minimum qty is greator than stock qty (WIP(based on wip report logic)+Godown )report should not be seen
2) Production variaence check list has to be added.

**Comment by sujin1708** [comment]
@Nandhineedevi please find the updated PFS kindly apply the logic Batch user product & remarks
[PFS.Material.Stock.Report_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5134248/PFS.Material.Stock.Report_v1.3.xlsx)

**Comment by Nandhineedevi** [comment]
[MATERIAL_STOCK_POP_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5173076/MATERIAL_STOCK_POP_v2.1.zip)

**Comment by AkashGleen** [comment]
@sujin1708 

Material Stock Report Plant Wise Testing 1 Completed Kindly Check & Update.

[Test Result v1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5305497/Test.Result.v1.zip)

[Material.Stock.Report.Test.Case.- (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5305499/Material.Stock.Report.Test.Case.-.1.xlsx)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Sujin, 

Kindly start Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Test data and result are atatched.

Test Data: 
[Test.Data.for.Material.Stock.Report.Syslos.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5428662/Test.Data.for.Material.Stock.Report.Syslos.xlsx)


Test Result: 
[Test.Result.for.Material.Stock.Report.Syslos.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5428667/Test.Result.for.Material.Stock.Report.Syslos.xlsx)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
@sujin1708 ,

Kindly check this report & Assign me for the final closure

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
PFS : [PFS.Material.Stock.Report_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5646570/PFS.Material.Stock.Report_v1.3.xlsx)
Deliverables : [MATERIAL_STOCK_POP_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5646571/MATERIAL_STOCK_POP_v2.1.zip)
Test case1 : [Material.Stock.Report.Test.Case1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5646572/Material.Stock.Report.Test.Case1.xlsx)
Test Result : [Test.Result_MTS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5646573/Test.Result_MTS.xlsx)
[Material.Stock.Report.Test.Case2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5646574/Material.Stock.Report.Test.Case2.xlsx)
[Material.Stock.Report.TR.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5646575/Material.Stock.Report.TR.xlsx)

**Comment by sujin1708** [comment]
@raju-kurup Material Stock Report Plant wise testing has been completed. Herewith I have attached testing documents kindly close the ticket

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by Nandhineedevi** [comment]
Deployed in Live Server.

[Final_live_import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5770166/Final_live_import.zip)

**Comment by sujin1708** [comment]
deployment completed..kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
