### ISSUE TITLE
PPD : Daily production summary/ rejection report stage wise- Press shop

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#115]
kindly create PFS for Daily production summary/ rejection report stage wise Report ..format will be attached once received from client.

**Comment by sujin1708** [comment]
Dear sir,
please find the attached pfs -daily production summary report..kindly review
PFS : [PFS.Daily  Production summary report_V1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3820138/PFS.Daily.Production.summary.report_V1.0.xlsx)
Regards,
sujin.m

**Comment by raju-kurup** [comment]
Karthi - Please start the development

**Comment by sujin1708** [comment]
@ raju as discuss with developers this report not possible to develop in Dcube

@Nandhineedevi kindly start the development in EDK..please refer the attached PFS
PFS : [PFS.Daily  Production summary report_V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3846084/PFS.Daily.Production.summary.report_V1.1.xlsx)

regards,
sujin.M

**Comment by raju-kurup** [comment]
Karthi - Please do this in RDW

**Comment by karthikeyanamitysoft** [comment]
DEar Manivel,

Kindly start DW desing and coding.
EDK desing completed by badam .

Regards,
Karthi

**Comment by badamnarendra028** [comment]
[JCIE - 97.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3903968/JCIE.-.97.zip)

**Comment by karthikeyanamitysoft** [comment]
Assinged to Narendranath.
REgards,
Karthi

**Comment by karthikeyanamitysoft** [comment]
Dear Sujin,

As we discussed kindly provide the Logic for Shift quantity.

Regards,
Karthi

**Comment by sujin1708** [comment]
Hi,

please refer the pfs for shift logic..

[PFS.Daily  Production summary report_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4018817/PFS.Daily.Production.summary.report_V1.2.xlsx)

Regards,
sujin.M

**Comment by karthikeyanamitysoft** [comment]
Dear Sujin,

Kindly test and send me the test data
REgards,
Karthi

**Comment by sujin1708** [comment]
@narendara 
1. input field - add category code

**Comment by sujin1708** [comment]
@Naren rao :
Following things need to correct  
1. Need Category code in input filter
2. item code input field remove the unwanted sysmbol #
3. Period From and period to alignment 
4. Product code not fetching
5. product description not fetching
6. Report field headings not display

Regards,
sujin. M

**Comment by badamnarendra028** [comment]
kindly give test data

**Comment by badamnarendra028** [comment]
kindly give test data for all fields remaining

**Comment by sujin1708** [comment]
@badamnarendra028 
1. values  loaded multiple line...should generate day wise in one line
2. if variant nill should come blank--remove ##
3. report should generate pdf & excel
4. remove the decimal should come only eg : 1000.00
5. period from & to date alignment should proper

![image](https://user-images.githubusercontent.com/47313592/75967838-6a7e9a80-5ef2-11ea-8c1c-d2ebbeb48b8e.png)

![image](https://user-images.githubusercontent.com/47313592/75967896-841fe200-5ef2-11ea-91b1-458df93f057c.png)

regards,
Sujin.M

**Comment by sujin1708** [comment]
@badamnarendra028 
values should fetch in one line & unitech trasfer details not fetching
![image](https://user-images.githubusercontent.com/47313592/76057391-6e1c2b00-5f9f-11ea-8a4d-06187589c66c.png)

**Comment by badamnarendra028** [comment]
report completed upto now what data u given 
kindly  give test data for remaing fields
and logic for remaining fields

**Comment by sujin1708** [comment]
![image](https://user-images.githubusercontent.com/47313592/77056087-f535be00-69f7-11ea-87cb-0b84d11367de.png)

1, item description not fetching
2, period from and to date not fetching

**Comment by sujin1708** [comment]
1. do the alignment changes in input filter
2. Category code / Process cell/process stage/ item code description should fetch 
3. By default blank should display in the category code
4. include the variant field 
5. Description not fetching
6. if there is no variant values should shown as blank
 ![image](https://user-images.githubusercontent.com/47313592/78256639-6f953080-7516-11ea-92b4-3f2bdd61c887.png)
![image](https://user-images.githubusercontent.com/47313592/78257526-9738c880-7517-11ea-88a8-c6f5ddf93998.png)

**Comment by raju-kurup** [comment]
please attach the exact test data as your result and mention what is wrong and what is the correct data.

**Comment by sujin1708** [comment]
@raju sir find the updated pfs ..kindly review this
[PFS.Daily  Production summary report_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4434450/PFS.Daily.Production.summary.report_V1.2.xlsx)

**Comment by raju-kurup** [comment]
@sujin1708 : please work out the item logic and revert back.

**Comment by sujin1708** [comment]
@raju-kurup please find the PFS ..kindly review
[PFS.Daily  Production summary report_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4444995/PFS.Daily.Production.summary.report_V1.2.xlsx)

**Comment by raju-kurup** [comment]
@sujin1708 : please create 5 separate tickets for each division and revert back

**Comment by sujin1708** [comment]
[PFS.Daily  Production summary report_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4448252/PFS.Daily.Production.summary.report_V1.2.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please start the development, test case will be given by sujin today

**Comment by raju-kurup** [comment]
Wrongly closed

**Comment by badamnarendra028** [comment]
kindly update pfs

**Comment by sujin1708** [comment]
@raju-kurup please find the updated PFS for your reference..kindly review

[PFS.Daily  Production summary report_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4527013/PFS.Daily.Production.summary.report_V1.2.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Upto Green production data are coming correct, balance to be checked. Test Data attached in PFS itself. Badam has done this report

**Comment by sujin1708** [comment]
@raju sir..Please find the updated PFS.kindly review
[PFS.Daily  Production summary report_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4586612/PFS.Daily.Production.summary.report_V1.2.xlsx)

**Comment by badamnarendra028** [comment]
JCIE-269 rtrack raised

**Comment by badamnarendra028** [comment]
[pressshop.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4588039/pressshop.pdf)
completed kindly check

**Comment by sujin1708** [comment]
@srinivasanbaskaran  Testing 1 cpmpleted..please check
[PFS.Daily  Production summary report_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4602585/PFS.Daily.Production.summary.report_V1.2.xlsx)

[Test Result_Press Shop.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4602614/Test.Result_Press.Shop.xlsx)

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly Start Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan

**Comment by basha123456** [comment]
@badamnarendra028 

Values are not fetching properly as discussed. actual & output attached. please correct.

[03_Quality.Final_Inspection_Report_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4700981/03_Quality.Final_Inspection_Report_PFS_v1.6.xlsx)
[Daily Production Summary TR - Press shop.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4700991/Daily.Production.Summary.TR.-.Press.shop.xlsx)

**Comment by badamnarendra028** [comment]
kindly update crt test data

**Comment by sujin1708** [comment]
@badam values not fetching properly
PFS : [PFS.Daily  Production summary report_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762391/PFS.Daily.Production.summary.report_V1.2.xlsx)

**Comment by badamnarendra028** [comment]
completde check and revert

**Comment by sujin1708** [comment]
@srinivasanbaskaran Testing1 completed ..kindly move to next level
[Test Result_Press Shop.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4823296/Test.Result_Press.Shop.xlsx)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 2 completed. Please ref the Attached doc.

Test Case : [Daily production Summary report_Test Case_Press shop.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4843910/Daily.production.Summary.report_Test.Case_Press.shop.xlsx)

Test Result :  [daily Production summary report _press shop.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4843912/daily.Production.summary.report._press.shop.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@srinivasanbaskaran Testing 2 completed kindly move to next level

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Daily Production Summary / Rejection Report testing has been completed. Herewith I have attached the Testing documents for the future references.

PFS: [PFS.Daily.Production.summary.report_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4900973/PFS.Daily.Production.summary.report_V1.2.xlsx)

DELIVERABLES:
 
TESTCASE1 & TEST RESULT1: [Test.Result_Press.Shop (2).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4900976/Test.Result_Press.Shop.2.xlsx)

TESTCASE2: [Daily production Summary report_Test Case_Press shop.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4843910/Daily.production.Summary.report_Test.Case_Press.shop.xlsx)

TEST RESULT2:  [daily Production summary report _press shop.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4843912/daily.Production.summary.report._press.shop.pdf)

**Comment by srinivasanbaskaran** [comment]
@badamnarendra028 ,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[jcie-297 (2).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4901301/jcie-297.2.zip)
attached

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Daily Production Summary / Rejection Report testing has been completed. Herewith I have attached the Testing documents for the future references.

PFS: [PFS.Daily.Production.summary.report_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4900973/PFS.Daily.Production.summary.report_V1.2.xlsx)

DELIVERABLES: [jcie-297.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4904182/jcie-297.2.zip)
 
TESTCASE1 & TEST RESULT1: [Test.Result_Press.Shop (2).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4900976/Test.Result_Press.Shop.2.xlsx)

TESTCASE2: [Daily production Summary report_Test Case_Press shop.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4843910/Daily.production.Summary.report_Test.Case_Press.shop.xlsx)

TEST RESULT2:  [daily Production summary report _press shop.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4843912/daily.Production.summary.report._press.shop.pdf)

**Comment by sujin1708** [comment]
@badam please find the attached test data values not fetching properly
[Reporting Qty shift wise PO 0356.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5180696/Reporting.Qty.shift.wise.PO.0356.xlsx)
[Test Data_press Shop.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5180698/Test.Data_press.Shop.xlsx)

**Comment by badamnarendra028** [comment]
[jcie-297 (3).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5183988/jcie-297.3.zip)
completed kindly check and revert

**Comment by Manimahat** [comment]
@eafaisal ,

Kindly Start the Testing 1 Process & prepare Test case as per our format.

Regards,
Manivel A

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 1 is completed.
Kindly check.

Test Data : 
[Daily_Prodn_Summary.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5216436/Daily_Prodn_Summary.xlsx)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Sujin,

Kindly start the Testing 2 & Prepare the Testing Documents 

And confirm that, this report satisfied the Customer requirements or not.. 

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[jcie-297 (4).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5252206/jcie-297.4.zip)

**Comment by sujin1708** [comment]
@raju-kurup please find the attached pfs kindly review and move to badam
[PFS.Daily  Production summary report_V1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5382438/PFS.Daily.Production.summary.report_V1.3.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as mentioned in PFS, Badam has done this report.

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The report is completed. Kindly check and revert back.

[dpsr_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5547229/dpsr_v2.1.zip)

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
PFS : [PFS.Daily.Production.summary.report_V1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5682399/PFS.Daily.Production.summary.report_V1.3.xlsx)
[dpsr-v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5682400/dpsr-v2.2.zip)
[Press.Shop_TestCase.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5682401/Press.Shop_TestCase.xlsx)
[Test.Data.Working.-.Press.Shop.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5682402/Test.Data.Working.-.Press.Shop.xlsx)
[Test.Result_Press.Shop.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5682403/Test.Result_Press.Shop.xlsx)

**Comment by sujin1708** [comment]
Testing 2 completed customer agreed report status in green..plz close the ticket

**Comment by sujin1708** [comment]
@karthikeyanamitysoft please find the updated PFS ..kindly apply the current stock logic in daily production summary report -press shop
[PFS.Daily.Production.summary.report_V1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5738217/PFS.Daily.Production.summary.report_V1.4.xlsx)

**Comment by sujin1708** [comment]
@Nandhineedevi kindly deploy the report in live

**Comment by Nandhineedevi** [comment]
Completed moving into Live Server.

[dpsr.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6606845/dpsr.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployed in Live server .Kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
