### ISSUE TITLE
JPA : Jyoti stage & process unit wise multiple item production screen -RDW

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#121]
kindly create the PFS for Jyoti stage & process unit wise multiple item production screen
[Stage Based Reporting - Multiple Production Order Based.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3634489/Stage.Based.Reporting.-.Multiple.Production.Order.Based.xlsx)

**Comment by sujin1708** [comment]
[Stage base Reporting.Automation.-.PFS_V1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3647612/Stage.base.Reporting.Automation.-.PFS_V1.xlsx)

**Comment by sujin1708** [comment]
@ezhil & karthick please find the attachment
[Report Production Stage based multiple item.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3766952/Report.Production.Stage.based.multiple.item.xlsx)

**Comment by sujin1708** [comment]
@ezhil please find the attached PFS for your refernece

 PFS : [Stage base Reporting.Automation.-.PFS_V1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3786993/Stage.base.Reporting.Automation.-.PFS_V1.xlsx)

Regards,
sujin.M

**Comment by sujin1708** [comment]
@Ezhilarasi-SP please refer the updated PFS
[Stage base Reporting.Automation.-.PFS_V2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3800415/Stage.base.Reporting.Automation.-.PFS_V2.xlsx)

**Comment by sujin1708** [comment]
@Nandhineedevi please find the attachment design changes for your reference
[Design changes.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4008984/Design.changes.xlsx)

**Comment by sujin1708** [comment]
@karthick please find the attachment stage base reporting logic for create & Authorize
[Logic Create_Authorize_Edit-v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4009000/Logic.Create_Authorize_Edit-v1.2.xlsx)

**Comment by srinivasanbaskaran** [comment]
Dear Team,

PFA Latest Open Points 


1. Hard   allocation based  production issue   logic to be fix in automation screen
2. Stage based report screen alllignment changes
3. Transcation date should be system date in the multiline   -header should be default date 
4. Allow one day back date to consider calendar
5. Different process cel1 -firing stage through report the common   production order

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
development completed

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly test this report & Prepare the Testing Document with new format 

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
this is not report new screen

**Comment by sujin1708** [comment]
PFS :[Stage.base.Reporting.Automation.-.PFS_V4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4163323/Stage.base.Reporting.Automation.-.PFS_V4.xlsx)

**Comment by basha123456** [comment]
@srinivasanbaskaran : screen is designed as per PFS..kindly check and move

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly prepare the Testing Document for this screen. 

Update & Revert.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Sample Testcase attached For your References...

Sample: [Kanam Planning Information Test case_v1.14.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4169736/Kanam.Planning.Information.Test.case_v1.14.xlsx)

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasan: Screen is tested and testing results are attached in the document with screenshots. 
[Stage.base.Reporting.Automation.-.PFS_V4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4172241/Stage.base.Reporting.Automation.-.PFS_V4.xlsx)

**Comment by srinivasanbaskaran** [comment]
Sujin, 

Kindly prepare the Testing documents for Testing 1 ( done by Sujin )  & Testing 2 ( Basha ) based on the Sample Document attached . 

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@karthikeyanamitysoft to be fix this
![image](https://user-images.githubusercontent.com/47313592/77610316-5e618800-6f48-11ea-90f4-8e2563a34cc3.png)

**Comment by sujin1708** [comment]
@raju-kurup  kindly review the PFS
[Stage.base.Reporting.Automation.-.PFS_V4 26.03.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4385063/Stage.base.Reporting.Automation.-.PFS_V4.26.03.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as discussed with Sujin

**Comment by karthikeyanamitysoft** [comment]
Dear JP,

Screen design is completed by Nandini,
coding need to add..

Note : only add the newly added control in the existing sp's, Alredy existing logic should not change.

Regards,
Karthi

**Comment by Jeyapriyat** [comment]
@sujin1708 

changes completed,kinldly check

**Comment by sujin1708** [comment]
1. kindly check the alligment
2. write logic for description fetching
3. loss id not fetching

**Comment by raju-kurup** [comment]
@sujin : please do the testing mentioned by Jeyapriya and karthi and list the correction to be done and forward the ticket to me

**Comment by sujin1708** [comment]
@raju sir1. Multiple Tran no and multiple qc not generated
2. write logic for description fetching (github no -235)
3. loss id not fetching
4. Access control codification 
5. created time & modified time -coding to be handled
6. PPD : Transaction   date should allow one day back date to fix.
7. Tool logic to be discuss with --jyoti

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As discussed with sujin and suresh sir, please proceed further correction.

**Comment by sujin1708** [comment]
please find the below points and close earlier
1.  in create lot no not Generating ( po no : p/po/20-21/0056)
2. po has 3 line item  one item not shown and first two items shown negative values
3. 2 items authorized in green production stage it will not shown in next stage
4. in view cumulative reported qty shown wrong
[Automation bugs.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4457810/Automation.bugs.xlsx)

**Comment by sujin1708** [comment]
SP need to run --for tool combo
[jcie-249.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4457820/jcie-249.zip)

**Comment by sujin1708** [comment]
1. Process unit not loading properly -while select the stage
2. in view multiline only 7 po loading but in header so many po loading in po combo.
![image](https://user-images.githubusercontent.com/47313592/80368564-8c6d1b80-88aa-11ea-9fe2-6b7bfd4bde03.png)

**Comment by karthikeyanamitysoft** [comment]
Please check the Combo reload for process unit on process stage and process cell

Regards,
Karthi

**Comment by sujin1708** [comment]
kindly do the screen alignment  like below screenshot in automation screen.. 
![image](https://user-images.githubusercontent.com/47313592/80522008-85790280-89a9-11ea-8d00-db0131bb98cc.png)

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The process unit combo against the process stage has been completed. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@karthikeyanamitysoft 
If possible kindly do the alignment
![image](https://user-images.githubusercontent.com/47313592/80997406-e3e92980-8e5e-11ea-8f6b-09aa5c402016.png)

while open new work area.. below error message came 
![image](https://user-images.githubusercontent.com/47313592/80997553-1b57d600-8e5f-11ea-975a-cd3bbc93788c.png)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the alingment as mentioned by Sujin.

**Comment by sujin1708** [comment]
@please process unit should display against the process stage

![image](https://user-images.githubusercontent.com/47313592/81321006-ad561d80-90af-11ea-8efb-96c9eee2f5fc.png)

**Comment by Nandhineedevi** [comment]
Hi sujin,
The issue has been resolved. Kindly check and revert back.
All the combo reload has been updated as before. 

![image](https://user-images.githubusercontent.com/52193780/81524944-b590b000-9370-11ea-89c5-621aa9333863.png)

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@basha kindly test the below

1.  Parameter log value updation
2. Check the All the action based Functionalities

create
Edit
Delete
Authorize
view

**Comment by sujin1708** [comment]
@raju Sir..,please find the revised PFS for your reference..kindly review
PFS : [Stage.base.Reporting.Automation.-.PFS_V5 21.05.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4661371/Stage.base.Reporting.Automation.-.PFS_V5.21.05.xlsx)
Design Changes : [Design changes.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4661372/Design.changes.xlsx)

**Comment by raju-kurup** [comment]
@sujin1708 : please get the confirmation mail from Mr.Gautam and proceed further.

**Comment by sujin1708** [comment]
@raju-kurup As Discuss with MR.Gautam on 25.05.2020 we agreed to inculde the 3 new fields in the automation screen..kindly move to developers.

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : we want to add 3 coloumns in this reporting screen. please do the correction as mentioned in PFS which is highlighted in yellow.  Nandhinee has done the designing.

**Comment by karthikeyanamitysoft** [comment]
Dear Jeyapriya,

Kindly do the EDK desing change and raise rtrack, only need to add 3 column in multiline.

Note : combo reload should not change.
Regards,
Karthi

**Comment by Jeyapriyat** [comment]
@karthikeyanamitysoft 

design changes completed.
rtrack id: JCIE-286

**Comment by Jeyapriyat** [comment]
@karthikeyanamitysoft 
deliverables attached:
[jcie-286.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4705406/jcie-286.zip)

**Comment by karthikeyanamitysoft** [comment]
Dear Jeyapriya,

Kindly deploy the deliverables and do the change in BACK END SP.
Regards,
Karthi

**Comment by basha123456** [comment]
@raju-kurup 

For Tool & Tool Description, PFS is updated. kindly review.
[Stage.base.Reporting.Automation.-.PFS_V5.21.05.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4716549/Stage.base.Reporting.Automation.-.PFS_V5.21.05.xlsx)

**Comment by Nandhineedevi** [comment]
Hi Karthi Na,
Deployed the deliverables and updated sp from backend.
I have done the below changes.

I have added column column fire_date, fire_time, operator_hrs in below tables.

mul_process_prod_amity_edit
mul_process_prod_amity_delete    
mul_process_prod_amity
	
In all grid sp, I have included the below statement in select query sp

fire_date	'FIRE_DATE',
fire_time	'FIRE_OUUT_TIME',
operator_hrs	'OPERATOR_HOURS_ADD' 

In gs sp, In header I have included the below statement

@fire_date                     	date,
@fire_ouut_time             hrtime,
@operator_hours_add   	desc255,

Regards
Nandhinee Devi

**Comment by basha123456** [comment]
@raju-kurup 

sir, kindly allocate this ticket to developemnt team for Tool combo & description.

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction of Tool Name and Tool Description in multiline.

**Comment by Nandhineedevi** [comment]
Hi Basha,
The Tool combo and Description has been completed. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Tool Combo & Tool Description is loading correctly for Green Production stages. kindly move to testing2
[Tool Loading in Reporting screen - TR.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4799932/Tool.Loading.in.Reporting.screen.-.TR.xlsx)

**Comment by srinivasanbaskaran** [comment]
Sujin,

Kindly start the Testing 2 & Prepare the TEsting documents 

**NOTE**

Kindly get the full KT from Basha on which part he handled in this Report

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@karthikeyanamitysoft while authorize face below error..kindly check on priority basis

![image](https://user-images.githubusercontent.com/47313592/85189292-5907a580-b2cb-11ea-858e-a7eb4db91d61.png)

**Comment by sujin1708** [comment]
@karthikeyanamitysoft refer jcie-205

![image](https://user-images.githubusercontent.com/47313592/85189346-e9de8100-b2cb-11ea-932d-1f11f0275648.png)

**Comment by karthikeyanamitysoft** [comment]
what is this screen shot
how handling..

**Comment by sujin1708** [comment]
@karthikeyanamitysoft please refer above screen shot..while open new work area we face internal server error for that ramco provide one fix ..kindly deploy the same and confirm.

**Comment by karthikeyanamitysoft** [comment]
Dear Sujin,

There is no Fix provided for the issue, they told upgrade to lates-d Cu
![image](https://user-images.githubusercontent.com/40713407/85999926-7b679480-ba2a-11ea-9466-058614cc538b.png)

Regards,
Karthi

**Comment by sujin1708** [comment]
@raju-kurup screen delivered to customer ..please close the ticket

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Being customer given clearance, we are closing this ticket

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by Nandhineedevi** [comment]
Latest Deliverables

[Final Live Import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5963414/Final.Live.Import.zip)

**Comment by Jeyapriyat** [comment]
@sujin1708 
deployment completed in live server.
![image](https://user-images.githubusercontent.com/37791285/108191468-2901f200-7139-11eb-95e3-8b05e9efa1d3.png)

**Comment by sujin1708** [comment]
@raju-kurup Deployed in Live server .Kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.

**Comment by sujin1708** [comment]
@raju-kurup While authorize facing error no record found 

![image](https://user-images.githubusercontent.com/47313592/127819850-714c76ee-21f2-4e13-9221-5392d213c301.png)
