### ISSUE TITLE
PPD : Tool production quantity Report

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#122]
kindly create the PFS for Tool production Qty

**Comment by sujin1708** [comment]
[Doc-1141.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3650643/Doc-1141.pdf)

**Comment by sujin1708** [comment]
kindly start the PFS

**Comment by sujin1708** [comment]
Duplicate

**Comment by raju-kurup** [comment]
being duplicate so closed
