### ISSUE TITLE
PPD : Car No Based Fire No Trigger logic -Testing-Trigger

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#123]
Karthick kindly fix logic as per the discussion with MR.Suresh Sir

[FireNo Logic.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3650741/FireNo.Logic.xlsx)

**Comment by karthikeyanamitysoft** [comment]
Dear Sujin

Kindly provide full detail.

Regards,
Karthi

**Comment by sujin1708** [comment]
Duplicate

**Comment by sujin1708** [comment]
# github no 69
