### ISSUE TITLE
PPD : Production Order Tollerence scenario checking-Trigger

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#125]
To be  check in Production Order - Edit Control Receipt - Parameter Details, Will Handle In Trigger

**Comment by sujin1708** [comment]
as discuss with jyoti Production team & Sales production order tolerance  user should enter manually.

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by sujin1708** [comment]
@raju-kurup Trained to user kinldy close the ticket

**Comment by raju-kurup** [comment]
Training given, so closing this ticket
