### ISSUE TITLE
TRG : Purchase and Subcontracting Handout document Preparation

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#126]
Dear Sir, 

Please find the attached Purchase and subcontracting handout document for your reference.

**P&S Handout Document :** [01_JCIPL_Purchase and Subcontracting Handout.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3682536/01_JCIPL_Purchase.and.Subcontracting.Handout.docx)

Thanks Regards,
M.Maheshwaran

**Comment by srinivasanbaskaran** [comment]
Hi,

Kindly find the updated Handout for Purchase & Subcontract

HANDOUT: 
[01_JCIPL_Purchase & Subcontracting - Handout_v1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3686370/01_JCIPL_Purchase.Subcontracting.-.Handout_v1.1.docx)

Regards,

Srinivasan Baskaran

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the attached Purchase and Sub contracting Handout Final Document For your reference.

**01_Handout Document :** [01_JCIPL_Purchase and Subcontracting Handout Document.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3689021/01_JCIPL_Purchase.and.Subcontracting.Handout.Document.docx)
**02_Handout PDF :** [02_JCIPL_Purchase and Subcontracting Handout Document.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3689024/02_JCIPL_Purchase.and.Subcontracting.Handout.Document.pdf)

Thanks and **Regards,**
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the attached Purchase and Sub contracting Handout Final Document For your reference.

**01_Handout Document :**[Uploading 01_JCIPL_Purchase and Subcontracting Handout Document V 1.1.docx…]()
**02_Handout PDF :** [Uploading 01_JCIPL_Purchase and Subcontracting Handout Document V 1.1.pdf…]()


Thanks and Regards,
M.Maheshwaran
