### ISSUE TITLE
TRG : Inventory and PICC Handout Preparation

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#127]
Dear Sir,

Please find the attached Inventory and PICC handout document for your reference.

**I&P Document :** [01_JCIPL_Inventory and PICC Handout V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3832850/01_JCIPL_Inventory.and.PICC.Handout.V.1.0.docx)
 
@srinivasanbaskaran : Kindly testing Inventory handout document for High priority basis, And release  the Handout document tomorrow itself.

Thanks and Regards,
M.Maheshwaran

**Comment by basha123456** [comment]
Jyoti server is down from 05/10/2019(saturday). So, Inventory handout is kept on hold. will start once the server works properly.

**Comment by basha123456** [comment]
dear mahesh,

PFA of the Inventory handout..
[01_JCIPL_Inventory and PICC Handout file.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3746232/01_JCIPL_Inventory.and.PICC.Handout.file.docx)

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the attached Inventory & PICC handout. There is some small changes like allignment corrections. I did that corrections. 

Kindly proceed further. 

Handout: [01_JCIPL_Inventory.and.PICC.Handout_v1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3834616/01_JCIPL_Inventory.and.PICC.Handout_v1.1.docx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Maghesh,

Handouts verified, please transfer to customer

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the attached Inventory and PICC final Handout for your reference.

**Inventory and PICC Handout :** [01_JCIPL_Inventory and PICC Handout V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3835720/01_JCIPL_Inventory.and.PICC.Handout.V.1.0.docx)

Regards,
M.Maheshwaran
