### ISSUE TITLE
TRG : Maintenance Handout document preparation 

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#129]
@srinivasanbaskaran 

Please find the attached Maintenance Handout document for your reference. kindly check and Review.

**EAM Document :** [01_JCIPL_EAM Handout Document V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3921321/01_JCIPL_EAM.Handout.Document.V.1.0.docx)

Thanks and Regards,
M.Maheshwaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Maintenance Handout verified successfully. I am changing the below points 

1. Sentence correction ( 1st letter of the word capital ) - only for HIGHLIGHTED words.
2. Table of Content - ( Empty line came under the Table of Content )
3. Footer - ( Updated version of the Handout name should come )

HANDOUT: [01_JCIPL_EAM.Handout.Document_v1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3921592/01_JCIPL_EAM.Handout.Document_v1.1.docx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Please circulate this to customer
