### ISSUE TITLE
TRG : Process Production Handout document Preparation

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#130]
Dear sir,

Please find the attached Process Production handout document for your reference.

**PPD Doucment :**

Thanks and Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Sujin,

Kindly start Process Production Handout Document preparation.

Regards,
M.Maheshwaran

**Comment by sujin1708** [comment]
Basha,

kindly create the Handout Document Jyoti Process Production -Masters..

regards,
sujin.M

**Comment by basha123456** [comment]
Sujin,

As Discussed, i need some time to start this handout preparation..i will assign it in my name that time.

regards,
Basha

**Comment by sujin1708** [comment]
@basha kindly start the Handout document for master 

1,Time Table
2,Maintain Calendar
3, Maintain User Defined Category Values
4, Select Usage for Template
5, Maintain Reason Code
6, Create Physical Element
7, Create Procss Element
8, Create Process Element - Physical Element Association
9, Create Formula
10, Create Master Recipe
11, Associate Lot Templates
12, Maintain Net Relalizable Value
13, Maintain Formula Access Rights

Format use which is followed by mahesh

Try to completed before 22.10.2019

Regards,
sujin.M

**Comment by basha123456** [comment]
started working on this ticket on 18/10/2019

**Comment by basha123456** [comment]
Dear Sujin,

PFA..as discussed, i have done the Masters handout preparation upto master recipe.
from Associate lot template, please continue and the transactions also.
[01_JCIPL_Process Production Handout - Masters.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3760396/01_JCIPL_Process.Production.Handout.-.Masters.docx)

**Comment by sujin1708** [comment]
Dear Sirni, 

Please find the attached Process production  handout document for your reference.

**P&P Handout : [01_JCIPL_Process Production Handout Master -1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3810010/01_JCIPL_Process.Production.Handout.Master.-1.0.docx)

Regards,
sujin.M

**Comment by srinivasanbaskaran** [comment]
Mani,

Please start the Test this Handout & Revert 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Sujin,

 Kindly do the below correction for the Process production Handout,

1. The header Text is missing For (6.12,6.13) in the table of content .
2. The Text Realizable word is different both header and sub-header. Kindly check it correct it.
3. Kindly remove the Arrow marks before the text and put nos for last 3 Pages.
Note :  The Header text and screen shot placed in same page.

Regards,
Manivel A

**Comment by sujin1708** [comment]
@manivel find the update version ....kindly revie
[01_JCIPL_Process Production Handout - Masters V1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3819867/01_JCIPL_Process.Production.Handout.-.Masters.V1.1.docx)
w

**Comment by sujin1708** [comment]
Dear Sirni, 

Please find the attachment of  Process production  handout transaction document for your reference.

**P&P Handout : [Uploading 01_JCIPL_Process Production Handout Transaction…]()


Regards,
sujin.M

**Comment by srinivasanbaskaran** [comment]
Sujin,

Once you correct the changes in th Handout, then this will be under 52. In-Progress_GEN nit in 04.PFS_Review..

Kindky follow this... 

Regards,

Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

I have checked the Process production handout, It is looking fine.

Regards,
Manivel A

**Comment by sujin1708** [comment]
Dear Manivel/Srini, 

Please find the revised attachment of  Process production  handout- transaction document for your reference.kindly review

P&P Handout Transaction V1.1 : [01_JCIPL_Process.Production.Handout.TranscationV1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3828563/01_JCIPL_Process.Production.Handout.TranscationV1.1.docx)


Regards,
Sujin. M

**Comment by Manimahat** [comment]
Hi Srinivasan,

I have checked the handout, it is looking fine.

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the attached updated Handouts for both Process Production Masters & Transactions

Masters: [01_JCIPL_Process.Production.Handout.-.Masters.V1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3830112/01_JCIPL_Process.Production.Handout.-.Masters.V1.2.docx)

Transactions: [01_JCIPL_Process.Production.Handout.TranscationV1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3830116/01_JCIPL_Process.Production.Handout.TranscationV1.2.docx)

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Kindly please Check & Review the Handouts. Revert back in case of any corrections.. 

Regards,

Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Sujin- Please submit the handouts to the customer
