### ISSUE TITLE
PPD: Parameter Log value Updation  for Tool - trigger 

### ISSUE THREAD

**Issue by basha123456** [astpl1998/Jyoti-Ceramic#133]
Hi Karthi,

PFA.. for tool management we need a trigger to find the tool capacity. I have mentioned clearly how the trigger should work..please go through the file. If any clarification required, please contact me or sujin.
[Tool Management - Trigger.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3720191/Tool.Management.-.Trigger.xlsx)

Note : Please take this priority and do the needful

**Comment by karthikeyanamitysoft** [comment]
Dear Bhasha,

Dont allocate to me directly allocate to Raju sir, raju Sir will allocate to me.

Regards,
Karthi

**Comment by basha123456** [comment]
Cool Karthikeyan..but why you unassigned sujin?

**Comment by basha123456** [comment]
Dear Raju Sir,

PFA for the tool management Trigger. Need to review this and assign for development.

[Tool.Management.-.Trigger.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3727520/Tool.Management.-.Trigger.xlsx)

**Comment by basha123456** [comment]
Dear Raju Sir,

After our discussion, i have updated the trigger PFS. please assign for developmnet.

[Tool Management Trigger PFS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3742461/Tool.Management.Trigger.PFS.xlsx)

**Comment by basha123456** [comment]
Dear Raju Sir,

After our discussion, i have updated the trigger PFS. please assign for developmnet
[Tool Management Trigger PFS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3755317/Tool.Management.Trigger.PFS.xlsx)

**Comment by basha123456** [comment]
badam,

please hold the PFS for now..the screen is changed. it is in development in progress..i will tell you one it is done.

**Comment by sujin1708** [comment]
don't assigned to me 

revise the PFS get review from raju sir ..then assigned to developers(gayathiri)

**Comment by basha123456** [comment]
Sujin,

suresh sir said that you are going to handle this ticket. and i have given KT to you. so i am assigning ticket to you. if any doubt speak with suresh sir.

**Comment by sujin1708** [comment]
first revise the pfs get review from raju sir

**Comment by basha123456** [comment]
this you have to discuss with raju sir and finalize ..as you are aware the functionality of reporting screen.

**Comment by sujin1708** [comment]
hold...

**Comment by karthikeyanamitysoft** [comment]
Kindly provide the test data or test and confirm.

Regards,
Karthi

**Comment by basha123456** [comment]
Dear Kathi,

PFA..refer sheet "Test data".
[Tool Management Trigger PFS v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3966484/Tool.Management.Trigger.PFS.v1.1.xlsx)
 
I have created the data and checked. reported qty is not updated.

**Comment by karthikeyanamitysoft** [comment]
Kindly provide test data

**Comment by karthikeyanamitysoft** [comment]
DEar Bhasha,

logic changed by other person , kindly check now and confirm me or give me trace on Authorize.
Regareds,
Karthi

**Comment by sujin1708** [comment]
hold logic to be freeze...

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly update the Logic in PFS & Allocate to Me for Review. 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Srini,

This ticket is not handled by me and i am not aware of the Logic..please route it to the correct person.

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly get the knowledge. Then you update the PFS & Allocate to me 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Srini,

suresh sir said strictly that production related trigger will not be handled by me. so kindly dont allocate me this ticket.

**Comment by basha123456** [comment]
[Parameter value updation trigger PFS.v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4123112/Parameter.value.updation.trigger.PFS.v1.2.xlsx)

Sujin,

PFS is completed. kindly review and move.

**Comment by sujin1708** [comment]
@karthikeyanamitysoft  please do the changes

**Comment by karthikeyanamitysoft** [comment]
This trigger completed sujin

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly allocate this report to Developers to correct the Report

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
kindly do the following changes 👍 

1. when clicking on Authorize button, Automatically value should update in below path (status - Accepted/rejected/authorize qc pending)
 go to Enterprise Asset management -> parameter log -> Insert Parameter value -> In the consumption parameters section, following data should be filled for value updating.

Process unit -COFPAC_PU1
Tool : CYCLAM202

logic : 
1.Parameter = Consumption type parameter
2.value = reported qty + Loss qty from the reporting screen(for all status).
3. Delta/New.
if the parameter value is 0, then Delta/New field should select New from the combo.
if the parameter value is not 0, then Delta/New field should select Delta from the combo.
4. Date = system date when Authorizing
5. Time = system date when Authorizing
6. Click on button ""Insert Parameter Values

**Comment by karthikeyanamitysoft** [comment]
Dear Naren,

Kindly do the changes

**Comment by karthikeyanamitysoft** [comment]
how can i find the parameter

**Comment by Narendiranath** [comment]
Hi Basha,

             Parameter log updation is completed. Kindly check.

**Comment by basha123456** [comment]
@srinivasanbaskaran 

esting1 is completed..kindly check & move
[Parameter value updation trigger PFS.v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4292772/Parameter.value.updation.trigger.PFS.v1.2.xlsx)

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start the Testing 2 & Prepare the Testing Dcoument as per our new format

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 2 Completed. Please Find the Attached document for your reference.

Test case : [Test case _ Mail trigger for Report Production Qty.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4382272/Test.case._.Mail.trigger.for.Report.Production.Qty.xlsx)

Result : [Mail trigger for Tool Report Production Qty Result.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4382275/Mail.trigger.for.Tool.Report.Production.Qty.Result.docx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Naren,

Kindly attach the Latest Deliverables ASAP.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Parameter Log Value Updation for Tool Testing has been completed. Herewith I have attached the Testing Documents for future references.

PFS: [Parameter_Value_Updation_Trigger_PFS.v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389646/Parameter_Value_Updation_Trigger_PFS.v1.2.xlsx)

DELIVERABLES:

TESTCASE1 & TEST RESULT1: [Testcase1_Parameter_Value_Updation_Trigger_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389647/Testcase1_Parameter_Value_Updation_Trigger_v1.0.xlsx)

TESTCASE2: [Test.case._.Mail.trigger.for.Report.Production.Qty.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389650/Test.case._.Mail.trigger.for.Report.Production.Qty.xlsx)

TEST RESULT2: [Mail.trigger.for.Tool.Report.Production.Qty.Result.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389652/Mail.trigger.for.Tool.Report.Production.Qty.Result.docx)

Regards,
Srinivasan Baskaran

**Comment by Narendiranath** [comment]
Hi Srini,
   
          Deliverables attached. Kindly check.
[Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4392156/Deliverables.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

Parameter Log Value Updation for Tool Testing has been completed. Herewith I have attached the Testing Documents for future references.

PFS: [Parameter_Value_Updation_Trigger_PFS.v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389646/Parameter_Value_Updation_Trigger_PFS.v1.2.xlsx)

DELIVERABLES: [Parameter Log Value Updation.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4397463/Parameter.Log.Value.Updation.zip)

TESTCASE1 & TEST RESULT1: [Testcase1_Parameter_Value_Updation_Trigger_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389647/Testcase1_Parameter_Value_Updation_Trigger_v1.0.xlsx)

TESTCASE2: [Test.case._.Mail.trigger.for.Report.Production.Qty.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389650/Test.case._.Mail.trigger.for.Report.Production.Qty.xlsx)

TEST RESULT2: [Mail.trigger.for.Tool.Report.Production.Qty.Result.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389652/Mail.trigger.for.Tool.Report.Production.Qty.Result.docx)

Regards,
Srinivasan Baskaran

**Comment by Narendiranath** [comment]
Hi ,

  Latest Deliverables attached. Kindly check.
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4614526/Deliverable.zip)

**Comment by srinivasanbaskaran** [comment]
Basha,

Pls add the latest points & Proceed further

**Comment by srinivasanbaskaran** [comment]
![IMG_20200518_132416_20200518_132528267](https://user-images.githubusercontent.com/46194039/82188200-243eb200-990b-11ea-909a-fc8c6158b79e.jpg)

**Comment by basha123456** [comment]
@raju-kurup 

PFS is updated as per the customer requirement.  Need to assign to developer after review.
[Parameter value updation trigger PFS.v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4655116/Parameter.value.updation.trigger.PFS.v1.3.xlsx)
[Test.Case - Paraameter Log Updation.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4655191/Test.Case.-.Paraameter.Log.Updation.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction of validation while authorizing the production report screen.

**Comment by karthikeyanamitysoft** [comment]
Sir 
i can't understand the changes
if the item is not mapped with toll then it will not work.

REgards,
Karthi

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As discussed with Basha and me please do the correction as per the PFS mentioned in 2(i), 2(ii), 4 and 5.

**Comment by basha123456** [comment]
@raju-kurup 

Sir, I have added a condition inthe PFS in yellow colour. please assign to developer.
[Parameter value updation trigger PFS.v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4715184/Parameter.value.updation.trigger.PFS.v1.3.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Parameter log value is to be corrected, test data with exact value is attached.

**Comment by Narendiranath** [comment]
@raju-kurup 

This ticket is dependency on Ticket no 121 for Tool & Tool description loading

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Parameter log updation for tool is completed. kindly move to testing2.
[Parameter Log updation - TR.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4799944/Parameter.Log.updation.-.TR.xlsx)

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start the Testing 2 & Prepare the Testing Documents 

**NOTE** 

**Kindly get the full KT from Basha **

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@Narendiranath ,

Tool Description Name Should be Tool Consumption. but it is Working in All description.

Please re-check & correct it.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 2 Completed. please find the Attached Document for your ref...

[Paramenter Log Value Updation. TR.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4807948/Paramenter.Log.Value.Updation.TR.zip)

Regards,
Manivel A

**Comment by Narendiranath** [comment]
Hi,

Here i attach Latest deliverable. Kindly check.
[Latest Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4808144/Latest.Deliverable.zip)

**Comment by Narendiranath** [comment]
Hi,

Here i attach Latest deliverable. Kindly check.
[Lat Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4835535/Lat.Deliverables.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

Parameter Lig Value Updation for Tool - Trigger testing has been completed. Herewith I have attached Testing documents for future references.

PFS: [Parameter.value.updation.trigger.PFS.v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4882742/Parameter.value.updation.trigger.PFS.v1.4.xlsx)

DELIVERABLES: [Lat.Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4882743/Lat.Deliverables.zip)

TESTCASE1 & TEST RESULT1: [Parameter.Log.updation.-.TR.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4882744/Parameter.Log.updation.-.TR.xlsx)

TESTCASE2 & TEST RESULT2: [Paramenter.Log.Value.Updation_TR2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4882756/Paramenter.Log.Value.Updation_TR2.zip)

Regards,
Srinivasan Baskaran

**Comment by Narendiranath** [comment]
Hi,

          PFA Latest Deliverable for your referance.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5709015/Deliverable.zip)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by Narendiranath** [comment]
Hi Srinivasan Baskaran,

                  Report deployed in live server. PFA Latest Deliverable.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5764121/Deliverable.zip)

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Parameter Log value tool trigger Deployed in Live server successfully.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
