### ISSUE TITLE
FIN - Transfer Pricing Comparative Sales

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#135]
Create PFS for report to develop Transfer Pricing (comparative statement of Item rates between export sales and domestic sales) 
Customer format : [Transfer Pricing comparitive statement.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3803597/Transfer.Pricing.comparitive.statement.xlsx)

**Comment by Dhanwandher** [comment]
Dear Sir....

I herewith attach the PFS for Transfer pricing comparative Statement....

Regards....
S.Dhanwandher....
[Transfer Price Compartive Sales_PFS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3884923/Transfer.Price.Compartive.Sales_PFS.xlsx)

**Comment by raju-kurup** [comment]
Dear Dhanwandher,

We will discuss and finalise this PFS

**Comment by Nandhineedevi** [comment]
Hi Dhanwander,
The Report design and coding has been completed. Kindly check and revert back.

[Transfer Pricing Comparative Statement del_v1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4085115/Transfer.Pricing.Comparative.Statement.del_v1.0.zip)

Regards
Nandhinee Devi

**Comment by Dhanwandher** [comment]
Nandinee.....

Please Check the below issue.... Only one entry should be passed in one customer but entry is coming in both customers....

Regards.
S.Dhanwandher....
![image](https://user-images.githubusercontent.com/50094013/72781938-867ef300-3c48-11ea-8d03-528804f9c897.png)

**Comment by Nandhineedevi** [comment]
Hi Dhanwander,
The Rework has been completed. Kindly check and revert back.

[Transfer_Price_Compartive_Sales_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4089830/Transfer_Price_Compartive_Sales_v1.1.zip)

Regards
Nandhinee Devi

**Comment by Dhanwandher** [comment]
Dear Srini.....

Testing one completed....Kindly start with Testing 2......

Regards...
S.Dhanwandher...
[Test.Case for Transfer Pricing Comparsion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4107485/Test.Case.for.Transfer.Pricing.Comparsion.xlsx)
[Transfer Pricing Comparsion.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4107486/Transfer.Pricing.Comparsion.pdf)

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start Test this report & Prepare the Testing Documents.

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srini....

Testing 2 Completed Kindly Check & Update

Regards,
Akash

[Transfer Pricing Comparative Sales Test Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4111722/Transfer.Pricing.Comparative.Sales.Test.Result.pdf)

[Transfer Pricing Comparative Sales TEST CASE v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4111724/Transfer.Pricing.Comparative.Sales.TEST.CASE.v2.xlsx)

**Comment by srinivasanbaskaran** [comment]
Dhanwandher,

Please change the logic as per the Customer Requirements

Regards,
Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Nandinee....

Please do the following changes in the report.

1.Rate (FC) should be taken from unit price in multi line for each item 
2.Amt (FC) should be taken from Unit amount in multi line for each item
3.Rate (Rs) and Amt (Rs) should be taken from Rate*exchange rate (Rs) and Amt*exchange rate (Rs) 
4.Grand total should come in the end of the report.
5. Heading should not be hardcorded its should be taken from finance year.

Regards.
S.Dhanwandher...

**Comment by Nandhineedevi** [comment]
Hi Dhanwander,
The Rework has been completed. Kindly check and revert back.

[Transfer_Price_Compartive_Sales_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4142262/Transfer_Price_Compartive_Sales_v1.2.zip)

Regards
Nandhinee Devi

**Comment by raju-kurup** [comment]
Nandhini - All the data is coming correct.

But add new condition - Status of Deleted, Draft, Fresh and Returned Invoice should not come. Apart from everything is correct.

**Comment by raju-kurup** [comment]
Nandhini - All the data is coming correct.

But add new condition - Status of Deleted, Draft, Fresh and Returned Invoice should not come. Apart from everything is correct.

**Comment by Nandhineedevi** [comment]
Hi Raju sir, 
The rework has been completed. Kindly check and revert back.

[Transfer_Price_Compartive_Sales_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4146337/Transfer_Price_Compartive_Sales_v1.3.zip)

Regards
Nandhinee Devi

**Comment by Dhanwandher** [comment]
[Transfer Pricing Comparsion_new.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4147303/Transfer.Pricing.Comparsion_new.pdf)
Dear Srini.....

Testing one completed....Kindly start with Testing 2......

Regards...
S.Dhanwandher...
[Test.Case for Transfer Pricing Comparsion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4147294/Test.Case.for.Transfer.Pricing.Comparsion.xlsx)

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start the Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srini.....

Testing 2 Completed Kindly Check & Update

Regards,
Akash

1. Test Result :[Transfer Pricing Comparative Sales v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4163743/Transfer.Pricing.Comparative.Sales.v2.pdf)

2. Test Case2 :[Test.Case.for.Transfer.Pricing.Comparsion (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4163745/Test.Case.for.Transfer.Pricing.Comparsion.1.xlsx)

**Comment by srinivasanbaskaran** [comment]
Dear Dhanwnadher & Akash,

Please find the below screen shot.. Value is wrongly calculated. Can you please check & Correct it with Developers.

Before correct it with Developers, Pls clarify this point to Mr. Raju Sir.

Screenshot: 
![image](https://user-images.githubusercontent.com/46194039/77693684-bf33a380-6fce-11ea-813f-14c8dbd943ef.png)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Transfer Pricing Comparative Sales Report testing has been completed. Herewith I have attached the Testing Documents for future references.

PFS: [Transfer.Price.Compartive.Sales_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4397468/Transfer.Price.Compartive.Sales_PFS_v1.0.xlsx)

PATH: Receivable Management --> Reports - Receivable Management --> Transfer Price Comparative Statement 

DELIVERABLES: [Transfer_Price_Compartive_Statement_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4397478/Transfer_Price_Compartive_Statement_v1.3.zip)

TESTCASE1: [Test.Case.for.Transfer.Pricing.Comparsion.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4397479/Test.Case.for.Transfer.Pricing.Comparsion.1.xlsx)

TEST RESULT1: [Transfer.Pricing.Comparative.Sales.v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4397480/Transfer.Pricing.Comparative.Sales.v2.pdf)

TESTCASE2: [Test.Case.for.Transfer.Pricing.Comparsion.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4397482/Test.Case.for.Transfer.Pricing.Comparsion.1.xlsx)

TEST RESULT2: [Transfer_Pricing_Comparsion_New.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4397483/Transfer_Pricing_Comparsion_New.pdf)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed, so closing this development

**Comment by raju-kurup** [comment]
Development completed and user agreeded orally and they mentioned they are not able to check in this financial year, they will check this in live server. But they agreed the format and the data sample checked. So closing this development.

**Comment by Manimahat** [comment]
@raju-kurup Sir,

To be Deployed this Report in Live Server. Please Allocate to developers.

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by Nandhineedevi** [comment]
@Narendiranath
DW Report Name: tran_price_rpt

Kindly Move only the DW Report from UAT to Live Server.
All Back end and Front end Deployment had been completed.
Latest Deliverable has been attached below.

[Live_import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5918667/Live_import.zip)

**Comment by Narendiranath** [comment]
Hi Manivel,

DW Report deployed in live server. Kindly check. PFA Latest Deliverables for your ref.

[Dw_ER_03Feb2021233409.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5920580/Dw_ER_03Feb2021233409.zip)

**Comment by Manimahat** [comment]
@raju-kurup sir,

Report has been deployed Successfully. Kindly close this ticket.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
