### ISSUE TITLE
FIN - Purchase Register

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#137]
Karthi,

Please deploy the purchase register from Kanam Latex - "Purchase_Register_rpt_kannam" but kanam name should not come
[Purchase register format.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3803669/Purchase.register.format.xlsx)

**Comment by badamnarendra028** [comment]
![image](https://user-images.githubusercontent.com/46923845/68288006-ac651480-00a9-11ea-85c7-3bdd22fc1fc7.png)

**Comment by badamnarendra028** [comment]
[Purchase_Register_rpt_pop.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3813761/Purchase_Register_rpt_pop.zip)
completed plz check and revert

**Comment by karthikeyanamitysoft** [comment]
Development completed

**Comment by raju-kurup** [comment]
Dhanwander-please check the register

**Comment by Dhanwandher** [comment]
Dear Badam....

Kindly do the following changes in Purchase_Register DCUBE report and revert.

1.Report is not fetching according to OU wise.
2. OU ID along with OU name.
3. GST Input Credit Register(Hard Corded).
4. From date and To Date not fetching.

Regards.
S.Dhanwandher

**Comment by Dhanwandher** [comment]
Sir....

Herewith i have attached updated Purchase Register format.Kindly review & do the needful.

Regards.
S.Dhanwandher
[Purchase_register_new.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3819676/Purchase_register_new.xlsx)

**Comment by Dhanwandher** [comment]
Sir....

Herewith i have attached updated Purchase Register format.Kindly review & do the needful.

Regards.
S.Dhanwandher
[Purchase Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3845408/Purchase.Register.xlsx)

**Comment by Dhanwandher** [comment]
Sir....

Herewith i have attached revised Purchase Register format.Kindly review & do the needful.

Regards.
S.Dhanwandher.
[Purchase.Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3900262/Purchase.Register.xlsx)

**Comment by raju-kurup** [comment]
[Purchase.Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3906985/Purchase.Register.xlsx)

**Comment by Dhanwandher** [comment]
Dear Team....

PFS Completed and attached....

Regards.
S.Dhanwandher
[Purchase Register_PFS (Autosaved).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4015700/Purchase.Register_PFS.Autosaved.xlsx)

**Comment by badamnarendra028** [comment]
[Purchase_Register_rpt_pop (2).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4019064/Purchase_Register_rpt_pop.2.zip)

**Comment by Dhanwandher** [comment]
Dear Badam.

Please rectify the below mentioned points in purchase Register...
1.For Supplier Direct invoice Invoice date should come.
2.at the end of the page only total should be shown.
3.only AUT status should appear in report.
4.records should be fetched within the given date in report.
5.Supplier Registration should appear in the report.

Regards.
S.Dhanwandher.

**Comment by badamnarendra028** [comment]
completed

**Comment by Dhanwandher** [comment]
Badam....

Please find the correction in Purchase register in attached revised PFS

Regards....
S.Dhanwandher
[Purchase Register__Revised_PFS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4111834/Purchase.Register__Revised_PFS.xlsx)

**Comment by badamnarendra028** [comment]
completed

**Comment by Dhanwandher** [comment]
Srini......

Testing 1 completed.....Kindly start with testing 2....

Regards.....
S.Dhanwandher....
[Test.Case for Purchase Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4133797/Test.Case.for.Purchase.Register.xlsx)
[Purchase Register Test result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4133798/Purchase.Register.Test.result.xlsx)

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start test this Report & Prepare the Testing Documents

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Dhanwandhar....

Kindly Check The Testing 1 Properly 

Regards,
Akash

**Comment by Dhanwandher** [comment]
Badam.....

In purchase register the line level TCD not fetching....Kindly check.....

Regards.
S.Dhanwandher....

**Comment by badamnarendra028** [comment]
completed

**Comment by Dhanwandher** [comment]
Srini......

Testing 1 completed.....Kindly start with testing 2....

Regards.....
S.Dhanwandher....
[Test.Case for Purchase Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4169522/Test.Case.for.Purchase.Register.xlsx)
[Test result for Purchase register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4169532/Test.result.for.Purchase.register.xlsx)

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly Test this report & Prepare the Testing Document

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srini......

Purchase Register Testing 2 Completed kindly Check & Update

Regards,
Akash

1. Testing Result : [Purchase Regester v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4173861/Purchase.Register.v2.xlsx)

2. Test Case : [Test.Case.for.Purchase.Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4173864/Test.Case.for.Purchase.Register.xlsx)

**Comment by srinivasanbaskaran** [comment]
Dhanwandher,

Pls check the Purchase Register clearly 

Regards,
Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Dear Badam.....

Please do the following changes in Purchase register...

1.Remove Column "X-GROSS BEFORE TAX INR".
2. Add Taxable Column (Basic Amount+Charges-Discount Allowed) this column should come after Charges column.
1.Remove Column "S-TAXABLE AMOUNT".

Regards
S.Dhanwandher 
[purchase register_new Changes.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4196810/purchase.register_new.Changes.xlsx)

**Comment by Narendiranath** [comment]
Hi Dhanwandher,

             Changes are done. Kindly check.

**Comment by Dhanwandher** [comment]
Dear Narendiranath....

1.For Subcontract Order date should come
2.if values are not there it should not be blank zero should come.

Note: its marked in Yellow colour

Thanks....
S.Dhanwandher....
[Sales register correction.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4228961/Sales.register.correction.xlsx)

**Comment by Narendiranath** [comment]
Hi Dhanwandher,

               Issue is resolved. Kindly check.

**Comment by Dhanwandher** [comment]
Srini......

Testing 1 completed.....Kindly start with testing 2....

Regards.....
S.Dhanwandher....
[Test result for Purchase register new.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4243246/Test.result.for.Purchase.register.new.xlsx)
[Test.Case for Purchase Register new.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4243248/Test.Case.for.Purchase.Register.new.xlsx)

**Comment by srinivasanbaskaran** [comment]
Akash,

Please start the Testing2 & Prepare the Testing Document

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Narendiranath......

In Purchase Register TCD Value is fetching wrongly (Discount amount & charges).

Thanks &  Regards,
Akash

**Comment by Narendiranath** [comment]
Hi Akash....

            Issue resolved. Kindly check.

**Comment by AkashGleen** [comment]
Dear Srini.....

Purchase Register Testing 2 Completed Kindly Check & Update

[Purchase Register Test Result v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4270202/Purchase.Register.Test.Result.v2.xlsx)
[Test.Case.for.Purchase.Register v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4270208/Test.Case.for.Purchase.Register.v2.xlsx)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Naren,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Purchase Register Report testing has been completed. Herewith I have attached the Testing documents for the future references.

PFS: [Purchase.Register__Revised_PFS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356425/Purchase.Register__Revised_PFS.xlsx)

DELIVERABLES:

TESTCASE1: [Test.Case.for.Purchase.Register.new.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356427/Test.Case.for.Purchase.Register.new.xlsx)

TEST RESULT1: [Test.result.for.Purchase.register.new.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356428/Test.result.for.Purchase.register.new.xlsx)

TESTCASE2: [Test.Case.for.Purchase.Register.v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356429/Test.Case.for.Purchase.Register.v2.xlsx)

TEST RESULT2: [Purchase.Register.Test.Result.v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356432/Purchase.Register.Test.Result.v2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Narendiranath** [comment]
Hi Srini,

           I attached Deliverables for Purchase Register. Kindly check.
[Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4358920/Deliverables.zip)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Purchase Register Report testing has been completed. Herewith I have attached the Testing documents for the future references.

PFS: [Purchase.Register__Revised_PFS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356425/Purchase.Register__Revised_PFS.xlsx)

DELIVERABLES: 

TESTCASE1: [Test.Case.for.Purchase.Register.new.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356427/Test.Case.for.Purchase.Register.new.xlsx)

TEST RESULT1: [Test.result.for.Purchase.register.new.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356428/Test.result.for.Purchase.register.new.xlsx)

TESTCASE2: [Test.Case.for.Purchase.Register.v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356429/Test.Case.for.Purchase.Register.v2.xlsx)

TEST RESULT2: [Purchase.Register.Test.Result.v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356432/Purchase.Register.Test.Result.v2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested, so closing this issue

**Comment by raju-kurup** [comment]
@Dhanwandher : please check this report and update the PFS if needed

**Comment by Dhanwandher** [comment]
Dear Sir.

PFS updated as per GMBH OU.

Regards.
S.Dhanwandher.
[Purchase Register__Revised_PFS_GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5015634/Purchase.Register__Revised_PFS_GMBH.xlsx)

**Comment by Dhanwandher** [comment]
Dear Sir.

PFS updated as per discussion for GMBH OU.

Regards.
S.Dhanwandher.
[Purchase Register__Revised_PFS_GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5032145/Purchase.Register__Revised_PFS_GMBH.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft  : please do the correction as mentioned in PFS which is coloured in yellow and test case attached.

**Comment by Narendiranath** [comment]
Hi Dhanwandher,

                    Changes are done. Kindly check. PFA Report for your reference
[Purchase_Register_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5068935/Purchase_Register_Report.xlsx)

**Comment by Dhanwandher** [comment]
Sir....

While Executing report this error comes.
![image](https://user-images.githubusercontent.com/50094013/90465699-89ce5480-e12d-11ea-8b1f-b3424450a289.png)


Regards.
S.Dhanwandher....

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please resolve this issue, report was not able to generate

**Comment by Narendiranath** [comment]
Hi Dhanwandher,

              Issue resolved. Kindly check. PFA for your referance

![image](https://user-images.githubusercontent.com/59695578/90507188-19e2bd00-e173-11ea-9a1a-327eab3d51b5.png)

**Comment by Dhanwandher** [comment]
Testing one completed....

Regards....
S.Dhanwandher..
[Test Case for purchase register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5095325/Test.Case.for.purchase.register.xlsx)
[Test result for Purchase register for testing.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5095326/Test.result.for.Purchase.register.for.testing.xlsx)

**Comment by Dhanwandher** [comment]
Naren.

Tax Category not coming for MFG OU....

Regards.
S.Dhanwandher.
[Purchase Register__Revised_PFS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5100473/Purchase.Register__Revised_PFS.xlsx)

**Comment by Narendiranath** [comment]
Dhanwandher,

As we discussed i remove Status column from this report and also Tax Category is coming for MFG OU....

![image](https://user-images.githubusercontent.com/59695578/90724461-3bab8380-e2dc-11ea-96bf-9c7bfc69fce3.png)

**Comment by Dhanwandher** [comment]
Team....

Testing One completed.....

Regards.
S.Dhanwandher....
[Test Case for purchase register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5107230/Test.Case.for.purchase.register.xlsx)
[Test result for Purchase register for testing.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5107231/Test.result.for.Purchase.register.for.testing.xlsx)
[Purchase Register__Revised_PFS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5107234/Purchase.Register__Revised_PFS.xlsx)

**Comment by AkashGleen** [comment]
Dear Srinivasanbaskaran,

Purchase Register Testing 2 Completed Kindly Check & Update.


[Test.Case.for.purchase.register.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5116951/Test.Case.for.purchase.register.zip)

[Test.Case.for.purchase.register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5116952/Test.Case.for.purchase.register.xlsx)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Dhanwandher,

Please find the below points are not fetched in the Report.

MFG OU:
1. Frieght Inward
2. Doc IGST

GmbH OU:
1. Supplier PAN No
2. Supplier Tax Registration No
3. Frieght Inward
4. Doc IGST

**Comment by Dhanwandher** [comment]
Srini.....

PFS has been changed.Kindly check....

[Purchase.Register__Revised_PFS_GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5140116/Purchase.Register__Revised_PFS_GMBH.xlsx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir, 

Purchase Register Report Testing has been completed. Herewith I have attached the Testing Documents for the future references. 

PFS for MFG: [Purchase.Register__Revised_PFS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145027/Purchase.Register__Revised_PFS.xlsx)

PFS for GmbH: [Purchase.Register__Newly_Revised_PFS_GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145029/Purchase.Register__Newly_Revised_PFS_GMBH.xlsx)

DELIVERABLES: [Deliverable (1).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5145043/Deliverable.1.zip)

TESTCASE1: [Test.Case.for.purchase.register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145031/Test.Case.for.purchase.register.xlsx)

TEST RESULT1: [Test.result.for.Purchase.register.for.testing.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145033/Test.result.for.Purchase.register.for.testing.xlsx)

TESTCASE2: [Testcase2_for_Purchase_Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145045/Testcase2_for_Purchase_Register.xlsx)

TEST RESULT2:

**Comment by srinivasanbaskaran** [comment]
@AkashGleen ,

Kindly update the Test Result2 correcly

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srinivasanbaskaran.

Purchase Register Test Result 2 Kindly Update.

[Test Result v2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5148433/Test.Result.v2.zip)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Raju Sir, 

Purchase Register Report Testing has been completed. Herewith I have attached the Testing Documents for the future references. 

PFS for MFG: [Purchase.Register__Revised_PFS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145027/Purchase.Register__Revised_PFS.xlsx)

PFS for GmbH: [Purchase.Register__Newly_Revised_PFS_GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145029/Purchase.Register__Newly_Revised_PFS_GMBH.xlsx)

DELIVERABLES: [Deliverable (1).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5145043/Deliverable.1.zip)

TESTCASE1: [Test.Case.for.purchase.register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145031/Test.Case.for.purchase.register.xlsx)

TEST RESULT1: [Test.result.for.Purchase.register.for.testing.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145033/Test.result.for.Purchase.register.for.testing.xlsx)

TESTCASE2: [Testcase2_for_Purchase_Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145045/Testcase2_for_Purchase_Register.xlsx)

TEST RESULT2: [Test.Result.v2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5154124/Test.Result.v2.zip)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer gave confirmation to move this report to GREEN on 18-10-2020 through mail confirmation. 

Kindly proceed this to close.

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@raju-kurup report status moved to green plz close the ticket

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by Narendiranath** [comment]
Hi Srinivasan Baskaran,

              Report deployed in live server. PFA Latest Deliverable

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5764046/Deliverable.zip)

**Comment by Dhanwandher** [comment]
Akash...

Kindly check the report is launching in live server

**Comment by AkashGleen** [comment]
Dear Raju Sir,

Purchase Register report is launching in live server

Regards,
Akash

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket

**Comment by Manimahat** [comment]
@raju-kurup sir,

Customer face below Attached while Execute the purchase Register report in Live server So we Re-opened this ticket. Please allocate to developer for resolving this issue.

![image](https://user-images.githubusercontent.com/55881685/127820244-af3c0a57-d631-4228-816e-9b2c1938a416.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please check the issue which is populating in Purchase Register.

**Comment by Jeyapriyat** [comment]
@Manimahat 

issue completed,kindly check and revert.

**Comment by Manimahat** [comment]
@raju-kurup sir,

Report has been Launched successfully with data. So please close this ticket.

Report Screen shot : ![image](https://user-images.githubusercontent.com/55881685/129194851-b4abbb47-a184-4478-bd5a-071f67e22122.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Being report launched successfully, we are closing this ticket.
