### ISSUE TITLE
FIN - Sales Register

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#138]
Format : [Sales Register format.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3803685/Sales.Register.format.xlsx)
Dear Karthi,

Please deploy Sales Register from Subhasri - "Subhasri GST Sales Register" but Subhasri name should not come

**Comment by badamnarendra028** [comment]
[sales_register_pop.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3840312/sales_register_pop.zip)
completed kindly check

**Comment by Dhanwandher** [comment]
Dear Sir......

Please find the revised sales register format.....

Regards....
S.Dhanwandher...

[Sales Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3900443/Sales.Register.xlsx)

**Comment by raju-kurup** [comment]
[Sales.Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3906981/Sales.Register.xlsx)

Please do the modification and correction mentioned in the excel

**Comment by karthikeyanamitysoft** [comment]
Changes completed by Siva, kindly check and confirm.

Regards,
Karthi

**Comment by Dhanwandher** [comment]
Srini......

Testing one completed as per changed told.....Kindly processed with testing two....

Regards....
S.Dhanwandher..

[Sales Register new.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4038710/Sales.Register.new.xlsx)

**Comment by srinivasanbaskaran** [comment]
Prabakaran,

Kindly start the Testing1 & Prepare teh Test Documents & Revert on 11-01-2020

Regards,
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@Dhanwandher 
Kindly update the testing 1 document

**Comment by Prabakaran92** [comment]
@Dhanwandher 
Kindly add some new fields in the PFS as per UAT Changes
1.P&F 
2.Insurance
3.Freight
4. Assessable Value 
This fields kindly add the Updated PFS.

Regards,
Prabakaran A

**Comment by Dhanwandher** [comment]
Sir.....

Please find revised PFS of sales register....

Regards...
S.Dhanwandher....
[Sales Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4057456/Sales.Register.xlsx)

**Comment by Dhanwandher** [comment]
Sir.....

Please find revised PFS of sales register....

Regards...
S.Dhanwandher....
[Sales Register_Revised.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4076271/Sales.Register_Revised.xlsx)

**Comment by raju-kurup** [comment]
Please start development

**Comment by Dhanwandher** [comment]
Dear Badam....

Kindly rectify the Invoice Value (Base) column......

Regards...
S.Dhanwandher

**Comment by badamnarendra028** [comment]
completed

**Comment by Dhanwandher** [comment]
Dear Srini.....

Testing one completed....Kindly start with Testing 2......

Regards...
S.Dhanwandher...

[Test.Case for Sales Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4107552/Test.Case.for.Sales.Register.xlsx)
[Sales Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4107568/Sales.Register.xlsx)

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start Test this report & Prepare the Testing documents 

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Dhanwandher.........

Kindly Few Changes in Sales Register Report,& Add The Base Value In The Report.

Regards,
Akash

**Comment by Dhanwandher** [comment]
Badam.....

Please change the Assessable Value to Assessable Value(Tran) and add Assessable Value(Base) to the report....

Revised PFS attached......

Regards...
S.Dhanwandher....
[Sales.Register__PFS_Revised_V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4111660/Sales.Register__PFS_Revised_V1.1.xlsx)

**Comment by Dhanwandher** [comment]
Akash.....

Testing one completed....Kindly start with Testing 2......

Regards...
S.Dhanwandher...
[Test.Case for Sales Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4111916/Test.Case.for.Sales.Register.xlsx)

[Sales register new.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4111920/Sales.register.new.xlsx)

**Comment by AkashGleen** [comment]
Dear Srini.....

Testing 2 Completed Kindly Check & Update 

Regards,
Akash

[Sales.Register (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4115960/Sales.Register.1.xlsx)

**Comment by srinivasanbaskaran** [comment]
Dhanwandher,

Pls do the Testing Properly

Regards,
Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Badam....

Please find the changes for the same the changes are marked in Yellow colour....

Regards....
S.Dhanwandher...
[Sales Register changes.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4180426/Sales.Register.changes.xlsx)

**Comment by karthikeyanamitysoft** [comment]
Kindly do the changes.

REgards,
Karhi

**Comment by Narendiranath** [comment]
Hi Dhanwandher,

      Changes are done. Kindly check.

**Comment by Dhanwandher** [comment]
Srini......

Testing one completed as per changed told.....Kindly processed with testing two....

Regards....
S.Dhanwandher..
[Test result for Sales register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4228892/Test.result.for.Sales.register.xlsx)
[Test.Case for Sales Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4228893/Test.Case.for.Sales.Register.xlsx)

**Comment by srinivasanbaskaran** [comment]
Akash,

Please start Testing 2 & Prepare the Testing Documents ASAP

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srini......

Sales Register Testing 2 Completed Kindly Check & Update.

1.Test Result: [Sales Register Test Result v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4244190/Sales.Register.Test.Result.v2.xlsx)
2. Test Case: [Test.Case.for.Sales.Register v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4244201/Test.Case.for.Sales.Register.v2.xlsx)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Naren,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by Narendiranath** [comment]
Hi Srini,

             I attached Latest Deliverables for Sales register report. Kindly check.

**Comment by Narendiranath** [comment]
[Sales Register Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4323661/Sales.Register.Deliverables.zip)

**Comment by srinivasanbaskaran** [comment]
Sir, 

Sales Register Report Testing completed. Herewith I have attached the Testing Documents for future references.

PFS: [Sales.Register__PFS_Revised_V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333996/Sales.Register__PFS_Revised_V1.1.xlsx)

PATH: Tools --> Drill Down --> Inquires ( Sales Register )

DELIVERABLES: [Sales.Register.Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4334563/Sales.Register.Deliverables.zip)

TESTCASE1: [Test.Case.for.Sales.Register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334564/Test.Case.for.Sales.Register.xlsx)

TEST RESULT1: [Test.result.for.Sales.register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334565/Test.result.for.Sales.register.xlsx)
 
TESTCASE2: [TestCase2_Sales_Register_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334570/TestCase2_Sales_Register_v2.xlsx)

TEST RESULT2: [Sales.Register_Test_Result_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334572/Sales.Register_Test_Result_v2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Testing 2 completed, so closing this issue

**Comment by raju-kurup** [comment]
Testing 2 completed, so closing this issue

**Comment by raju-kurup** [comment]
@Dhanwandher : please recheck the report - Assessable value of export invoice are coming wrong

**Comment by Dhanwandher** [comment]
Dear Naren...

The following changes needs to be done in Sales register for Currency USD and EUR.
1. Assessable Value(Tran) Wrongly Calculated.
2. Assessable Value(Base) Wrongly Calculated.
3. Invoice Value(Tran) Wrongly Calculated.
4. Invoice Value(Base) Wrongly Calculated.
5. COI/2021/0030/P1 -Currency wrongly showing as "Finished Goods Account Group".

Regards.
S.Dhanwandher,
[Sales register new correction.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4896656/Sales.register.new.correction.xlsx)

**Comment by Narendiranath** [comment]
@Dhanwandher

Kindly provide the test data & Column level requirment for this report.

**Comment by Dhanwandher** [comment]
Dear Naren...

The following changes needs to be done in Sales register for Currency USD and EUR.

1. Assessable Value(Tran) Wrongly Calculated.
2. Assessable Value(Base) Wrongly Calculated.
3. Invoice Value(Tran) Wrongly Calculated.
4. Invoice Value(Base) Wrongly Calculated.
5. COI/2021/0030/P1 -Currency wrongly showing as "Finished Goods Account Group".


From Date : 04/01/2020
End Date : 05/31/2020

Regards.
S.Dhanwandher,
[Sales.Register__PFS_Revised_V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4897758/Sales.Register__PFS_Revised_V1.1.xlsx)

**Comment by Narendiranath** [comment]
Hi  Dhanwandher,

Changes are done. Kindly check. PFA Deliverables.
[Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4906324/Deliverables.zip)

**Comment by Narendiranath** [comment]
Hi Dhanwandher,

Changes are done. Kindly check. PFA Deliverables.
[Latest Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4906479/Latest.Deliverables.zip)

**Comment by Dhanwandher** [comment]
Dear Team....

Testing one completed....

Regards,,,
S.Dhanwandher....
[Sales.Register__PFS_Revised_V1.1 (3).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4906645/Sales.Register__PFS_Revised_V1.1.3.xlsx)
[sales register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4906646/sales.register.xlsx)
[Test Case for sales register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4906649/Test.Case.for.sales.register.xlsx)

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly Start Testing 2 & Prepare the Testing documents 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@Dhanwandher : please add sales type, customer type and also keep rate column in decimal 3 digits

**Comment by Dhanwandher** [comment]
Dear Sir....

New PFS has been updated.....

Regards....
S.Dhanwandher...
[Sales.Register__PFS_Revised.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4937637/Sales.Register__PFS_Revised.xlsx)

**Comment by raju-kurup** [comment]
@Dhanwandher : please give the test case for this ticket

**Comment by Dhanwandher** [comment]
Dear Sir....

New PFS has been updated.....

Regards....
S.Dhanwandher...
[Sales.Register__PFS_Revised.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4975331/Sales.Register__PFS_Revised.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction for the yellow colour marked.

**Comment by Narendiranath** [comment]
Hi Dhanwandher,

                            Changes are done. Kindly check.

**Comment by Dhanwandher** [comment]
Dear Sir.

The following changes need to done in GMBH Ou .
1. HSN Code not coming in report.
2. Customer VAT number should be incorporated in the report.
3. Ship To VAT number should be incorporated in the report.
4. Item Category Description not coming in the report.
5. VAT % and VAT Value should be incorporated in the report.
6. Total Tax Value(Tran) and Total Tax Value(Base) should be calculated according.
7. Invoice Value(Tran) and Invoice Value(Base) should be calculated according.

Regards.
S.Dhanwandher
[Sales register for GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5007098/Sales.register.for.GMBH.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as mentioned above.

**Comment by Dhanwandher** [comment]
Dear Sir.

The following changes need to done in GMBH Ou .

HSN Code not coming in report.
Customer VAT number should be incorporated in the report.
Ship To VAT number should be incorporated in the report.
Item Category Description not coming in the report.
VAT % and VAT Value should be incorporated in the report.
Total Tax Value(Tran) and Total Tax Value(Base) should be calculated according.
Invoice Value(Tran) and Invoice Value(Base) should be calculated according.

Regards.
S.Dhanwandher
[Sales register for GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5015723/Sales.register.for.GMBH.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction in GMBH OU.  Test data is attached and taken for the month of April 2020

**Comment by Narendiranath** [comment]
Hi Dhanwandher,

       Changes are done. Kindly check. PFA Report for your raference. Report taken from 01 Apr to 30 Apr 2020.
[Sales_Register_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5034666/Sales_Register_Report.xlsx)

**Comment by Dhanwandher** [comment]
Naren....

For MFG OU Customer pertainting to INR the following error is coming...
1.Ship to VAT number is coming.
2. VAT % and VAT Value is calculated.
3. Total Tax Value (Base) and Total Tax Value (Tran) are calculated wrong.

Regards.
S.Dhanwandher
[Sales Register error.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5048936/Sales.Register.error.xlsx)

**Comment by Narendiranath** [comment]
Hi Dhanwandher,

   Changes are done. Kindly check. PFA Report for your raference. Report taken from 01 Apr to 30 Apr 2020.
[Sales_Register_Report_MFGOU.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5055141/Sales_Register_Report_MFGOU.xlsx)

**Comment by Dhanwandher** [comment]
Team....
 
Testing one completed......

Regards....
S.Dhanwandher..
[Sales Register test result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5056758/Sales.Register.test.result.xlsx)
[Test Case for sales register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5056761/Test.Case.for.sales.register.xlsx)

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly Start Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srinivasanbaskaran,

Sales Register Testing 2 Completed Kindly Check & Update.

[Test.Case.for.sales.register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5084328/Test.Case.for.sales.register.xlsx)

[Sales Register Test Result All OUv2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5084347/Sales.Register.Test.Result.All.OUv2.zip)

Regards,
Akash

**Comment by Narendiranath** [comment]
Hi,

      PFA Latest deliverable.
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5084587/Deliverable.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

Sales Register Dcube Report Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS for MFG: [Sales.Register__PFS_Revised.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5090296/Sales.Register__PFS_Revised.xlsx)

PFS for GmbH: [Sales register for GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5090301/Sales.register.for.GMBH.xlsx)

DELIVERABLES: [Deliverable_Sales Register.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5090309/Deliverable_Sales.Register.zip)

TESTCASE1: [Test.Case.for.sales.register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5090342/Test.Case.for.sales.register.xlsx)

TEST RESULT1: [Sales.Register.test.result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5090344/Sales.Register.test.result.xlsx)

TESTCASE2: [Test.Case.for.sales.register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5084328/Test.Case.for.sales.register.xlsx)

TEST RESULT2: [Sales Register Test Result All OUv2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5084347/Sales.Register.Test.Result.All.OUv2.zip)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dhanwandher,

Please update the PFS as per the Customer's Requirements.

Please prepare the PFS along with Test Data & Review with Raju sir

Regards,
Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Dear Sir.....

As per Client requirement PFS has been updated.

1 Rate (Tran) and Rate (Base) Should come four decimals both in MFG and GMBH.
[Sales.register V1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5419544/Sales.register.V1.0.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please update the Rate (Trn) and Rate (Base) column to 4 decimal points in all OU.

**Comment by Narendiranath** [comment]
Hi Dhanwandher,

                            Changes are done. Kindly check. PFA Test Result for your ref.

![image](https://user-images.githubusercontent.com/59695578/97663710-4a62a380-1aa0-11eb-97be-8f8039cb6916.png)

**Comment by Dhanwandher** [comment]
Team.....

Testing one completed.....

[Test Case for sales register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5620598/Test.Case.for.sales.register.xlsx)
[Sales Register test result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5620599/Sales.Register.test.result.xlsx)

**Comment by AkashGleen** [comment]
Dear Sujin

Sales Register Testing 2 Completed, Kindly Check & Update.

[Test Result v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5628412/Test.Result.v2.xlsx)
[Test.Case.for.sales.register v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5628414/Test.Case.for.sales.register.v2.xlsx)

Regards,
Akash

**Comment by Manimahat** [comment]
@Narendiranath,

Kindly Attached the Latest deliverable.

Regards,
Manivel A

**Comment by Narendiranath** [comment]
Hi Manivel,

                   PFA Latest Deliverables for your ref.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5686725/Deliverable.zip)

**Comment by Manimahat** [comment]
@raju-kurup ,

Testing 1& 2 completed. All test Case , Result & Deliverable are attached in the ticket. Sales register Moved to green By Jyoti. Please Close this Ticket

Test case 1: [Test.Case.for.sales.register.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5686773/Test.Case.for.sales.register.xlsx)
 Test Result 1: [Sales.Register.test.result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5686774/Sales.Register.test.result.xlsx)
Test case 2: [Test.Case.for.sales.register.v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5686777/Test.Case.for.sales.register.v2.xlsx)
Test Result 2: [Test.Result.v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5686778/Test.Result.v2.xlsx)
Deliverable : [Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5686781/Deliverable.zip)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by Narendiranath** [comment]
Hi Manivel,

Report deployed this in live server. Kindly check. PFA Latest Deliverables.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5750670/Deliverable.zip)

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Sales Register report deployed successfully. Please Close this ticket.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
