### ISSUE TITLE
TRG - Fixed Asset Handout

### ISSUE THREAD

**Issue by Dhanwandher** [astpl1998/Jyoti-Ceramic#139]
Dear Srini....

Please find the Handout for Fixed Asset....Kindly check and revert back for any corrections for the same..
[JCIPL_FA_HANDOUT_1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3814173/JCIPL_FA_HANDOUT_1.0.docx)

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly check & Confirm the Fixed Asset Handout...

Regards,

Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Dhanwandher.......

Fixed Asset Handout Correction

              1.  6. Creation of Asset Location........... Path Screen..... Asset Location Type Missing in the Pic

              2.  4. Business Process Component (BPC):......... Pic Mistake

              3.  5. Creation of Asset Class........... Path Screen.... Land Information Required & Residual 
                       Value  Missing in the pic
                   
              4.  9. Creation of Budget......... Path Screen.... Allow Variance, Variance Percentage, Remarks 
                       Missing in the Pic

              5.  12. Create Complex Asset........ Path Screen.... Capitalization Amount Missing in the Pic

              6.  Kindly Update the Page Numbers.

Regards,

Akash
[JCIPL_FA_HANDOUT_1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3835729/JCIPL_FA_HANDOUT_1.1.docx)

**Comment by srinivasanbaskaran** [comment]
Dhanwandher,

Please Find the attached updated FA Handout.

HANDOUT: [JCIPL_FA_HANDOUT_v1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3901090/JCIPL_FA_HANDOUT_v1.2.docx)

Regards,
Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Sir.....

Kindly review the Fixed Asset and Kindly do the needful......

Regards....
S.Dhanwandher......
[JCIPL_FA_HANDOUT_v1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3903780/JCIPL_FA_HANDOUT_v1.2.docx)

**Comment by raju-kurup** [comment]
Please check the alignment of the page and send it to customer
