### ISSUE TITLE
TRG - Book Keeping Handout

### ISSUE THREAD

**Issue by Dhanwandher** [astpl1998/Jyoti-Ceramic#140]
Dear Srini....

Please find the Handout for Book Keeping.Kindly check and revert back for any corrections for the same..
[JCIPL_BK_HANDOUT_1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3814180/JCIPL_BK_HANDOUT_1.0.docx)

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly check & Confirm the Book Keeping Handout...

Regards,

Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Dhanwandher

Kindly Check the Book Keeping Handout and Revert

Correction
                   1. Page Number not Mention All Pages
                   2. Account Code Creation.........Path Screen Word Missing
                   3. Pic Mistake

Regards,

Akash
[JCIPL_BK_HANDOUT_1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3823448/JCIPL_BK_HANDOUT_1.1.docx)

**Comment by Dhanwandher** [comment]
Akash....

Please find the changes......

Regards.
S.Dhanwandher
[JCIPL_RECEIVABLE_HANDOUT_v1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3823894/JCIPL_RECEIVABLE_HANDOUT_v1.2.docx)

**Comment by AkashGleen** [comment]
Dear Srini......

Booking Keeping Handout Completed Kindly Check and Update.

Regards,

Akash
[JCIPL_BK_HANDOUT_v1.3.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3824296/JCIPL_BK_HANDOUT_v1.3.docx)

**Comment by srinivasanbaskaran** [comment]
Hi Dhanwandher,

Please fidn the attached Handout of Book Keeping. I have checked, all the detailes are correct. 

Kindly check & Proceed further 

Handout: [JCIPL_BK_HANDOUT_v1.4.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3829895/JCIPL_BK_HANDOUT_v1.4.docx)

Regards,

Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Sir....

Please find the attachment for Book Keeping handout....

Regards.
S. Dhanwandher....
[JCIPL_BK_HANDOUT_v1.4.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3835105/JCIPL_BK_HANDOUT_v1.4.pdf)

**Comment by raju-kurup** [comment]
Dhanwander - Please submit this handout to customer
