### ISSUE TITLE
TRG - Payable Management Handout

### ISSUE THREAD

**Issue by Dhanwandher** [astpl1998/Jyoti-Ceramic#141]
Dear Srini....

Please find the Handout for Payable Management....Kindly check and revert back for any corrections for the same..
[JCIPL_PAYABLE_HANDOUT_1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3814185/JCIPL_PAYABLE_HANDOUT_1.0.docx)

**Comment by srinivasanbaskaran** [comment]
Mani,

Kindly check & Confirm the Payable Handout...

Regards,

Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Dhanwandher,

I have checked the handout, kindly Following the below points, it will looks fine.

1. Re-arrange the table of content.
2. Kindly Highlight the Text and provide the Nos in the Screen shot.
3. kindly Remove the excess screen shot ( NO: 7.2)
4. kindly provide the Screen shot and Header text in single page.

Regards,
Manivel A

**Comment by Manimahat** [comment]
Hi Dhanwandhar,

I have attached the updated handout for payable management. Please find it.
Note : Kindly do the screen shot changes and text Alignment.

Updated Handout:  
[JCIPL_PAYABLE_HANDOUT_v1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3830957/JCIPL_PAYABLE_HANDOUT_v1.1.docx)


Regards,
Manivel A

**Comment by Dhanwandher** [comment]
Dear Mani.

Please Find the updated handout for payable management.


Regards.
S.Dhanwandher
[JCIPL_RECEIVABLE_HANDOUT_v1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3834186/JCIPL_RECEIVABLE_HANDOUT_v1.1.docx)

**Comment by Manimahat** [comment]
Hi Srinivasan,

I have checked the Payable handout, It is looking good and easy to understand.

Updated Handout : 
[JCIPL_PAYABLE_HANDOUT_v1.3.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3834617/JCIPL_PAYABLE_HANDOUT_v1.3.docx)


Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

Herewith I have attached Payable Mgnt handout (PDF version).

Kindly proceed further..

Handout (doc version):[JCIPL_PAYABLE_HANDOUT_v1.4.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3834793/JCIPL_PAYABLE_HANDOUT_v1.4.docx)
Handout (pdf version): [JCIPL_PAYABLE_HANDOUT_v1.4-converted.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3834794/JCIPL_PAYABLE_HANDOUT_v1.4-converted.pdf)

Regards,

Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dhanwandher - Please change the screenshot of BPC and path of supplier receipt.

**Comment by Dhanwandher** [comment]
Raju Sir...

Changes done sir....

Regards...
S.Dhanwandher

[JCIPL_PAYABLE_HANDOUT_v1.4.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3834986/JCIPL_PAYABLE_HANDOUT_v1.4.pdf)
[Uploading JCIPL_PAYABLE_HANDOUT_v1.4.docx…]()

**Comment by raju-kurup** [comment]
Handout can be submitted to customer
