### ISSUE TITLE
TRG -Receivable Management Handout

### ISSUE THREAD

**Issue by Dhanwandher** [astpl1998/Jyoti-Ceramic#142]
Dear Srini....

Please find the Handout for Receivable Management....Kindly check and revert back for any corrections for the same..
[JCIPL_RECEIVABLE_HANDOUT_1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3814194/JCIPL_RECEIVABLE_HANDOUT_1.0.docx)

**Comment by srinivasanbaskaran** [comment]
Mani,

Kindly check & Confirm the Receivable Handout...

Regards,

Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Dhanwandher,

I have checked the handout, kindly Following the below points, it will looks fine.

1. Re-arrange the table of content.
2. Kindly Highlight the Text and provide the Nos in the Screen shot.
3. kindly Remove the excess screen shot ( NO: 6 )
4. kindly provide the Screen shot and Header text in single page.

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Manivel,

Please find the attached Receivable Handout. 

Kindly check & Revert to Dhanwandher, Incase of any corrections

HANDOUT:[JCIPL_RECEIVABLE_MGNT_v1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3835844/JCIPL_RECEIVABLE_MGNT_v1.2.docx)

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

I have checked the handout, it is looking fine. Please fine the attached Document.

Handout : 
[JCIPL_RECEIVABLE_MGNT_v1.3.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3839492/JCIPL_RECEIVABLE_MGNT_v1.3.docx)

Regards,,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the attached Receivable Handout.

Kindly proceed further...

HANDOUT (pdf): [JCIPL_RECEIVABLE_MGNT_Updated_v1.4.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3839841/JCIPL_RECEIVABLE_MGNT_Updated_v1.4.pdf)
HANDOUT (doc): [JCIPL_RECEIVABLE_MGNT_v1.4.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3839842/JCIPL_RECEIVABLE_MGNT_v1.4.docx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Handout completed. Can be submitted to customer
