### ISSUE TITLE
TRG - Global Tax Solution Handout

### ISSUE THREAD

**Issue by Dhanwandher** [astpl1998/Jyoti-Ceramic#143]
Dear Srini....

Please find the Handout for Global Tax Solution...Kindly check and revert back for any corrections for the same..
[JCIPL_GTS_HANDOUT_1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3814202/JCIPL_GTS_HANDOUT_1.0.docx)

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly do the changes & Do the needful 

Regards,

Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

Kindly check the alignment and verified.

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Dhanwandher,

Please find the attached GTS Handout for your references.

HANDOUT: [JCIPL_GTS_HANDOUT_v1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3845093/JCIPL_GTS_HANDOUT_v1.1.docx)

Regards,
Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Sir....

Changes made......

Regards.
S.Dhanwandher
[JCIPL_GTS_HANDOUT_v1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3845196/JCIPL_GTS_HANDOUT_v1.2.docx)

**Comment by raju-kurup** [comment]
dhanwander - Change the handout heading and some more screens also to be added

**Comment by srinivasanbaskaran** [comment]
Dear Sir,

Herewith I have attached updated & Revised version of GTS Handout. 

Kindly proceed further..

HANDOUT: 
[JCIPL_GTS_HANDOUT_v1.3.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3850297/JCIPL_GTS_HANDOUT_v1.3.docx)

Regards,
Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Sir.

Changes done in GTS handout.....Kindly do the needful.....

Regards....
S.Dhanwandher

[JCIPL_GTS_HANDOUT_v1.3.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3900800/JCIPL_GTS_HANDOUT_v1.3.docx)

**Comment by raju-kurup** [comment]
Please check alignment and content letter size and send to customer
