### ISSUE TITLE
TRG - Management Accounting Handout

### ISSUE THREAD

**Issue by Dhanwandher** [astpl1998/Jyoti-Ceramic#144]
Dear Srini....

Please find the Handout for Management Accounting....Kindly check and revert back for any corrections for the same..
[JCIPL_MAC_HANDOUT_1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3814211/JCIPL_MAC_HANDOUT_1.0.docx)

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly check & Confirm the MAC Handout...

Regards,

Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Dhanwandher.......

MAC Handout Correction

         1. 10.3.2. Maintain Sales Cost Center..... Path Screen Mistake & Path Screen Word Mistake & 
              Cost Center and Effective date Pic Missing 

         2. 10.2.3. Define Usage for Maintain Purchase Cost Center....... Pic Mistake

         3. 10.2.2 Maintain Purchase Cost Center...... Path Screen Word Mistake & Cost Center and 
             Effective date Pic Missing 

         4. 10.2.1 Purchase Cost Center........ Additional Parameters Missing in the Path Screen Pic

         5. 10.1.2 Maintain Inventory Cost Center.......  Cost Center and Effective date Pic Missing 

         6. 10.1.1. Inventory Cost Center............ Additional Parameters Missing in the Path Screen Pic

         7. 9. Cost Center to Cost Element Mapping....... “MAP NORMAL COST ELEMENTS” button 
                 Missing in the Path Screen Pic

         8. Screen No : 7 & 8 Pic Same Pic Kindly Check

Kindly Check Above the Correction & do the Needful.

Regards,

Akash
[JCIPL_MAC_HANDOUT_1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3834863/JCIPL_MAC_HANDOUT_1.2.docx)

**Comment by Dhanwandher** [comment]
Dear Akash.....

Changes done kindly check......

Regards.
S.Dhanwandher
[JCIPL_MAC_HANDOUT_1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3863279/JCIPL_MAC_HANDOUT_1.2.docx)

**Comment by AkashGleen** [comment]
Dear Dhanwandher.....

MAC Handout Testing Completed Kindly Check & Update

Kindly Update All Page Numbers in Handout

Regards,

Akash
[JCIPL_MAC_HANDOUT_1.2 (2).docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3863813/JCIPL_MAC_HANDOUT_1.2.2.docx)

**Comment by Dhanwandher** [comment]
Dear Srini....

Please check the MAC handout......

Regards....
S.Dhanwandher
[JCIPL_MAC_HANDOUT_1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3867771/JCIPL_MAC_HANDOUT_1.2.docx)

**Comment by srinivasanbaskaran** [comment]
Dhanwandher,

Please find the updated version of MAC Handout..

Kindly proceed further 

HANDOUT: [JCIPL_MAC_HANDOUT_1.4.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3868315/JCIPL_MAC_HANDOUT_1.4.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Kindly check the Handout & Proceed further to the Customer 

Regards,
Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Sir.....

Checked and Kindly do the Needful.....

Regards....
S.Dhanwandher....
[JCIPL_MAC_HANDOUT_1.4.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3868953/JCIPL_MAC_HANDOUT_1.4.docx)

**Comment by raju-kurup** [comment]
Please refer page no : 9 & 10.

**Comment by Dhanwandher** [comment]
Sir.....

Changes has been done.....


Regards....
S.Dhanwandher...
[JCIPL_MAC_HANDOUT_1.5.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3891037/JCIPL_MAC_HANDOUT_1.5.docx)

**Comment by AkashGleen** [comment]
Sir, 

Mentioned Changes are corrected and overall verification also done.


Handout:  
[JCIPL_MAC_HANDOUT_1.6.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3891581/JCIPL_MAC_HANDOUT_1.6.docx)


Regards,
Akash

**Comment by raju-kurup** [comment]
Please do the page alignment and send to customer
