### ISSUE TITLE
IMP - Training and UAT - Quality

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#145]
Team,

Training & UAT to Quality Department

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Master Training Completed. 

Transaction related Training is pending & planned on 27/12/2019

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Transaction related Training Completed.

UAT is in INPROGRESS.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Training has been completed on 27-12-2019. 

User doing UAT. 

Kindly proceed further on this ticket.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Training completed so closing the ticket
