### ISSUE TITLE
TOOL : Automatically Effort Spent calculation in Project Progress Reporting

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#146]
Effort Spent field in Project Progress reporting screen should calculate automatically as per dated given.

Rtrack raised. 
JCIE-162

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Effort spent filed is to be given manually only. message from ramco.
![image](https://user-images.githubusercontent.com/47315921/73004336-1b424600-3e2d-11ea-89e6-67534b3d11d1.png)

**Comment by basha123456** [comment]
cumulative effort automatically caluculation document.
[Cummulative effort automatic calculation.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4104270/Cummulative.effort.automatic.calculation.docx)

**Comment by basha123456** [comment]
Dear Raju Sir,
Resolution for this open point is Accepted by the users. PFA of the resolution document
[2. Cummulative effort automatic calculation.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4174747/2.Cummulative.effort.automatic.calculation.docx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
please upload the signed copy.

**Comment by basha123456** [comment]
@raju-kurup 
CUstomer signed document for your reference

[effort spent calculation.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4338498/effort.spent.calculation.pdf)

**Comment by raju-kurup** [comment]
User accepted and signed off, so closing this issue.
