### ISSUE TITLE
TOOL : Maintenance Trigger for Tool - Quantity Basis

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#147]
Maintenance Trigger for Tool - Quantity Basis

Remarks: Need to check with Developers

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Srini,

Mail Trigger PFS is completed. need to review
[Maintenance Trigger for Tool - Quantity Based.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4015194/Maintenance.Trigger.for.Tool.-.Quantity.Based.xlsx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please Find the above attached PFS for Maintenance Trigger - Quantity Based

Kindly review the PFS 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Karthi,
Please start the development

**Comment by karthikeyanamitysoft** [comment]
Assign to Naredranath,

Regards,
Karthi

**Comment by raju-kurup** [comment]
Development completed.  Basha please check and revert

**Comment by basha123456** [comment]
Hi Naren,

follwing points are observered while testing the trigger. some corrections needs to be done. please check & correct.

![image](https://user-images.githubusercontent.com/47315921/72235961-f6fb9380-35fa-11ea-97ce-2acbaa68957e.png)

**Comment by Narendiranath** [comment]
Hi Basha,
              I completed the trigger. Kindly test and revert back.

**Comment by basha123456** [comment]
Hi Naren,

The trigger is not coming at exact intervals as per our conversation. kindly check & correct.

![image](https://user-images.githubusercontent.com/47315921/72797717-a5d94880-3c67-11ea-83d9-62263d038d63.png)

**Comment by Narendiranath** [comment]
Hi Basha,

  The trigger is now coming at exact intervals. kindly check & revert back.

**Comment by basha123456** [comment]
Hi Naren,
Trigger came for the correct intervals. but after the value in remarks whenever the parameter gets updated, everytime we need the trigger. please correct.
![image](https://user-images.githubusercontent.com/47315921/73118367-299d7880-3f79-11ea-9115-ea6f32303b09.png)

**Comment by Narendiranath** [comment]
Hi Basha,

The trigger is now coming at exact intervals. kindly check & revert back.

**Comment by basha123456** [comment]
@srinivasanbaskaran:

Testing1 is completed. please  do testing2.
[9. Maintenance Trigger for Tool - Quantity Basis.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4148007/9.Maintenance.Trigger.for.Tool.-.Quantity.Basis.docx)

**Comment by srinivasanbaskaran** [comment]
Dhanwandher,

Kindly start Test this report & Prepare the Testing Documents 

**NOTE**
Please call to Basha for KT on this report

Regards,

Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 2 Completed. Please find the attached file for your Ref...

Testing 2 : 
[Mail Trigger For Tool Production Quantity.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4189968/Mail.Trigger.For.Tool.Production.Quantity.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Manivel,

Please make the Testing Documents as per our format

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 2 Completed. Please find the attached file for your Ref..

Test Case : [Mail Trigger For Tool Production Quantity.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4347085/Mail.Trigger.For.Tool.Production.Quantity.xlsx)

Test Result : [Maintanance Mail Trigger Test Result Document.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4347086/Maintanance.Mail.Trigger.Test.Result.Document.docx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Naren,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Trigger for Tool Production Quantity testing has been completed. Herewith I have attached the Testing Documents for future references.

PFS: [Maintenance.Trigger.for.Tool_Quantity Based.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356453/Maintenance.Trigger.for.Tool_Quantity.Based.xlsx)

DELIVERABLES:

TESTCASE1 & TEST RESULT1: [Mail.Trigger.For.Tool.Production.Quantity_TC&TR.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356457/Mail.Trigger.For.Tool.Production.Quantity_TC.TR.xlsx)

TESTCASE2: [Mail.Trigger.For.Tool.Production.Quantity_Updated.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356459/Mail.Trigger.For.Tool.Production.Quantity_Updated.xlsx)

TEST RESULT2: [Maintanance.Mail.Trigger.Test.Result.Document.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356460/Maintanance.Mail.Trigger.Test.Result.Document.docx)

Regards,
Srinivasan Baskaran

**Comment by Narendiranath** [comment]
Hi Srini,

 I attached Deliverables for Tool Maintance Mail Trigger. Kindly check.

**Comment by Narendiranath** [comment]
[Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4358930/Deliverables.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

Trigger for Tool Production Quantity testing has been completed. Herewith I have attached the Testing Documents for future references.

PFS: [Maintenance.Trigger.for.Tool_Quantity Based.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356453/Maintenance.Trigger.for.Tool_Quantity.Based.xlsx)

DELIVERABLES: [Deliverables_147.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4362467/Deliverables_147.zip)

TESTCASE1 & TEST RESULT1: [Mail.Trigger.For.Tool.Production.Quantity_TC&TR.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356457/Mail.Trigger.For.Tool.Production.Quantity_TC.TR.xlsx)

TESTCASE2: [Mail.Trigger.For.Tool.Production.Quantity_Updated.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356459/Mail.Trigger.For.Tool.Production.Quantity_Updated.xlsx)

TEST RESULT2: [Maintanance.Mail.Trigger.Test.Result.Document.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356460/Maintanance.Mail.Trigger.Test.Result.Document.docx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested, so closing this ticket

**Comment by Narendiranath** [comment]
Hi,

As per Manivel told In this Tool Maintenance trigger i remove Sequence Number = 1 coding for Machine column logic.  Here i attach latest deliverables. Kindly check.
[Latest Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4808125/Latest.Deliverable.zip)

**Comment by Manimahat** [comment]
@raju-kurup Sir,

1. User needs to give mail ID at common place for all OU.
2. One tool Mapped with multiple Equipment / FG item, Multiple tool Mapped With Single FG Item.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Please Review the Updated PFS & allocated to Developers.

Updated PFS : [Maintenance.Trigger.for.Tool_Quantity.Based_1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5244727/Maintenance.Trigger.for.Tool_Quantity.Based_1.1.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do 2 correction in this trigger as 1. Conditions to be satisfied, 2. Mail id to kept at common place, mentioned in PFS.

**Comment by Narendiranath** [comment]
Hi Manivel,

                   Changes are done. Kindly check. PFA Latest deliverable for your referance.
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5261460/Deliverable.zip)

**Comment by Manimahat** [comment]
@AkashGleen ,

Kindly start testing 1 process.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 Completed. Kindly start testing 2 Process.

Test Case : [Mail.Trigger.For.Tool.Production.Quantity.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5296132/Mail.Trigger.For.Tool.Production.Quantity.xlsx)

Test Result : [Maintanance.Mail.Trigger.Test.Result.Document.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5296133/Maintanance.Mail.Trigger.Test.Result.Document.docx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Faisal,

Kindly start Testing 2 & Prepare the Testing Documents

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Kindly check.

Test Case : 
[Mail.Trigger.For.Tool.Production.Quantity.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5311159/Mail.Trigger.For.Tool.Production.Quantity.xlsx)

Test Result : 
[Maintanance.Mail.Trigger.Test.Result.Document.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5311161/Maintanance.Mail.Trigger.Test.Result.Document.docx)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Maintenance Trigger for Tool on Quantity Basis testing has been completed. Herewith I have attached the Testing Documents for future referencs.

PFS: [Maintenance.Trigger.for.Tool_Quantity.Based_1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5244727/Maintenance.Trigger.for.Tool_Quantity.Based_1.1.xlsx)

DELIVERABLES: [Deliverable_Quantity Basis.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5311395/Deliverable_Quantity.Basis.zip)

TESTCASE1: [Mail.Trigger.For.Tool.Production.Quantity.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5296132/Mail.Trigger.For.Tool.Production.Quantity.xlsx)

TEST RESULT1: [Maintanance.Mail.Trigger.Test.Result.Document.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5296133/Maintanance.Mail.Trigger.Test.Result.Document.docx)

TESTCASE2 : [Mail.Trigger.For.Tool.Production.Quantity.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5311159/Mail.Trigger.For.Tool.Production.Quantity.xlsx)

TEST RESULT2 : [Maintanance.Mail.Trigger.Test.Result.Document.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5311161/Maintanance.Mail.Trigger.Test.Result.Document.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Manivel,

Please do the PFS as per the Customer Requirements 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup sir,

Need to increase the Table Size trigger.  please Allocated to developers

 PDF : [Tool Qty.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5415485/Tool.Qty.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Karthi,

Please correct the above points from Manivel. Kindly co ordinate with Manivel & close this report

Regards,
Srinivasan Baskaran

**Comment by Narendiranath** [comment]
Hi Manivel,

                       Changes are done. Kindly check. PFA Latest deliverable & Test result.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5428296/Deliverable.zip)

![image](https://user-images.githubusercontent.com/59695578/96975910-ca38bd00-1538-11eb-8cd5-6d9c77e302fb.png)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 Completed. KIndly Proceed Testing 2 Process.

Test Case : [Maintanance.Mail.Trigger.Test.Result.Document .xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5463031/Maintanance.Mail.Trigger.Test.Result.Document.xlsx)

Test Result : [Maintanance.Mail.Trigger.Test.Result.Document .docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5463033/Maintanance.Mail.Trigger.Test.Result.Document.docx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Faizal,

Kindly start the Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Testing documents are attached.

Test Case : 
[Mail.Trigger.For.Tool.Production.Quantity.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5474084/Mail.Trigger.For.Tool.Production.Quantity.xlsx)

Test Result: 
[Maintanance.Mail.Trigger.Test.Result.Document.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5474085/Maintanance.Mail.Trigger.Test.Result.Document.docx)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Maintenance Trigger for Tool - Qunatity Basis Dcube Report testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [Maintenance.Trigger.for.Tool_Quantity.Based_1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5514848/Maintenance.Trigger.for.Tool_Quantity.Based_1.1.xlsx)

DELIVERABLES: [Tool Qyt_Deliverable_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5514851/Tool.Qyt_Deliverable_v1.1.zip)

TESTCASE1 : [Maintanance.Mail.Trigger.Test.Result.Document .xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5463031/Maintanance.Mail.Trigger.Test.Result.Document.xlsx)

TEST RESULT1: [Maintanance.Mail.Trigger.Test.Result.Document .docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5463033/Maintanance.Mail.Trigger.Test.Result.Document.docx)

TESTCASE2 : [Mail.Trigger.For.Tool.Production.Quantity.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5474084/Mail.Trigger.For.Tool.Production.Quantity.xlsx)

TEST RESULT2:  [Maintanance.Mail.Trigger.Test.Result.Document.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5474085/Maintanance.Mail.Trigger.Test.Result.Document.docx)

Regards,
Srinivasan Baskaran

**Comment by Narendiranath** [comment]
Hi,

               Please find Latest Deliverable for your ref.
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5708988/Deliverable.zip)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by Narendiranath** [comment]
Hi Sujin,

       Trigger deployed in live server. Kindly check. PFA Latest Deliverable for your ref.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5786909/Deliverable.zip)

**Comment by sujin1708** [comment]
deployment completed..kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
