### ISSUE TITLE
TOOL : Project Status Report - Meta data removal 

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#148]
Project Status Report - Meta data removal 

Rtrack - JCIE-163

Regards, 
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,
Toda , we got the solution for this issue. Herewith I have attached the query which was given by Ramco team. 

Kindly do the needful at earliest. 

NOTE:

Kindly backup the table component_metadata_table and delete the other values other project status

delete component_metadata_table(nolock)
where componentname = 'PRJREP'
and paramcategory = 'COMBO'
and paramtype = 'DOCTYPE'
and langid = @ctxt_language

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
COMPLETED

**Comment by basha123456** [comment]
Dear Raju Sir,
Resolution for this open point is Accepted by the users. PFA of the resolution document
[4. Project Staus Report - Meta Data Issue.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4174744/4.Project.Staus.Report.-.Meta.Data.Issue.docx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
please upload the signed copy.

**Comment by basha123456** [comment]
@raju-kurup 

CUstomer signed document for your reference

[meta data removal.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4338491/meta.data.removal.pdf)

**Comment by raju-kurup** [comment]
User accepted and signed off, so closing this issue.
