### ISSUE TITLE
TOOL - Project Status Report - Extra blank pages generated should be removed

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#149]
Dear Team,

Project   status Report - Extra blank pages generated should be removed

Rtrack - JCIE-171

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Fix deployed in UAT server by Karthi. Pls check & Let him know..

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
FIx is delopyed and now extra pages not generated in the report. its working fine now.
![image](https://user-images.githubusercontent.com/47315921/72881821-8144a580-3d27-11ea-8ae2-599b2d6d247c.png)

**Comment by basha123456** [comment]
Dear Raju Sir,
Resolution for this open point is Accepted by the users. PFA of the resolution document
[8. Extra blank pages removal in project status report.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4174740/8.Extra.blank.pages.removal.in.project.status.report.docx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
please upload the signed copy.

**Comment by basha123456** [comment]
@raju-kurup 
CUstomer signed document for your reference

[extra blank pages.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4338483/extra.blank.pages.pdf)

**Comment by raju-kurup** [comment]
User accepted and signed off, so closing this issue.
