### ISSUE TITLE
PPD : Create production order -Multiple items

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#150]
Dear Team,

Division   wise production order numbering series

Remarks: 
Need to Check   with developers

Regards,

Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
completed

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start the Testing of this logic & Update

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 2 completed. Please find the attachment for your ref...

Testing 2 Result : 
[Numbering Series PO for Divsion wise.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4163425/Numbering.Series.PO.for.Divsion.wise.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Karthi,

Kindly update the Latest Deliverables..

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
[production_order_number_trigger.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4285146/production_order_number_trigger.zip)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Create Production Order - Multiple Items logic development & Testing completed. 

Herewith, I have attached the Testing Documents for the future references.

PFS: [Nubering.Series.Production.Order.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4285238/Nubering.Series.Production.Order.xlsx)

DELIVERABLES: [production_order_number_trigger.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4285239/production_order_number_trigger.zip)

TESTING DOCUMENT: [Numbering.Series.PO.for.Divsion.wise_Updated.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4285243/Numbering.Series.PO.for.Divsion.wise_Updated.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested, so closing this issue

**Comment by Manimahat** [comment]
@raju-kurup Sir,

To be Deployed in this automation in Live Server. Please Allocate this ticket to developer.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by karthikeyanamitysoft** [comment]
Dear Mani,

Deliverables Deployed in live server.

REgards,
Karthi
[prodno_trigger.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5785624/prodno_trigger.zip)

**Comment by sujin1708** [comment]
deployment completed ..kindly close the ticket

**Comment by Narendiranath** [comment]
Hi Sujin,

         PFA Latest Deliverable for your ref. 

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5959561/Deliverable.zip)

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket

**Comment by sujin1708** [comment]
@Narendiranath as dsicussed with u and raju sir kindly apply the below logic

Finanacial year logic is based on production order start date

[Nubering.Series.Production.Order V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6862249/Nubering.Series.Production.Order.V1.1.xlsx)

**Comment by Narendiranath** [comment]
@sujin1708 

     Above mentioned logic is applied. Kindly check & revert back. PFA Latest deliverable or your ref.

[Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6866970/Deliverables.zip)

**Comment by Narendiranath** [comment]
@sujin1708 

     Above mentioned logic is applied. Kindly check & revert back. PFA Latest deliverable or your ref.

[Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6866970/Deliverables.zip)
