### ISSUE TITLE
PPD : Production order tollerance logic testing

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#152]
Dear Team,
PFA below Latest Open Points

1. Tolerance   for production order Qty

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer given confirmation so closing this issue
