### ISSUE TITLE
S&S : GST Invoice in Base Currency for Export

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#153]
Dear Team,

GST Invoice and commercial invoice need different Currency while doing the Export transactions

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Need to development a report like Currency Difference in the Existing Invoice Print 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

PFS is completed. please review.

[PFS Postshipment - Currency difference in GST & Commercial Invoice.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414634/PFS.Postshipment.-.Currency.difference.in.GST.Commercial.Invoice.xlsx)

**Comment by srinivasanbaskaran** [comment]
Sir,

Please Review the below PFS & Proceed to the further development 

PFS: [Different_Currency_GST Invoice_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4443560/Different_Currency_GST.Invoice_v1.1.xlsx)

Regards,
Srinivasan

**Comment by Nandhineedevi** [comment]
Hi Raju Sir,
As discussed, The development will be taken after you have confirmed.

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir, 
Please find the attached updated PFS & Test Data

PFS: 
[00_PFS_GST Invoice for Base Currency_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4774404/00_PFS_GST.Invoice.for.Base.Currency_v1.0.xlsx)

**Comment by srinivasanbaskaran** [comment]
@Manimahat,

Pls prepare the Test Data as discussed

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

please find the test data in this PFS.

Test Data : [00_PFS_GST Invoice for Base Currency_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4779274/00_PFS_GST.Invoice.for.Base.Currency_v1.0.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the attached PFS along with Test Data 

PFS: [00_PFS_GST Invoice for Base Currency_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4779649/00_PFS_GST.Invoice.for.Base.Currency_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per mentioned in PFS and test data is attached.

**Comment by badamnarendra028** [comment]
PACKING CHARGES,fright charges,insurance charges,rate in rs,value in rs 
exchange rate has been added 
kindly check and revert
--

**Comment by Manimahat** [comment]
@badamnarendra028 ,

1. Report is Showing Error While Selected Transaction Currency, Please resolve It.
2. Other Currency Is not Converted with Exchange rate in the Base Currency in UDS Screen. 
  Please Check & Resolve It.

Regards,
Manivel A

**Comment by badamnarendra028** [comment]
[22--06.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4813855/22--06.pdf)
[transactio.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4813856/transactio.pdf)
completed kindly check

**Comment by Manimahat** [comment]
@badamnarendra028,

![image](https://user-images.githubusercontent.com/55881685/85304841-d993f500-b4c9-11ea-9148-0b68257f7525.png)

Please Resolve below Points 
1. 2 numbers only Come After the Decimal in the Rate & Value Column.
2. Total is Incorrect 
3. Freight Charges is not Calculated With Exchange Rate
4. Packing & Forwarding Charges is not Calculated With Exchange Rate
5. Insurance Charges is not Calculated With Exchange Rate

Test Data Attached in this Ticket, Please Refer it.

Regards,
Manivel A

**Comment by badamnarendra028** [comment]
[base.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4817374/base.pdf)
[tran_cation.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4817377/tran_cation.pdf)
completed kindly check

**Comment by Manimahat** [comment]
@srinivasanbaskaran,

Testing 1 completed. Kindly Start The Testing 2 process.

Test Case : [Testcase1_GST.Invoice_ Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4823032/Testcase1_GST.Invoice_.Export.xlsx)

Test Result : [GST Invoice For Export.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4823033/GST.Invoice.For.Export.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@eafaisal kindly do the testing 2 and prepare test case

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.Kindly verify.

1.Test Case : 
[Testcase2_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4840453/Testcase2_GST.Invoice_.Export.xlsx)
2. Test Result : 
[GST Invoice For Export.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4840454/GST.Invoice.For.Export.pdf)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Sir,

GST Invoice in Base Currency for Export report testing has been completed. Herewith, I have attached the Testing Documents for future references.

PFS: [00_PFS_GST_Invoice for Base Currency_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886015/00_PFS_GST_Invoice.for.Base.Currency_v1.0.xlsx)

DELIVERABLES:

TESTCASE1: [Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886017/Testcase1_GST.Invoice_.Export.xlsx)

TEST RESULT1: [GST.Invoice.For.Export_TR1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4886018/GST.Invoice.For.Export_TR1.pdf)

TESTCASE2: [Testcase2_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886023/Testcase2_GST.Invoice_.Export.xlsx)

TEST RESULT2: [GST.Invoice.For.Export_TR2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4886025/GST.Invoice.For.Export_TR2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
@badamnarendra028 ,

Kindly update the Latest Deliverables ASAP....

Regards,
Srinivasan

**Comment by badamnarendra028** [comment]
[jcie-251.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4895184/jcie-251.zip)
updated

**Comment by badamnarendra028** [comment]
[jcie-251 (2).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4903036/jcie-251.2.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

GST Invoice in Base Currency for Export report testing has been completed. Herewith, I have attached the Testing Documents for future references.

PFS: [00_PFS_GST_Invoice for Base Currency_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886015/00_PFS_GST_Invoice.for.Base.Currency_v1.0.xlsx)

DELIVERABLES: [jcie-251.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4904169/jcie-251.2.zip)

TESTCASE1: [Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886017/Testcase1_GST.Invoice_.Export.xlsx)

TEST RESULT1: [GST.Invoice.For.Export_TR1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4886018/GST.Invoice.For.Export_TR1.pdf)

TESTCASE2: [Testcase2_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886023/Testcase2_GST.Invoice_.Export.xlsx)

TEST RESULT2: [GST.Invoice.For.Export_TR2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4886025/GST.Invoice.For.Export_TR2.pdf)

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[jcie-251 (3).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4912533/jcie-251.3.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

GST Invoice in Base Currency for Export report testing has been completed. Herewith, I have attached the Testing Documents for future references.

PFS: [00_PFS_GST_Invoice for Base Currency_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886015/00_PFS_GST_Invoice.for.Base.Currency_v1.0.xlsx)

DELIVERABLES: 
[jcie-251.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5088377/jcie-251.3.zip)

TESTCASE1: [Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886017/Testcase1_GST.Invoice_.Export.xlsx)

TEST RESULT1: [GST.Invoice.For.Export_TR1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4886018/GST.Invoice.For.Export_TR1.pdf)

TESTCASE2: [Testcase2_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886023/Testcase2_GST.Invoice_.Export.xlsx)

TEST RESULT2: [GST.Invoice.For.Export_TR2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4886025/GST.Invoice.For.Export_TR2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Mani,

Please do the modeling of DUTY PAID & PER 100 along with Modeling Data 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Faizal,

Prepare the Testdata

Regards,
Srinivasan

**Comment by eafaisal** [comment]
@Manimahat 

Kindly check.

New Invoice Format : 
[PFS_Base.Currency.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5121533/PFS_Base.Currency.xlsx)

Regards,
Faisal

**Comment by Manimahat** [comment]
@raju-kurup sir,

Please review the Updated PFS & allocated to developers.

Updated PFS: [GST Invoice _Base Currency for Export_PFS.v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5129123/GST.Invoice._Base.Currency.for.Export_PFS.v1.2.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction of column interchange of Qty, Rate, Unit and rate column should have 5 decimal points.

**Comment by badamnarendra028** [comment]
[jcie-303.2 (2).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5157580/jcie-303.2.2.zip)
completed kindly check and revert

**Comment by Manimahat** [comment]
@badamnarendra028 ,

As discussed with you & karthick please fixed Header & footer for all the pages.

Regards,
Manivel A

**Comment by badamnarendra028** [comment]
[Sale Invoice GST base currency for Export.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5282506/Sale.Invoice.GST.base.currency.for.Export.pdf)
[Uploading jcie-303.2 (4).zip…]()
as discussed completed

**Comment by badamnarendra028** [comment]
[Uploading jcie-303.2 (4).zip…]()

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 Completed, Kindly Proceed testing 2.

Test Case : [Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5288670/Testcase1_GST.Invoice_.Export.xlsx)

Test Result : [Sale GST invoice for Export.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5288674/Sale.GST.invoice.for.Export.pdf)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@eafaisal ,

Kindly Start testing 2 Process. prepare documents as per new format

Regards,
Manivel A

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Kindly check.

Test Case : 
[Testcase2_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5304521/Testcase2_GST.Invoice_.Export.xlsx)

Test Result : 
[Sale.GST.invoice.for.Export.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5304525/Sale.GST.invoice.for.Export.pdf)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Badam,

Kindly update the Deliverables correctly. I cant able to download the deliverables. 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

GST Invoice in Bas Currency for Export Report Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [GST.Invoice._Base.Currency.for.Export_PFS.v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5305184/GST.Invoice._Base.Currency.for.Export_PFS.v1.2.xlsx)

DELIVERABLES:

TESTCASE1: [Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5288670/Testcase1_GST.Invoice_.Export.xlsx)

TEST RESULT1 : [Sale GST invoice for Export.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5288674/Sale.GST.invoice.for.Export.pdf)

TESTCASE2: [Testcase2_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5304521/Testcase2_GST.Invoice_.Export.xlsx)

TEST RESULT2: [Sale.GST.invoice.for.Export.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5304525/Sale.GST.invoice.for.Export.pdf)

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[jcie-303.2 (4).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5306861/jcie-303.2.4.zip)
attached

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

GST Invoice in Bas Currency for Export Report Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [GST.Invoice._Base.Currency.for.Export_PFS.v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5305184/GST.Invoice._Base.Currency.for.Export_PFS.v1.2.xlsx)

DELIVERABLES: [jcie-303.2.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5310239/jcie-303.2.4.zip)

TESTCASE1: [Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5288670/Testcase1_GST.Invoice_.Export.xlsx)

TEST RESULT1 : [Sale GST invoice for Export.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5288674/Sale.GST.invoice.for.Export.pdf)

TESTCASE2: [Testcase2_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5304521/Testcase2_GST.Invoice_.Export.xlsx)

TEST RESULT2: [Sale.GST.invoice.for.Export.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5304525/Sale.GST.invoice.for.Export.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly prepare the PFS as per the Requirement of the Customer & Prepare the Test Data also

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Please review the Updated PFS & allocated to developers.

Updated PFS: [GST.Invoice._Base.Currency.for.Export_PFS.v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5413438/GST.Invoice._Base.Currency.for.Export_PFS.v1.3.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction of 1entry as per PFS, badam has done this report

**Comment by badamnarendra028** [comment]
raised ticket for INR symbol JCIE-335

**Comment by badamnarendra028** [comment]
[jcie-303.2 (5).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5429259/jcie-303.2.5.zip)
[rate_in_rs.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5429262/rate_in_rs.pdf)
completed kindly and revert

**Comment by Manimahat** [comment]
@karthikeyanamitysoft ,

Round off value is wrong beacuse of round off value is not multiplied with Exchange rate. Please change it.

Thanks,
Manivel A

**Comment by karthikeyanamitysoft** [comment]
Dear Mani,

Kindly check and confirm.
1.Exchange Rate multiplied with round off
2.multiline Heading not able to change Bold

Regards,
Karthi

**Comment by Manimahat** [comment]
@Narendiranath ,

1. Round off value should multiplied with Exchange rate.
2. Amount in words should fetch from net amount value & it should be Rupees only even though it is foreign currency
3. CIF/FOB value should fetch from gross amount
4. Net FOB value should fetch from CIF/FOB value - ( Frighet + Insurance)
5.IGST involved (18%) = CIF/ FOB value /0.18%

Regards,
Manivel A

**Comment by Narendiranath** [comment]
Hi Manivel,

Changes are done. Kindly check. PFA Latest Deliverable & Test result for your ref.

![image](https://user-images.githubusercontent.com/59695578/97441341-a1586380-194e-11eb-9222-f182a0a302e1.png)

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5452091/Deliverable.zip)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 Completed. Kindly proceed testing 2 process

Test case : [Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5463005/Testcase1_GST.Invoice_.Export.xlsx)

Test Result : [GST Invoice Base currency -Export.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5463008/GST.Invoice.Base.currency.-Export.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Faizal,

Kindly start the Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@Narendiranath ,

in the report following points to be corrected ,
1.Net FOB value to be corrected
2. need to be add currency Symbol in Rate & value column
3. Need to Handle If same item code has scheduled with different in one Pack slip. it should be sum in the report.

regards,
Manivel A

**Comment by Narendiranath** [comment]
Hi Manivel,

             Changes are done. Kindly check. PFA Latest Deliverable for your ref.
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5485965/Deliverable.zip)

**Comment by Narendiranath** [comment]
Hi,

    PFA Latest Deliverable & Test Result For your Ref.

[New Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5487245/New.Deliverable.zip)

![image](https://user-images.githubusercontent.com/59695578/98101447-3b249100-1eb8-11eb-8332-70ebc171ac3a.png)

**Comment by Narendiranath** [comment]
Hi,

PFA Latest Deliverable
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5504535/Deliverable.zip)

**Comment by Manimahat** [comment]
@AkashGleen ,

Testing 1 Completed. Kindly Proceed Testing two Process.

Test Case : [Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5508642/Testcase1_GST.Invoice_.Export.xlsx)

Test Result ; [GST_invoice base Currency.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5508643/GST_invoice.base.Currency.pdf)

Regards,
Manivel A

**Comment by Narendiranath** [comment]
Hi,

Please find Latest Deliverable for your ref.
[cobsigs_gst_pr_grd1_gr.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5558104/cobsigs_gst_pr_grd1_gr.zip)

**Comment by AkashGleen** [comment]
Dear Mani,

GST Invoice in Base Currency for Export Testing 2 Completed.

[Test Result For Sale GST Export.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5564979/Test.Result.For.Sale.GST.Export.pdf)
[Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5564980/Testcase1_GST.Invoice_.Export.xlsx)

Regards,
Akash

**Comment by Manimahat** [comment]
@Narendiranath ,

Need to remove Round off Column & Exchange rate Full value Should be multiplied with the amount.

Regards,
Manivel A

**Comment by Narendiranath** [comment]
Hi Manivel,

      Changes are done. Kindly check. PFA Latest Deliverables for your ref.

[Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5610113/Deliverables.zip)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 completed. Kindly Start testing 2 process.

Test Case: [Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5613915/Testcase1_GST.Invoice_.Export.xlsx)

Test Result : [GST_Invoice Base Currency Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5613916/GST_Invoice.Base.Currency.Report.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@AkashGleen kindly do the testing 2

**Comment by AkashGleen** [comment]
Dear Sujin

GST Invoice  in Base Currency for Export Testing 2 Completed.

[Sales GST Invoice Export Test Result v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5628655/Sales.GST.Invoice.Export.Test.Result.v2.pdf)
[Testcase1_GST.Invoice_.Export (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5628657/Testcase1_GST.Invoice_.Export.1.xlsx)

Regards,
Akash

**Comment by sujin1708** [comment]
PFS : [00_PFS_GST_Invoice.for.Base.Currency_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5650424/00_PFS_GST_Invoice.for.Base.Currency_v1.0.xlsx)
Deliverables : [Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5650425/Deliverable.zip)
Test Result1 : [Uploading GST_Invoice.Base.Currency.Report.pdf…]()
Test Case1 :[Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5650427/Testcase1_GST.Invoice_.Export.xlsx)

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Please review the Updated PFS & allocated to Developers.

Updated PFS: [GST.Invoice._Base.Currency.for.Export_PFS.v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5752916/GST.Invoice._Base.Currency.for.Export_PFS.v1.4.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per PFS.

**Comment by Jeyapriyat** [comment]
@Manimahat 
changes completed .kindly check and revert.
i hava attached latest deliverables.
[deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5801781/deliverables.zip)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 Completed. Kindly Start the Testing 2 Process.

Test Case : [Testcase1_GST.Invoice_.Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5827362/Testcase1_GST.Invoice_.Export.xlsx)

Test Result : [GST.Invoice.For.Export (1).pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5827388/GST.Invoice.For.Export.1.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@AkashGleen kindly do the testing2 and prepare test case for this

**Comment by AkashGleen** [comment]
Dear Sujin,

GST Invoice Base Currency for Export Testing 2 Completed.

[Test Case For GST Invoice v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5864244/Test.Case.For.GST.Invoice.v2.xlsx)

[Test Result For GST Invoice v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5864249/Test.Result.For.GST.Invoice.v2.pdf)

Regards,
Akash

**Comment by Manimahat** [comment]
@Jeyapriyat ,

 Kindly Remove the below Logic in the Coding. Remaining things is Ok. 

If Sale UOM is PER100 means Quantity should multiplied with 100 & Rate divided by 100.

Regards,
Manivel A

**Comment by mohanaamity** [comment]
@Manimahat 

100 PER logic has been modified. 
[deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5949286/deliverables.zip)

Regards,
Mohana B
Kindly check and confirm.

**Comment by Manimahat** [comment]
@sujin1708,

Testing 1 Completed. Kindly Proceed Testing 2 Process.

Test Case : [Testcase1_GST.Invoice_.Export_1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6240341/Testcase1_GST.Invoice_.Export_1.xlsx)

Test Result : [GST.Invoice.For.Export.1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6240349/GST.Invoice.For.Export.1.pdf)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Pl deploy this in   live server
--

**Comment by sujin1708** [comment]
@raju-kurup Testing 2 completed ..kindly check and move to next level

Test Case 2 : [Testcase1_GST.Invoice_.Export_1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6269524/Testcase1_GST.Invoice_.Export_1.xlsx)
Test Result 2 : [GST.Invoice.For.Export.1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6269523/GST.Invoice.For.Export.1.pdf)
Deliverables : [deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6269529/deliverables.zip)

**Comment by raju-kurup** [comment]
Deployed in live server, so closing this ticket.  This ticket is same as GST Invoice.
