### ISSUE TITLE
PPD : Fired Qty as Auto Generated

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#154]
Dear Team,

User wants that Fired Qty dhould be Triggered Automatically

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
Not possible

**Comment by raju-kurup** [comment]
Please mention the communication details.

**Comment by sujin1708** [comment]
@raju-kurup through verbally communicated at the time of open point discussion its not possible please close the ticket.

**Comment by raju-kurup** [comment]
Verbally communicated to Jyoti, so closing this ticket.
