### ISSUE TITLE
I&P : Numbering Type based on Item Category

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#156]
Dear Team.

Numbering   type and Item category should be same, while creating an item , at the time of creation system   through error if mismatched.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Solution for the above Query,

Checked with Karthi by Mahesh.

Its possible 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Trigger to create & Tested on or before 16-01-2020

Srinivasan need to give logic to Karthi

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Open Points on 13-01-2020 

1. User wise access details are to be loaded in the Item Type field ( Meta Data should not loaded like that )

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the attached PFS for the Logic of Item Code creation based on the Numbering Type.

PFS: [Item Category & Numbering Type_Trigger Logic.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4087775/Item.Category.Numbering.Type_Trigger.Logic.docx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Please do the error trigger for the above said details

**Comment by karthikeyanamitysoft** [comment]
completed

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

This requirement has been explained to the Users. They are Accepted this. 

Kindly proceed further on this.

**Resolution Doc:** 
[01_Resolution Doc for Sales & Shipping OpenPoint 1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4180093/01_Resolution.Doc.for.Sales.Shipping.OpenPoint.1.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Please attach the document of user accpetance.

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

As we discussed earlier, Sunil faced this error. 

Newly created Item Category & Numbering Type has not been validated. 

Kindly inform to the Developer to check this.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Please check the validation regarding the item creation logic

**Comment by karthikeyanamitysoft** [comment]
as we discussed completed kindly update the discussed logic on Comments

**Comment by srinivasanbaskaran** [comment]
Karthi,

As we discussed, Please find the below logic for the Numbering Type & Category validation.

•	While Creating the Item code, system should check the Item category & Numbering Type. 
•	Both Item Category & Numbering Type should be equal. If it is equal means, system allowed to Create the Item Code based on the Numbering type. If it is not equal means should throw an error message like “Item Category & Numbering Type is not Equal. Please Check” 

Regards,
Srinvasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
[itm_mst_trigger_num_ser.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4358105/itm_mst_trigger_num_ser.zip)

**Comment by karthikeyanamitysoft** [comment]
as we discussed completed for given itemcode check with different data and confirm.

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

This requirement has been explained to the Users. They are Accepted this.

Kindly proceed further on this.

Resolution Signed Doc: [NT Validation.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4358926/NT.Validation.pdf)
 
Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested, so closing this issue

**Comment by raju-kurup** [comment]
Development completed and tested, so closing this issue

**Comment by Manimahat** [comment]
@raju-kurup Sir,

System doesn't allow the variant for Same item code So we Need  to change the Logic.

**Comment by Manimahat** [comment]
@raju-kurup Sir,

System doesn't allow the variant for Same item code So we Need to change the Logic

**Comment by karthikeyanamitysoft** [comment]
This trigger is checking whether numbering type will same with item category, if need to change the logic kindly mention the new logic.

Regards,
Karthi

**Comment by karthikeyanamitysoft** [comment]
[trigger itm_mst_trigger_num_ser.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6431750/trigger.itm_mst_trigger_num_ser.zip)
final deliverables attached

**Comment by Manimahat** [comment]
@sujin1708 ,

Variant code is Allowing for same Item Code as well numbering type Error also working. Kindly close this Ticket

Resolution Signed Doc. : [NT.Validation.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6691386/NT.Validation.pdf)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup sir,

Variant code is Allowing for same Item Code as well numbering type Error also working. Kindly close this Ticket

Resolution Signed Doc. : [NT.Validation.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6824700/NT.Validation.pdf)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup sir,

We have done the Development in the Item master.. if item category & numbering type is same that time only it should allow to generate the item code. otherwise it should through error. Kindly close this Ticket

We have deployed the item category & numbering type Development in both UAT & live server through call Successfully.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
