### ISSUE TITLE
S&S : Sale Order related Issues

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#157]
Dear Team,

PFA Updated open points in Sale Order 

1.TCD   Not transfer to Sale Order via Quotation     
2.UOM Decimal allowed in Stock Inquiry. But In master Decimal Req. set as   "NO"

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Solution for the above queries

1.TCD is transferred to Sale Orderfrom Quotation
2. Checked in Stock Report, All the values are correct as per the UOM. But Exsiting Data should not be able to change.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,

For this Report, Document prepared & Need to Explain to the Users

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Explained to the Users & They are Accepted this solution. 

Kindly proceed this to further

**Resolution Doc:**[01_Resolution Doc for Sales & Shipping OpenPoint 1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4180072/01_Resolution.Doc.for.Sales.Shipping.OpenPoint.1.docx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
please upload the signed copy.

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Explained to the Users & They are Accepted this solution.

Kindly proceed this to further

Resolution Doc: [01_Resolution.Doc.for.Sales.Shipping.OpenPoint.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/6820538/01_Resolution.Doc.for.Sales.Shipping.OpenPoint.1.docx)

Note: Still now They haven't provide the Signed copy.. So we have consider this point is Closed

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Document shared, so closing this ticket
