### ISSUE TITLE
TOOL : Single Material Request for Multiple Projects

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#160]
Dear Team,

Following are the queries which was raised at the time of Training 
Single Material Request for Multiple Projects

Solution:
MR can   be raised for 1 Project… for multiple projects single MR can't be raised

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Single Material Request is not possible for Multiple projects. MR can generate for 1 project only.
[160. Single MR for Multiple Projects.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4018664/160.Single.MR.for.Multiple.Projects.docx)

**Comment by basha123456** [comment]
Explained to user and user agreed for the solution.

**Comment by basha123456** [comment]
[160. Single MR for Multiple Projects.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4052216/160.Single.MR.for.Multiple.Projects.docx)

**Comment by basha123456** [comment]
Dear Raju Sir,
Resolution for this open point is Accepted by the users. PFA of the resolution document
[7. Single MR for Multiple Projects.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4174734/7.Single.MR.for.Multiple.Projects.docx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
please upload the signed copy.

**Comment by basha123456** [comment]
@raju-kurup 
CUstomer signed document for your reference
[single MR for multiple projects.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4338475/single.MR.for.multiple.projects.pdf)

**Comment by raju-kurup** [comment]
User accepted and signed off, so closing this issue.
