### ISSUE TITLE
TOOL : Reporting of 2 qty separately for the tool

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#161]
Dear Team,

QUERIES:
1. While reporting 2 items produced from the same tool -parameter should be updated in   the same tool

Solution:
1. We have to map the tool code through process unit. Hence this issue will be take

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Explained to user and user agreed for the solution.

**Comment by basha123456** [comment]
Dear Raju Sir,
Resolution for this open point is Accepted by the users. PFA of the resolution document
[6. First piece & last piece reporting - qty updated for the tool.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4174728/6.First.piece.last.piece.reporting.-.qty.updated.for.the.tool.docx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
please upload the signed copy.

**Comment by basha123456** [comment]
@raju-kurup 

CUstomer signed document for your reference
[reporting of 2 qty.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4338471/reporting.of.2.qty.pdf)

**Comment by raju-kurup** [comment]
User accepted and signed off, so closing this issue.
