### ISSUE TITLE
PPD : Extrusion Mould change rejection how to account

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#162]
Dear Team,

Queries:

Mould change rejection??

Sol : Through scrap we have to report

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@raju-kurup Delivered to customer kindly close the ticket

**Comment by raju-kurup** [comment]
Attach the document

**Comment by sujin1708** [comment]
@raju-kurup documet attached kindly close the ticket
[01_Mould Change Rejection.12.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/7029427/01_Mould.Change.Rejection.12.docx)

**Comment by raju-kurup** [comment]
Document shared to customer, so closing this ticket
