### ISSUE TITLE
PPD : Report Production Two different stages – select same process unit scenario to check

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#163]
1. Godown –   After sorting, who will move the reported qty
2. Two different stages – select same process unit
3. When we   go kg to Pcs. In one stage to another stage Unit must be change     
           i) Primary output –FG & intermediate in pcs      
          ii) Input – should be in kgs
4. In extrusion End Pcs, caps, pins, How to account? And material batch consumption
5. Different   variant in one code is not working
6. After double disc stage QC not required
7. NRGP is not clear
8. QC Rejected some qty after fired – for re-firing. How to report re-fired qty in   system
9. Product   have process stages in press shop and extrusion then how it will be report in   system??     Can we change process unit in running production –???
10. When   final sorting done, some Qty. send to unitech for reprocess??
11. In sales   order drawing attachment mandatory
12. Infurnace   - we reporting car wise
13. How to report when   customer send some assembly parts. (Shafts)

Solution:
1. Go down   as process stage ->> Stage authorization & movement will be done be        by dispatch
2.One   process stage –multiple process units (report multiple times)
4. Open   production order the above items in kgs      In case if you want to convert above items from rejected moulds then use   product conversion
5. System   will support variant, logic has to be defined by Jyoti
6. As confirmed by Jyoti we are removing qc from this stage
7. Scenario   shown to user on 24.12.2019
8. Has to be rejected in the firing stage and that has to be done through separate work   order
9. i) We   have to change configuration from logic of department wise for this   codification      of process stage has to be commonized for all departments
10.  “held” full qty in qc and    rework immediately then continue the process     2. Reject the item and move rejection warehouse –and rework after sometimes
11. In sale   order some field has to be made mandatory, if typed “yes” by the sales person      he has to attach the drawing. If typed “no” he need not do the attach
12. We have   to change configuration from logic of department wise for this codification        of process stage has to be commonized for all departments
13. In the   sale order customer supplied parts will be mapped, this will be taken into   the      warehouse through a GRN-goods receipt note, during production this item   will be drawn from the stores and assembled

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
SDD : [01_Process.Production.OpenPoint.6.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4123066/01_Process.Production.OpenPoint.6.docx)

**Comment by sujin1708** [comment]
@raju-kurup Document shared to customer .kindly close the ticket

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, but confirmation not given. Anyhow we are closing this ticket.
