### ISSUE TITLE
PPD : Trigger for Packing Material in Production Order

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#164]
new requirement from mr.goutham

**Comment by srinivasanbaskaran** [comment]
pack id not workable for the customer and we want trigger on material request(MR)..fecability has to be estabilish by sujin and karthick on authorization of production order

**Comment by sujin1708** [comment]
[PFS. Trigger For Material Request V1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4394611/PFS.Trigger.For.Material.Request.V1.0.xlsx)

**Comment by raju-kurup** [comment]
@sujin1708 : We cannot create a pop-up message in base message.  So email trigger is possible, so speak to customer and correct the PFS accordingly

**Comment by sujin1708** [comment]
@raju-kurup they agreed plz go with email trigger
Email id : sujin@amitysoft,com

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As discussed with sujin, please do the email trigger with the email id mentioned in the Github (sujin@amitysoft,com)

**Comment by sujin1708** [comment]
in mail trigger add po -- item description /qty/ & production order end date

**Comment by badamnarendra028** [comment]
completed kindly check

**Comment by sujin1708** [comment]
@Manimahat Check the mail came as per the logic are not..

**Comment by Manimahat** [comment]
@ sujin,

I have Gotten Wrong PO Mail trigger.  Plz find the Screen Shot.

Wrong PO 1. : ![image](https://user-images.githubusercontent.com/55881685/78469252-13602580-773d-11ea-998d-5b319cdc8ca5.png)

2. ![image](https://user-images.githubusercontent.com/55881685/78469294-70f47200-773d-11ea-915a-2550984e539a.png)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@raju sir please find the above screenshot and do the needful

**Comment by sujin1708** [comment]
@raju-kurup please find the updated pfs ..kindly review
[PFS. Trigger For Material Request V1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4433170/PFS.Trigger.For.Material.Request.V1.0.xlsx)

**Comment by raju-kurup** [comment]
Please add the new columns and correction as discussed with Sujin (News columns requested by Mr.Gautam Merani)

**Comment by karthikeyanamitysoft** [comment]
Dear Badham,

Kindly add 3 new columns .
Regards,
Karthi

**Comment by badamnarendra028** [comment]
![trigger_mrp](https://user-images.githubusercontent.com/46923845/78562563-3969f080-7837-11ea-968a-eb5809e7843c.JPG)
completed kindly check and revert me back

**Comment by sujin1708** [comment]
One mail multiple times received ...please check

**Comment by sujin1708** [comment]
in the mentioned screenshot 3 line items ..but only one item display in the mail
![image](https://user-images.githubusercontent.com/47313592/78974639-1178d680-7b30-11ea-8406-2697c11e09cb.png)

**Comment by badamnarendra028** [comment]
completed

**Comment by badamnarendra028** [comment]
[trigger_mrp_based-09-04.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4481575/trigger_mrp_based-09-04.zip)

**Comment by sujin1708** [comment]
Testing 1 completed ,test result attached in the file, kindly check n move to next level
[PFS. Trigger For Material Request V1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4481918/PFS.Trigger.For.Material.Request.V1.0.xlsx)

**Comment by sujin1708** [comment]
Assign to manivel his mail only configure in the back end

**Comment by srinivasanbaskaran** [comment]
Mani

Kindly start Testing 2 & Prepare the Testing Documents

Regards,
Srinivasan

**Comment by srinivasanbaskaran** [comment]
Hi Srinivasan,

Testing 2 Completed. Please Find the Document For Your Ref..

MRP Based Production Test Case With Result : 
[MRP Based Production Test Case With Result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4494783/MRP.Based.Production.Test.Case.With.Result.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

MRP Based Production Scenario to Check Trigger has been Testing completed. Herewith I have attached the Testing Documents for future references

PFS: [PFS.Trigger.For.Material.Request.V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4499185/PFS.Trigger.For.Material.Request.V1.1.xlsx)

DELIVERABLES: [trigger_mrp_based-09-04.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4499186/trigger_mrp_based-09-04.zip)

TESTCASE1 & TEST RESULT1: [PFS.Trigger.For.Material.Request_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4499207/PFS.Trigger.For.Material.Request_v1.0.xlsx)

TESTCASE2: TEST RESULT2: [MRP.Based.Production.Test.Case.With.Result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4499208/MRP.Based.Production.Test.Case.With.Result.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

This has been submitted to the User for Final. 

Waiting for Customer Acceptance

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

PFA of Latest points

![1589457183223](https://user-images.githubusercontent.com/46194039/82189361-dfb41600-990c-11ea-8be0-7fef6e3b1b31.JPEG)

**Comment by sujin1708** [comment]
@raju Sir..please find the updated pfs for your reference..kindly review
[PFS. Trigger For Material Request V1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4661473/PFS.Trigger.For.Material.Request.V1.0.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Please do the correction as discussed and mentioned in PFS

**Comment by badamnarendra028** [comment]
completed kindly check

**Comment by sujin1708** [comment]
remove the scheduler, apply the logic  Due date should be 7 days  before completion of production order.

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start Testing 2 & Prepare Testing Documents

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@srinivasanbaskaran Testing1 Completed..kindly assign to manivel
PFS : [PFS. Trigger For Material Request V1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4693126/PFS.Trigger.For.Material.Request.V1.0.xlsx)

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 2 Completed. Please find the attached Testing Documents 

TESTCASE 2 & TEST RESULT2: [Testcase2_MRP_Based_Trigger.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4750021/Testcase2_MRP_Based_Trigger.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Badam,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[prod_number_create_trigger_amity.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4757627/prod_number_create_trigger_amity.zip)

**Comment by badamnarendra028** [comment]
attached

**Comment by srinivasanbaskaran** [comment]
Sir,

MRP Based Production Scenario to Check Trigger has been Testing completed. Herewith I have attached the Testing Documents for future references

PFS: [PFS.Trigger.For.Material.Request.V1.0 (2).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4766799/PFS.Trigger.For.Material.Request.V1.0.2.xlsx)

DELIVERABLES: [prod_number_create_trigger_amity.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4766801/prod_number_create_trigger_amity.zip)

TESTCASE1 & TEST RESULT1: [PFS.Trigger.For.Material.Request.V1.0 (3).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4766805/PFS.Trigger.For.Material.Request.V1.0.3.xlsx)

TESTCASE2: TEST RESULT2: [Testcase2_MRP_Based_Trigger.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4766806/Testcase2_MRP_Based_Trigger.xlsx)

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@badamnarendra028 please find the below mentioned attachment kindly do the allignment as per quotation remainder
 
![Quotation remainder](https://user-images.githubusercontent.com/47313592/93181929-b5f1eb00-f756-11ea-82a9-0c1a16c73b3b.png)

![po](https://user-images.githubusercontent.com/47313592/93181918-b4282780-f756-11ea-8546-0ac61a5c4031.png)

**Comment by badamnarendra028** [comment]
[prod_number_create_trigger_amity--16-09.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5233653/prod_number_create_trigger_amity--16-09.zip)
completed kindly check and revert

**Comment by eafaisal** [comment]
@sujin1708 

Trigger mail was generated.Testing 1 is completed.
Kindly proceed with testing 2.

Test Case & Result : 
![Testcase_MRP_Based_Trigger](https://user-images.githubusercontent.com/65998153/93967020-d5ef6300-fd83-11ea-9609-09c26d1b90dd.png)


Regards,
Faisal

**Comment by sujin1708** [comment]
@srinivasanbaskaran Please find the attachment testing 2 completed kindly check and move to next level
[Trigger For Packing Material-TestResult.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5309283/Trigger.For.Packing.Material-TestResult.xlsx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Packing Material Trigger Testing has been completed. Herewith I have attached the Testing Documents for the future references. 

PFS: [PFS.Trigger.For.Material.Request.V1.0.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5309974/PFS.Trigger.For.Material.Request.V1.0.2.xlsx)

DELIVERABLES: [prod_number_create_trigger_amity--16-09.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5309975/prod_number_create_trigger_amity--16-09.zip)

TESTCASE1 & TEST RESULT1: ![Testcase1   Test Result1](https://user-images.githubusercontent.com/46194039/94777919-e934ab00-03e1-11eb-9a6d-7ea4ab876b87.png)

TESTCASE2 & TEST RESULT2: [Trigger.For.Packing.Material-TestResult.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5309986/Trigger.For.Packing.Material-TestResult.xlsx)

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[prod_order_numb_ser_trigger_amity.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5353931/prod_order_numb_ser_trigger_amity.zip)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS for the Packing Material Trigger.

PFS: [PFS.Trigger.For.Material.Request.V1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5415893/PFS.Trigger.For.Material.Request.V1.3.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do correction in the mail subject and in body of the trigger mail. Contact Sujin/Manivel for this issue.

**Comment by badamnarendra028** [comment]
[prod_number_create_trigger_amity--16-09 (2).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5463482/prod_number_create_trigger_amity--16-09.2.zip)
[prod_order_numb_ser_trigger_amity.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5463483/prod_order_numb_ser_trigger_amity.zip)
completed kindly check and revert

**Comment by badamnarendra028** [comment]
[prod_number_create_trigger_amity--16-09 (4).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5473186/prod_number_create_trigger_amity--16-09.4.zip)
[prod_order_numb_ser_trigger_amity.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5473187/prod_order_numb_ser_trigger_amity.zip)

**Comment by sujin1708** [comment]
@Manimahat kindly do the testing 1

**Comment by Manimahat** [comment]
@sujin1708 ,

I have faced Wrong Due Date & Excess item in the Trigger. Please check & resolve this Issue.

Please find below Screen Shot:
![image](https://user-images.githubusercontent.com/55881685/100493839-3377a580-3161-11eb-8ea7-0ae308a1203c.png)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@badamnarendra028 check above issue

**Comment by badamnarendra028** [comment]
[prod_number_create_trigger_amity--16-09 (5).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5614182/prod_number_create_trigger_amity--16-09.5.zip)
[prod_order_numb_ser_trigger_amity.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5614183/prod_order_numb_ser_trigger_amity.zip)
completed kindly check and revert

**Comment by badamnarendra028** [comment]
![image](https://user-images.githubusercontent.com/46923845/100577607-99e9f880-3306-11eb-9192-0d9fff93f753.png)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 completed. Kindly proceed Testing 2.

Test Case & Test Result: [Trigger.For.Packing.Material-TestResult.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5623558/Trigger.For.Packing.Material-TestResult.xlsx)

Regards,
Manivel A

**Comment by sujin1708** [comment]
Customer status was in green .kindly close the ticket

PFS : [PFS.Trigger.For.Material.Request.V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5706994/PFS.Trigger.For.Material.Request.V1.1.xlsx)
Deliverables : [prod_number_create_trigger_amity--16-09.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5706998/prod_number_create_trigger_amity--16-09.5.zip)
Test Case : [MRP.Based.Production.Test.Case.With.Result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5706995/MRP.Based.Production.Test.Case.With.Result.xlsx)
Test Result 1 : [Trigger.For.Packing.Material-TestResult.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5707001/Trigger.For.Packing.Material-TestResult.xlsx)
Test Result 2 : [PFS.Trigger.For.Material.Request.V1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5707004/PFS.Trigger.For.Material.Request.V1.0.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by karthikeyanamitysoft** [comment]
Dear Naren,

Get the deliverables from Badam and deploy it in live server.

Regards,
Karthi

**Comment by Narendiranath** [comment]
Hi Sujin,

             Trigger deployed in live server. PFA Latest Deliverable.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5764277/Deliverable.zip)

**Comment by sujin1708** [comment]
deployment completed ..kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
