### ISSUE TITLE
TOOL : Lens search required for Reference Document No field to be added in Purchase Request multiline

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#166]
Dear Team,

Reference Document No to be added in Purchase Request based on MR

Rtrack - JCIE-164

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Lens search for Ref Doc No in PR is not possible as there are validations exist for this field in the base.
[166.Purchase request lens search.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4018684/166.Purchase.request.lens.search.docx)

**Comment by basha123456** [comment]
Explained to user and user agreed for the solution.

**Comment by basha123456** [comment]
[38.PR to PO Description.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4052213/38.PR.to.PO.Description.docx)

**Comment by basha123456** [comment]
Dear Raju Sir,
Resolution for this open point is Accepted by the users. PFA of the resolution document
[5. Purchase request lens search.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4174726/5.Purchase.request.lens.search.docx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
please upload the signed copy.

**Comment by basha123456** [comment]
@raju-kurup 

CUstomer signed document for your reference
[multi line lens search.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4338465/multi.line.lens.search.pdf)

**Comment by raju-kurup** [comment]
User accepted and signed off, so closing this issue.
