### ISSUE TITLE
PPD : Fire no - One furnance -one car logic trigger

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#167]
Furnance wise car details logic to be given by jyoti

**Comment by sujin1708** [comment]
please start the trigger
[Fire No Logic.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4122703/Fire.No.Logic.xlsx)

**Comment by sujin1708** [comment]
SDD :[01_Car Base Fire No Trigger.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4126430/01_Car.Base.Fire.No.Trigger.docx)

**Comment by sujin1708** [comment]
testing 1 completed ..kindly check n move to next level
[Furnance wsie Car Details Test data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4172213/Furnance.wsie.Car.Details.Test.data.xlsx)

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing 2 & Prepare the Testing Documents

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@sujin1708 :

As discussed, tested the logic of fire no generation.
[Fire.No.Logic (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4180510/Fire.No.Logic.1.xlsx)

**Comment by srinivasanbaskaran** [comment]
Sujin / Basha,

Kindly provide me the status of this Report

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
testing 1 completed fire no logic working fine.move to next level

**Comment by sujin1708** [comment]
check all the division

**Comment by sujin1708** [comment]
testing 1 & 2 completed ..

**Comment by basha123456** [comment]
@srinivasanbaskaran 
Testing2 completed. kindly check. PFA of test documents

Test case: [Test.Case.-.Fire No-One Furnace-One car Logic_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354079/Test.Case.-.Fire.No-One.Furnace-One.car.Logic_v1.0.xlsx)
Test Result: [Test Result. Fire no - One furnance -one car logic trigger.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354082/Test.Result.Fire.no.-.One.furnance.-one.car.logic.trigger.docx)

**Comment by srinivasanbaskaran** [comment]
Karthi,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

This report testing has been completed. Herewith, I have attached testing documents for future references.

PFS: [Fire.No.Logic.1 (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354810/Fire.No.Logic.1.1.xlsx)

DELIVERABLES: 

TESTCASE1 & TEST RESULT1: [Furnance.wsie.Car.Details.Test.data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354821/Furnance.wsie.Car.Details.Test.data.xlsx)

TESTCASE2: [Test.Case.-.Fire.No-One.Furnace-One.car.Logic_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354825/Test.Case.-.Fire.No-One.Furnace-One.car.Logic_v1.0.xlsx)

TEST RESULT2: [Test.Result.Fire.no.-.One.furnance.-one.car.logic.trigger.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354826/Test.Result.Fire.no.-.One.furnance.-one.car.logic.trigger.docx)

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
[pajsbrjsbr_a_jsbr_g_gs.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4358028/pajsbrjsbr_a_jsbr_g_gs.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

This report testing has been completed. Herewith, I have attached testing documents for future references.

PFS: [Fire.No.Logic.1 (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354810/Fire.No.Logic.1.1.xlsx)

DELIVERABLES: [pajsbrjsbr_a_jsbr_g_gs_167.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4358085/pajsbrjsbr_a_jsbr_g_gs_167.zip)


TESTCASE1 & TEST RESULT1: [Furnance.wsie.Car.Details.Test.data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354821/Furnance.wsie.Car.Details.Test.data.xlsx)

TESTCASE2: [Test.Case.-.Fire.No-One.Furnace-One.car.Logic_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354825/Test.Case.-.Fire.No-One.Furnace-One.car.Logic_v1.0.xlsx)

TEST RESULT2: [Test.Result.Fire.no.-.One.furnance.-one.car.logic.trigger.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354826/Test.Result.Fire.no.-.One.furnance.-one.car.logic.trigger.docx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested, so closing this issue

**Comment by sujin1708** [comment]
waiting for customer acceptance

**Comment by sujin1708** [comment]
@raju-kurup Document shared to customer .kindly close the ticket

**Comment by raju-kurup** [comment]
Document shared, so closing this ticket
