### ISSUE TITLE
PPD : Hard allocation based  production issue logic to be fix in automation screen

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#168]
Hard   allocation based  production issue   logic to be fix in automation screen-scenario to check n give the logic to developers

**Comment by sujin1708** [comment]
@karthick 
kindly apply the base logic in automation screen ...
[Hard Allocation.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4015124/Hard.Allocation.zip)

**Comment by karthikeyanamitysoft** [comment]
As we discussed not required

**Comment by sujin1708** [comment]
Modeling Has been done kindly check and move to next level
Modeling : [Hard Allocation.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4112299/Hard.Allocation.zip)

**Comment by sujin1708** [comment]
@raju-kurup Document shared to customer .kindly close the ticket

**Comment by raju-kurup** [comment]
Document shared so closing this ticket
