### ISSUE TITLE
PPD : Transaction date should allow one day back date to fix 

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#169]
1. Transaction   date should be system date in the multi line -header should be default date  
2. .allow one day back date to consider calendar

**Comment by karthikeyanamitysoft** [comment]
completed

**Comment by sujin1708** [comment]
We try the same today but Saturday system allow to do the transaction

**Comment by sujin1708** [comment]
@karthikeyanamitysoft 
Back date validation working fine kindly fix this..
SDD : [01_Process Production OpenPoint 10.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4111706/01_Process.Production.OpenPoint.10.docx)

**Comment by sujin1708** [comment]
@raju-kurup kindly review the pfs
[Report Production Stage Based tran Date  Back date allow procedure.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4412681/Report.Production.Stage.Based.tran.Date.Back.date.allow.procedure.xlsx)

**Comment by raju-kurup** [comment]
Please do the PFS as discussed

**Comment by sujin1708** [comment]
@raju sir please find the PFS ..kindly review [Report.Production.Stage.Based.tran.Date.Back.date.allow.procedure v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4416625/Report.Production.Stage.Based.tran.Date.Back.date.allow.procedure.v1.0.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please devlop as discussed with sujin

**Comment by sujin1708** [comment]
Testing 1 completed ..please find the attached test result for your reference.kindly check n move
[Report.Production.Stage.Based.tran.Date.Back.date.allow.procedure v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4505694/Report.Production.Stage.Based.tran.Date.Back.date.allow.procedure.v1.0.xlsx)

**Comment by srinivasanbaskaran** [comment]
Basha,

Pleasae start Testing 2 & Prepare the Testing Document

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2 completed...
[Reporting screen Transaction date  TR.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4511039/Reporting.screen.Transaction.date.TR.xlsx)

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2 completed...
[Reporting screen Transaction date  TR.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4511039/Reporting.screen.Transaction.date.TR.xlsx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Back dated Transaction in Automation screen testing has been completed. Herewith I have attached the Testing Documents for future references.

PFS: [Report_Production_Stage_Based_Tran_Date_Backdate_Allow_Procedure_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4543668/Report_Production_Stage_Based_Tran_Date_Backdate_Allow_Procedure_v1.0.xlsx)

DELIVERABLES: 

TESTCASE 1 & TEST RESULT 1:[Report.Production.Stage.Based.tran.Date.Back.date.allow.procedure_TC1&TR1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4543686/Report.Production.Stage.Based.tran.Date.Back.date.allow.procedure_TC1.TR1.xlsx)

TESTCASE 2:
[Report_Production_Stage_Based_Tran_Date_Backdate_Allow_Procedure_TC2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4543691/Report_Production_Stage_Based_Tran_Date_Backdate_Allow_Procedure_TC2.xlsx)

TEST RESULT 2: [Reporting.screen.Transaction.date.TR2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4543695/Reporting.screen.Transaction.date.TR2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Karthik,

Kindly update teh Latest Deliverables ASAP.

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
[169.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4545275/169.zip)
attached

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Back dated Transaction in Automation screen testing has been completed. Herewith I have attached the Testing Documents for future references.

PFS: [Report_Production_Stage_Based_Tran_Date_Backdate_Allow_Procedure_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4543668/Report_Production_Stage_Based_Tran_Date_Backdate_Allow_Procedure_v1.0.xlsx)

DELIVERABLES: [169.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4545417/169.zip)

TESTCASE 1 & TEST RESULT 1:[Report.Production.Stage.Based.tran.Date.Back.date.allow.procedure_TC1&TR1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4543686/Report.Production.Stage.Based.tran.Date.Back.date.allow.procedure_TC1.TR1.xlsx)

TESTCASE 2:
[Report_Production_Stage_Based_Tran_Date_Backdate_Allow_Procedure_TC2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4543691/Report_Production_Stage_Based_Tran_Date_Backdate_Allow_Procedure_TC2.xlsx)

TEST RESULT 2: [Reporting.screen.Transaction.date.TR2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4543695/Reporting.screen.Transaction.date.TR2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@raju-kurup Document shared to customer .kindly close the ticket

**Comment by sujin1708** [comment]
@karthikeyanamitysoft Kindly deploy in live server

**Comment by karthikeyanamitysoft** [comment]
deliverables already deployed, automation sp

**Comment by sujin1708** [comment]
@raju-kurup Deliverables Deployed in Live Server .kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
