### ISSUE TITLE
PPD : Extrusion Mould end piece how to accounting scenario to be check

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#170]
i) Open production order the above items in kgs -closed
ii) In case if you want to convert above items from rejected moulds then use product conversion

**Comment by sujin1708** [comment]
@raju-kurup Document shared to customer .kindly close the ticket

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, but confirmation not given. Anyhow we are closing this ticket.
