### ISSUE TITLE
PPD : Different process cel1 -firing stage through report the common production order

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#171]
Firing stage should be common

**Comment by sujin1708** [comment]
[01_Process.Production.OpenPoint.5.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4172018/01_Process.Production.OpenPoint.5.docx)

**Comment by sujin1708** [comment]
@raju-kurup Document shared to customer .kindly close the ticket

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, but confirmation not given. Anyhow we are closing this ticket.
