### ISSUE TITLE
PPD: RGP Scenario through  unitech NRGP 

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#172]
press shop through uni tech transfer through scenarion showned on 24.12.2019--cclosed

**Comment by sujin1708** [comment]
Modeling has been done
SDD : [01_Process Production OpenPoint Unitech.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4125976/01_Process.Production.OpenPoint.Unitech.docx)

**Comment by sujin1708** [comment]
@raju-kurup Document shared to customer .kindly close the ticket

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, but confirmation not given. Anyhow we are closing this ticket.
