### ISSUE TITLE
PPD : Create & Authorize - Stage base access level

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#173]
Create   –Process cell, Process stage, shift and process unit based     Authorization level – Based on process cell, process stage wise

**Comment by sujin1708** [comment]
Design completed ...once complete the codification confirm me

**Comment by sujin1708** [comment]
@karthikeyanamitysoft kindly start the coding

**Comment by sujin1708** [comment]
[Stage Wise Access Control.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4388984/Stage.Wise.Access.Control.xlsx)

**Comment by sujin1708** [comment]
[01_Maintain_User_Access Rights_PFS_v1.1.XLSX](https://github.com/astpl1998/Jyoti-Ceramic/files/4389057/01_Maintain_User_Access.Rights_PFS_v1.1.XLSX)

**Comment by raju-kurup** [comment]
As discussed with Sujin and suresh sir, please do the development for this access rights

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The coding has been completed. 
Once Design changes in the automation screen completed, The changes will reflected in the screen

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
1.  Stages Duplicating
![image](https://user-images.githubusercontent.com/47313592/78926032-05523200-7aba-11ea-9c76-beddf11f99d4.png)

2. Description not fetching
![image](https://user-images.githubusercontent.com/47313592/78926124-2d419580-7aba-11ea-9ba8-34838f64596c.png)

**Comment by raju-kurup** [comment]
@sujin1708 : do the full testing and then transfer for review

**Comment by sujin1708** [comment]
@raju sir please find the attched test result..values not fetching properly
[01_Maintain_User_Access Rights_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4488915/01_Maintain_User_Access.Rights_PFS_v1.2.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as mentioned by sujin

**Comment by sujin1708** [comment]
kindly run the SP  for tool & access control changes ..before run take backup 
[jcie-249.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4501270/jcie-249.zip)

**Comment by karthikeyanamitysoft** [comment]
Dear mohana,

Kindly add the new control on existing sps

Regards,
Karthi

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The sp has been runned in the server.
The Loss id issue has been resolved. Kindly check and revert back.
For the tool and tool description combo reload against process unit, I raised ticket for ramco https://rtrack.ramco.com/browse/JCIE-259 .

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
As discuss with mr .Goutham he confirmed 22-04.2020
#Rename the remarks field as a  **operator Hrs**

**Comment by sujin1708** [comment]
![image](https://user-images.githubusercontent.com/47313592/80014720-54528b00-84ee-11ea-8faa-1dd97164c058.png)

**Comment by sujin1708** [comment]
@raju-kurup we found some correction please find the test result refer sheet name **bugs** ..kindly review
[01_Maintain_User_Access Rights_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4547793/01_Maintain_User_Access.Rights_PFS_v1.2.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : In this report some bugs are coming, bugs are attached in the PFS itself.  Nandhinee has done this report.

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The rework has been completed. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@srinivasanbaskaran Testing 1 Completed kindly Check
Test Case : [Test.Case.-Maintain User Acess Rights.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4570950/Test.Case.-Maintain.User.Acess.Rights.xlsx)
Test Result # PFS :  [01_Maintain_User_Access Rights_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4570956/01_Maintain_User_Access.Rights_PFS_v1.2.xlsx)

**Comment by srinivasanbaskaran** [comment]
Sujin,

Please check the attached Document for the Stage Based Access Screen. 
As per my Testing, Screen is not working ( Cant able to Revert the Access which was already given to the particular User. )
Please check & guide me if I am wrong... 

DOC: [Access Rights Screen.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4611726/Access.Rights.Screen.docx)

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@shreenivasan kindly check again..if any doubt call me back

**Comment by srinivasanbaskaran** [comment]
Team,

Testing2 Completed. Please find the below Testing Documents.

TESTCASE2: [Testcase2_Maintain.User.Acess.Rights.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4739344/Testcase2_Maintain.User.Acess.Rights.xlsx)

TEST RESULT2: 
![image](https://user-images.githubusercontent.com/46194039/83935735-e0d4b680-a7d9-11ea-882a-be0f4b53edb3.png)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Please update the Latest Deliverables ASAP

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the latest deliverables.

[acsd_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4739374/acsd_v2.1.zip)

Regards
Nandhinee Dev

**Comment by srinivasanbaskaran** [comment]
Sir,

Stage Base Access Level screen testing has been complted. Herewith I have attached the Testing Documents for future references.

PFS: [01_Maintain_User_Access.Rights_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4739535/01_Maintain_User_Access.Rights_PFS_v1.2.xlsx)

DELIVERABLES: [acsd_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4739539/acsd_v2.1.zip)

TESTCASE1: [Test.Case1-Maintain.User.Acess.Rights.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4739540/Test.Case1-Maintain.User.Acess.Rights.xlsx)

TEST RESULT1: [01_Maintain_User_Access.Rights_PFS_v1.2 (2).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4739543/01_Maintain_User_Access.Rights_PFS_v1.2.2.xlsx)

TESTCASE2: [Testcase2_Maintain.User.Acess.Rights.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4739567/Testcase2_Maintain.User.Acess.Rights.xlsx)

TEST RESULT2: ![Test Result2_Stage Based Access Level Screen](https://user-images.githubusercontent.com/46194039/83939011-fdcbb280-a7f6-11ea-8006-f03c306885c4.png)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer given confirmation, so closing this ticket
