### ISSUE TITLE
PPD : PCS to kGS one stage to another stage scenario checking

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#175]
When we   go kg to Pcs. In one stage to another stage Unit must be change   
  i) Primary output –FG & intermediate in pcs      ii) Input – should be in kgs.

**Comment by sujin1708** [comment]
Modeling hase been completed
SDD : [01_Process Production OpenPoint 7.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4112224/01_Process.Production.OpenPoint.7.docx)

**Comment by sujin1708** [comment]
@raju-kurup Document shared to customer .kindly close the ticket

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, but confirmation not given. Anyhow we are closing this ticket.
