### ISSUE TITLE
PPD : Different variant in one item code -codification

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#177]
Different variant in one code scenario checking

**Comment by sujin1708** [comment]
customer need to confirm this
[Same itemcode differnt variant.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4019399/Same.itemcode.differnt.variant.xlsx)

**Comment by sujin1708** [comment]
SDD : [01_Process Production OpenPoint 10.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4111642/01_Process.Production.OpenPoint.10.docx)

**Comment by sujin1708** [comment]
@raju-kurup Document shared to customer .kindly close the ticket

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, but confirmation not given. Anyhow we are closing this ticket.
