### ISSUE TITLE
PPD : Unitech Process stage double disk grinding qc  disabled

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#178]

**Comment by sujin1708** [comment]
[Double disk grinding Qc disabled.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4019171/Double.disk.grinding.Qc.disabled.docx)

**Comment by sujin1708** [comment]
convey this to  customer

**Comment by sujin1708** [comment]
Modeling has been done
SDD :[01_Process Production Open Point14.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4113195/01_Process.Production.Open.Point14.docx)

**Comment by sujin1708** [comment]
@raju-kurup Document shared to customer .kindly close the ticket

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, but confirmation not given. Anyhow we are closing this ticket.
