### ISSUE TITLE
TOOL : Material Request for Zero Stock items

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#179]
Dear Team,
 Below point has been raised at the time of Training.

Material   Request for zero stock items.

Solution:
Possible to create MR while Item having Zero stocks

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Explained to user and user agreed for the solution.

**Comment by basha123456** [comment]
Dear Raju Sir,
Resolution for this open point is Accepted by the users. PFA of the resolution document
[1. Material Request to be raised for zero quantity stock items.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4174719/1.Material.Request.to.be.raised.for.zero.quantity.stock.items.docx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
please upload the signed copy.

**Comment by basha123456** [comment]
@raju-kurup :

Customer signed document attached for your reference.

[Mr for 0 stock items.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4338436/Mr.for.0.stock.items.pdf)

**Comment by raju-kurup** [comment]
User accepted and sign off given, so closing this issue
