### ISSUE TITLE
IMP-SDD for Sales & Distribution 

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#18]
IMP-SDD for Sales & Distribution

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the attached Updated Sales and shipping SDD all version for your reference.

SDD : [01_JCIPL_SAL&SHP_SDD_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3476830/01_JCIPL_SAL.SHP_SDD_V.1.0.docx)
          [02_JCIPL_SAL&SHP_SDD_V 1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3476829/02_JCIPL_SAL.SHP_SDD_V.1.1.docx)

**Comment by raju-kurup** [comment]
SDD issued waiting for Sign-off
