### ISSUE TITLE
TOOL : New Tool is Prepared using already prepared parts

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#181]
Dear Team,

Below points raised at the time of Training

Query:
2  Identical tool having variation in only one part

Solution:
 The parts are manufacture as separate project and move to store. Whenever assembly needed move to new project

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Explained to user and user agreed for the solution.

**Comment by basha123456** [comment]
[3. New tool manufactured by using manufactured tools or components.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4174712/3.New.tool.manufactured.by.using.manufactured.tools.or.components.docx)
Dear Raju Sir,
Resolution for this open point is Accepted by the users. PFA of the resolution document

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly proceed further on this point

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Signed off received from User
