### ISSUE TITLE
PPD : One item  different process in two divison scenario checking

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#182]
i) We   have to change configuration from logic of department wise for this   codification      of process stage has to be commonized for all departments
--

**Comment by sujin1708** [comment]
Modeling has been completed ,document shared to customer
SDD :[01_process Stage press shop & extrusion .docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4144563/01_process.Stage.press.shop.extrusion.docx)

**Comment by sujin1708** [comment]
@raju-kurup Document shared to customer .kindly close the ticket

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, but confirmation not given. Anyhow we are closing this ticket.
