### ISSUE TITLE
PPD :  final sorting - some Qty send to unitech for reprocess scenario

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#183]
1.   “held” full qty in qc and    rework immediately then continue the process     
2. Reject the item and move rejection warehouse –and rework after sometimes
--

**Comment by sujin1708** [comment]
Modeling has been completed
SDD : [01_Process Production Final Sorting Send to  Unitech reporocess.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4144386/01_Process.Production.Final.Sorting.Send.to.Unitech.reporocess.docx)

**Comment by sujin1708** [comment]
@raju-kurup Document Delivered to Customer .please close the ticket.

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, but confirmation not given. Anyhow we are closing this ticket.
