### ISSUE TITLE
S&S : Drawing Required in Sales Order

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#184]
Dear Team,

Below point are raised at the time of Training .

In sales order drawing attachment mandatory

Solution:
Handled through Folder in Sale Order screen

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
1. FOLDER ( DRAWING ) User wants to DEFAULT as BLANK at the time of Loading the screen
2. Currency should be changed in AMED

**Comment by sujin1708** [comment]
point 1 above mentioned make document and share this 

below points requested in production :
In sales order drawing attachment mandatory???
Sol : In sale order some field has to be made mandatory, if typed “yes” by the sales person he has to attach the drawing. If typed “no” he need not do the attach

**Comment by srinivasanbaskaran** [comment]
Sujin.

Please find the attached Resolution document 

Document: [01_Resolution Doc for Sales & Shipping OpenPoint 35.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4143615/01_Resolution.Doc.for.Sales.Shipping.OpenPoint.35.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Need to show this to Mr.Sunil & Close this report

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
kindly take this ticket into the sales part

**Comment by Manimahat** [comment]
@raju-kurup sir.

Please find the attached Resolution document

Document: [01_Resolution.Doc.for.Sales.Shipping.OpenPoint.35.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/6824657/01_Resolution.Doc.for.Sales.Shipping.OpenPoint.35.docx)

Note: We submitted the document to user & accepted by user but they haven't given any signed copy. So we are consider this point as closed.

Regards,
Manivel A

**Comment by sujin1708** [comment]
@raju-kurup Document attached kindly close the ticket

**Comment by raju-kurup** [comment]
Document shared, so closing this ticket
