### ISSUE TITLE
PPD : when customer send some assembly parts. (Shafts) How to account 

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#185]
In the   sale order customer supplied parts will be mapped, this will be taken into  the  warehouse through a GRN-goods receipt note, during production this item   will be drawn from the stores and assembled.

**Comment by sujin1708** [comment]
@srinivasanbaskaran as discuss with mr.sunil through DC or RGP we can do the scenario...kindly do the modeling

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly do the 2 modelings & Explain to Sujin

Modeling 1: Create a Sale Order along with Customer Item

Modeling 2: Directly create a RGP / NRGP with the mentioned Item

**NOTE** Please clarify your doubts with Sujin, while doing the modeling, 
Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran : as discussed with sujin, scenario is checked using sale order and Goods receipt process.
[shaft accounting scenario with sale order.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4170214/shaft.accounting.scenario.with.sale.order.docx)

**Comment by srinivasanbaskaran** [comment]
@sujin1708 ,

Please check the above scenario modeling by Basha. Convey this to the User

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@raju-kurup Delivered to customer please close the ticket

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, but confirmation not given. Anyhow we are closing this ticket.
