### ISSUE TITLE
JPA : Jyoti Acess control screen Automation -RDW

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#186]
Access control stage wise - create & authorize

**Comment by sujin1708** [comment]
@karthikeyanamitysoft please find the attachment of Access control screen design ..kindly start the development
[Access control Screen Design.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4029812/Access.control.Screen.Design.xlsx)

**Comment by sujin1708** [comment]
[Access control Screen Design 1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4041569/Access.control.Screen.Design.1.1.xlsx)

**Comment by sujin1708** [comment]
[01_Maintain_User_Access Rights_PFS_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4052782/01_Maintain_User_Access.Rights_PFS_v1.2.zip)

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The development has been completed. Kindly check and revert back. 
Please find the attached deliverables.

[Del-v1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4120858/Del-v1.0.zip)

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@Manimahat Test the screen ...make document at earlier

**Comment by Manimahat** [comment]
Hi Sujin,

Testing 2 Completed For Access Control Screen. Please Find the Attached File.

Testing 2 : 
[Jyoti Access Control screen Testing 2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4184321/Jyoti.Access.Control.screen.Testing.2.xlsx)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@srinivasanbaskaran testing2 completed kindly move to next level

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Access Control Screen for Automation Testing has been completed.

Herewith, I have attached the Testing Documents for the future references.

PFS: [01_Maintain_User_Access.Rights_PFS_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4192497/01_Maintain_User_Access.Rights_PFS_v1.2.zip)

DELIVERABLES: [Del-v1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4192500/Del-v1.0.zip)

TESTCASE & TEST RESULT: [Uploading Jyoti_Access_Control_Screen_Testing_2.xlsx…]()


Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Test case and result excel is not opening. so please attach it once more.

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Access Control Screen for Automation Testing has been completed.

Herewith, I have attached the Testing Documents for the future references.

PFS: [01_Maintain_User_Access.Rights_PFS_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4192497/01_Maintain_User_Access.Rights_PFS_v1.2.zip)

DELIVERABLES: [Del-v1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4192500/Del-v1.0.zip)

TESTCASE & TEST RESULT: [Jyot_.Access_Control_Screen_Testing2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334657/Jyot_.Access_Control_Screen_Testing2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Testing 2 completed, so closing this ticket

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by sujin1708** [comment]
kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
