### ISSUE TITLE
QLT : Receiving Packing Material Inspection Report - RDW

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#187]
Dear Team,

Pleas find the PFS for Receiving Packing Material Inspection Report

PFS: [01_Quality Receiving (Packing) Material Inspection Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4172437/01_Quality.Receiving.Packing.Material.Inspection.Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please start develoment

**Comment by srinivasanbaskaran** [comment]
Team,

Please Refer #45 for EDK Design

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The coding has been completed.
The deliverables will be attached in #45 

Regards
Nandhinee devi

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Please check the Report Name. I am selecting Receiving Packing Material Report but in Report Name came like Raw Material Report. 

Kindly check & Revert me

![image](https://user-images.githubusercontent.com/46194039/74705654-ae0eae80-523a-11ea-83ff-05d2e71e85ff.png)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The coding part only I have done. The DW Report modeling has been assigned to Mohana. Kindly contact her.

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Karthi,

Please do the needful 

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
mohana kindly change the report name in dw desing.

name as : Receiving Packing Material Report

**Comment by mohanaamity** [comment]
completed

**Comment by srinivasanbaskaran** [comment]
Kindly do the following changes & Revert me.

1. Report should in Landscape
2. Decimal Digits ( 2 Digits only )

**Comment by srinivasanbaskaran** [comment]
Sir,

Kindly check the above points & Assign to development 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the attached Updated PFS for Receiving Packing Material Inspection Report

PFS: [01_Quality Receiving (Packing) Material Inspection Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4279504/01_Quality.Receiving.Packing.Material.Inspection.Report_PFS_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
kindly do the changes

**Comment by srinivasanbaskaran** [comment]
Updated PFS: [01_Quality Receiving (Packing) Material Inspection Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4280045/01_Quality.Receiving.Packing.Material.Inspection.Report_PFS_v1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
1.Remarks column name should be change 'Status'
2. If the values like lenth, height etc are Null then need to fetch 'N/A'
3. New column to add Size
4. Remaining logic change

**Comment by karthikeyanamitysoft** [comment]
DW changes completed

**Comment by raju-kurup** [comment]
Design completed please do the coding for this ticket

**Comment by srinivasanbaskaran** [comment]
Sir,

Receiving Packing Material Inspection Report testing completed. Herewith, I have attached the Testing Documents for future references.

PFS: [01_Quality Receiving (Packing) Material Inspection Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333983/01_Quality.Receiving.Packing.Material.Inspection.Report_PFS_v1.2.xlsx)

PATH: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details

DELIVERABLES:

TESTCASE: [TestCase_Receiving Packing Material_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333985/TestCase_Receiving.Packing.Material_Report.xlsx)

TEST RESULT: [Test Result_Receiving Packing Material Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4333988/Test.Result_Receiving.Packing.Material.Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the latest deliverables for this report.

[receiving packing material.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4336171/receiving.packing.material.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Receiving Packing Material Inspection Report testing completed. Herewith, I have attached the Testing Documents for future references.

PFS: [01_Quality Receiving (Packing) Material Inspection Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333983/01_Quality.Receiving.Packing.Material.Inspection.Report_PFS_v1.2.xlsx)

PATH: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details

DELIVERABLES: [receiving.packing.material.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4342002/receiving.packing.material.zip)

TESTCASE: [TestCase_Receiving Packing Material_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333985/TestCase_Receiving.Packing.Material_Report.xlsx)

TEST RESULT: [Test Result_Receiving Packing Material Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4333988/Test.Result_Receiving.Packing.Material.Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start the Testing 2 & Prepare the Test case

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 2 Completed. Please find the Attached document for your reference.

Test Case :
[TestCase_Receiving.Packing.Material_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4352585/TestCase_Receiving.Packing.Material_Report.xlsx)

Test Result : [Receiving Packing Material Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4352586/Receiving.Packing.Material.Result.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

Receiving Packing Material Inspection Report testing completed. Herewith, I have attached the Testing Documents for future references.

PFS: [01_Quality Receiving (Packing) Material Inspection Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333983/01_Quality.Receiving.Packing.Material.Inspection.Report_PFS_v1.2.xlsx)

PATH: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details

DELIVERABLES: [receiving.packing.material.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4342002/receiving.packing.material.zip)

TESTCASE1: [TestCase_Receiving Packing Material_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333985/TestCase_Receiving.Packing.Material_Report.xlsx)

TEST RESULT1: [Test Result_Receiving Packing Material Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4333988/Test.Result_Receiving.Packing.Material.Report.pdf)

TESTCASE2: [TestCase_Receiving.Packing.Material_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354779/TestCase_Receiving.Packing.Material_Report.xlsx)

TEST RESULT: [Receiving.Packing.Material.Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4354780/Receiving.Packing.Material.Result.pdf)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested, so closing this issue

**Comment by raju-kurup** [comment]
Customer accepted and waiting for signature

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

User given confirmation.. Attached the same

Doc: 
![Receiving Packing Material_Confirmation](https://user-images.githubusercontent.com/46194039/81582078-3a111c00-93cd-11ea-8145-627970c7ace5.jpg)

Kindly close this ticket.

Regards,
Srinivasan

**Comment by raju-kurup** [comment]
Development completed, so closing this development.

**Comment by sujin1708** [comment]
to be deploy in live server

**Comment by Nandhineedevi** [comment]
@Narendiranath
DW Report Name: quality_control_rpt_r

Kindly Move only the DW Report from UAT to Live Server.
All Back end and Front end Deployment had been completed.
Latest Deliverable has been attached below.

[Live_import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5918656/Live_import.zip)

**Comment by Narendiranath** [comment]
Hi Sujin,

         DW Report deployed in live server. Kindly check. PFA Latest Deliverables for your ref.

[Dw_ER_03Feb2021232046.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5920518/Dw_ER_03Feb2021232046.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployment Completed in Live Server Kindly Closed the ticket

**Comment by raju-kurup** [comment]
Deployed in Live server, so closing this ticket
