### ISSUE TITLE
QLT : Green Piece Inspection Report

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#188]
Dear Team,

Please Fidn the attached PFS for Green Piece Inspection Report

PFS: 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

PFS Completed As per the Customer Requirement .Please Find the Attachment.

PFS : 
[Green Piece Inspection Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4158994/Green.Piece.Inspection.Report_PFS_v1.0.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

Kindly Review the PFS & Allocate to Development 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please start the development

**Comment by srinivasanbaskaran** [comment]
Team,

Please Refer #45 for EDK Design

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The deliverables will be attached in #45

Regards
Nandhinee devi

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly Start the Testing 1 & Prepare the Testing Documents

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Nadhinee,

Please find the Updated PFS & Kindly Do the Changes.

Updated PFS : 
[Green Piece Inspection Report_PFS_v1.1 - Copy.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4228953/Green.Piece.Inspection.Report_PFS_v1.1.-.Copy.xlsx)

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
Hi Manivel,
The rework has been updated as per pfs.

Regards
Nandhinee devi

**Comment by Manimahat** [comment]
Hi Nandhinee,

Please find the Updated PFS & Kindly Do the Changes.

Updated PFS : 
[Green Piece Inspection Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4239430/Green.Piece.Inspection.Report_PFS_v1.2.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

PFS updated. Kindly allocate to Development
PFS: 
Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Karthi,
Please start the rework.

**Comment by raju-kurup** [comment]
Ezhil - Please do the correction as per PFS and contact Srini/Manivel for clarification

**Comment by srinivasanbaskaran** [comment]
Kindly made the corrections for the below points 

1. 2 Digit decimals after digits
2. DRG No 
3. Check points
4. Obtained Start PC 
5. Obtained End PC Date

Please made the corrections as per the PFS. 

PFS: [Green.Piece.Inspection.Report_PFS_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4267027/Green.Piece.Inspection.Report_PFS_v1.3.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the signed copy of the changes of Green Piece Inspection Report.

Green Piece Inspection Report: ![1583814589722](https://user-images.githubusercontent.com/46194039/76280977-abdbc500-62b9-11ea-8d00-19c5c3aea358.JPEG)

Below are the Points to be changed.

1. Inspection Request No
2. Material value to be fetched from Item Category

Regards,
Srinvasan Baskaran

**Comment by raju-kurup** [comment]
Please update the PFS

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the attached updated PFS as per the User Requirements. Kindly Review this PFS & Proceed to Development

PFS: [Green.Piece.Inspection.Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4316889/Green.Piece.Inspection.Report_PFS_v1.4.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@Nandhineedevi : please do the correction as mentioned

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The Rework has been completed. Kindly check and revert back.
Please find the unit test results attached below.

[green piece.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4323816/green.piece.pdf)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Green Piece Inspection Report Testing has been completed. Herewith I have attached Testing documents for future references.

PFS: [Green.Piece.Inspection.Report_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333882/Green.Piece.Inspection.Report_PFS_v1.5.xlsx)

PATH: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details 

DELIVERABLES:

TESTCASE: [Test Case - Green_Piece_Insecption_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333883/Test.Case.-.Green_Piece_Insecption_Report_v1.0.xlsx)

TEST RESULT: [Test Result_Green__Piece_Inspection_Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4333885/Test.Result_Green__Piece_Inspection_Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the latest deliverables for this report.

[green piece ins report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4336179/green.piece.ins.report.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Green Piece Inspection Report Testing has been completed. Herewith I have attached Testing documents for future references.

PFS: [Green.Piece.Inspection.Report_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333882/Green.Piece.Inspection.Report_PFS_v1.5.xlsx)

PATH: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details 

DELIVERABLES: 

TESTCASE: [Test Case - Green_Piece_Insecption_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333883/Test.Case.-.Green_Piece_Insecption_Report_v1.0.xlsx)

TEST RESULT: [Test Result_Green__Piece_Inspection_Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4333885/Test.Result_Green__Piece_Inspection_Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing & Prepare the Testcase 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly start the Testing 2 & Prepare the Testcase 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing & Prepare the Testcase

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Please add PC in OBTAINED END 20/03/2020.

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran :

Testing2 completed...test documents attached.

Test Case: [Test.Case.-.Green_Piece_Insecption_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4368893/Test.Case.-.Green_Piece_Insecption_Report_v1.0.xlsx)

Test Result: [test result - green piece inspection report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4368894/test.result.-.green.piece.inspection.report.pdf)

**Comment by srinivasanbaskaran** [comment]
Sir,

Green Piece Inspection Report Testing has been completed. Herewith I have attached Testing documents for future references.

PFS: [Green.Piece.Inspection.Report_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333882/Green.Piece.Inspection.Report_PFS_v1.5.xlsx)

PATH: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details 

DELIVERABLES: 
TESTCASE: [Test Case - Green_Piece_Insecption_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333883/Test.Case.-.Green_Piece_Insecption_Report_v1.0.xlsx)

TEST RESULT: 
Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the latest deliverables.

[green piece ins report_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4379035/green.piece.ins.report_v1.2.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Green Piece Inspection Report Testing has been completed. Herewith I have attached Testing documents for future references.

PFS: [Green.Piece.Inspection.Report_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333882/Green.Piece.Inspection.Report_PFS_v1.5.xlsx)

PATH: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details 

DELIVERABLES: [green.piece.ins.report_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4388012/green.piece.ins.report_v1.2.zip)

TESTCASE1: [Test Case - Green_Piece_Insecption_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333883/Test.Case.-.Green_Piece_Insecption_Report_v1.0.xlsx)

TEST RESULT1: [02_Green Piece Inspection Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4378777/02_Green.Piece.Inspection.Report.pdf)

TESTCASE2: [Test.Case.-.Green_Piece_Insecption_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4378784/Test.Case.-.Green_Piece_Insecption_Report_v1.0.xlsx)

TEST RESULT2: [Test_Result2_Green_Piece_Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4378785/Test_Result2_Green_Piece_Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

User given confirmation.. Attached the same

Doc: 
![Green Piece Inspection Report_Confirmation](https://user-images.githubusercontent.com/46194039/81581996-1e0d7a80-93cd-11ea-99e9-030d6e271348.jpg)

Kindly close this ticket.

Regards,
Srinivasan

**Comment by raju-kurup** [comment]
Development completed, so closing this development

**Comment by sujin1708** [comment]
Customer comments :

![image](https://user-images.githubusercontent.com/47313592/89153571-c83b0f80-d582-11ea-9073-b21cd30296d8.png)

**Comment by sujin1708** [comment]
@raju-kurup  Please find the updated PFS.  Need to remove the Least &  Highest logic from the Obtained Start & Obtained End column

[Green.Piece.Inspection.Report_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5072756/Green.Piece.Inspection.Report_PFS_v1.6.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as mentioned in PFS. Nandhinee has done this report and discussed with her also.

**Comment by Nandhineedevi** [comment]
[grn_piece_rpt_sp_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5107443/grn_piece_rpt_sp_v2.1.zip)

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 1 Completed.

TESTCASE1:

TEST RESULT1:

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srinivasanbaskaran

Green Piece Inspection Report Testing 2 Completed Kindly Check & Update.

[Test.Case.-.Green_Piece_Insecption_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5135516/Test.Case.-.Green_Piece_Insecption_Report_v1.0.xlsx)

[Test Result v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5135518/Test.Result.v2.pdf)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer gave Confirmation to move this report to GREEN. 

So, Kindly proceed further 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer Approved, so closing this ticket

**Comment by sujin1708** [comment]
Variant logic to be handled

**Comment by sujin1708** [comment]
@karthikeyanamitysoft kindly apply the material name logic as per the attached PFS
[Uploading Green.Piece.Inspection.Report_PFS_v1.7.xlsx…]()

**Comment by Nandhineedevi** [comment]
Completed.

[QCR_v3.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5708260/QCR_v3.1.zip)
[green piece.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5708262/green.piece.pdf)

**Comment by sujin1708** [comment]
kindly deploy the report in live server

**Comment by Nandhineedevi** [comment]
@Narendiranath
DW Report Name: quality_control_rpt_g

Kindly Move only the DW Report from UAT to Live Server.
All Back end and Front end Deployment had been completed.
Latest Deliverable has been attached below.

[Live_import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5918651/Live_import.zip)

**Comment by Narendiranath** [comment]
Hi Sujin,

         DW Report deployed in live server. Kindly check. PFA Latest Deliverables for your ref.

[Dw_ER_03Feb2021230656.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5920441/Dw_ER_03Feb2021230656.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployment Completed in Live Server Kindly Closed the ticket

**Comment by sujin1708** [comment]
@karthikeyanamitysoft please check the below issue

1. Material name not fetching

![image](https://user-images.githubusercontent.com/47313592/125384220-394f8d80-e3b6-11eb-82e5-a234080a53a2.png)

**Comment by Jeyapriyat** [comment]
@sujin1708 
changes completed,kindly check and revert.
i have attached latest deliverables.
[new live sp - 16-07-2021.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6830171/new.live.sp.-.16-07-2021.zip)
![image](https://user-images.githubusercontent.com/37791285/125938004-6145567e-9f71-491c-b2bc-45660d1c51fd.png)

**Comment by sujin1708** [comment]
@Manimahat kindly test this

**Comment by Manimahat** [comment]
@Jeyapriyat ,

Please deploy the same deliverable in UAT server.

Thanks,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup sir,

Need to deploy the same deliverable in UAT server.  Please allocate a developer to for this point.

Thanks,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy the same deliverables in UAT server also

**Comment by Jeyapriyat** [comment]
@Manimahat 
changes completed, kindly check and revert.
i have attached latest deliverables and sample output.
[final inspection report - jcie-211.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6855632/final.inspection.report.-.jcie-211.zip)
[sample output - uat.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6855636/sample.output.-.uat.pdf)

**Comment by Manimahat** [comment]
@raju-kurup sir,

As per our new Requirement Material Name Logic Changed & other Issue has been Resolved. New Deliverable deployed & Tested Successfully in Both UAT & Live Server. Test Result has been attached Below.  Please close this Ticket.

Live Server Result : [Green piece Inspection report - Live.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6872216/Green.piece.Inspection.report.-.Live.pdf)

UAT Server Result : [Green piece Inspection report - UAT.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6872217/Green.piece.Inspection.report.-.UAT.pdf)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Report Developed and deployed in both Live and Test, so Closing this ticket.
