### ISSUE TITLE
QLT : Final Inspection Report - RDW

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#189]
Dear Team,

Please find the PFS for Final Inspection Report - RDW. PFS will be updated in future

PFS : [03_Quality Final_Inspection_Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4176542/03_Quality.Final_Inspection_Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please start the development

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start the Testing1 & Prepare the Testing Document

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The deliverables will be attached in #45 

Regards
Nandhinee devi

**Comment by srinivasanbaskaran** [comment]
Sir,

PFS updated as per the User Requirements.

PFS: [03_Quality Final_Inspection_Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4240715/03_Quality.Final_Inspection_Report_PFS_v1.1.xlsx)

Below are the points to be corrected.

1. Bio Ceramic Division - Should not come in MFG OU
2. Sampling Type - Wrongly fetched
3. Lot No. & Lot Size - Values are missing
4. Decimals - ( 2 digits only come after the decimals )
5. Where ever there is no values - ( - Hypen ) will come
6. Remarks changed to Obtained Values
7. Remarks - To be added into this report ( Values to be fetched from Attach Notes )

**Comment by srinivasanbaskaran** [comment]
Sir,

Please Review the PFS & Allocate to Developers.

Regards, 
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Please Reivew the PFS & Allocate to the Development 

PFS: [03_Quality Final_Inspection_Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4244888/03_Quality.Final_Inspection_Report_PFS_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Karthi,
please do the correction in this reports

Below are the points to be corrected.

Bio Ceramic Division - Should not come in MFG OU
Sampling Type - Wrongly fetched
Lot No. & Lot Size - Values are missing
Decimals - ( 2 digits only come after the decimals )
Where ever there is no values - ( - Hypen ) will come
Remarks changed to Obtained Values
Remarks - To be added into this report ( Values to be fetched from Attach Notes )

**Comment by raju-kurup** [comment]
Ezhil - Please do the correction as per PFS and contact Srini/Manivel for clarification

**Comment by srinivasanbaskaran** [comment]
Hi,

Please find teh updated PFS for Final Inspection Report.

PFS: [03_Quality.Final_Inspection_Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4266629/03_Quality.Final_Inspection_Report_PFS_v1.2.xlsx)

Below are the points to be corrected.

Bio Ceramic Division - Should not come in MFG OU
Sampling Type - Wrongly fetched
Lot No. & Lot Size - Values are missing
Decimals - ( 2 digits only come after the decimals )
Where ever there is no values - ( - Hypen ) will come
Remarks changed to Obtained Values
Remarks - To be added into this report ( Values to be fetched from Attach Notes )

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Please find the updated PFS for Final Inspection Report 

PFS: [03_Quality.Final_Inspection_Report_PFS_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4285647/03_Quality.Final_Inspection_Report_PFS_v1.3.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The deliverables will be attached in #45 

Regards
Nandhinee devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the signed copy of the changes of Final Inspection Report.

Final Inspection Report: ![1583814589640](https://user-images.githubusercontent.com/46194039/76281261-826f6900-62ba-11ea-842c-430d62d0d0fb.JPEG)

Below are the Points to be changed.

1. Inspection Request No
3. Product value to be fetched from Item Category
4. Green related information doesn't required in the Print
5. Don't want the Fired Dimensions which are all the Items having Grinding & Lapping

Regards,
Srinvasan Baskaran

**Comment by raju-kurup** [comment]
Please update the PFS

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the updated PFS as per the User Requirements.

PFS: [03_Quality.Final_Inspection_Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4316357/03_Quality.Final_Inspection_Report_PFS_v1.4.xlsx)

Kindly review the PFS & Proceed to Development 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the attached updated PFS as per the User's Requirements

PFS: 
[04_Quality_Feedback_Form_Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4332655/04_Quality_Feedback_Form_Report_PFS_v1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back
Please find the latest deliverables for this report.

[Final Inspection Report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4337978/Final.Inspection.Report.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,
Sampling Type is wrongly fetched. Please check the below image & mvoe to development Rework

![image](https://user-images.githubusercontent.com/46194039/77038576-1f788300-69da-11ea-8c82-33ae6b1e4a39.png)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@ Nandhinee : please do the correction for 1 point.

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back
Please find the latest deliverables for this report.

[final_227_p1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4354091/final_227_p1.pdf)
[Final Inspection Report_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4354095/Final.Inspection.Report_v1.2.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

Final Inspection Report testing has been completed. 

PFS: [03_Quality.Final_Inspection_Report_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354754/03_Quality.Final_Inspection_Report_PFS_v1.5.xlsx)

TESTCASE1: [Test Case - Final_Insecption_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4354757/Test.Case.-.Final_Insecption_Report_v1.0.xlsx)

TEST RESULT 1: [Final Inspection Report -Newly Update.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4354761/Final.Inspection.Report.-Newly.Update.pdf)

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2 completed. PFA

Test case2: [Test.Case.-.Final_Insecption_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4355761/Test.Case.-.Final_Insecption_Report_v1.0.xlsx)

Test Result: [Final Inspect report test result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4355763/Final.Inspect.report.test.result.pdf)

**Comment by srinivasanbaskaran** [comment]
Sir,

Certificate of Analysis Report testing completed. Herewith I have attached testing documents for future references.

PFS:
PATH : Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details 

DELIVERABLES: [Final.Inspection.Report_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4356486/Final.Inspection.Report_v1.2.zip)
 
TESTCASE 1: [Test Case - Final_Insecption_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356490/Test.Case.-.Final_Insecption_Report_v1.0.xlsx)

TEST RESULT 1: [Final Inspection Report -Newly Update.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4356492/Final.Inspection.Report.-Newly.Update.pdf)

TESTCASE2: [Test.Case.-.Final_Insecption_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356489/Test.Case.-.Final_Insecption_Report_v1.0.xlsx)

TEST RESULT2: [Final.Inspect.report.test.result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4356494/Final.Inspect.report.test.result.pdf)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested, so closing this issue

**Comment by raju-kurup** [comment]
Customer accepted and waiting for signature

**Comment by srinivasanbaskaran** [comment]
Team,

Please find the attached image of the changes requestes by User.

IMG: ![Final Inspection Report_Correction](https://user-images.githubusercontent.com/46194039/81604621-cfbca380-93ed-11ea-9a74-e53bd483d4be.jpg)

Need to update the PFS... 

NOTE: Srinivasan will do it 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Please Find the Updated PFS & Allocated to Developers.

Updated PFS : [03_Quality.Final_Inspection_Report_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4656286/03_Quality.Final_Inspection_Report_PFS_v1.6.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do correction of 1 point, test data is attached in PFS itself

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back
Please find the latest deliverables for this report.

[test_output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4661242/test_output.pdf)
[final_ins_rpt_sp_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4661250/final_ins_rpt_sp_v1.3.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start Testing 1 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 completed. Kindly Start the Testing 2 process.

Test Case : [Test.Case.-.Final_Insecption_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4690258/Test.Case.-.Final_Insecption_Report.xlsx)

Test Result : [test_output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4690263/test_output.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
@basha123456 ,

Kindly start Testing 2

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2  is completed. 

[Final Inspect report test result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4701343/Final.Inspect.report.test.result.pdf)
[Test.Case.-.Final_Insecption_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4701349/Test.Case.-.Final_Insecption_Report.xlsx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Final Inspection Report Testing has been completed. Herewith I have attached the Testing documents for future references.

PFS: [03_Quality.Final_Inspection_Report_PFS_v1.6 (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4705772/03_Quality.Final_Inspection_Report_PFS_v1.6.1.xlsx)

DELIVERABLES: [final_ins_rpt_sp_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4705774/final_ins_rpt_sp_v1.3.zip)

TESTCASE1: [Test.Case1-.Final_Insecption_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4705775/Test.Case1-.Final_Insecption_Report.xlsx)

TEST RESULT1: [test_output (1).pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4705778/test_output.1.pdf)

TESTCASE2: [Test.Case2-.Final_Insecption_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4705780/Test.Case2-.Final_Insecption_Report.xlsx)

TEST RESULT2: [Test Result2_FIR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4705781/Test.Result2_FIR.pdf)

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@raju sir please find the updated PFS kinly move to next level

Qc No : QIR/2021/0818/P1

PFS : [03_Quality.Final_Inspection_Report_Updated_PFS_v1.8.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5009726/03_Quality.Final_Inspection_Report_Updated_PFS_v1.8.xlsx)

Customer Comments 👍 
 
![image](https://user-images.githubusercontent.com/47313592/89092190-3a69f380-d3cd-11ea-8d49-6bdfb6632399.png)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as mentioned in PFS

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The rework has been completed. Kindly check and revert back.

[Final Inspection Report_After Correction.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5020535/Final.Inspection.Report_After.Correction.pdf)
[final_ins_rpt_sp_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5020538/final_ins_rpt_sp_v2.1.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Faizal,

Kindly start the Testing 1 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 1 is completed.
Please proceed with testing 2.
Test Case : [Test.Case-.Final_Insecption_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5034926/Test.Case-.Final_Insecption_Report.xlsx)

Test Result : [Test_Result_FIR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5034929/Test_Result_FIR.pdf)

Regards,
Mohideen Faisal

**Comment by srinivasanbaskaran** [comment]
Team,

Final Inspection Testing 2 Completed.

Testcase2: [Final_Insecption_Report - Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5052856/Final_Insecption_Report.-.Testcase2.xlsx)

Test Result2: [Final Inspection_TR2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5052857/Final.Inspection_TR2.pdf)

Regards,
Srinivasan

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Final Inspection Report testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [03_Quality.Final_Inspection_Report_Updated_PFS_v1.8.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5052865/03_Quality.Final_Inspection_Report_Updated_PFS_v1.8.xlsx)

DELIVERABLES: [final_ins_rpt_sp_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5052867/final_ins_rpt_sp_v2.1.zip)

TESTCASE1: [Final_Insecption_Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5052869/Final_Insecption_Testcase1.xlsx)

TEST RESULT1: [Test_Result_FIR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5052871/Test_Result_FIR.pdf)

TESTCASE2: [Final_Insecption_Report - Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5052856/Final_Insecption_Report.-.Testcase2.xlsx)

TEST RESULT2: [Final Inspection_TR2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5052857/Final.Inspection_TR2.pdf)

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@eafaisal kindly update PFS and move to development for variant 

![image](https://user-images.githubusercontent.com/47313592/90097005-92e8ab80-dd52-11ea-8af6-0f4ae95fd3f1.png)

**Comment by srinivasanbaskaran** [comment]
Team,

There is no PFS updation as of now. So this ticket goes to previous stage 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer gave Confirmation to move this report to GREEN. 

So, Kindly proceed further 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer Approved, so closing this ticket

**Comment by sujin1708** [comment]
Variant logic to be handled

**Comment by sujin1708** [comment]
Refer the below image and apply the material description logic in final inspection report

![image](https://user-images.githubusercontent.com/47313592/102455310-64167500-4065-11eb-98fe-f0788b2d7661.png)

**Comment by Nandhineedevi** [comment]
Completed.

[final inspection.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5709334/final.inspection.pdf)
[QCR_V3.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5709339/QCR_V3.1.zip)

**Comment by sujin1708** [comment]
kindly deploy the report in live server

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by Nandhineedevi** [comment]
@Narendiranath
DW Report Name: quality_control_rpt_f

Kindly Move only the DW Report from UAT to Live Server.
All Back end and Front end Deployment had been completed.
Latest Deliverable has been attached below.

[Live_import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5918640/Live_import.zip)

**Comment by Narendiranath** [comment]
Hi Sujin,

         DW Report deployed in live server. Kindly check. PFA Latest Deliverables for your ref.

[Dw_ER_03Feb2021225248.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5920363/Dw_ER_03Feb2021225248.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployment Completed in Live Server Kindly Closed the ticket

**Comment by sujin1708** [comment]
@karthikeyanamitysoft please check below
1. Material name not fethcing
![image](https://user-images.githubusercontent.com/47313592/125385321-e37be500-e3b7-11eb-9fea-b651d1083a70.png)

**Comment by Jeyapriyat** [comment]
@sujin1708 
changes completed,kindly check and revert.
i have attached latest deliverables.
[new sp live - 16-07-2021.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6830098/new.sp.live.-.16-07-2021.zip)
![image](https://user-images.githubusercontent.com/37791285/125935929-fb4363b1-78f5-4817-8d5e-a0a6931912ca.png)

**Comment by sujin1708** [comment]
@Manimahat Kindly test this

**Comment by Manimahat** [comment]
@Jeyapriyat ,

Please deploy the same deliverable in UAT server.

Thanks,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup sir,

Need to deploy the same deliverable in UAT server.

Thanks,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy the same deliverables in UAT server also

**Comment by Jeyapriyat** [comment]
@Manimahat 
deployment completed in uat server.kindly check and revert.
i have attached latest deliverables and sample output.
[final inspection report - jcie-211.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6855441/final.inspection.report.-.jcie-211.zip)
[sample output - uat.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6855448/sample.output.-.uat.pdf)

**Comment by Manimahat** [comment]
@raju-kurup sir,

As per our new Requirement Material Name Logic Changed & other Issue has been Resolved. New Deliverable deployed & Tested Successfully in Both UAT & Live Server. Test Result has been attached Below.  Please close this Ticket.

Live Server Result : [Final Inspection report - Live.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6872207/Final.Inspection.report.-.Live.pdf)

UAT Server Result : [Final Inspection report - UAT.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6872208/Final.Inspection.report.-.UAT.pdf)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Report Developed and deployed in both Live and Test, so Closing this ticket.
