### ISSUE TITLE
IMP-SDD for Maintenance Management

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#19]
IMP-SDD for Maintenance Management

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the attached updated Maintenance SDD all version for your reference.

SDD : [01_JCIPL_EAM_SDD_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3476841/01_JCIPL_EAM_SDD_V.1.0.docx)
SDD : [02_JCIPL_EAM_SDD_V 1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3476843/02_JCIPL_EAM_SDD_V.1.1.docx)
SDD : [03_JCIPL_EAM_SDD_V 1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3476846/03_JCIPL_EAM_SDD_V.1.2.docx)

Thanks and Regards,
M.Maheshwaran

**Comment by raju-kurup** [comment]
SDD issued waiting for Sign-off
