### ISSUE TITLE
QLT : Feedback Form - RDW

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#190]
Dear Team,

Please find the PFS for Feedback Form RDW.

PFS will be attached in future

PFS: 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

PFS Completed As per customer Requirement. Please find the below attachment.

PFS :  [FEED BACK FORM_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4163747/FEED.BACK.FORM_PFS_v1.0.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Karthi - Please start the development

**Comment by karthikeyanamitysoft** [comment]
Sir Review the PFS sir,

There is no EDK screen layout .

REgards,
Karthi

**Comment by srinivasanbaskaran** [comment]
Team,

Please Refer #45 for EDK Design

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Manivel or Srinivasan,
Kindly update Remarks field and department field in the PFS.

Regards
Nandhinee Devi

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Please Review the Updated PFS & Allocated to Developers. We Need to show this report to user On Monday.

Updated PFS : 
[FEED BACK FORM_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4239481/FEED.BACK.FORM_PFS_v1.1.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Please start doing the rework of this report

**Comment by raju-kurup** [comment]
Ezhil - Please do the correction as per PFS and contact Srini/Manivel for clarification

**Comment by srinivasanbaskaran** [comment]
Manivel,

Please Start Testing & Prepare the Testing Documents

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Percentage & Remarks Column condition Still not Updated. Kindly allocate this ticket to Developer.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@mani : please check with Srinivasan and change the ticket.

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the signed copy of the changes of Feedback Form Report.

Feedback Form Report: ![1583814589440](https://user-images.githubusercontent.com/46194039/76281438-0c1f3680-62bb-11ea-9a8d-71569f42b6b9.JPEG)

Below are the Points to be changed.

1. Inspection Request No
2. Material value to be fetched from Item Category
3. Green related information doesn't required in the Print
4. Don't want the Fired Dimensions which are all the Items having Grinding & Lapping
5. Percentage ( 2 digits ) [ 5.01%]

Regards,
Srinvasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the attached updated PFS. Kindly Review this & Proceed for the Development

PFS: [04_Quality_Feedback_Form_Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4311500/04_Quality_Feedback_Form_Report_PFS_v1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Pease find the updated PFS as per the User's Requirements.

PFS: 
[04_Quality_Feedback_Form_Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4332652/04_Quality_Feedback_Form_Report_PFS_v1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back
Please find the latest deliverables for this report.

[Feedback Form.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4337987/Feedback.Form.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start the Testing 1 & Prepare the Testcase 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju Sir,

Kindly Review the Updated PFS & Allocated to developers

Updated PFS : [04_Quality_Feedback_Form_Report_PFS_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4357951/04_Quality_Feedback_Form_Report_PFS_v1.3.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Team,

Please find the attached Updated PFS.

PFS: [04_Quality_Feedback_Form_Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4359744/04_Quality_Feedback_Form_Report_PFS_v1.4.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back
Please find the latest deliverables for this report.

[feedback_937_p1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4362578/feedback_937_p1.pdf)
[Feedback Form_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4362580/Feedback.Form_v1.2.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start the Testing & Preapre the Testing document

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,
Testing 1 Process Completed. Kindly start the Testing 2 Process.

Test Case : 
[Test.Case.-.Feed Back Form Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4368150/Test.Case.-.Feed.Back.Form.Report_v1.0.xlsx)

Test Result : 
[Feed Back Form Test Result_1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4368151/Feed.Back.Form.Test.Result_1.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

Feedback Form Report Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [04_Quality_Feedback_Form_Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389378/04_Quality_Feedback_Form_Report_PFS_v1.4.xlsx)

PATH: Inventory & PICC --> Quality Management --> View Final Feedback Clearance Details 

DELIVERABLES: [Feedback.Form_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4389387/Feedback.Form_v1.2.zip)

TESTCASE1: [Test.Case.-.Feed.Back.Form_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389389/Test.Case.-.Feed.Back.Form_Report_v1.0.xlsx)

TEST RESULT1: [Feed.Back.Form.Test.Result_1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4389392/Feed.Back.Form.Test.Result_1.pdf)

TESTCASE2: [Testcase2_Feedback_Form_Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389397/Testcase2_Feedback_Form_Report_v1.0.xlsx)

TEST RESULT2: [05_Feedback Form_1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4389402/05_Feedback.Form_1.pdf)

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Kindly Review the Updated PFS with Test Data & Allocated to Developers.

Need To Change the Column Name: Name Of the Component into Item Description 

Updated PFS : [04_Quality_Feedback_Form_Report_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4442973/04_Quality_Feedback_Form_Report_PFS_v1.5.xlsx)

Test Data : [Test data For Feed Back Form.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4442975/Test.data.For.Feed.Back.Form.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction in changing the column name " Name of component" to "Item Description"

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Tesing1 completed. PFA documents.
[Feedback Form TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4456539/Feedback.Form.TR.pdf)
[Testcase Feedback_Form_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4456540/Testcase.Feedback_Form_Report.xlsx)

**Comment by srinivasanbaskaran** [comment]
@srinivasanbaskaran,

Feedback Form Report Testing2 Completed. 

Testcase2: [Testcase2_Feedback_Form_Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4464887/Testcase2_Feedback_Form_Report_v1.2.xlsx)

Test Result2: [Feedback Form Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4464889/Feedback.Form.Report.pdf)

Regards,
Manivel.A

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan.B

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the latest deliverables.

[feedback_form_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4468058/feedback_form_v1.3.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS as per the Customer Requirements.

PFS: [04_Quality_Feedback_Form_Report_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4509799/04_Quality_Feedback_Form_Report_PFS_v1.5.xlsx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS along with Test Data of Feedback Form Report

PFS & Test Data : [04_Quality_Feedback_Form_Report_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4513678/04_Quality_Feedback_Form_Report_PFS_v1.6.xlsx)

REgards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Add 2 data in report of rejected reason data and qty.  Nandhinee has done this report

**Comment by Narendiranath** [comment]
Hi Srini,

              Changes are done. Please find the attached report.
[Feed_Back_Form_Test_report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4520443/Feed_Back_Form_Test_report.pdf)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

User given confirmation.. Attached the same

Doc: 
![Feedback Form Report](https://user-images.githubusercontent.com/46194039/81581849-ebfc1880-93cc-11ea-8302-9cd0e311a91a.jpg)

Kindly close this ticket.

Regards,
Srinivasan

**Comment by srinivasanbaskaran** [comment]
Manivel,

Report is working correctly. Pls start the Testing & Prepare the Testcase

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 1 Completed. Kindly start the Testing 2 process.

Test Case : [Test.Case.-.Feed.Back.Form.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4626211/Test.Case.-.Feed.Back.Form.Report.xlsx)

Test Result : [Feed Back form Report Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4626213/Feed.Back.form.Report.Result.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing 2 & Prepare the Testing documents 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing 2 is completed..
[FEED BACK FORM TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4654597/FEED.BACK.FORM.TR.pdf)
[Test.Case.-.Feed.Back.Form.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4654598/Test.Case.-.Feed.Back.Form.Report.xlsx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Feedback Form Report Development & Testing has been completed. Herewith I have attached some testing documents for future references.

PFS: [04_Quality_Feedback_Form_Report_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4654781/04_Quality_Feedback_Form_Report_PFS_v1.6.xlsx)

DELIVERABLES: 

TESTCASE1: [Test.Case.-.Feed.Back.Form.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4654782/Test.Case.-.Feed.Back.Form.Report.xlsx)

TEST RESULT1: [Feed.Back.form.Report.Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4654783/Feed.Back.form.Report.Result.pdf)

TESTCASE2: [Test.Case2-.Feed.Back.Form.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4654784/Test.Case2-.Feed.Back.Form.Report.xlsx)

TEST RESULT2: [FEED.BACK.FORM.TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4654786/FEED.BACK.FORM.TR.pdf)

**Comment by Narendiranath** [comment]
Hi Srinivasan,

                     Deliverables Attached. Kindly check.
[Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4654794/Deliverables.zip)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Feedback Form Report Development & Testing has been completed. Herewith I have attached some testing documents for future references.

PFS: [04_Quality_Feedback_Form_Report_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4654781/04_Quality_Feedback_Form_Report_PFS_v1.6.xlsx)

DELIVERABLES: [Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4654798/Deliverables.zip)

TESTCASE1: [Test.Case.-.Feed.Back.Form.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4654782/Test.Case.-.Feed.Back.Form.Report.xlsx)

TEST RESULT1: [Feed.Back.form.Report.Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4654783/Feed.Back.form.Report.Result.pdf)

TESTCASE2: [Test.Case2-.Feed.Back.Form.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4654784/Test.Case2-.Feed.Back.Form.Report.xlsx)

TEST RESULT2: [FEED.BACK.FORM.TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4654786/FEED.BACK.FORM.TR.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir, 

Customer gave confirmation for this report. So, you can proceed to close this ticket sir... 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed, so closing this development

**Comment by sujin1708** [comment]
Customer Comments :

In ok column we want minimum  & maximum Actual value. Rejection also not shown we sent you scan copy

**Comment by srinivasanbaskaran** [comment]
Sujin, 

Rejection Details are provided in the transaction. But In report it not shown

Feedback Form Transaction : 
![image](https://user-images.githubusercontent.com/46194039/89022944-73a85200-d340-11ea-8d63-53030f139913.png)


Feedback Form Report : ![image](https://user-images.githubusercontent.com/46194039/89022826-3e9bff80-d340-11ea-8182-54d2df365b70.png)

**Comment by sujin1708** [comment]
@nandhini please find the update pfs kindly do the changes yellow highlighted points
PFS : [04_Quality_Feedback_Form_Report_PFS_v1.7.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5006315/04_Quality_Feedback_Form_Report_PFS_v1.7.xlsx)

Customer comments :
![image](https://user-images.githubusercontent.com/47313592/89023351-12cd4980-d341-11ea-83b7-bf544297cf60.png)

**Comment by Nandhineedevi** [comment]
[feedback.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5014073/feedback.pdf)
[feed_form_rpt_sp.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5014075/feed_form_rpt_sp.zip)

**Comment by srinivasanbaskaran** [comment]
Akash, 

Kindly start the Testing 1 & Prepare the Testing Documents.

Regards,

Srinivasan Baskaran

**Comment by sujin1708** [comment]
@eafaisal kindly update the PFS for variant and move to review raju sir

![image](https://user-images.githubusercontent.com/47313592/90098190-494d9000-dd55-11ea-9f0e-70da7b3e0883.png)

**Comment by srinivasanbaskaran** [comment]
@eafaisal ,

Kindly start Testing 1 & Prepare the Testing Document 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 1 is completed.
Kindly proceed with testing 2.

Test Case : 
[Test.Case1-.Feed.Back.Form.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145159/Test.Case1-.Feed.Back.Form.Report.xlsx)

Test Result : 
[FEED.BACK.FORM.TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5145160/FEED.BACK.FORM.TR.pdf)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 2 Completed. Herewith I have attached the Testing Documents for the future references.

TESTCASE: [Testcase2_Feedback_Form_Report_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5155018/Testcase2_Feedback_Form_Report_v1.3.xlsx)

TEST RESULT: [Feedback Form_ New Testing2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5155019/Feedback.Form_.New.Testing2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Feedback Form Report testing has been completed. Herewith I have attached the Testing Documents for the Future references.

PFS: [04_Quality_Feedback_Form_Report_PFS_v1.7.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5155067/04_Quality_Feedback_Form_Report_PFS_v1.7.xlsx)

DELIVERABLES: [feed_form_rpt_sp.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5155073/feed_form_rpt_sp.zip)

TESTCASE1: [Test.Case1-.Feed.Back.Form.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145159/Test.Case1-.Feed.Back.Form.Report.xlsx)

TEST RESULT1 : [FEED.BACK.FORM.TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5145160/FEED.BACK.FORM.TR.pdf)

TESTCASE2: [Testcase2_Feedback_Form_Report_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5155051/Testcase2_Feedback_Form_Report_v1.3.xlsx)

TEST RESULT2: [Feedback Form_ New Testing2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5155053/Feedback.Form_.New.Testing2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer gave confirmation to MOVE this report to GREEN.

So, Kindly proceed further to Close this report

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer Approved, so closing this ticket

**Comment by sujin1708** [comment]
Variant to be handled

**Comment by sujin1708** [comment]
@karthikeyanamitysoft  please find the updated PFS ..kindly change the material description  logic as per the PFS [04_Quality_Feedback_Form_Report_PFS_v1.8.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5700142/04_Quality_Feedback_Form_Report_PFS_v1.8.xlsx)

**Comment by Nandhineedevi** [comment]
Completed

[feedback.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5708234/feedback.pdf)
[QCR_v3.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5708240/QCR_v3.1.zip)

**Comment by sujin1708** [comment]
kindly deploy the report in live server

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by Nandhineedevi** [comment]
@Narendiranath
DW Report Name: quality_control_rpt_ff

Kindly Move only the DW Report from UAT to Live Server.
All Back end and Front end Deployment had been completed.
Latest Deliverable has been attached below.

[Live_import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5918632/Live_import.zip)

**Comment by Narendiranath** [comment]
Hi Sujin,

            DW Report deployed in live server. Kindly check. PFA Latest deliverables for your ref.

[Dw_ER_03Feb2021222247.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5920143/Dw_ER_03Feb2021222247.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployment Completed in Live Server Kindly Closed the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Due to Material Name & Q.C Supervisor is not fetching. So we re-opened this ticket for correction.Please allocate to developers

Material Name : STEATE
Q.C SUPERVISOR: Mr. K.S. CHINCHORE    this value is missing in the Report.

![image](https://user-images.githubusercontent.com/55881685/126458070-1b521e3b-3e7d-4367-b8db-5d0a1b19226e.png)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Due to Material Name & Q.C Supervisor is not fetching. So we re-opened this ticket for correction.Please allocate to developers

Material Name : STEATE
Q.C SUPERVISOR: Mr. K.S. CHINCHORE    this value is missing in the Report.

![image](https://user-images.githubusercontent.com/55881685/126458070-1b521e3b-3e7d-4367-b8db-5d0a1b19226e.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction in the report 
Material Name 
Q.C SUPERVISOR : value is missing in the Report.
**Drawing No. is coming correct so Please leave this Error.**

**Comment by karthikeyanamitysoft** [comment]
Dear Sir ,

There is no standard format is followed, so that QC supervisor  value is not coming sir.

Regards,
Karthi

**Comment by raju-kurup** [comment]
Dear Karthi,
We checked in both UAT and live regarding the QC Supervisor fed, but no changes are found.  For your reference, both the live server and test server attach notes are attached in the above comments.

**Comment by Narendiranath** [comment]
Hi Manivel,

             Above mentioned issues are completed in both UAT & Live server. Kindly check and reveert back. PFA Latest Deliverable & Test result for your ref.

[Deliverable V.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6869655/Deliverable.V.1.zip)
[Test_Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6869656/Test_Result.pdf)

Regards,
Naren

**Comment by Manimahat** [comment]
@raju-kurup sir,

As per our new Requirement Material Name Logic Changed & other Issue has been Resolved. New Deliverable deployed & Tested Successfully in Both UAT & Live Server. Test Result has been attached Below.  Please close this Ticket.

Live Server Result : [Feed back form - Live.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6872214/Feed.back.form.-.Live.pdf)

UAT Server Result : [Feed back form - UAT.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6872215/Feed.back.form.-.UAT.pdf)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Report Developed and deployed in both Live and Test, so Closing this ticket.
