### ISSUE TITLE
QLT : Certificate of Analysis Report - RDW

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#192]
Dear Team,

Please find the attached PFS for Certificate Of Analaysis Report RDW.

PFS will be updated later

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please start the development

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Wrongly named this report. So I change this Ticket name to Certificate of Analysis Report - RDW. 

PFS is inprogress. Will update once it completed.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Please find the attached PFS for Certificate Of Analaysis Report RDW.

PFS: [05_Quality_Certificate of Analysis_Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4176781/05_Quality_Certificate.of.Analysis_Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Please Refer #45 for EDK Design

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Format received on 21-02-2020

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Please Review the PFS & Allocate to Development 

PFS: [05_Quality_Certificate of Analysis_Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4243228/05_Quality_Certificate.of.Analysis_Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Karthi,
New Report, Please start development only bank details will be given later

**Comment by raju-kurup** [comment]
Nandhinee - Please start developing and contact Srinivasan for clarification

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

As discussed with Raju sir, Please start the Rework on this report..

Values are not comes in this report. 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Please do the following corrections 

1. Invoice Number 
2. Expiry Date
3. Invoice Date
4. Company Name ( Header )
5. Address ( Footer )

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the signed copy of the changes of Certificate of Analysis Report.

COA: ![1583814590033](https://user-images.githubusercontent.com/46194039/76280734-daa56b80-62b8-11ea-8aef-c7f6a5734511.JPEG)

Below are the Points to be changed.

1. Logo
2. Inspection Request No
3. Material value to be fetched from Item Category
4. Green related information doesn't required in the Print
5. Don't want the Fired Dimensions which are all the Items having Grinding & Lapping

Regards,
Srinvasan Baskaran

**Comment by raju-kurup** [comment]
Please update the PFS and send it for review

**Comment by srinivasanbaskaran** [comment]
Sir,

PFS updated. Kindly Review & Proceed for the Development

PFS: [05_Quality_Certificate of Analysis_Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4311196/05_Quality_Certificate.of.Analysis_Report_PFS_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the updated PFS as per the Customer's Requirements.

PFS: 
[05_Quality_Certificate of Analysis_Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4332631/05_Quality_Certificate.of.Analysis_Report_PFS_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back
Please find the latest deliverables for this report.

[Certificate analysis report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4337993/Certificate.analysis.report.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Certificate of Analysis Report testing completed. Herewith I have attached testing documents for future references.

PFS:[05_Quality_Certificate of Analysis_Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4353712/05_Quality_Certificate.of.Analysis_Report_PFS_v1.1.xlsx)

TESTCASE 1: [Test Case - Certificate of Analysis Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4353716/Test.Case.-.Certificate.of.Analysis.Report_v1.0.xlsx)

TEST RESULT 1: [799_COA_Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4353717/799_COA_Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start the Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 2 Completed. Please find the Document for your Reference.

Test Case : [Test.Case.-.Certificate.of.Analysis.Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356111/Test.Case.-.Certificate.of.Analysis.Report_v1.1.xlsx)

Test Result : [Certificate of Analysis Report Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4356113/Certificate.of.Analysis.Report.Result.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

Certificate of Analysis Report testing completed. Herewith I have attached testing documents for future references.

PFS:[05_Quality_Certificate of Analysis_Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4353712/05_Quality_Certificate.of.Analysis_Report_PFS_v1.1.xlsx)

PATH : Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details 

DELIVERABLES: [Certificate.analysis.report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4353739/Certificate.analysis.report.zip)

TESTCASE 1: [Test Case - Certificate of Analysis Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4353716/Test.Case.-.Certificate.of.Analysis.Report_v1.0.xlsx)

TEST RESULT 1: [799_COA_Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4353717/799_COA_Report.pdf)

TESTCASE2: [Test.Case.-.Certificate.of.Analysis.Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356473/Test.Case.-.Certificate.of.Analysis.Report_v1.1.xlsx)

TEST RESULT2: [Certificate.of.Analysis.Report.Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4356477/Certificate.of.Analysis.Report.Result.pdf)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested, so closing this issue

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

I re-open this Report, Due to the changes given by the Users. Received on 20-03-2020. 

Below are the Corrections to be made in this report. 

1. Name of the Report - Certificate Of Analysis ( Remove the Report ) 
2. Dont want to Print the Fired related data for the Item having GRINDING Attributes

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.
Kindly provide Document credit number with label otherwise Document number will be empty

![image](https://user-images.githubusercontent.com/52193780/77512652-77f7c680-6e99-11ea-8c75-c791e3844935.png)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Certificate of Analysis Report testing completed. Herewith I have attached testing documents for future references.

PFS:[05_Quality_Certificate of Analysis_Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4353712/05_Quality_Certificate.of.Analysis_Report_PFS_v1.1.xlsx)

PATH : Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details 

DELIVERABLES: [Certificate.analysis.report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4353739/Certificate.analysis.report.zip)

TESTCASE 1: [Test Case - Certificate of Analysis Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4387964/Test.Case.-.Certificate.of.Analysis.Report_v1.1.xlsx)

TEST RESULT 1: [08_Certificate of Analysis.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4387966/08_Certificate.of.Analysis.pdf)

TESTCASE2: [Test.Case.-.Certificate.of.Analysis.Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356473/Test.Case.-.Certificate.of.Analysis.Report_v1.1.xlsx)

TEST RESULT2: [Certificate.of.Analysis.Report.Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4356477/Certificate.of.Analysis.Report.Result.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start Testing2 & Prepare the Testing document 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 2 Completed. Please find the Attached Document For Your Refer....

Result : [Result - Certificate Of Analysis.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4394162/Result.-.Certificate.Of.Analysis.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

Certificate of Analysis Report testing completed. Herewith I have attached testing documents for future references.

PFS:[05_Quality_Certificate of Analysis_Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4353712/05_Quality_Certificate.of.Analysis_Report_PFS_v1.1.xlsx)

PATH : Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details 

DELIVERABLES: [Certificate.analysis.report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4353739/Certificate.analysis.report.zip)

TESTCASE 1: [Test Case - Certificate of Analysis Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4387964/Test.Case.-.Certificate.of.Analysis.Report_v1.1.xlsx)

TEST RESULT 1: [08_Certificate of Analysis.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4387966/08_Certificate.of.Analysis.pdf)

TESTCASE2: [Test.Case.-.Certificate.of.Analysis.Report_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4397460/Test.Case.-.Certificate.of.Analysis.Report_v2.xlsx)

TEST RESULT2: [Result.-.Certificate.Of.Analysis.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4397450/Result.-.Certificate.Of.Analysis.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

User given confirmation.. Attached the same

Doc: ![Certificate of Analysis_Confirmation](https://user-images.githubusercontent.com/46194039/81581709-b6efc600-93cc-11ea-93a1-e91bc20ad962.jpg)

Kindly close this ticket.

Regards,
Srinivasan

**Comment by raju-kurup** [comment]
Development completed, so closing this issue

**Comment by sujin1708** [comment]
Customer Comments :

We want BIO CERAMIC DIVISION below our companies name.
Instead of QC Inspector we want format no. FRM/QCD/03 & it should be variable.

**Comment by sujin1708** [comment]
@raju-kurup please find attached revised PFS fro your reference ..kindly assign to nandhini
[05_Quality_Certificate of Analysis_Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5054652/05_Quality_Certificate.of.Analysis_Report_PFS_v1.2.xlsx)

**Comment by sujin1708** [comment]
@srinivasanbaskaran kindly do the modeling as per the customer requierment

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS as per the Customer Requirement

PFS: [05_Quality_Certificate of Analysis_Report_PFS_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5161017/05_Quality_Certificate.of.Analysis_Report_PFS_v1.3.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir, 

Kindly review this PFS & allocate to Developer for the Development

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS.

PFS: [05_Quality_Certificate.of.Analysis_Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5162549/05_Quality_Certificate.of.Analysis_Report_PFS_v1.4.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction mentioned in PFS.

**Comment by Narendiranath** [comment]
Hi Srinivasan Baskaran,

               Changes are done. Kindly check. PFA Latest Deliverable & Test Result.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5169105/Deliverable.zip)
[QIR_2021_1171_P1_Test_Result_1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5169110/QIR_2021_1171_P1_Test_Result_1.pdf)
[QIR_1920_0538_P1_Test_Result_2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5169111/QIR_1920_0538_P1_Test_Result_2.pdf)
[QIR_2021_1018_P1_Test_Result_3.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5169112/QIR_2021_1018_P1_Test_Result_3.pdf)

Thanks,
Naren

**Comment by Narendiranath** [comment]
Hi,

PFA Latest Deliverable
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5182681/Deliverable.zip)

**Comment by srinivasanbaskaran** [comment]
team,

Certificate Of Analysis Report Testing1 has been completed. Herewith I have attached Testing Documents of the Testing1. 

TESTCASE1: [Test Case - Certificate of Analysis Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5188857/Test.Case.-.Certificate.of.Analysis.Report_v1.2.xlsx)

TEST RESULT1: [Certificate Of Analysis_New_After Correction.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5188867/Certificate.Of.Analysis_New_After.Correction.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Report will have the Logic change of MATERIAL NAME. So, I HOLD this report testing

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Faizal,

Kindly start the Testing 2 & Prepate the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Kindly check.

Test Case : 
[Test.Case.-.Certificate.of.Analysis.Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5201210/Test.Case.-.Certificate.of.Analysis.Report_v1.2.xlsx)

Test Result : 
[Certificate.Of.Analysis_New_After.Correction.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5201212/Certificate.Of.Analysis_New_After.Correction.pdf)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Certificate of Analysis Report Testing has been completed. Herewith I have attached the Testing documents for the future references.

PFS: [05_Quality_Certificate.of.Analysis_Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5243426/05_Quality_Certificate.of.Analysis_Report_PFS_v1.4.xlsx)

DELIVERABLES: [Deliverable_COA.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5243428/Deliverable_COA.zip)

TESTCASE1: [Test Case - Certificate of Analysis Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5188857/Test.Case.-.Certificate.of.Analysis.Report_v1.2.xlsx)

TEST RESULT1: [Certificate Of Analysis_New_After Correction.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5188867/Certificate.Of.Analysis_New_After.Correction.pdf)

TESTCASE2 :[Test.Case.-.Certificate.of.Analysis.Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5201210/Test.Case.-.Certificate.of.Analysis.Report_v1.2.xlsx)

TEST RESULT2 : [Certificate.Of.Analysis_New_After.Correction.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5201212/Certificate.Of.Analysis_New_After.Correction.pdf)

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
QC inspector lable to be display for all other division except dental.

**Comment by Narendiranath** [comment]
Hi Srinivasan Baskaran,

                      Changes are done. Kindly check. PFA Latest deliverable & Test result for your referance.
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5267715/Deliverable.zip)
[Dental.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5267717/Dental.pdf)
[Non_Dental.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5267720/Non_Dental.pdf)

**Comment by srinivasanbaskaran** [comment]
Faisal,

Kindly start Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srinivasanbaskaran,

Certificate of Analysis Report Testing 2 Completed Kindly Check & Update.

[Test Result For-Certificate Of Analysis Report v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5292977/Test.Result.For-Certificate.Of.Analysis.Report.v2.pdf)

[Test.Case v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5292980/Test.Case.v2.xlsx)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Certificate of Analysis Report Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [05_Quality_Certificate.of.Analysis_Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5304252/05_Quality_Certificate.of.Analysis_Report_PFS_v1.4.xlsx)

DELIVERABLES: [Deliverable-COA.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5304270/Deliverable-COA.zip)

TESTCASE1: [Test Case - Certificate of Analysis Report_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5304221/Test.Case.-.Certificate.of.Analysis.Report_v1.3.xlsx)

TEST RESULT1(a): [COA_Dental.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5304224/COA_Dental.pdf)

TEST RESULT 1(b): [COA_Non Dental.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5304230/COA_Non.Dental.pdf)

TESTCASE2: [Test Result For-Certificate Of Analysis Report v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5292977/Test.Result.For-Certificate.Of.Analysis.Report.v2.pdf)

TEST RESULT2: [Test.Case v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5292980/Test.Case.v2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS as per the Latest Requirments of the Customer. 

PFS: [05_Quality_Certificate.of.Analysis_Report_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5353027/05_Quality_Certificate.of.Analysis_Report_PFS_v1.5.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as mentioned in PFS.

**Comment by Narendiranath** [comment]
Hi Srinivasan Baskaran,

                         Changes are done. Kindly check. PFA Test result & Latest Deliverable

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5364892/Deliverable.zip)
[Non_BIO_Ceramic.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5364893/Non_BIO_Ceramic.pdf)
[BIO_Ceramic.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5364894/BIO_Ceramic.pdf)

**Comment by srinivasanbaskaran** [comment]
Team, 

Testing1 Completed. Herewith I have attached the Testing Documents for the Future references.

TESTCASE1: [Test Case - Certificate of Analysis Report_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5369640/Test.Case.-.Certificate.of.Analysis.Report_v1.4.xlsx)

TEST RESULT1: [COA_P3.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5369642/COA_P3.pdf)

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Test case and result are attached.

Test Case : 
[COA.TEST.CASE.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5391886/COA.TEST.CASE.2.xlsx)

Test Result: 
[COA.TEST.RESULT.2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5391890/COA.TEST.RESULT.2.pdf)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Certificate Of Analysis Report Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [05_Quality_Certificate.of.Analysis_Report_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5406765/05_Quality_Certificate.of.Analysis_Report_PFS_v1.5.xlsx)

DELIVERABLES: [COA_Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5406770/COA_Deliverables.zip)

TESTCASE1: [Test Case - Certificate of Analysis Report_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5369640/Test.Case.-.Certificate.of.Analysis.Report_v1.4.xlsx)

TEST RESULT1: [COA_P3.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5369642/COA_P3.pdf)

TESTCASE2 : [COA.TEST.CASE.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5391886/COA.TEST.CASE.2.xlsx)

TEST RESULT2: [COA.TEST.RESULT.2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5391890/COA.TEST.RESULT.2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer gave confirmation to move this report to GREEN on 18-10-2020 through mail confirmation.

Kindly proceed to close this report

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@raju-kurup plz close the ticket

**Comment by sujin1708** [comment]
variant logic to be handled

**Comment by Narendiranath** [comment]
Hi Sujin,

           Development Completed. Test data is not given for this report. So i am not tested. PFA Latest deliverable.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5719602/Deliverable.zip)

**Comment by sujin1708** [comment]
@Manimahat kindly do the testing 1 and prepare test document

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 Completed. kindly Start the Testing 2 Process.

Test Case 1 : [Test.Case.-.Certificate.of.Analysis.Report_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5827271/Test.Case.-.Certificate.of.Analysis.Report_v1.4.xlsx)

Test Result : [COA_P3.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5827277/COA_P3.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
Testing 2 completed

Test result2 : [Certificate.of.Analysis.Report.Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5836333/Certificate.of.Analysis.Report.Result.pdf)

Test case2 : [Test.Case.-.Certificate.of.Analysis.Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5836336/Test.Case.-.Certificate.of.Analysis.Report_v1.1.xlsx)

**Comment by sujin1708** [comment]
Awaiting for customer confirmation..

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this development to live server

**Comment by Nandhineedevi** [comment]
Completed Moving into Live Server.

[Import Files.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6591917/Import.Files.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployment Completed in Live Server Kindly Closed the ticket

**Comment by Narendiranath** [comment]
Hi, 

         PFA latest deliverable.

[Deliverable V.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6699584/Deliverable.V.1.zip)

Regards,
Naren

**Comment by sujin1708** [comment]
@karthikeyanamitysoft 

1. Material name not fetching
![image](https://user-images.githubusercontent.com/47313592/125385712-a5cb8c00-e3b8-11eb-9007-25d1d8f0064d.png)

**Comment by Jeyapriyat** [comment]
@sujin1708 
changes completed,kindly check and revert.
i have attached latest deliverables.
[new sp live.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6829973/new.sp.live.zip)
![image](https://user-images.githubusercontent.com/37791285/125933513-a5039aa7-a59c-4aef-8dc3-cee9cdacb975.png)

**Comment by sujin1708** [comment]
@Manimahat kindly test this

**Comment by Manimahat** [comment]
@Jeyapriyat ,

Please deploy the same deliverable in UAT server.

Thanks,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup sir,

Need to deploy the same deliverable in UAT server. Please allocate this ticket to Developer.

Thanks,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this development in UAT server also.

**Comment by Jeyapriyat** [comment]
@Manimahat 
changes completed, kindly check and revert.
i have attached latest deliverables.
[jcie-211.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6872118/jcie-211.zip)

**Comment by Manimahat** [comment]
@raju-kurup sir,

As per our new Requirement Material Name Logic Changed & other Issue has been Resolved. New Deliverable deployed & Tested Successfully in Both UAT & Live Server. Test Result has been attached Below.  Please close this Ticket.

Live Server Result 1 : [Certificate of analysis report With Bio Ceramic divison - Live.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6875793/Certificate.of.analysis.report.With.Bio.Ceramic.divison.-.Live.pdf)

Live Server Result 2 : [Certificate of analysis report Without Bio Ceramic divison - Live.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6875795/Certificate.of.analysis.report.Without.Bio.Ceramic.divison.-.Live.pdf)
 

UAT Server Result 1 : [Certificate of analysis report With Bio Ceramic divison - UAT.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6875814/Certificate.of.analysis.report.With.Bio.Ceramic.divison.-.UAT.pdf)

UAT Server Result 2: [Certificate of analysis report Without Bio Ceramic divison - UAT.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6875815/Certificate.of.analysis.report.Without.Bio.Ceramic.divison.-.UAT.pdf)
 
Regards,
Manivel A

**Comment by raju-kurup** [comment]
Report Developed and deployed in both Live and Test, so Closing this ticket.
