### ISSUE TITLE
QLT : Raw Material Test Report - RDW

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#193]
Team,

Herewith I have attached the PFS for Raw Material Test Report.

PFS: [01_Quality Control_Raw Material Inspection Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4172371/01_Quality.Control_Raw.Material.Inspection.Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi,
The DW design has been completed for the report with name "quality_control_rpt"

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

Please Refer #45 for EDK Design

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The coding has been completed.
The deliverables will be attached in #45 

Regards
Nandhinee devi

**Comment by srinivasanbaskaran** [comment]
Nadhinee,

Please find the below points for corrections..

1. Accepted / Rejected  -- Not coming into the Report
2. Big Gap between Product Description Supplier Name
3. Lot Number is not coming against the Item code which GR status is in MOVED.

Ref. Doc. No: 

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Please Review the Updated PFS as per the User Requirement & Allocate to Developers.

PFS: [01_Quality Control_Raw Material Inspection Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4240682/01_Quality.Control_Raw.Material.Inspection.Report_PFS_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Pleasae find the updated PFS for Raw Material Test Report.

Kindly Review & Allocate this to Developers.

PFS: [01_Quality Control_Raw Material Inspection Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4248169/01_Quality.Control_Raw.Material.Inspection.Report_PFS_v1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Karthi,
Please do the rework

**Comment by raju-kurup** [comment]
Ezhil - Please do the correction as per PFS and contact Srini/Manivel for clarification.

**Comment by srinivasanbaskaran** [comment]
Ezhil,

While taking the Report, got the error as attached. 

![image](https://user-images.githubusercontent.com/46194039/75558341-b3a09b80-5a67-11ea-98ac-cf80005b4fa1.png)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Ezhil,

Kindly remove the Remarks column at the bottom of the reports. Instead of Remarks only we are provide Feedback. 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Please update the below points in this report.

1. Minimum & Maximum values to updated in both ( SPECIFIED & OBTAINED )
2. HARDCODED - All the Dimensions are in MM
3. Lot Number 
4. Qty Received

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly update the Latest deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Raw Material Test Report Testing has been done. Herewith, I have attached Testing documents for the future references

PFS: [01_Quality Control_Raw Material Inspection Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333856/01_Quality.Control_Raw.Material.Inspection.Report_PFS_v1.2.xlsx)

NAVIGATION: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details 

DELIVERABLES:

TESTCASE: [Test Case - Raw Material Test Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333857/Test.Case.-.Raw.Material.Test.Report_v1.0.xlsx)

TEST RESULT: [Test Result1_Raw_Material_Test_Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4333858/Test.Result1_Raw_Material_Test_Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the latest deliverables for this report.

[raw material test report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4336163/raw.material.test.report.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Raw Material Test Report Testing has been done. Herewith, I have attached Testing documents for the future references

PFS: [01_Quality Control_Raw Material Inspection Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333856/01_Quality.Control_Raw.Material.Inspection.Report_PFS_v1.2.xlsx)

NAVIGATION: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details 

DELIVERABLES: [raw.material.test.report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4336390/raw.material.test.report.zip)

TESTCASE: [Test Case - Raw Material Test Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333857/Test.Case.-.Raw.Material.Test.Report_v1.0.xlsx)

TEST RESULT: [Test Result_Raw_Material_Test_Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4333861/Test.Result_Raw_Material_Test_Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing 2 & Prepare the Testcase 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly start the Testing 2 & Prepare the Testcase 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran :

Testing2 completed. PFA

Test case : [Test.Case.-.Raw.Material.Test.Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4359670/Test.Case.-.Raw.Material.Test.Report_v1.0.xlsx)
Test Result:[Test Result - raw material report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4359672/Test.Result.-.raw.material.report.pdf)
t:

**Comment by srinivasanbaskaran** [comment]
Sir,

Raw Material Test Report Testing has been done. Herewith, I have attached Testing documents for the future references

PFS: [01_Quality Control_Raw Material Inspection Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333856/01_Quality.Control_Raw.Material.Inspection.Report_PFS_v1.2.xlsx)

NAVIGATION: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details 

DELIVERABLES: [raw.material.test.report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4336390/raw.material.test.report.zip)

TESTCASE1: [Test Case - Raw Material Test Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333857/Test.Case.-.Raw.Material.Test.Report_v1.0.xlsx)

TEST RESULT1: [Test Result_Raw_Material_Test_Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4333861/Test.Result_Raw_Material_Test_Report.pdf)

TESTCASE2: [Test.Case.-.Raw.Material.Test.Report_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4362462/Test.Case.-.Raw.Material.Test.Report_v1.0.xlsx)

TEST RESULT2: [Test.Result.-.raw.material.report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4362465/Test.Result.-.raw.material.report.pdf)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested, so closing this issue

**Comment by raju-kurup** [comment]
Customer accepted and waiting for sign

**Comment by srinivasanbaskaran** [comment]
Sir,

PFA of Customer Signed Copy
You can proceed further on closing this ticket

Doc: 
![Raw Material Test Report - Customer Signed Copy](https://user-images.githubusercontent.com/46194039/82276585-500d7680-99a3-11ea-9c59-b826f0091be5.jpg)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed, so closing this development

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by karthikeyanamitysoft** [comment]
Dear Nandinee,

Kindly deploy the deliverables into live server.

Regards,
Karthi

**Comment by Nandhineedevi** [comment]
@Narendiranath
DW Report Name: quality_control_rpt

Kindly Move only the DW Report from UAT to Live Server.
All Back end and Front end Deployment had been completed.
Latest Deliverable has been attached below.

[Live_import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5918629/Live_import.zip)

**Comment by Narendiranath** [comment]
Hi Srinivasan,

          DW Report deployed in live server. Kindly check. PFA Latest Deliverable for your ref. 

[Dw_ER_03Feb2021215621.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5920047/Dw_ER_03Feb2021215621.zip)

**Comment by raju-kurup** [comment]
Development Completed, so closing this ticket
