### ISSUE TITLE
TOOL - Process Document - Tool Management

### ISSUE THREAD

**Issue by basha123456** [astpl1998/Jyoti-Ceramic#194]
End to End Process Document for Tool Management.

**Comment by basha123456** [comment]
@raju-kurup :

Hi Sir,

Process Document is completed . Please review.
[Process Document - Tool Management.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4176590/Process.Document.-.Tool.Management.xlsx)

**Comment by basha123456** [comment]
Dear Sir,

Updated process document for your reference..pfa
[Process Document - Tool Management.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4239344/Process.Document.-.Tool.Management.xlsx)

**Comment by raju-kurup** [comment]
Freeze the template with Sunil and do the rework accordingly if needed and assign to me.

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Tool Management Process document is completed. kindly review
[Process Document - Tool Management.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4437759/Process.Document.-.Tool.Management.xlsx)

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Tool Management Process Document is completed. Kindly review.
[Process Document - Tool Management.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4518442/Process.Document.-.Tool.Management.xlsx)

**Comment by srinivasanbaskaran** [comment]
Sir,

Kindly Review the Process Document with Basha & Do the needful 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Sunil has accepted and received mail.
