### ISSUE TITLE
P&S : Process Document - Purchase & Subcontract

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#195]
Dear Team, 

Please Create & Attach the Process Document for Purchase & Subcontract

Document: 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

 Kindly Review the process Document for Purchase Module.

Purchase Doc : 
[Process Document for Purchase Module.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4219780/Process.Document.for.Purchase.Module.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the attached Process Document for Purchase & Subcontract

DOC: [Process Document for Purchase Module.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4243235/Process.Document.for.Purchase.Module.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Freeze the template with Sunil and do the rework accordingly if needed and assign to me.

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Please find the attached Process Document for Purchase & Subcontract.

Document : [Process.Document.for.Purchase.Module_1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4768237/Process.Document.for.Purchase.Module_1.1.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Document send to customer
