### ISSUE TITLE
I&P : Process Document - Inventory & PICC 

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#196]
Dear Team,

Please create & attach the Process Document for Inventory & PICC

Document:

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

Process document has been Completed. Please find the Attached Document.

Process Document : [Process Document for Inventory & PICC Module.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4394063/Process.Document.for.Inventory.PICC.Module.xlsx)

Regards,
Manivel A

**Comment by Manimahat** [comment]
Hi Srinivasan,

Kindly Review the Updated Process Document For Inventory & PICC.

Updated Process Document : [Process.Document.for.Inventory & PICC 1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4439498/Process.Document.for.Inventory.PICC.1.1.xlsx)

Regards,
Manivel A

**Comment by Manimahat** [comment]
Hi Srinivasan,

Kindly Review the Updated Process Document For Inventory & PICC.

Updated Document : [Process.Document.for.Inventory.PICC.1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4735707/Process.Document.for.Inventory.PICC.1.2.xlsx)

Regards,
Manivel A

**Comment by Manimahat** [comment]
Hi Srinivasan,

Kindly Review the Updated Process Document For Inventory & PICC.

Updated Document : [Process.Document.for.Inventory.PICC.1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4756073/Process.Document.for.Inventory.PICC.1.3.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Document send to customer

**Comment by Manimahat** [comment]
@raju Sir,

Some Points are missing in the Process Document That's why We are Re-open this Ticket

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup ,

We have Provided Mail to jyoti about user Some required Points in the Inventory.  There is no transaction process. So we can close this ticket.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Process Document submitted
