### ISSUE TITLE
S&S : Process Document - Sales & Shipping

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#197]
Dear Team,

Please create & attach the Process Document for Sales & Shipping

Document:

Regards,
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
Dear Srini
Process document Completed.
Kindly check and close 
Document : [Process.Document Sales & Shipping.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4234938/Process.Document.Sales.Shipping.xlsx)

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Sir,

Need to Review this Process Document. Then We will show this to Sunil 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Praba,
Correction done.  Show it to Sunil and if OK then circulate it.

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Show it to Sunil and if OK then circulate it.

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the updated Process Document

DOC: [Process.Document.Sales.Shipping_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4783975/Process.Document.Sales.Shipping_v1.3.xlsx)

Mail sent to Jyoti for submission.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Process data send to jyoti and attached. so closing this ticket
