### ISSUE TITLE
QLT : Process Document - Quality Management

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#198]
Dear Team,

Please create & attach the Process Document for Quality Management

Document:

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir, 

Process Document created for Quality Management. 

DOC: [Process Document - Quality Management.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4398371/Process.Document.-.Quality.Management.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@srinivasanbaskaran : please submit this to jyoti

**Comment by srinivasanbaskaran** [comment]
Team,

Process Document updated as per the User Requirements

DOC: 
[Process Document - Quality Management.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4448446/Process.Document.-.Quality.Management.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Please find the below attached Process Document for Quality Mgnt.

Doc: [Quality Mgnt_Process Document_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4739315/Quality.Mgnt_Process.Document_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Document send to customer
