### ISSUE TITLE
EAM : Process Document - Enterprise Asset Management

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#199]
Dear Team,

Please create & attach the Process Document for Enterprise Asset Management

Document:

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 
Process Document for EAM is completed. kindly review
[EAM Process Document.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4393751/EAM.Process.Document.xlsx)

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly update the Process Document as per the User requirement

**Comment by basha123456** [comment]
@srinivasanbaskaran 

EAM Process document completed. kindlyreview
[Process Document - EAM.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4443536/Process.Document.-.EAM.xlsx)

**Comment by basha123456** [comment]
@srinivasanbaskaran 

[Process Document - EAM.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4528710/Process.Document.-.EAM.xlsx)

**Comment by raju-kurup** [comment]
Sunil accepted this Process document, so closing this ticket.

![image](https://user-images.githubusercontent.com/38855314/80564984-fac9ef00-8a0c-11ea-8cfc-64c3d71b8fbc.png)
