### ISSUE TITLE
IMP-Solution Definition Document ( SDD) sign-off SCM & Finance

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#20]
IMP-Solution Definition Document ( SDD) sign-off SCM & Finance

**Comment by maheshwaran-m** [comment]
Dear Sir,

Please find the attached SDD sign off document scan copy for your reference,

SDD Sign Off Scan Copy : [DOCUMENT SIGN OFF.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3609796/DOCUMENT.SIGN.OFF.pdf)


Regards,
M.Maheshwaran
