### ISSUE TITLE
PPD : Process Document - Process Production

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#200]
Dear Team,

Please create & attach the Process Document for Process Production

Document:

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
Dear Sir,

please find the process document ..kindly review n move to next level

[Workflow Production.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4229427/Workflow.Production.xlsx)
[Workflow Production1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4229429/Workflow.Production1.xlsx)

regards,
sujin.M

**Comment by raju-kurup** [comment]
Freeze the template with Sunil and do the rework accordingly if needed and assign to me.

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please Review this Process Document with Sujin & Proceed further.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@sujin1708 : Please submit this to customer

**Comment by raju-kurup** [comment]
@sujin1708 : Please submit this to customer

**Comment by srinivasanbaskaran** [comment]
Srini need to check & close

**Comment by sujin1708** [comment]
@basha123456  kindly prepare the documentation for masters..as per the sunil format

**Comment by sujin1708** [comment]
[Process Production _Process Document.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4537481/Process.Production._Process.Document.xlsx)

**Comment by basha123456** [comment]
@sujin1708 

Process Document done for Masters.
[Process.Production._Process.Document.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4546464/Process.Production._Process.Document.xlsx)

**Comment by sujin1708** [comment]
@basha include this in the process document..
1. TIME   TABLE - SHIFT 
2. MAINTAIN   CALANDER
3.. Process   Element - Physical Element Association
4. Master  receipe -Explain  more about qc link &  validation
5. LINE   REJECTION REASON -type of rejection and where it ll impact
6. process model - include more about the impact of process model

**Comment by basha123456** [comment]
@sujin1708 

Process document for masters is completed...all above points are included..
[Process.Production._Process.Document - Masters.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4552924/Process.Production._Process.Document.-.Masters.xlsx)

**Comment by sujin1708** [comment]
it's look fine once transaction process document completed ..we will move to next phase

**Comment by sujin1708** [comment]
@basha123456 Include this also in master
Maintain User Defined Category Values
Select Usage for Template
Associate Lot Templates
Maintain Net Relalizable Value
Maintain Formula Access Rights

**Comment by basha123456** [comment]
@sujin1708 

Process Document for Masters is completed..
[Process.Production._Process.Document - Masters.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4568520/Process.Production._Process.Document.-.Masters.xlsx)

**Comment by raju-kurup** [comment]
Document send to customer.
