### ISSUE TITLE
P&S: BLANKET ORDER TO BE INTEGRATED WITH PURCHASE ORDER PRINT

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#201]
Dear Team,

SUBCON & BLANKET ORDER TO BE INTEGRATED WITH PURCHASE ORDER PRINT

**NOTE:**
1. In SDD itself, Blanket & Subcontract related details are not informed to Us ( Amity Team ).
2. In Scenario showcasing also not done for the same

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Please inform to Developers to add the UDS button in View Blanket PO screen for the Testing purposes.

Then only, we have to test this report.

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan.

Blanket PO PFS has Completed. Kindly review it.

PFS : [JCIPL_BPO_Print_PFS_1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414698/JCIPL_BPO_Print_PFS_1.0.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sir,

Kindly review the above PFS of Blanket Purchase Order Print. 

Kindly proceed further to Development

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@Manimahat : please close the issue related to Tax Calculation summary and transfer to me

**Comment by Manimahat** [comment]
@raju-kurup Sir

JCIE-244 - Rtrack Raised For View Tax Calculation Summary issue in Blanket PO.

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Need to check CIM

**Comment by srinivasanbaskaran** [comment]
Manivel,

Please prepare the Test Data 

REgards,
Srinivasan

**Comment by Manimahat** [comment]
Hi Srinivasan,

Test Data Process Completed.

Test data : [Test Data for Blanket Purchase Order.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4446569/Test.Data.for.Blanket.Purchase.Order.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop this report and contact manivel for clarification

**Comment by karthikeyanamitysoft** [comment]
Dear Mohana,

Kindly start new development with EDK screen and dw report.

Regards,
Karthi

**Comment by karthikeyanamitysoft** [comment]
Dear JP,

Kindly start new EDK screen desing.
REgards,
Karthi

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 
kindly give the correct screen navigation.

**Comment by srinivasanbaskaran** [comment]
@raju-kurup Sir,

Kindly allocate this ticket to jayapriya.

@Jeyapriyat 
Kindly make the uds screnn & report as below PFS Format.

Updated PFS : [JCIPL_BPO_Print_PFS_1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4507502/JCIPL_BPO_Print_PFS_1.2.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft :  please develop this report, PFS and test data is attached.  Jeyapriya transfered for some doubt.

**Comment by karthikeyanamitysoft** [comment]
Dear Jeya Priya,

Kindly complete the remaining work.
REgards,
Karthi

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 
kindly provide the test data.

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 
report completed,kindly check and revert.
i have attached report deliverables and report output.
[blanket purchase order report jcie-271.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4637868/blanket.purchase.order.report.jcie-271.zip)
[blanket purchase order report output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4637869/blanket.purchase.order.report.output.pdf)

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start the Testing 1 & Prepare the Testing Documents 

Regards,
Srinivasan.B

**Comment by srinivasanbaskaran** [comment]
Team,

PFA of Latest Open Points 

![IMG_20200514_152023_20200514_152038555](https://user-images.githubusercontent.com/46194039/82203701-43483e80-9921-11ea-9c62-68bf9a92f130.jpg)

**Comment by Manimahat** [comment]
@raju Sir,

Kindly review the Updated PFS & Allocated to Developers.

Updated PFS : [JCIPL_BPO_Print_PFS_1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4671225/JCIPL_BPO_Print_PFS_1.3.xlsx)

Correction Points : [Blanket Purchase order - 1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4671227/Blanket.Purchase.order.-.1.pdf)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per the PFS highlighted in yellow and test data is attached and the developer should test the same no and attach the result, they should not attach the different No.

**Comment by karthikeyanamitysoft** [comment]
Dear Jeyapriya,

1.Check the allignment properly.
2.Pan no fetching wrongly.

regards,
Karthi

**Comment by Jeyapriyat** [comment]
@Manimahat 

 changes completed,kindly check and revert.
i have attached latest deliverables.
[blanket purchase order deliverables 28-5-2020 jcie-271.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4693613/blanket.purchase.order.deliverables.28-5-2020.jcie-271.zip)
i have attached report output.
[blanket purchase order output 28-5-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4693616/blanket.purchase.order.output.28-5-2020.pdf)

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 1 Completed. Kindly start the Testing 2 Process.

Test Case : [Blanket purchase order Test Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4711352/Blanket.purchase.order.Test.Case.xlsx)

Test Result : [Blanket purchase order result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4711357/Blanket.purchase.order.result.pdf)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Kindly Review the Updated PFS & Allocated To Developers.

Updated PFS : [JCIPL_BPO_Print_PFS_1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4744968/JCIPL_BPO_Print_PFS_1.4.xlsx)

Test Case : [Test.Data.for.Blanket.Purchase.Order.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4744971/Test.Data.for.Blanket.Purchase.Order.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Hold Due to Advance concept clarification from Jyoti.

**Comment by srinivasanbaskaran** [comment]
Update the PFS... Jyoti given the Confirmation, But some clarification needed

**Comment by Manimahat** [comment]
@raju-kurup sir,

Kindly Review the Updated PFS & Allocated To Developers.

Updated PFS : [JCIPL_BPO_Print_PFS_1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4790197/JCIPL_BPO_Print_PFS_1.4.xlsx)

Test Case : [Test.Data.for.Blanket.Purchase.Order.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4790198/Test.Data.for.Blanket.Purchase.Order.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do 3 correction in this report which is mentioned in PFS.  Please check the report with the test data given and if correct only transfer the ticket to functional consultant or any doubt contact and clear the doubts.

**Comment by Jeyapriyat** [comment]
@Manimahat 

changes completed,kindly check and revert.
i have attached latest deliverables and sample output.
[blanket purchase order report deliverables jcie-271 v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4808226/blanket.purchase.order.report.deliverables.jcie-271.v1.1.zip)
[blanket purchase order sample output 20-6-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4808229/blanket.purchase.order.sample.output.20-6-2020.pdf)

**Comment by Manimahat** [comment]
@srinivasan,

Testing 1 completed, Kindly Start the Testing 2 Process.

Test Case : [Blanket.purchase.order.Test.Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4814188/Blanket.purchase.order.Test.Case.xlsx)

Test Result : [Blanket PO _Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4814189/Blanket.PO._Result.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@raju-kurup 

While Click UDS button for Blanket Po we face above error


![image](https://user-images.githubusercontent.com/47313592/85496382-d009aa80-b5f9-11ea-9af3-8a6e2491d0fb.png)

**Comment by raju-kurup** [comment]
@sujin1708 : please try this UDS in "Default Window", it will work

**Comment by sujin1708** [comment]
@srinivasan testing2 completed

[Blanket PO1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4839842/Blanket.PO1.pdf)

Regards,
sujin.M

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Blanket Purchase Order Print Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [JCIPL_BPO_Print - PFS_1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886301/JCIPL_BPO_Print.-.PFS_1.4.xlsx)

DELIVERABLES: [blanket.purchase.order.report.deliverables.jcie-271.v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4886306/blanket.purchase.order.report.deliverables.jcie-271.v1.1.zip)

TESTCASE1: [Blanket.purchase.order.Test.Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4814188/Blanket.purchase.order.Test.Case.xlsx)

TEST RESULT1: [Blanket PO _Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4814189/Blanket.PO._Result.pdf)

TESTCASE2 : [Testcase2_Blanket Purchase Order.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886278/Testcase2_Blanket.Purchase.Order.xlsx)

TEST RESULT2 : [Blanket PO1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4839842/Blanket.PO1.pdf)

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju Sir,

As per user Requirement, Name & Designation Point will add in the MFG OU. I have updated the PFS As per the Requirement.

We need to Add the Employee Name Field in the UDS Screen, After That we will Add the Name & Designation in the Report.

Updated PFS : [JCIPL_BPO_Print.-.PFS_1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4916359/JCIPL_BPO_Print.-.PFS_1.5.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do correction on name and designation in UDS and report

**Comment by Jeyapriyat** [comment]
@Manimahat 
edk design completed.
ticket id : JCIE-306

**Comment by Jeyapriyat** [comment]
@Manimahat 
changes completed,kindly check and revert.
i have attached latest deliverables and sample output.
[blanket purchase order deli jcie-306-new v.1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4993217/blanket.purchase.order.deli.jcie-306-new.v.1.2.zip)
[blanket purchase order sample output 29-7-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4993218/blanket.purchase.order.sample.output.29-7-2020.pdf)
![image](https://user-images.githubusercontent.com/37791285/88768543-df4fbb00-d198-11ea-8f95-d98d5a98ce04.png)

**Comment by Jeyapriyat** [comment]
@Manimahat 
changes completed,kindly check and revert.
i have attached latest deliverables and sample output.
[blanket purchase order deli jcie-306-newv.1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4993505/blanket.purchase.order.deli.jcie-306-newv.1.2.zip)
[blanket purchase order sample output 29-7-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4993509/blanket.purchase.order.sample.output.29-7-2020.pdf)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 completed. Kindly Proceed Testing 2 Process.

Test Case : [Blanket.purchase.order.Test.Case (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4996293/Blanket.purchase.order.Test.Case.1.xlsx)

Test Result : [Blanket Purchase Order _Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4996297/Blanket.Purchase.Order._Result.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Team,

Blanket PO Print Testing 2 Completed. 

TESTCASE2: [Blanket_Purchase_Order_Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5053326/Blanket_Purchase_Order_Testcase2.xlsx)

TEST RESULT2: [Blanket PO_TR2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5053328/Blanket.PO_TR2.pdf)

Regards,
Srinivasan

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Blanket Purchase Order Print Testing has been Completed. Herewith I have attached the Testing Documents for the future references. 

PFS: [JCIPL_BPO_Print.-.PFS_1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5053343/JCIPL_BPO_Print.-.PFS_1.5.xlsx)

DELIVERABLES: [blanket.purchase.order.deli.jcie-306-newv.1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5053345/blanket.purchase.order.deli.jcie-306-newv.1.2.zip)

TESTCASE1:[Blanket.purchase.order.Test.Case.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5053348/Blanket.purchase.order.Test.Case.1.xlsx)

TEST RESULT1: [Blanket.Purchase.Order._Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5053350/Blanket.Purchase.Order._Result.pdf)

TESTCASE2: [Blanket_Purchase_Order_Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5053326/Blanket_Purchase_Order_Testcase2.xlsx)

TEST RESULT2: [Blanket PO_TR2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5053328/Blanket.PO_TR2.pdf)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer gave confirmation to close this ticket. So, Kindly proceed further

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer Approved, so closing this ticket

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Need to Change the Format Like Purchase Order. So we re-open this ticket.

![Uploading image.png…]()

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

User Need the Blanket PO same as Normal PO Format ( Header & Footer , Tax Summary Should be Fixed for all Pages. Please allocated this Ticket to developers. 

Regards,
Manivel A

**Comment by raju-kurup** [comment]
This report was done by Jeyapriya but PO was done by Nandhinee. So if we can give it to Nandhinee it will be goof

**Comment by Nandhineedevi** [comment]
[Print_bla_pur_or_rpt_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5209288/Print_bla_pur_or_rpt_v2.1.zip)
[mfg blanket.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5209290/mfg.blanket.pdf)
[unitech blanket.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5209291/unitech.blanket.pdf)

**Comment by Manimahat** [comment]
@AkashGleen ,

Kindly start Testing 1 process & prepare the Documents as per our Requirement.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@Nandhineedevi ,

I have faced a issue in Taxable value summary page. The Tax name is changes between IGST & SGST. Please re-write the in correct column.

![image](https://user-images.githubusercontent.com/55881685/93113869-6fa97700-f6d7-11ea-887f-fab824b55cda.png)


Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
Completed.

[bpo1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5222737/bpo1.pdf)
[blppbpo_print__grd1_gr_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5222735/blppbpo_print__grd1_gr_v2.2.zip)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 Completed. Kindly start testing 2 process.

Test case : [Blanket.purchase.order.Test.Case.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5224271/Blanket.purchase.order.Test.Case.1.xlsx)

Test Result : [Blanket purchase order.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5224272/Blanket.purchase.order.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
@eafaisal,

Kindly start the Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srinivasanbaskaran 

Blanket Order To Be Integrated With Purchase Order Print Testing 2 Completed Kindly Check & Update.

[Blanket.purchase.order.Test.Case.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5249028/Blanket.purchase.order.Test.Case.2.xlsx)

[Test Result For Blanket Purchase Order.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5249029/Test.Result.For.Blanket.Purchase.Order.pdf)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Blanket Purchase Order Print Report Testing has been completed. Herewith I have attached the Testing Documents fir hte future references. 

PFS: [JCIPL_BPO_Print.-.PFS_1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5254302/JCIPL_BPO_Print.-.PFS_1.5.xlsx)

DELIVERABLES: [blppbpo_print__grd1_gr_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5254304/blppbpo_print__grd1_gr_v2.2.zip)

TESTCASE1: [Blanket.purchase.order.Test.Case.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5224271/Blanket.purchase.order.Test.Case.1.xlsx)

TEST RESULT1: [Blanket purchase order.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5224272/Blanket.purchase.order.pdf)

TESTCASE2: [Blanket.purchase.order.Test.Case.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5249028/Blanket.purchase.order.Test.Case.2.xlsx)

TEST RESULT2: [Test Result For Blanket Purchase Order.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5249029/Test.Result.For.Blanket.Purchase.Order.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Being customer given clearance, we are closing this ticket

**Comment by sujin1708** [comment]
to be deploy in live server

**Comment by Jeyapriyat** [comment]
@Manimahat 
deployment completed in live server,kindly check and revert.
i have attached latest deliverables and sample output .
[blanket purchase order deli jcie-306-new -1 v.1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6008341/blanket.purchase.order.deli.jcie-306-new.-1.v.1.3.zip)
[sample output 19-2-2021.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6008343/sample.output.19-2-2021.pdf)

**Comment by Manimahat** [comment]
@raju-kurup sir,

Report has been Deployed successfully. Kindly close this ticket.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
