### ISSUE TITLE
QLT : Stage based QC Details 

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#203]
Dear Team,

Stage Based QC Details are to be come while stage base Reporting

JCIE-224

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Lakshmi M added a comment - 05/Mar/20 11:00 AM
"Try updating inspection results for the specific attributes at each stage"

This ticket is in "Clarification provided", if the solution is satisfied please close the ticket or reopen it

**Comment by srinivasanbaskaran** [comment]
Team,

Open Point document prepared & Sent to Mr. Sunil 

DOC: 
[01_Resolution Doc for Quality Mgnt - OpenPoint - Stage Based QC Details.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4430709/01_Resolution.Doc.for.Quality.Mgnt.-.OpenPoint.-.Stage.Based.QC.Details.docx)
Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, so closing this tickets.
