### ISSUE TITLE
QLT : Held Qty in Final Clearance Feedback Details in QC

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#204]
Dear Team, 

User wants that Held Qty in Final Clearance Feedback Details in QC

JCIE-223

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Ramco Team gave solution for this issue.

Need to Test & Provide the Solution to the User

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Open Point document prepared & Sent to Mr. Sunil

DOC: 
[01_Resolution Doc for Quality Mgnt - OpenPoint - Held Quantity.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4430708/01_Resolution.Doc.for.Quality.Mgnt.-.OpenPoint.-.Held.Quantity.docx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@srinivasanbaskaran : Attach the confirmation copy and then proceed for closing

**Comment by raju-kurup** [comment]
@sujin1708: please attach the proof document for this issue

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, so closing this tickets.
