### ISSUE TITLE
QLT : Spray Dried Granules Report

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#212]
Dear Team,

User wants Spray Dried Granules Report

PFS will update later

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the attached PFS for Spray Dried Granules Batch Test Report 

PFS: [01_Spray Dreid Granules Batch Test Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4348398/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@Nandhineedevi : please develop the report and contact Srinivasan for clarification

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The report design and coding has been completed. Kindly check and revert back.

[sdgr_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4354019/sdgr_v1.1.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Raju Sir.

Below points are to be Corrected.
1. Pressure related information is not fetching
2. Fired by Calculation - wrong value calculated
3. Green Mercury related information is not fetching 

Test Result: [Spray Dried Granules Report - 1st.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4356227/Spray.Dried.Granules.Report.-.1st.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Please find the updated PFS.

PFS: [01_Spray Dreid Granules Batch Test Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4362522/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

While taking report, I got this error "Conversion failed when converting the nvarchar value '15.00000000' to data type int". 

Kindly check & Revert ASAP.

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The error has been resolved. Kindly check and revert back.

[sdgr-v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4380363/sdgr-v1.2.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

Spary Dried Granules Report Testing 1 competed. 

PFS: [01_Spray Dreid Granules Batch Test Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4387791/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.1.xlsx)

PATH: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details

DELIVERABLES: [sdgr-v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4387797/sdgr-v1.2.zip)

TESTCASE1: [Uploading TestCase1_Spray Dried Granules Report.xlsx…]()

TEST RESULT1: [07_Spary Dried Granules Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4387806/07_Spary.Dried.Granules.Report.pdf)

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing 2 & Prepare the Testing Document

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2 completed. PFA of test documents.

Test Case: [TestCase2_Spray Dried Granules Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4391784/TestCase2_Spray.Dried.Granules.Report.xlsx)
Test Result: [Test Result - spray dried granules report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4391785/Test.Result.-.spray.dried.granules.report.pdf)

**Comment by srinivasanbaskaran** [comment]
Team,

Spary Dried Granules Report Testing 1 competed. 

PFS: [01_Spray Dreid Granules Batch Test Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4387791/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.1.xlsx)

PATH: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details

DELIVERABLES: [sdgr-v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4387797/sdgr-v1.2.zip)

TESTCASE1: [Uploading TestCase1_Spray Dried Granules Report.xlsx…]()

TEST RESULT1: [07_Spary Dried Granules Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4387806/07_Spary.Dried.Granules.Report.pdf)

TESTCASE2: [TestCase2_Spray.Dried.Granules.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4396626/TestCase2_Spray.Dried.Granules.Report.xlsx)

TEST RESULT2: [Test.Result.-.spray.dried.granules.report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4396627/Test.Result.-.spray.dried.granules.report.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

As per the User Requirements PFS has been updated. 

PFS: [01_Spray Dreid Granules Batch Test Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4452205/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.2.xlsx)

REgards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As discussed with Srini please do the correction and also please allocate to Nandhinee

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing1 & Prepare the Testing Document

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing1 completed..PFA

[TR spray dried granules report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4469653/TR.spray.dried.granules.report.pdf)
[spray drier granules report test data 1304.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4469654/spray.drier.granules.report.test.data.1304.xlsx)
[TestCase1_Spray.Dried.Granules.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4469655/TestCase1_Spray.Dried.Granules.Report.xlsx)

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 2 Completed. PFA.

Testcase2: [TestCase2_Spray Dried Granules Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4498003/TestCase2_Spray.Dried.Granules.Report.xlsx)

Test Result2: [Test Result2_Spray Dried Granules Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4498004/Test.Result2_Spray.Dried.Granules.Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly update the Latest Deliverables ASAP

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The deliverables has been attached.

[sdgr_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4501273/sdgr_v1.3.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Spray Dreid Granules Report testing has been completed. Herewith I have attached the Testing Document for future references.

PFS: [01_Spray Dreid Granules Batch Test Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4509591/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.2.xlsx)

DELIVERABLES: [sdgr_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4509598/sdgr_v1.3.zip)

TESTCASE1: [TestCase1_Spray.Dried.Granules.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4509600/TestCase1_Spray.Dried.Granules.Report.xlsx)

TEST DATA: [spray.drier.granules.report.test.data.1304.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4509604/spray.drier.granules.report.test.data.1304.xlsx)

TEST RESULT1: [TR.spray.dried.granules.report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4509608/TR.spray.dried.granules.report.pdf)

TESTCASE2: [TestCase2_Spray Dried Granules Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4509611/TestCase2_Spray.Dried.Granules.Report.xlsx)

TEST RESULT2: [Test.Result2_Spray.Dried.Granules.Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4509620/Test.Result2_Spray.Dried.Granules.Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Green Date, Fired Date to be taken into Print 

So, PFS Inprogress

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

PFA of Latest Points 

![Spray Dried Granules](https://user-images.githubusercontent.com/46194039/82190196-4b4ab300-990e-11ea-8f66-dd569fa4283c.jpg)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS for Spray Dried Granules Report

PFS: [01_Spray Dreid Granules Batch Test Report_PFS_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4662264/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.3.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction of 2 points in UDS and 2 points in report.

**Comment by mohanaamity** [comment]
@srinivasanbaskaran 

Completed,Kindly find the test data 
[spray dried report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4705899/spray.dried.report.pdf)

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 1 Completed. PFA of Testing Documents 

Testcase1: [TestCase1_Spray_Dried_Granules_Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4715282/TestCase1_Spray_Dried_Granules_Report_v1.1.xlsx)

Test Result1: [Spray Dried Granules Report_ Test Result1_v1.1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4715287/Spray.Dried.Granules.Report_.Test.Result1_v1.1.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly Start the Testing 2 & Prepare the Testing Documents

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@karthick,

I got wrong Green & fired date during the testing. This value fetched from UDS Screen. I have provided Green & Fired Date in the UDS Screen.  But it is fetching Wrong Dates for Both Field.

Error File : [Error Screen Shot for Spray dried Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4727613/Error.Screen.Shot.for.Spray.dried.Report.xlsx)

Regards,
ManiVel A

**Comment by mohanaamity** [comment]
@Manimahat 

Issue resolved

Regards,
Mohana

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 2 Completed. Please Find the Attachment For Your Ref...

Test Case : [TestCase_2 Spray_Dried_Granules_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4729157/TestCase_2.Spray_Dried_Granules_Report.xlsx)

Test Result : [sprey dreied report - output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4729160/sprey.dreied.report.-.output.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Mohana,

Kindly update the Latest Deliverables ASAP

**Comment by mohanaamity** [comment]
@srinivasanbaskaran 

Here with, i have attached deliverables for Spray Dried Granules Report #212

[spray dried granules sp.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4733938/spray.dried.granules.sp.zip)

Regards,
Mohana B

**Comment by srinivasanbaskaran** [comment]
Sir,

Spray Dried Granules Report Testing has been completed. Herewith I have attached the some of the Testing Documents for future references. 

PFS: [01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4735875/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.3.xlsx)

DELIVERABLES: [spray.dried.granules.sp.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4735880/spray.dried.granules.sp.zip)

TESTCASE1: [TestCase1_Spray_Dried_Granules_Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4735883/TestCase1_Spray_Dried_Granules_Report_v1.1.xlsx)

TEST RESULT1: [Spray.Dried.Granules.Report_.Test.Result1_v1.1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4735885/Spray.Dried.Granules.Report_.Test.Result1_v1.1.pdf)

TESTCASE2: [TestCase_2.Spray_Dried_Granules_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4735886/TestCase_2.Spray_Dried_Granules_Report.xlsx)

TEST RESULT2: [sprey.dreied.report.-.output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4735888/sprey.dreied.report.-.output.pdf)

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@raju-kurup please find the updated PFS kindly move to next level
PFS : [01_Spray Dreid Granules Batch Test Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5006922/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.4.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction mentioned in PFS

**Comment by srinivasanbaskaran** [comment]
Faizal,

Kindly start the Testing 1 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 1 is completed.
Kindly do the testing 2.

Test Case : [TestCase.Spray_Dried_Granules_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5040988/TestCase.Spray_Dried_Granules_Report.xlsx)

Test Result : [Spray.Dried.Granules.Report_.Test.Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5040990/Spray.Dried.Granules.Report_.Test.Result.pdf)

Regards,
Faisal

**Comment by mohanaamity** [comment]
Hi Sujin

Report correction completed.I have attached the Deliverables and test data for your reference.
[spray_granules _testdata.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5044774/spray_granules._testdata.pdf)
[spray dried granules final sp.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5044775/spray.dried.granules.final.sp.zip)

**Comment by srinivasanbaskaran** [comment]
Team,

Spary Dried Granules Report Testing 2 Completed. 

TESTCASE2: [Spray Dried Granules Report_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5052720/Spray.Dried.Granules.Report_TestCase2.xlsx)

TEST RESULT2: [SDGR_TR2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5052722/SDGR_TR2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Spray Dried Granule Report Testing has been completed. Herewith I have attached the Testing Documents for the Future references.

PFS: [01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5052737/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.4.xlsx)

DELIVERABLES: [spray.dried.granules.final.sp.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5052738/spray.dried.granules.final.sp.zip)

TESTCASAE1: [TestCase.Spray_Dried_Granules_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5052746/TestCase.Spray_Dried_Granules_Report.xlsx)

TEST RESULT1: [Spray.Dried.Granules.Report_.Test.Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5052749/Spray.Dried.Granules.Report_.Test.Result.pdf)

TESTCASE2: [Spray Dried Granules Report_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5052720/Spray.Dried.Granules.Report_TestCase2.xlsx)

TEST RESULT2: [SDGR_TR2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5052722/SDGR_TR2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer gave confirmation to close this ticket. So, Kindly proceed further

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Mohana,

Please do the mentioned changes in this report.

**Report with Remarks column means Allignment changed** 

![image](https://user-images.githubusercontent.com/46194039/91630972-853e5180-e9f3-11ea-881c-be66a7200b3c.png)


Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee, 

Please do the above Correction.

Call me once you start 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Karthi,

Since, there is no PFS corrections in this. Already we are allocated this report to Mohana, since Mohana is on leave. Please transfer it to Nandhinee if possible.

**Comment by Nandhineedevi** [comment]
Completed.

[Sdgr_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5160522/Sdgr_v2.1.zip)
[granules report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5160523/granules.report.pdf)

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 1 Completed. Herewith I have attached the Testing Documents 

TESTCASE1: [TestCase1_Spray Dried Granules Report_New.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5162626/TestCase1_Spray.Dried.Granules.Report_New.xlsx)

TEST RESULT1: [TR1_Spray Dried Granules Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5162628/TR1_Spray.Dried.Granules.Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Faizal,

Kindly Start Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Kindly check.

Test Case : 
[TestCase2_Spray.Dried.Granules.Report_New.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5166355/TestCase2_Spray.Dried.Granules.Report_New.xlsx)

Test Result : 
[TR2_Spray.Dried.Granules.Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5166356/TR2_Spray.Dried.Granules.Report.pdf)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Spray Dreid Granules Report Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [01_Spray Dreid Granules Batch Test Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5181225/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.4.xlsx)

DELIVERABLES: [Sdgr_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5181227/Sdgr_v2.1.zip)

TESTCASE1: [TestCase1_Spray Dried Granules Report_New.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5162626/TestCase1_Spray.Dried.Granules.Report_New.xlsx)

TEST RESULT1: [TR1_Spray Dried Granules Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5162628/TR1_Spray.Dried.Granules.Report.pdf)

TESTCASE2 : [TestCase2_Spray.Dried.Granules.Report_New.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5166355/TestCase2_Spray.Dried.Granules.Report_New.xlsx)

TEST RESULT2 :[TR2_Spray.Dried.Granules.Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5166356/TR2_Spray.Dried.Granules.Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@karthikeyanamitysoft please find the below mentioned screenshot 

while enter the remarks its going in to the next page please check 

![image](https://user-images.githubusercontent.com/47313592/92988724-bd618c00-f4eb-11ea-8d83-67d599d7341a.png)

**Comment by Nandhineedevi** [comment]
Hi Sujin,
As discussed, i have modified the design level changes. Please find the attached document for your reference.

[spray1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5217106/spray1.pdf)
[spray2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5217105/spray2.pdf)

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 1 Completed.

**Comment by srinivasanbaskaran** [comment]
Faizal,

Kindly start Testing2 & PRepare tne Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Kindly check.

Test Case : 
[TestCase2_Spray.Dried.Granules.Report_New.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5249231/TestCase2_Spray.Dried.Granules.Report_New.xlsx)

Test Result : 
[TestCase2_Spray.Dried.Granules.Report_New.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5249232/TestCase2_Spray.Dried.Granules.Report_New.pdf)

Regards,
Faisal

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Kindly check.

Test Case : 
[TestCase2_Spray.Dried.Granules.Report_New.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5249239/TestCase2_Spray.Dried.Granules.Report_New.xlsx)

Test Result : 
[TestResult2_Spray.Dried.Granules.Report_New.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5249240/TestResult2_Spray.Dried.Granules.Report_New.pdf)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Spray Dried Granules Report Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [01_Spray Dreid Granules Batch Test Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5253834/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.4.xlsx)

DELIVERABLES: 

TESTCASE1: [Spray Dried Granules Report_TestCase1_Updated.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5253836/Spray.Dried.Granules.Report_TestCase1_Updated.xlsx)

TEST RESULT1: [SPDRG-NEW.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5253839/SPDRG-NEW.pdf)

TESTCASE2 : [TestCase2_Spray.Dried.Granules.Report_New.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5249239/TestCase2_Spray.Dried.Granules.Report_New.xlsx)

TEST RESULT2: [TestResult2_Spray.Dried.Granules.Report_New.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5249240/TestResult2_Spray.Dried.Granules.Report_New.pdf)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by karthikeyanamitysoft** [comment]
DEar  Mohana,

Kindly move the deliverables into live server.

Regards,
Karthi

**Comment by mohanaamity** [comment]
@srinivasanbaskaran ,

Live server deployment completed. I have attached the deliverables for your ref.
[Sdgr.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5981390/Sdgr.zip)

Regards,
Mohana B

**Comment by raju-kurup** [comment]
Development Completed, so closing this ticket

**Comment by sujin1708** [comment]
@karthikeyanamitysoft 
1. Material not fetching
2. Fired density value not came
![image](https://user-images.githubusercontent.com/47313592/125298916-3c129a00-e346-11eb-98a1-3c9bac22458a.png)

**Comment by raju-kurup** [comment]
Due to the correction in Material name this ticket is reopened

**Comment by Manimahat** [comment]
While Generating the Report it is coming Blank. 

![image](https://user-images.githubusercontent.com/55881685/126321858-d905ec7c-5a8c-49e5-a505-4ea7148c2ce4.png)

**Comment by mohanaamity** [comment]
@Manimahat 
Report values are fetching. Kindly check and confirm.
[test data.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6853300/test.data.pdf)

Regards,
Mohana B

**Comment by Manimahat** [comment]
@mohanaamity,

All above points are not resolved, Please help on this.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup sir,

For material Name logic has been changes & updated in the Ticket itself. Please find it

Updated PFS : [01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6854865/01_Spray.Dreid.Granules.Batch.Test.Report_PFS_v1.5.xlsx)

1. Material name not fetching 
2. Fired density value not came

![image](https://user-images.githubusercontent.com/47313592/125298916-3c129a00-e346-11eb-98a1-3c9bac22458a.png)

first Record in the Weight Column fired value is 9.36 but in the report it is showing NA. please check & resolve... please find the Below screen shot for your ref..

![image](https://user-images.githubusercontent.com/55881685/126322187-92144284-2208-4cda-be3b-bf9d30c26af6.png)

**Note: Kindly deploy same deliverable both UAT & Live server after the correction.**

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft: please correct the report as mentioned in PFS.
Material name not fetching: Changes updated in PFS
Green Weight value not came: NA Coming but 10.44 should come (Screenshot of value attached)
Fired Weight value not came: NA Coming but 9.36 should come (Screenshot of value attached)

**Comment by karthikeyanamitysoft** [comment]
Dear Mohana,

1 .Material name not fetching: Changes updated in PFS -- logic changed, its wont fetch for new logic now, coding need to change.
Green Weight value not came: NA Coming but 10.44 should come (Screenshot of value attached)
Fired Weight value not came: NA Coming but 9.36 should come (Screenshot of value attached)

Regards,
Karthi

**Comment by mohanaamity** [comment]
@Manimahat 

Changes have been done. I haveattached latest deliverables FYR.
[Sdgr.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6872081/Sdgr.zip)

Regards,
Mohana B

**Comment by Manimahat** [comment]
@raju-kurup sir,

As per our new Requirement Material Name Logic Changed & other Issue has been Resolved. New Deliverable deployed & Tested Successfully in Both UAT & Live Server. Test Result has been attached Below.  Please close this Ticket.

Live Server Result : [Spray dried Granules report - Live.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6872236/Spray.dried.Granules.report.-.Live.pdf)

UAT Server Result : [Spray dried Granules report - UAT.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6872238/Spray.dried.Granules.report.-.UAT.pdf)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Report Developed and deployed in both Live and Test, so Closing this ticket.
