### ISSUE TITLE
LSC-LIVE SERVER CONFIGURATION

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#213]
Dear Team,

Live Server  Configuration has to be start 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
completed till 01/04/2020

1. Components mapping to all OU's
2. Components mapping to RM Server
3. Components mapping to App Server

**Comment by basha123456** [comment]
Completed on 02/04/2020

![image](https://user-images.githubusercontent.com/47315921/78336765-8d61a480-75ad-11ea-81df-d82184b1bfc3.png)

**Comment by basha123456** [comment]
Components mapping for the OU for the errors and CIM is completed.

[CIM Script_Live_Updated.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4475827/CIM.Script_Live_Updated.xlsx)
[Error file.txt](https://github.com/astpl1998/Jyoti-Ceramic/files/4475829/Error.file.txt)

**Comment by basha123456** [comment]
The following tasks are completed on 15/04/2020

Create   Company
Assign Permitted Currencies
Maintain Address details
Create BU - within Company
Create LO - (Mapping of BU to LO)
Map BU - LO
Map BU - OU
Maintain OU properties

**Comment by basha123456** [comment]
@Dhanwandher 

Live Server Configuration Setup is Completed and Handover to you.

[EMOD Setup for Live.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4802662/EMOD.Setup.for.Live.xlsx)
[GTS module_GST setup_Material from Raju.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4802663/GTS.module_GST.setup_Material.from.Raju.xlsx)

**Comment by raju-kurup** [comment]
Live Server configuration is done. So closing this ticket.
