### ISSUE TITLE
MDC-Live Server Master Collection - Pur & Subcon  - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#214]
Dear Team,

Live Server Configuration - Inventory & PICC has to be start 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Supplier Data received from the User.

Supplier Domestic: [00_JCIPL_Supplier_Master_Domestic_1 to 849-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4442198/00_JCIPL_Supplier_Master_Domestic_1.to.849-C.xlsx)

Supplier Import: [01_JCIPL_Supplier_Master_Imports_1 to 46-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4442201/01_JCIPL_Supplier_Master_Imports_1.to.46-C.xlsx)

Supplier Group Domestic: 
[01_JCIPL_Domestic_Supplier Group_1 to 22-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4442199/01_JCIPL_Domestic_Supplier.Group_1.to.22-C.xlsx)

Supplier Group Import: [01_JCIPL_Imports_Supplier Group_1 to 10-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4442203/01_JCIPL_Imports_Supplier.Group_1.to.10-C.xlsx)
 
Payterm: [01_JCIPL_Create Payterm_1 to 39-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4442205/01_JCIPL_Create.Payterm_1.to.39-C.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
@Manimahat, 

Kindly confirm the data & Validate

**Comment by Manimahat** [comment]
@raju Sir,

MDC - Live Server Master Collection - purchase Completed. 

Please review it.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju Sir,

MDC - Live Server Master Collection - purchase Completed. 

Please review it.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Data Attached. So closing this ticket
