### ISSUE TITLE
MDC-Live Server Master Collection - Inv & PICC  - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#215]
Dear Team,

MDC-Live Server   Master Collection - Inv & PICC  -   JCIPL_MFG_OU
--

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Item Master: [PRODUCT CODES Update 18.04.20.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4578939/PRODUCT.CODES.Update.18.04.20.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Item Master FG : [JCIPL_FG_ItemCode_10062020.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4771924/JCIPL_FG_ItemCode_10062020.zip)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir, 

Inventory related Master Data received from the Customer. 

Kindly proceed on this ticekt for closure

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Master data collected and attached, so closing this ticket.
