### ISSUE TITLE
MDC-Live Server Master Collection - Process Prod  - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#216]
Dear Team,

Live Server Configuration - PP has to be start 

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
[Warehouse_Creation_MDCF.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4448309/Warehouse_Creation_MDCF.xlsx)
[CreateProcessElement_InsertData1_P.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4448317/CreateProcessElement_InsertData1_P.xlsx)
[CreateProcessElement_InsertData1_E.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4448318/CreateProcessElement_InsertData1_E.xlsx)

**Comment by raju-kurup** [comment]
Data Attached. So closing this ticket
