### ISSUE TITLE
MDC-Live Server Master Collection - Sales & Shipping -JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#217]
Dear Team,

MDC-Live Server   Master Collection - Sales & Shipping -JCIPL_MFG_OU
--

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly co-ordinate with Sujin & Do the needful

**Comment by srinivasanbaskaran** [comment]
Waiting for Item master from the Customer

So, this ticket HOLD

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Below are the data received from the Customer ...

MFG OU Customer Master: [01_JCIPL_Customer Master-ojas.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4578915/01_JCIPL_Customer.Master-ojas.xlsx)

GmbH OU Customer Master: [01_JCIPL_Customer Master_GmbH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4578916/01_JCIPL_Customer.Master_GmbH.xlsx)

Customer Group: 

SCM Employee Master:

Sales Person:

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Master data collected and attached, so closing this ticket.
