### ISSUE TITLE
MDC-Live Server Master Collection - Finance - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#218]
Dear Team,

Live Server Configuration - FInance has to be start 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Dear Team,

Below data received from Jyoti.

[Copy of Bank and Cash Details - FINAL.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4651181/Copy.of.Bank.and.Cash.Details.-.FINAL.xlsx)
[Copy of chart of accounts - FINAL.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4651182/Copy.of.chart.of.accounts.-.FINAL.xlsx)
[Copy of Tax Region - FINAL.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4651183/Copy.of.Tax.Region.-.FINAL.xlsx)

**Comment by basha123456** [comment]
Dear Sir,

Data received from joshi-finance.. this is the final data.
[Bank and Cash Details - FINAL.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757870/Bank.and.Cash.Details.-.FINAL.xlsx)
[chart of accounts - FINAL.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757871/chart.of.accounts.-.FINAL.xlsx)
[Tax Region - FINAL.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757872/Tax.Region.-.FINAL.xlsx)

**Comment by raju-kurup** [comment]
Details attached.  So closing this ticket.

**Comment by raju-kurup** [comment]
Details attached. So closing this ticket
