### ISSUE TITLE
MDC-Live Server Master Collection - Fixed Asset - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#219]
Dear Team,

MDC-Live Server   Master Collection - Fixed Asset - JCIPL_MFG_OU
--

Regards,
Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Dear Team.

Fixed Asset collected for MFG OU.

Regards.
S.Dhanwandher

[Asset Initial Entry - JYOTI.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4852427/Asset.Initial.Entry.-.JYOTI.xlsx)

**Comment by raju-kurup** [comment]
Master data for Fixed Asset Collected
