### ISSUE TITLE
MDC-Live Server Master Collection - EAM - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#220]
Dear Team,

MDC-Live Server   Master Collection - EAM - JCIPL_MFG_OU
--

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Dear Team,

Data received from jyoti is attached.
[EAM DATA.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4574345/EAM.DATA.zip)

**Comment by basha123456** [comment]
Dear Team,

EAM master data received from sonawane...it is final. 

[EAM MASTERS12MAY20.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4650375/EAM.MASTERS12MAY20.xlsx)

**Comment by basha123456** [comment]
Dear Sir,

Data received from Sonawane - EAM.. this is the final data.

[EAM MASTERS12MAY20.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757863/EAM.MASTERS12MAY20.xlsx)

**Comment by raju-kurup** [comment]
Details attached.  So closing this ticket.
