### ISSUE TITLE
MDC-Live Server Master Collection - TOOL - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#221]
Dear Team,

Inventory & PICC Live Server Master Upload has to be start 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
These are the list of masters collected from jyoti tool room.

[MASTER DATA - TOOL ROOM thorat.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4443068/MASTER.DATA.-.TOOL.ROOM.thorat.xlsx)
[MDCF_Item Master_RM_ jothi tool room.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4443069/MDCF_Item.Master_RM_.jothi.tool.room.xlsx)
[Tool Room - Codification - Data Collection - Sample - MFG(1)..gaurav.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4443070/Tool.Room.-.Codification.-.Data.Collection.-.Sample.-.MFG.1.gaurav.xlsx)

**Comment by basha123456** [comment]
Tool Data received from Jyoti
[Tool Data from sagar.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4464438/Tool.Data.from.sagar.xlsx)

**Comment by basha123456** [comment]
Tool Master data receivd from Gautam.
![image](https://user-images.githubusercontent.com/47315921/84766948-45b8b980-afef-11ea-8a38-af7eb07f2d1b.png)
![image](https://user-images.githubusercontent.com/47315921/84766944-45202300-afef-11ea-93ee-1e417797209e.png)

**Comment by raju-kurup** [comment]
Data Collected and attached for live server. so closing this ticket
