### ISSUE TITLE
MDC-Live Server Master Collection - Pur & Subcon  - JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#222]
Dear Team,

Purchase & Pubcontracting Live Server Master Upload has to be start 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Refer --- #214

**Comment by Manimahat** [comment]
@raju Sir,

MDC - Live Server Master Collection - purchase Completed.  

Please review it.   Ref --- 214

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Details attached.  So closing this ticket.
