### ISSUE TITLE
MDC-Live Server Master Collection - Inv & PICC  - JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#223]
Dear Team,

MDC-Live Server   Master Collection - Inv & PICC  -   JCIPL_ZIECON_OU
--

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Item Master: [PRODUCT CODES Update 18.04.20.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4578942/PRODUCT.CODES.Update.18.04.20.xlsx)

**Comment by srinivasanbaskaran** [comment]
Item master FG: [JCIPL_FG_ItemCode_10062020.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4771943/JCIPL_FG_ItemCode_10062020.zip)

**Comment by raju-kurup** [comment]
Master data collected and attached, so closing this ticket.
