### ISSUE TITLE
MDC-Live Server Master Collection - Process Prod  - JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#224]
Dear Team,

Process Production Live Server Master Upload has to be start 

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
please close the ticket..not  related to production..

**Comment by raju-kurup** [comment]
This OU doesn't have Process Production, so closing this ticket
