### ISSUE TITLE
MDC-Live Server Master Collection - Sales & Shipping -JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#225]
Dear Team,

MDC-Live Server   Master Collection - Sales & Shipping -JCIPL_ZIECON_OU
--

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Below are the data received from the Customer ...

MFG OU Customer Master: [01_JCIPL_Customer Master-ojas.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4578915/01_JCIPL_Customer.Master-ojas.xlsx)

Customer Group:  [01_JCIPL_Customer Group.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4656536/01_JCIPL_Customer.Group.xlsx)

SCM Employee Master: NA

Sales Person: NA

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Master data collected and attached, so closing this ticket.
