### ISSUE TITLE
MDC-Live Server Master Collection - Finance - JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#226]
Dear Team,

Fixed Asset Live Server Master Upload has to be start 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Dear Team,

Chart of Accounts received from the customer.
[Copy of chart of accounts - FINAL.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4680714/Copy.of.chart.of.accounts.-.FINAL.xlsx)

**Comment by basha123456** [comment]
Dear Sir,

Data received from joshi-finance..this is the final data.

[Bank and Cash Details - FINAL.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757837/Bank.and.Cash.Details.-.FINAL.xlsx)
[chart of accounts - FINAL.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757838/chart.of.accounts.-.FINAL.xlsx)
[Tax Region - FINAL.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757840/Tax.Region.-.FINAL.xlsx)

**Comment by raju-kurup** [comment]
Details attached.  So closing this ticket.
