### ISSUE TITLE
MDC-Live Server Master Collection - Fixed Asset - JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#227]
Dear Team,

Item Opening Balance Validation & Upload to the Live Server 

Regards,
Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Dear Team.

Fixed Asset collected for ZIECON OU.

Regards.
S.Dhanwandher
[Asset Initial Entry - ZIECON.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4852438/Asset.Initial.Entry.-.ZIECON.xlsx)

**Comment by raju-kurup** [comment]
Master data for Fixed Asset Collected
