### ISSUE TITLE
MDC-Live Server Master Collection - EAM - JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#228]
Dear Team,

MDC-Live Server   Master Collection - EAM - JCIPL_ZIECON_OU
--

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@raju-kurup ,

Sir,

As per the discussion with EAM Sonawane..there is no machine maintenance for Ziecon clinic. so we can close this ticket.

**Comment by raju-kurup** [comment]
Details attached.  So closing this ticket.
