### ISSUE TITLE
MDC-Live Server Master Collection - TOOL - JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#229]
Dear Team,

MDC-Live Server Master Collection - TOOL - JCIPL_ZIECON_OU

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@raju-kurup 

Tool Room is not there in ziecon OU

**Comment by raju-kurup** [comment]
In Ziecon OU, there is no Tool Management module, so closing this ticket
