### ISSUE TITLE
IMP-Master Data Collection for Test server

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#23]
Basha,

Kindly collect the Purchase and sub contracting master from Client.

Thanks and regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Basha,

What is the status for Purchase master collecting process.

Regards,
M.Maheshwaran

**Comment by basha123456** [comment]
Mahesh,

Sanjay patil has already given the supplier master sample data for scenario showcasing.
Entire masters he is preparing. i will collect it and update ASAP.

Regards,
Basha

**Comment by maheshwaran-m** [comment]
Team ,

Purchase and Sub contracting , Inventory and PICC, Quality Management, Sales and shipping MDCF training has been completed.

Thanks and Regards,
M.Maheshwaran.

**Comment by sujin1708** [comment]
[ERP CODING Extrusion 19.9.2019..xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3642575/ERP.CODING.Extrusion.19.9.2019.xlsx)
Finsished Good master data for production  file received from jyoti
1. [jyoti Dental MDCF01 ver.1-200919.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3642576/jyoti.Dental.MDCF01.ver.1-200919.xlsx)
2. [Press Shop, Sand & Coating.xlsx](https://github.com/astpl1998/Jyoti-
3. Ceramic/files/3642577/Press.Shop.Sand.Coating.xlsx)

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the attached Purchase Masters Uploaded MDCF For your reference.

**MDCF Purchase Master**

01 : [01_JCIPL_Create Payterm_1 to 39-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3684495/01_JCIPL_Create.Payterm_1.to.39-C.xlsx)
**Domestic**
02 : [00_JCIPL_Supplier_Master_Domestic_1 to 849-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3684506/00_JCIPL_Supplier_Master_Domestic_1.to.849-C.xlsx)
03 : [03_JCIPL_Edit_specify terms_Domestic_1 to 849-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3684508/03_JCIPL_Edit_specify.terms_Domestic_1.to.849-C.xlsx)
04 : [04_JCIPL_FinalEditSupplier_SpecifyTaxDetails_Domestic_1 to 849.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3684509/04_JCIPL_FinalEditSupplier_SpecifyTaxDetails_Domestic_1.to.849.xlsx)
05 : [Uploading 01_JCIPL_Domestic_Supplier Group_1 to 22-C.xlsx…]()

**Imports**
06 : [01_JCIPL_Supplier_Master_Imports_1 to 46-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3684510/01_JCIPL_Supplier_Master_Imports_1.to.46-C.xlsx)
07 : [Uploading 02_JCIPL_Edit_specify terms_Imports_1 to 46-C.xlsx…]()
08 : [Uploading 03_JCIPL_FinalEditSupplier_SpecifyTaxDetails_Import_1 to 46-C.xlsx…]()
09 : [Uploading 01_JCIPL_Imports_Supplier Group_1 to 10-C.xlsx…]()


Regards,
Maheshwaran

**Comment by raju-kurup** [comment]
UAT is in progress, so closing this issue
