### ISSUE TITLE
MDC-Live Server Master Collection - Pur & Subcon  - JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#230]
Dear Team,

Toolroom Live Server Configuration has to be start 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju Sir,

MDC - Live Server Master Collection - purchase Completed. 

Please review it.  Ref--214

Regards,
Manivel A
