### ISSUE TITLE
MDC-Live Server Master Collection - Inv & PICC  - JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#231]
Dear Team,
Inv& PICC -  Live Server Master collection has to be start 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Item master FG: [JCIPL_FG_ItemCode_10062020.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4771943/JCIPL_FG_ItemCode_10062020.zip)

**Comment by raju-kurup** [comment]
Master data collected and attached, so closing this ticket.
