### ISSUE TITLE
P&S: SUBCON ORDER TO BE INTEGRATED WITH PURCHASE ORDER PRINT

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#233]
Dear Team,

Subcontract Order print to be incorporate to Purchase Order

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

PFS completed. Kindly Review the PFS & Move it to further Development

PFS: [06_JCIPL_SCO_Print_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4412857/06_JCIPL_SCO_Print_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

In this, I have some of doubts to be clarified. We need to discuss those doubts while we are doing the Review .

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Please find the latest updated PFS for Subcontract Order Print

PFS: [06_JCIPL_SCO_Print_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414707/06_JCIPL_SCO_Print_PFS_v1.1.xlsx)

REgards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Test Data will be prepared & update later

REgards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Please find the updated PFS

PFS: [06_JCIPL_SCO_Print_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4431143/06_JCIPL_SCO_Print_PFS_v1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 

kindly provide the test data for this report

**Comment by srinivasanbaskaran** [comment]
@basha123456,

Please prepare the Test Data 

Regards,
Srinivasan

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Please finf the test data and test case.

[07_JCIPL_SCO_Test Data_V1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4486016/07_JCIPL_SCO_Test.Data_V1.0.xlsx)

**Comment by basha123456** [comment]
@basha123456,

Please prepare the Test Data as per our discussion

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Test data is prepared as per the format.. but github is not accepting the format. So i will send yoi in skype. 
![image](https://user-images.githubusercontent.com/47315921/79468217-45fefd80-801c-11ea-8576-57928417744c.png)

**Comment by basha123456** [comment]
@Jeyapriyat,

Please find the Test Data 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

PFS updated along with correct number fields and Test Data also attached. 

PFS: [06_JCIPL_SCO_Print_PFS_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4497834/06_JCIPL_SCO_Print_PFS_v1.3.xlsx)

Test Data: [07_JCIPL_SCO_Test Data_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4497838/07_JCIPL_SCO_Test.Data_v1.1.xlsx)

Regards,
Srinivasan

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 
Report Completed,kindly check and revert.
DW Report Name : print_subcontract_order_report
i have attached report deliverables.
[subcontracr order report _ jcie-248.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4507920/subcontracr.order.report._.jcie-248.zip)

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start Testing 1 & Prepare Testing Document 

Regards,
Srini

**Comment by srinivasanbaskaran** [comment]
Manivel, 

Kindly start Testing 1 & Prepare Testing Document

Regards,
Srinivasan

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Subcontract Print is not as per the PFS & Test Data. 

Kindly inform to Developer regarding this & After complete Developer has to Update the Test Result as per the PFS. 

Documents are attached for your references.

PRINT: [Subcontract Print-1st Level of Testing.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4593566/Subcontract.Print-1st.Level.of.Testing.pdf)

UDS: [Subcon - UDS Error.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4593572/Subcon.-.UDS.Error.docx)


Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Jeyapriya,

Please attach the Test Result.

Test Data is available in PFS "SCO Format All OU" sheet.

**Comment by raju-kurup** [comment]
@srinivasanbaskaran : Do the testing and update the PFS and mark it for review

**Comment by srinivasanbaskaran** [comment]
Team,

PFA of Latest Open Points 

![IMG_20200514_152023_20200514_152038555](https://user-images.githubusercontent.com/46194039/82203881-8e625180-9921-11ea-84a8-9f95034c362b.jpg)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per the PFS highlighted in yellow colour.

**Comment by Jeyapriyat** [comment]
@Manimahat 

report changes completed,kindly check and revert.
dw report name : print_subcontract_order_report
i have attached letest deliverables and sample report output .
[subcontract order report deliverables jcie-290 .zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4757665/subcontract.order.report.deliverables.jcie-290.zip)
[subcontract order report sample output 10-6-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4757667/subcontract.order.report.sample.output.10-6-2020.pdf)

**Comment by Manimahat** [comment]
@jayapriya,

We have faced below issue points while testing. Please Resolve it with High Priority.

 1. Type Value isn't Fetch fully.
 2.  Need some Space Between Line item & Tabular column.
 3. Total Amount is wrongly fetched.
 4. Advance Amount is not fetch

Please find the Below PDF Mentioned above highlighted point in this File.

File : [Subcon Order _ Issue Output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4764067/Subcon.Order._.Issue.Output.pdf)

Regards,
Manivel A

**Comment by Jeyapriyat** [comment]
@Manimahat 
report changes completed,kindly check and revert.
dw report name : print_subcontract_order_report
i have attached letest deliverables and sample report output .
[subcontract order report deliverables jcie-290 v 1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4766193/subcontract.order.report.deliverables.jcie-290.v.1.1.zip)
[subcontract order report sample output 11-6-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4766194/subcontract.order.report.sample.output.11-6-2020.pdf)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 Completed. Kindly start the Testing 2 Process.

Test Case : [Sub-con Order.Test.Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4766606/Sub-con.Order.Test.Case.xlsx)

Test Result : [Subcon Order _ Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4766609/Subcon.Order._.Result.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
@Manimahat,

Please find the below points to be changed in this report

1. Report Name
2. PAN Number 
3. Summary Tabular column will come to the down

Correct the above mentioned points 

Regards,
Srinivasan Baskaran

**Comment by Jeyapriyat** [comment]
@Manimahat 
report name and pan num changes completed ,kindly check and revert.
i have attached latest deliverables and sample output.
[subcontract order report deliverables jcie-290 v 1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4768994/subcontract.order.report.deliverables.jcie-290.v.1.2.zip)
[subcontract order report sample output 12-6-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4768997/subcontract.order.report.sample.output.12-6-2020.pdf)

**Comment by Manimahat** [comment]
@Jeyapriyat ,

![image](https://user-images.githubusercontent.com/55881685/84470909-f0ed0a00-aca1-11ea-9442-924a7809b310.png)

Please find the attached Screenshot for Subcontract PO.. Summary Detail tabular column should come just above to the Special Instruction field

So, please correct & deliver as per the Customer Requirement

**Comment by Jeyapriyat** [comment]
@Manimahat 
changes completed,kindly check and revert.
i have attached latest deliverables.
[subcontract order report deliverables jcie-290 v 1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4774162/subcontract.order.report.deliverables.jcie-290.v.1.3.zip)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing completed. kindly proceed testing 2 process.

Test case : [Sub-con Order.Test.Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4774166/Sub-con.Order.Test.Case.xlsx)

Test Result : [Subcon Order _ output1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4774168/Subcon.Order._.output1.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Sujin,

Kindly start Testing 2 & Prepare teh Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@srinivasanbaskaran Testing2 Completed kindly check and move to level
[subcon po test data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4777882/subcon.po.test.data.xlsx)
[Subcon po print _test result1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4777884/Subcon.po.print._test.result1.pdf)

**Comment by srinivasanbaskaran** [comment]
Sir,

Subcontract Purchase Order Print Testing has been completed. Herewith I have attached the Testing Documents for future references.

PFS: [07_JCIPL_SCO_PFS_1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4784002/07_JCIPL_SCO_PFS_1.4.xlsx)

DELIVERABLES: [subcontract.order.report.deliverables.jcie-290.v.1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4784021/subcontract.order.report.deliverables.jcie-290.v.1.3.zip)

TESTCASE1: [Sub-con.Order.Test.Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4784020/Sub-con.Order.Test.Case.xlsx)

TEST RESULT1: [Subcon.Order._.output1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4784023/Subcon.Order._.output1.pdf)

TESTCASE2: [subcon.po.test.data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4784028/subcon.po.test.data.xlsx)

TEST RESULT2:[Subcon.po.print._test.result2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4784036/Subcon.po.print._test.result2.pdf)

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju Sir,

As per user Requirement, Name & Designation Point will add in the MFG OU. I have updated the PFS As per the Requirement.

We need to Add the Employee Name Field in the UDS Screen, After That we will Add the Name & Designation in the Report.

Updated PFS : [07_JCIPL_SCO_PFS_1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4916366/07_JCIPL_SCO_PFS_1.5.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please add name and designation in the report and in UDS

**Comment by Jeyapriyat** [comment]
@Manimahat 
edk design completed.
ticket id : JCIE-305

**Comment by Jeyapriyat** [comment]
@Manimahat 
changes completed,kindly check and revert.
DW Report Name : print_subcontract_order_report
i have attached latest report deliverables and sample output.
![image](https://user-images.githubusercontent.com/37791285/88668138-dbbc2580-d0ff-11ea-95ad-916d2714f4b2.png)
[subcon order rpt jcie-305 -new v 1.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4988434/subcon.order.rpt.jcie-305.-new.v.1.4.zip)
[subcontract order report sample output 28-7-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4988437/subcontract.order.report.sample.output.28-7-2020.pdf)

**Comment by Jeyapriyat** [comment]
@Manimahat 

changes completed,kindly check and revert.
i have attached latest deliverables and sample output.
[subcontract order report deli jcie-305 - v1.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4993291/subcontract.order.report.deli.jcie-305.-.v1.5.zip)
[subcontract order report sample output 29-7-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4993292/subcontract.order.report.sample.output.29-7-2020.pdf)

**Comment by Jeyapriyat** [comment]
@Manimahat 
changes completed,kindly check and revert.
i have attached latest deliverables and sample output.
[subcontract order report deli jcie-305 new  - v1.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4993450/subcontract.order.report.deli.jcie-305.new.-.v1.5.zip)
[subcontract order report sample output 29-7-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4993453/subcontract.order.report.sample.output.29-7-2020.pdf)

**Comment by Manimahat** [comment]
@srinivasanbaskaran,

Testing 1 Completed. kindly Proceed Testing 2 Process.

Test Case : [Sub-con.Order.Test.Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4996308/Sub-con.Order.Test.Case.xlsx)

Test Result : [Subcon-Order _Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4996311/Subcon-Order._Result.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Team,

Subcontract PO Print Testing 2 Completed.

TESTCASE2: [Subcontract Purchase Order Report - Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5053064/Subcontract.Purchase.Order.Report.-.Testcase2.xlsx)

TEST RESULT2: [Subcontract_PO_TR2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5053065/Subcontract_PO_TR2.pdf)

Regards,
Srinivasan

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Subcontract Purchase Order Print Testing has been Completed. Herewith I have attached the Testing Documents for the Future references.

PFS: [07_JCIPL_SCO_PFS_1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5053069/07_JCIPL_SCO_PFS_1.5.xlsx)

DELIVERABLES: [subcontract.order.report.deli.jcie-305.new.-.v1.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5053071/subcontract.order.report.deli.jcie-305.new.-.v1.5.zip)

TESTCASE1: [Sub-con.Order.Test.Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5053075/Sub-con.Order.Test.Case.xlsx)

TEST RESULT1: [Subcon-Order._Result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5053080/Subcon-Order._Result.pdf)

TESTCASE2: [Subcontract Purchase Order Report - Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5053064/Subcontract.Purchase.Order.Report.-.Testcase2.xlsx)

TEST RESULT2: [Subcontract_PO_TR2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5053065/Subcontract_PO_TR2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer gave confirmation to close this ticket. So, Kindly proceed further

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer Approved, so closing this ticket

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Need to Change the Format Like Purchase Order. So we re-open this ticket

![Uploading image.png…]()

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

1. User Need the Blanket PO same as Normal PO Format ( Header & Footer , Tax Summary Should be Fixed for all Pages). 
2. Need to reduce the Size of the Ziecon OU Logo & Company Name. 
3. And also Add the Employee Name & Designation in Ziecon & Unitech OU.
4. Payment Term Is not fetched.

Updated PFS : [Uploading 07_JCIPL_SCO_PFS_1.6.xlsx…]()

Correction format : [ziecon Correction Format.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5187651/ziecon.Correction.Format.pdf)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
This report was done by JP but the PO format was done by Nandhinee. So if we giv e it to Nandhinee it will be good

**Comment by Nandhineedevi** [comment]
[ziecon subcon.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5209266/ziecon.subcon.pdf)
[unitech subcon.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5209267/unitech.subcon.pdf)
[mfg subcon.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5209268/mfg.subcon.pdf)
[P_subcon_order_report_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5209274/P_subcon_order_report_v2.1.zip)

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 1 is completed.
Kindly proceed with testing 2.

Test Case for MFG : 
[Subcontract.Purchase.Order.Report.-.Testcase_MFG.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5218450/Subcontract.Purchase.Order.Report.-.Testcase_MFG.xlsx)

Test Result for MFG : 
[SUBCON_PO_MFG_OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5218451/SUBCON_PO_MFG_OU.pdf)

Test Case for UNITECH : 
[Subcontract.Purchase.Order.Report.-.Testcase_UNITECH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5218455/Subcontract.Purchase.Order.Report.-.Testcase_UNITECH.xlsx)

Test Result for UNITECH : 
[SUBCON_PO_UNITECH_OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5218459/SUBCON_PO_UNITECH_OU.pdf)

Test case for ZIECON : 
[Subcontract.Purchase.Order.Report.-.Testcase_ZIECON_OU.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5218463/Subcontract.Purchase.Order.Report.-.Testcase_ZIECON_OU.xlsx)

Test Result for ZIECON : 
[SUBCON_PO_ZIECON_OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5218467/SUBCON_PO_ZIECON_OU.pdf)

Regards,
Faisal

**Comment by Manimahat** [comment]
@AkashGleen ,

Kindly start the testing process.

Regards,
Manivel A

**Comment by AkashGleen** [comment]
Dear @Manimahat 

Subcon Order To Be Integrated With Purchase Order Print Testing 2 Completed Kindly Check & Update.

[Sub-Con Po All OU's Test Case.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5229542/Sub-Con.Po.All.OU.s.Test.Case.zip)

[Sub-Con Po All OU's Test Results.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5229543/Sub-Con.Po.All.OU.s.Test.Results.zip)

Regards,
Akash

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Kindly start final Testing & close this Ticket.

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Subcontract Purchase Order Print Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [07_JCIPL_SCO_PFS_1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5243383/07_JCIPL_SCO_PFS_1.6.xlsx)

DELIVERABLES:[P_subcon_order_report_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5243384/P_subcon_order_report_v2.1.zip)

TESTCASE1: [Subcontract.Purchase.Order.Report.-.Testcase_MFG.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5218450/Subcontract.Purchase.Order.Report.-.Testcase_MFG.xlsx)

Test Result1 for MFG : [SUBCON_PO_MFG_OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5218451/SUBCON_PO_MFG_OU.pdf)

Test Result1 for UNITECH : [SUBCON_PO_UNITECH_OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5218459/SUBCON_PO_UNITECH_OU.pdf)

Test Result1 for ZIECON : 
[SUBCON_PO_ZIECON_OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5218467/SUBCON_PO_ZIECON_OU.pdf)

TESTCASE2: [Sub-Con Po All OU's Test Case.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5229542/Sub-Con.Po.All.OU.s.Test.Case.zip)

TEST RESULT2: [Sub-Con Po All OU's Test Results.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5229543/Sub-Con.Po.All.OU.s.Test.Results.zip)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Being customer given clearance, we are closing this ticket

**Comment by sujin1708** [comment]
to be deploy in live server

**Comment by Jeyapriyat** [comment]
@Manimahat 
deployment completed for live server. 
i have attached latest deliverables and sample output ,kindly check.
[subcontract order report deli jcie-305 new -1 - v1.6.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6008283/subcontract.order.report.deli.jcie-305.new.-1.-.v1.6.zip)


[sampleoutput 19-02-2021.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6008295/sampleoutput.19-02-2021.pdf)

**Comment by Manimahat** [comment]
@raju-kurup sir,

Report has been Deployed successfully. Kindly close this ticket.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live server, so closing this ticket
