### ISSUE TITLE
I&P - DC Challan Print - RDW

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#234]
#43.. 

Need to do the PFS changes as per the Customer Requirement

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Last PFS: [Delivery Challan Print_PFS.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389726/Delivery.Challan.Print_PFS.xlsx)

**NOTE: PFS need to be update as per the Customer Requirements** 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Rajju Sir,

Please find the attached updated PFS of DC Print 

PFS: [Delivery Challan Print_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4473380/Delivery.Challan.Print_PFS_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@srinivasanbaskaran : please give the test data

**Comment by srinivasanbaskaran** [comment]
@raju-kurup, 

Sir, Please find the Test Data for Delivery Challan Print

Test Data: [Test_Data_DC_Print.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4494289/Test_Data_DC_Print.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop the report.

**Comment by karthikeyanamitysoft** [comment]
Sir,

What report it is , DCube report or DW report
this will comes under DW report then where is the EDK screen layout.

REgards,
Karthi

**Comment by raju-kurup** [comment]
@srinivasanbaskaran : please mention the UDS screen details if needed.

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

UDS is not required for this report. While clicking the PRINT button in the screen, directly report is launching 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@srinivasanbaskaran : As discussed this report to be taken from RGP/NRGP screen print button and already report is there, it is the correction only.

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The coding has been completed. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly update teh Test Result which you got while Testing 

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the attached deliverables and test result.

[dc_challan.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4520815/dc_challan.pdf)
[RGP_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4520816/RGP_v1.1.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing 1 & Prepare Testing Document 

Regards,
Srini

**Comment by basha123456** [comment]
@raju-kurup 

In unnitech OU, stages are not loading in the combo against production order ref document.
this is required for testing. please assign developer to do this.
![image](https://user-images.githubusercontent.com/47315921/80270965-537e4c80-86da-11ea-8795-e6f1693209e7.png)

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing1 is completed.
[DCC UNIECH TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4532676/DCC.UNIECH.TR.pdf)
[DCC MFG TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4532677/DCC.MFG.TR.pdf)
[Delivery Challan Test Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4532680/Delivery.Challan.Test.Case.xlsx)

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 2 completed. 

Testcase2: [Delivery_Challan_Testcase_2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4544310/Delivery_Challan_Testcase_2.xlsx)

Test Result2: 
[DC Print_Test Result 2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4544314/DC.Print_Test.Result.2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir, 

DC Print testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [Delivery Challan Print_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4544321/Delivery.Challan.Print_PFS_v1.1.xlsx)

DELIVERABLES: [RGP_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4544329/RGP_v1.1.zip)

TESTCASE1: [Delivery.Challan.Test.Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4544331/Delivery.Challan.Test.Case.xlsx)

TEST RESULT1 (a): [DCC UNITECH TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4544333/DCC.UNITECH.TR.pdf)

TEST RESULT1 (b): [DCC.MFG.TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4544337/DCC.MFG.TR.pdf)

TESTCASE2: [Delivery_Challan_Testcase_2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4544346/Delivery_Challan_Testcase_2.xlsx)

TEST RESULT2: [DC Print_Test Result 2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4544350/DC.Print_Test.Result.2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer accept this report. You can proceed further on this report. Herewith I have attached Signed Copy of User.

![DC Print_Signed Copy](https://user-images.githubusercontent.com/46194039/83788366-b5a37780-a6b2-11ea-9d46-821bac0e3c95.jpeg)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@srinivasanbaskaran : please check the attached report signed by user and clarify the green highlighted matter.

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

As I discussed with User for the green highlighted points are to be corrected. 

As per that, I have updated the PFS for DC Print. 

PFS: [Delivery.Challan.Print_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4784676/Delivery.Challan.Print_PFS_v1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Please correct address as per OU and bold mentioned in PFS and logo to be taken from packslip size

**Comment by Nandhineedevi** [comment]
The development completed. Kindly check and revert back.

[dc test ouput.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4797639/dc.test.ouput.pdf)
[RGP_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4797642/RGP_v1.2.zip)

**Comment by srinivasanbaskaran** [comment]
Sir, 

Company Address & Logo fetched correctly. Report attached for the References

Output: [DC Print.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4800105/DC.Print.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer gave confirmation to close this ticket. So, Kindly proceed further

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
Variant logic to be handled

**Comment by Nandhineedevi** [comment]
Completed.

[dc challan.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5715640/dc.challan.pdf)
[rgp_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5715644/rgp_v2.2.zip)

**Comment by sujin1708** [comment]
@AkashGleen kindly do the testing 1

**Comment by Manimahat** [comment]
@karthikeyanamitysoft ,

If we Select any ref document type & number Then we click create button , it is showing  procedure or function error. please find the below error. 

![image](https://user-images.githubusercontent.com/55881685/105273740-e1cc2400-5bc1-11eb-8203-f24148947ee3.png)

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
@Manimahat 

Issue Resolved after deploying EDKUTIL.DLL in UAT Server.

Kindly check and revert back.

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 completed. Kindly Proceed Testing 2 Process.

Test Case : [Delivery.Challan.Test.Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6240326/Delivery.Challan.Test.Case.xlsx)

Test Result : [DCC.MFG.TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6240328/DCC.MFG.TR.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@AkashGleen kindly do the testing 2

**Comment by AkashGleen** [comment]
@sujin1708 

DC Print Testing as been Completed. Kindly Check & Update.

[Delivery Challan PrintTestCase v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6575572/Delivery.Challan.PrintTestCase.v2.xlsx)
[Testing Result DC Print v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6575573/Testing.Result.DC.Print.v2.pdf)
[Test Result DCC Print v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6575574/Test.Result.DCC.Print.v2.pdf)

Regards,
Akash

**Comment by sujin1708** [comment]
@karthikeyanamitysoft kindly attach the latest deliverables

**Comment by BalaramanM** [comment]
@sujin1708 
@Manimahat 
Pls find the attached deliverables
[RGP_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6725602/RGP_v1.2.zip)
[rgp_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6725604/rgp_v2.2.zip)

Regards,
Balaraman

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Testing 2 Completed. Please close this ticket.

Testing Case 1: [Delivery.Challan.Test.Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6820489/Delivery.Challan.Test.Case.xlsx)
Test Result 1 : [DCC.MFG.TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6820491/DCC.MFG.TR.pdf)
Test Case 2: [Delivery.Challan.PrintTestCase.v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6820495/Delivery.Challan.PrintTestCase.v2.xlsx)
Test Result 2: [Testing.Result.DC.Print.v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6820498/Testing.Result.DC.Print.v2.pdf)
Deliverbles : [rgp_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6820502/rgp_v2.2.zip)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Whether this is deployed in live server.

**Comment by Manimahat** [comment]
@raju-kurup Sir,

DC Challan print has been deployed in UAT & Live server Successfully. please close this ticket

Live Server Screen :  ![image](https://user-images.githubusercontent.com/55881685/125816896-b9ada2d1-64ec-4a53-abb1-e19b9851a674.png)

Live server Print : ![image](https://user-images.githubusercontent.com/55881685/125816830-adb8ff5d-e5bb-4b36-bdc1-e94d8206ca94.png)


Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in live, so closing this ticket.
