### ISSUE TITLE
PPD : Stage base reporting -Automation (Description coding to be handled)

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#235]
please write logic for description fetching in the automation screen

1. process Stage
2. process cell
3. operation
4. process unit

**Comment by sujin1708** [comment]
[Stage.base.Reporting.Automation.-.PFS_V4.26.03 (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4392524/Stage.base.Reporting.Automation.-.PFS_V4.26.03.1.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : as discussed with Sujin PFS raised for the description to be corrected

**Comment by Jeyapriyat** [comment]
@sujin1708 

changes completed,kindly check and revert.
![image](https://user-images.githubusercontent.com/37791285/78017814-7a12c700-736a-11ea-910c-76e77b97d67b.png)

**Comment by sujin1708** [comment]
values fetching properly..kindly check n move to next level

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly Start Testing 2 & Prepare the Testcase as per our format

Regards,

Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2 completed. PFA documents

Test Case - [Description fetching in Reporting screen - Test Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4413343/Description.fetching.in.Reporting.screen.-.Test.Case.xlsx)
Test Result - [Description fetching in Automation screen - Test Result.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4413345/Description.fetching.in.Automation.screen.-.Test.Result.docx)

**Comment by srinivasanbaskaran** [comment]
Jeyapriya,

Kindly update the Latest deliverables ASAP

REgards,
Srinivasan Baskaran

**Comment by Jeyapriyat** [comment]
@srinivasanbaskaran 

i have attached latest deliverables.
[Jyoti Automation - Stage Based Reporting-multiple items  - jcie-219 v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4420021/Jyoti.Automation.-.Stage.Based.Reporting-multiple.items.-.jcie-219.v1.1.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

Stage base Reporting - Automation Description coding testing has been Completed. Herewith I have attached Testing documents for future references.

PFS: [Stage.base.Reporting.Automation.-.PFS_v4.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4431617/Stage.base.Reporting.Automation.-.PFS_v4.0.xlsx)

DELIVERABLES: [Jyoti.Automation.-.Stage.Based.Reporting-multiple.items.-.jcie-219.v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4431620/Jyoti.Automation.-.Stage.Based.Reporting-multiple.items.-.jcie-219.v1.1.zip)

TESTCASE1 & TEST RESULT1: ![Testcase 1   Test Result1 - Stage based  Reporting Description](https://user-images.githubusercontent.com/46194039/78453249-0c3e0680-76ae-11ea-9aea-9eb3e0f53102.png)

TESTCASE2: [Description.fetching.in.Reporting.screen.-.Test.Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4431622/Description.fetching.in.Reporting.screen.-.Test.Case.xlsx)

TEST RESULT2: [Description.fetching.in.Automation.screen.-.Test.Result.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4431623/Description.fetching.in.Automation.screen.-.Test.Result.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly Close this ticket. Customer Accepted this point

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer Approved, so closing this ticket
