### ISSUE TITLE
IMP - Master Data Collection - PROCESS PRODUCTION

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#236]
Dear Team,

Collect the Master Data from the User with Respect to Process Prodcution Related Data. 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Physical Model - MDCF completed..

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Seperate ticket for collection, so closing this ticket.
