### ISSUE TITLE
SMO - Sample document collection for Scenario showcasing

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#24]
Prabha / Sujin

Required Purchase and sub contracting scenario showcasing test data. Kindly collect the sample data as per the scenario.

Thanks and Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Purchase and Subcontracting for Scenario show casing sample data has been collected from Client.

Sample Data : [01_Purchase sample data for Scenario Showcasing.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3349073/01_Purchase.sample.data.for.Scenario.Showcasing.xlsx)

Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Purchase and Subcontracting for Scenario show casing sample data has been collected from Client.

Sample data[02_Purchase Sample Data for Scenatio Showcasing V 1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3375737/02_Purchase.Sample.Data.for.Scenatio.Showcasing.V.1.1.xlsx)

Regards,
M.Maheshwaran

**Comment by Prabakaran92** [comment]
Sales & shipping Sample data for Scenario showcasing Collected from client.

Sample data : [01_Sales sample data for scenario showcasing.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3385017/01_Sales.sample.data.for.scenario.showcasing.xlsx)

Regards,
Prabakaran A

**Comment by maheshwaran-m** [comment]
Scenario show casing completed. Issue has been closed.

regards,
M.Maheshwaran
