### ISSUE TITLE
MDC-Live Server Master Collection - Sales & Shipping -JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#241]

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Below are the data are received from the Customer.

Customer Master: [01_JCIPL_Customer Master_GmbH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4578922/01_JCIPL_Customer.Master_GmbH.xlsx)

Customer Group:

SCM Employee Master: 

Sales Person:

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Master data collected and attached, so closing this ticket.
