### ISSUE TITLE
MDC-Live Server Master Collection - Finance - JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#242]

**Comment by basha123456** [comment]
Dear Sir,

Data received from Joshi - Finance.. this is the final data.
[Bank and Cash Details - FINAL GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757802/Bank.and.Cash.Details.-.FINAL.GMBH.xlsx)
[chart of accounts - FINAL GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757803/chart.of.accounts.-.FINAL.GMBH.xlsx)
[Tax Region - FINAL GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757804/Tax.Region.-.FINAL.GMBH.xlsx)

**Comment by raju-kurup** [comment]
Details attached.  So closing this ticket.
