### ISSUE TITLE
MDC-Live Server Master Collection - Pur & Subcon  - UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#246]

**Comment by srinivasanbaskaran** [comment]
Refer---- #214

**Comment by Manimahat** [comment]
@raju Sir,

MDC - Live Server Master Collection - purchase Completed. 

Please review it.  Ref -- 214

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Details attached.  So closing this ticket.
