### ISSUE TITLE
MDC-Live Server Master Collection - Inv & PICC  - UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#247]
MDC-Live Server Master Collection - Inv & PICC  - UNITECH_OU

**Comment by srinivasanbaskaran** [comment]
Item Master:[PRODUCT CODES Update 18.04.20.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4578943/PRODUCT.CODES.Update.18.04.20.xlsx)

**Comment by srinivasanbaskaran** [comment]
Item master FG: [JCIPL_FG_ItemCode_10062020.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4771943/JCIPL_FG_ItemCode_10062020.zip)

**Comment by raju-kurup** [comment]
Master data collected and attached, so closing this ticket.
