### ISSUE TITLE
IMP-SDD Business Process Study for Quality Management 

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#25]
Dear team,

Preparation for SDD Business Process Study for Quality Management.

Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Dear Team,

Business process study for Quality Management In-warding Quality process has been completed.

MOM : [03_JCIPL_MOM_INV_QUA_19.06.2019_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3356172/03_JCIPL_MOM_INV_QUA_19.06.2019_V.1.0.docx)
MOM : [03_JCIPL_MOM_INV_QUA_03.07.2019_V 1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3356173/03_JCIPL_MOM_INV_QUA_03.07.2019_V.1.1.docx)

Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Production Related Quality process in Not completed.

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the attached updated Quality Management SDD all version for your reference.

SDD : [01_JCIPL_Quality Management_SDD_Ver 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3476867/01_JCIPL_Quality.Management_SDD_Ver.1.0.docx)

Thanks and Regards,
M.Maheshwaran

**Comment by raju-kurup** [comment]
SDD issued waiting for Sign-off
