### ISSUE TITLE
MDC-Live Server Master Collection - Finance - UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#250]

**Comment by basha123456** [comment]
Dear Team,

Chart of Accounts received from the customer.
[Copy of chart of accounts - FINAL.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4680707/Copy.of.chart.of.accounts.-.FINAL.xlsx)

**Comment by basha123456** [comment]
Dear Sir,

Data received from joshi-finance.. this is the final data.

[Bank and Cash Details - FINAL UNITECH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757815/Bank.and.Cash.Details.-.FINAL.UNITECH.xlsx)
[chart of accounts - FINAL UNITECH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757817/chart.of.accounts.-.FINAL.UNITECH.xlsx)
[Tax Region - FINAL UNITECH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4757819/Tax.Region.-.FINAL.UNITECH.xlsx)

**Comment by raju-kurup** [comment]
Details attached.  So closing this ticket.
