### ISSUE TITLE
MDC-Live Server Master Collection - Fixed Asset - UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#251]

**Comment by Dhanwandher** [comment]
Dear Team.....

Received Fixed Asset data for Unitech OU....

Regards...
S.Dhanwandher...
[assets - UNITECH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4945211/assets.-.UNITECH.xlsx)

**Comment by raju-kurup** [comment]
Master collected and validated, so closing this ticket.
