### ISSUE TITLE
MDV-Live Server Master Validation - Pur & Subcon  - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#254]

**Comment by Manimahat** [comment]
@raju-kurup sir,
Sale Validation Process is Completed for Mfg OU. Kindly Proceed to Close this Ticket.

Customer  : [01_JCIPL_Customer Master-08JJuly2020_MFG.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4932661/01_JCIPL_Customer.Master-08JJuly2020_MFG.xlsx)

Customer Group : [01_JCIPL_Customer.Group.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4932669/01_JCIPL_Customer.Group.xlsx)

TCD : [TCD Master Data For Sales_1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4932673/TCD.Master.Data.For.Sales_1.xlsx)

Payterm : [01_Create Payterm-1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4932674/01_Create.Payterm-1.xlsx)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Purchase validation is Completed For MFG OU. Please find the Doc. for your ref...

Supplier Master for DOM : [01_Supplier_Master_DOM.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943595/01_Supplier_Master_DOM.xlsx)

Supplier Group : [01_SupplierGroup - DOM.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943596/01_SupplierGroup.-.DOM.xlsx)

Supplier Master for EXP : [01_Supplier_Master_EXP.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943597/01_Supplier_Master_EXP.xlsx)

Supplier Group : [01_SupplierGroup - EXP.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943599/01_SupplierGroup.-.EXP.xlsx)

TCD : [TCD.Master.Data.-.To.Customer.07.05.2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943600/TCD.Master.Data.-.To.Customer.07.05.2020.xlsx)

Payterm : [01_JCIPL_Create.Payterm_1.to.39-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943602/01_JCIPL_Create.Payterm_1.to.39-C.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Master collected and validated, so closing this ticket.

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Jyoti Provided New supplier Master Data by Mail dt 27/07/2020. So We Re-open this Ticket.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Validation process has Completed. Herewith i have attached the Ref Doc for you ref.

Supplier Master : [01_Supplier_Master27July2020..xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4992301/01_Supplier_Master27July2020.xlsx)

Supplier Group : [01_SupplierGroup27july2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4992304/01_SupplierGroup27july2020.xlsx)

TCD Details : [TCD.Master.Data.-.To.Customer.07.05.2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4992307/TCD.Master.Data.-.To.Customer.07.05.2020.xlsx)

Pay-term Details : [01_JCIPL_Create.Payterm_1.to.39-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4992310/01_JCIPL_Create.Payterm_1.to.39-C.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Validated completed, so closing this ticket
