### ISSUE TITLE
MDV-Live Server Master Validation - Inv & PICC  - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#255]

**Comment by srinivasanbaskaran** [comment]
Team,

Item Master: [PRODUCT CODES Update 18.04.20.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4578939/PRODUCT.CODES.Update.18.04.20.xlsx)

Item Master FG : [JCIPL_FG_ItemCode_10062020.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4771924/JCIPL_FG_ItemCode_10062020.zip)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Below are the file are validated. There is no problem in that.


DISC_Edit Item Attribute Mapping:[02_JCIPL_EditItemAttribute_InsertMasterData_DISC_Working.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4800877/02_JCIPL_EditItemAttribute_InsertMasterData_DISC_Working.xlsx)

**Comment by srinivasanbaskaran** [comment]
Sujin,

Please find the updated Item Master MDCF file. 

[03_JCIPL_Item Master-Revise4_16_08_2020_Workings.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5154158/03_JCIPL_Item.Master-Revise4_16_08_2020_Workings.xlsx)

Need to sent mail to customer 

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
[FG MASTERS-2Dec2020.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5806131/FG.MASTERS-2Dec2020.zip)

**Comment by sujin1708** [comment]
validation completed ...kindly close the ticket

**Comment by raju-kurup** [comment]
Being validation done, we are closing this issue
