### ISSUE TITLE
MDV-Live Server Master Validation - Sales & Shipping -JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#257]

**Comment by srinivasanbaskaran** [comment]
Team, 

The below are the list of Master Data receiced from the User.
[01_JCIPL_Customer Master-ojas.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4750245/01_JCIPL_Customer.Master-ojas.xlsx)
[01_JCIPL_Customer Master_GmbH_Updated 8May2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4750243/01_JCIPL_Customer.Master_GmbH_Updated.8May2020.xlsx)

**Comment by srinivasanbaskaran** [comment]
Sujin, 

Please proceed further on Validation

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@srinivasanbaskaran 

i) Above attachment File Name Customer Master Ojas - ok
ii) Customer Master GMBH no master details in that file except tax

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Below are the data received from the Customer ...

MFG OU Customer Master: [01_JCIPL_Customer Master-ojas.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4578915/01_JCIPL_Customer.Master-ojas.xlsx)

Customer Group:  [01_JCIPL_Customer Group.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4656536/01_JCIPL_Customer.Group.xlsx)

SCM Employee Master: NA

Sales Person: NA

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup sir,
Sale Validation Process is Completed for Mfg OU. Kindly Proceed to Close this Ticket.

Customer  : [01_JCIPL_Customer Master-08JJuly2020_MFG.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4932661/01_JCIPL_Customer.Master-08JJuly2020_MFG.xlsx)

Customer Group : [01_JCIPL_Customer.Group.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4932669/01_JCIPL_Customer.Group.xlsx)

TCD : [TCD Master Data For Sales_1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4932673/TCD.Master.Data.For.Sales_1.xlsx)

Payterm : [01_Create Payterm-1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4932674/01_Create.Payterm-1.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Master collected and validated, so closing this ticket.
