### ISSUE TITLE
MDV-Live Server Master Validation - Fixed Asset - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#259]

**Comment by Dhanwandher** [comment]
Dear Team.

Fixed file validated....

Regards...
S.Dhanwandher...
[Validation_MFG.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4901203/Validation_MFG.xlsx)

**Comment by raju-kurup** [comment]
Master data validation completed, so closing this ticket
