### ISSUE TITLE
PMO - Process Production Scenario Check - Continuous + Batch Production

### ISSUE THREAD

**Issue by Duraisingam-G** [astpl1998/Jyoti-Ceramic#26]

**Comment by sujin1708** [comment]
[Continuous Process.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3388487/Continuous.Process.xlsx)

1. while create report prodcution/consumption(flow based) at the time of authorize status not change automatically 
2. Transcation alert not display 
3.production issue qty shown as zero
4. lot consumption not happen

**Comment by sujin1708** [comment]
closed
