### ISSUE TITLE
MDV-Live Server Master Validation - TOOL - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#261]

**Comment by basha123456** [comment]
Press Shop Tool Data given by jyoti..with this we are able to create Equipments for Tools & subtools.
[Tool Data from sagar.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4466611/Tool.Data.from.sagar.xlsx)
With the below data we can create the Masters in the system.
[MASTER DATA - TOOL ROOM thorat small masters.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4466621/MASTER.DATA.-.TOOL.ROOM.thorat.small.masters.xlsx)

**Comment by basha123456** [comment]
Tool Master data received, validated. 
for clarification, mail sent to gautam.

**Comment by basha123456** [comment]
[Dental tool codification.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4797789/Dental.tool.codification.xlsx)
[Extrusion tooling170620.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4797790/Extrusion.tooling170620.xlsx)
[ISO TOOLS-170620.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4797791/ISO.TOOLS-170620.xlsx)
[Final tool coding list 3.6.20.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4797792/Final.tool.coding.list.3.6.20.xlsx)
@raju-kurup 

tool data is validated we can create Equipments for this..

**Comment by raju-kurup** [comment]
Tool data validated, so closing this ticket

**Comment by srinivasanbaskaran** [comment]
Team,

Please find the below validated file for Tool Management. User has to correct the mentioned points in this file 

FILE1: [Final.tool.coding.list.3.6.20.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5254883/Final.tool.coding.list.3.6.20.xlsx)

FILE2: [Dental.tool.codification.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5254897/Dental.tool.codification.xlsx)

FILE3: [ISO.TOOLS-170620.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5254901/ISO.TOOLS-170620.xlsx)

FILE4: [Extrusion.tooling170620.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5254903/Extrusion.tooling170620.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup sir,

File 1: [Dental MAIN TOOL for item& Equpment .xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5703800/Dental.MAIN.TOOL.for.item.Equpment.xlsx)
File 2: [ExtrusionMAIN TOOL for item& Equpment.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5703802/ExtrusionMAIN.TOOL.for.item.Equpment.xlsx)
File 3:[ISO.MAIN TOOL for item& Equpment.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5703806/ISO.MAIN.TOOL.for.item.Equpment.xlsx)
File 4: [Uploading Press shop MAIN TOOL for item& Equpment.xlsx…]()

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
