### ISSUE TITLE
MDV-Live Server Master Validation - Sales & Shipping -JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#265]

**Comment by sujin1708** [comment]
@srinivasanbaskaran attach the file..which u received for validation

**Comment by Manimahat** [comment]
@raju-kurup sir,

Ziecon OU don't have Customers. I have Attached the Mail Screen Shot for your reference.

Mail Screen Shot :  ![image](https://user-images.githubusercontent.com/55881685/87149095-3adf0500-c2cd-11ea-87d9-0b64f3f038cc.png)

So we have to close this Ticket

**Comment by raju-kurup** [comment]
Master data validation completed, so closing this ticket
