### ISSUE TITLE
MDV-Live Server Master Validation - Fixed Asset - JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#267]

**Comment by Dhanwandher** [comment]
Dear Team.

Fixed file validated....

Regards...
S.Dhanwandher...
[Validation_ZIECON.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4901192/Validation_ZIECON.xlsx)

**Comment by raju-kurup** [comment]
Master data Validation completed, so closing this ticket
