### ISSUE TITLE
PMO - Process Production Scenario Check - Yield, Material Loss

### ISSUE THREAD

**Issue by Duraisingam-G** [astpl1998/Jyoti-Ceramic#27]

**Comment by basha123456** [comment]
Dear Singham,

Material Loss% scenario is checked. I have checked in both kanam server and partner sandbox. In the formula i have given the Loss% for an item. i raised production order. 
In the kanam server, in the view control recipe-formula details screen, the Loss % for the material is calculating correctly.
But in the Partnersandbox, in the view control recipe-formula details screen, the Loss % for the material is not calculating correctly. 
PFA of the scenario modelling.
[Material Loss Scenario Showcasing.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3375903/Material.Loss.Scenario.Showcasing.xlsx)
