### ISSUE TITLE
MDV-Live Server Master Validation - Pur & Subcon  - JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#270]

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Purchase validation is Completed For GMBH OU. Please find the Doc. for your ref...

Supplier Master for DOM : [01_Supplier_Master_DOM.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943595/01_Supplier_Master_DOM.xlsx)

Supplier Group : [01_SupplierGroup - DOM.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943596/01_SupplierGroup.-.DOM.xlsx)

Supplier Master for EXP : [01_Supplier_Master_EXP.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943597/01_Supplier_Master_EXP.xlsx)

Supplier Group : [01_SupplierGroup - EXP.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943599/01_SupplierGroup.-.EXP.xlsx)

TCD : [TCD.Master.Data.-.To.Customer.07.05.2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943600/TCD.Master.Data.-.To.Customer.07.05.2020.xlsx)

Payterm : [01_JCIPL_Create.Payterm_1.to.39-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4943602/01_JCIPL_Create.Payterm_1.to.39-C.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Master collected and validated, so closing this ticket.

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Jyoti Provided New supplier Master Data by Mail dt 27/07/2020. So We Re-open this Ticket.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Validation process has Completed. Herewith i have attached the Ref Doc for you ref.

Supplier Master : [01_Supplier_Master27July2020..xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4992335/01_Supplier_Master27July2020.xlsx)

Supplier Group : [01_SupplierGroup27july2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4992336/01_SupplierGroup27july2020.xlsx)


TCD Details : [TCD.Master.Data.-.To.Customer.07.05.2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4992339/TCD.Master.Data.-.To.Customer.07.05.2020.xlsx)

Pay-term Details : [01_JCIPL_Create.Payterm_1.to.39-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4992341/01_JCIPL_Create.Payterm_1.to.39-C.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Validation completed, so closing this issue

**Comment by Manimahat** [comment]
@raju sir,

in GMBH OU Sunil Provided me additional Suppliers. So We Re-opened this ticket for Validation purpose

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup ,

in GMBH OU Sunil Provided me additional Suppliers. So We Re-opened this ticket for Validation purpose

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Validation Process has been Completed. Kindly Proceed to Close it.

GMBH Supplier : [01_JCIPL_Supplier_Master_GmbH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5062305/01_JCIPL_Supplier_Master_GmbH.xlsx)

GMBH Supplier Group: [01_SupplierGroup -Gmbh.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5062307/01_SupplierGroup.-Gmbh.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Validation completed, so closing this ticket
