### ISSUE TITLE
MDV-Live Server Master Validation - Sales & Shipping -JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#273]

**Comment by sujin1708** [comment]
@srinivasanbaskaran No files attched ..kindly upload the file for validation

**Comment by Manimahat** [comment]
@raju-kurup sir,
Sale Validation Process is Completed for GMBH OU. Kindly Proceed to Close this Ticket.

Customer  : [01_JCIPL_Customer.Master_GmbH_Updated. 26June2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4932696/01_JCIPL_Customer.Master_GmbH_Updated.26June2020.xlsx)

Customer Group : [01_JCIPL_Customer.Group - GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4932698/01_JCIPL_Customer.Group.-.GMBH.xlsx)

Payterm : [01_Create Payterm-1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4932674/01_Create.Payterm-1.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Master collected and validated, so closing this ticket.
