### ISSUE TITLE
MDV-Live Server Master Validation - Fixed Asset - JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#275]

**Comment by Dhanwandher** [comment]
Dear Team.....

Validated Fixed Asset data for GMBH OU and sent to client for clarification,

Regards...
S.Dhanwandher...
[Validation of GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4945254/Validation.of.GMBH.xlsx)

**Comment by Dhanwandher** [comment]
Dear Team.....

Validated Fixed Asset data for GMBH OU....

Regards...
S.Dhanwandher...
[Validation of GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4945945/Validation.of.GMBH.xlsx)

**Comment by raju-kurup** [comment]
Master collected and validated, so closing this ticket.
