### ISSUE TITLE
MDV-Live Server Master Validation - Inv & PICC  - UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#279]

**Comment by srinivasanbaskaran** [comment]
Team,

Item Master: [PRODUCT CODES Update 18.04.20.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4578939/PRODUCT.CODES.Update.18.04.20.xlsx)

Item Master FG : [JCIPL_FG_ItemCode_10062020.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4771924/JCIPL_FG_ItemCode_10062020.zip)

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
Validation completed kindly close the ticket

**Comment by raju-kurup** [comment]
Being uploading done in live server, we are closing this ticket.
