### ISSUE TITLE
MDV-Live Server Master Validation - Fixed Asset - UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#283]

**Comment by Dhanwandher** [comment]
Dear Team.....

Validated Fixed Asset data for Unitech OU....

Regards...
S.Dhanwandher...
[Validation of Unitech.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4945219/Validation.of.Unitech.xlsx)

**Comment by raju-kurup** [comment]
Master collected and validated, so closing this ticket.
