### ISSUE TITLE
MDU-Live Server Master Uploading - Pur & Subcon  - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#286]

**Comment by Manimahat** [comment]
@akash,

Kindly Upload the TCD & Payterm Master in Live Server.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup sir,

Purchase & Subcontracting Uploading completed for MFG OU. Kindly Close this Ticket.

Supplier Master : [01_Supplier_Master_17-12-20-MFG_.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759889/01_Supplier_Master_17-12-20-MFG_.xlsx)

Supplier Group : [01_SupplierGroup - Revise3_18DEC2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759890/01_SupplierGroup.-.Revise3_18DEC2020.xlsx)

TCD: [TCD.Master.Data.-.To.Customer.07.05.2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759892/TCD.Master.Data.-.To.Customer.07.05.2020.xlsx)

Payterm : [01_JCIPL_Create.Payterm_1.to.39-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759893/01_JCIPL_Create.Payterm_1.to.39-C.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
