### ISSUE TITLE
MDU-Live Server Master Uploading - Inv & PICC  - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#287]

**Comment by srinivasanbaskaran** [comment]
Need to upload the Item master after the confirmation from Jyoti

**Comment by raju-kurup** [comment]
[MFG Live Uploaded File_Jyoti.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6824290/MFG.Live.Uploaded.File_Jyoti.zip)

Master data uploaded, so closing this ticket

**Comment by sujin1708** [comment]
@raju-kurup Kindly Close the ticket upload completed
