### ISSUE TITLE
MDU-Live Server Master Uploading - Process Prod  - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#288]

**Comment by sujin1708** [comment]
[Warehouse_Creation_MDCF.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4441929/Warehouse_Creation_MDCF.xlsx)
[CreateProcessElement_InsertData1_P.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4441930/CreateProcessElement_InsertData1_P.xlsx)
[CreateProcessElement_InsertData1_E.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4441931/CreateProcessElement_InsertData1_E.xlsx)

**Comment by raju-kurup** [comment]
[MFG Live Uploaded File_Jyoti.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6824285/MFG.Live.Uploaded.File_Jyoti.zip)

Master data uploaded, so closing this ticket
