### ISSUE TITLE
MDU-Live Server Master Uploading - Sales & Shipping -JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#289]

**Comment by Manimahat** [comment]
@raju-kurup sir,

We have completed the Uploading process For GMBH OU. So please close this ticket.

Customer Master: [01_JCIPL_Customer Master-21JJuly2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5658467/01_JCIPL_Customer.Master-21JJuly2020.xlsx)

Customer Group: [01_JCIPL_Customer.Group.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5658469/01_JCIPL_Customer.Group.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
