### ISSUE TITLE
MDU-Live Server Master Uploading - Finance - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#290]

**Comment by basha123456** [comment]
COA uploaded for 331 accounts. for remaining accounts RSH clarification mail sent to joshi.
uploaded file:

**Comment by AkashGleen** [comment]
@raju-kurup Sir,

MFG OU Master Data Uploaded in Live Server Kindly Check the File & Move on Nxt Level

[MFG Live Uploaded File.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6820995/MFG.Live.Uploaded.File.zip)

Regards,
Akash

**Comment by raju-kurup** [comment]
[MFG Live Uploaded File_Jyoti.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6824279/MFG.Live.Uploaded.File_Jyoti.zip)

Master data uploaded, so closing this ticket
