### ISSUE TITLE
MDU-Live Server Master Uploading - Fixed Asset - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#291]

**Comment by Dhanwandher** [comment]
Dear Team...

Upload of Fixed completed...

[Validation_MFG fixed assets.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5619755/Validation_MFG.fixed.assets.xlsx)

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
