### ISSUE TITLE
MDU-Live Server Master Uploading - EAM - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#292]

**Comment by Manimahat** [comment]
@raju-kurup Sir,

EAM Uploading Completed for mfg ou. Please close this ticket.

EAM Location & Machine : [EAM MASTERS12MAY20.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5790188/EAM.MASTERS12MAY20.xlsx)

Planning group: [Planninng Group - as per UAT.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5790189/Planninng.Group.-.as.per.UAT.xlsx)

Work Group: [Work group - as per UAT.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5790190/Work.group.-.as.per.UAT.xlsx)

EAM Main Tool :[02_MFG _OU_Live_Create Equipment.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5790191/02_MFG._OU_Live_Create.Equipment.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Being uploading done in live server, we are closing this ticket.
