### ISSUE TITLE
MDU-Live Server Master Uploading - TOOL - JCIPL_MFG_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#293]

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Uploading completed for Tool Management. Please close this ticket.

Uploaded File : [Tool.Data.from.sagar (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759898/Tool.Data.from.sagar.1.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
