### ISSUE TITLE
MDU-Live Server Master Uploading - Pur & Subcon  - JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#294]

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Purchase & subcontracting Uploading Completed for Ziecon OU. Please close this ticket.
Supplier Master: [01_Supplier_Master_17-12-20-MFG_.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759916/01_Supplier_Master_17-12-20-MFG_.xlsx)
Supplier Group:[01_SupplierGroup - Revise3_18DEC2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759917/01_SupplierGroup.-.Revise3_18DEC2020.xlsx)
Supplier TCD:[TCD.Master.Data.-.To.Customer.07.05.2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759921/TCD.Master.Data.-.To.Customer.07.05.2020.xlsx)
Supplier payterm: [01_JCIPL_Create.Payterm_1.to.39-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759923/01_JCIPL_Create.Payterm_1.to.39-C.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
