### ISSUE TITLE
MDU-Live Server Master Uploading - Sales & Shipping -JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#297]

**Comment by Manimahat** [comment]
@raju-kurup sir,

Ziecon OU don't have customer.I have Attached the Mail Screen Shot for your reference.

Mail Screen Shot :  ![image](https://user-images.githubusercontent.com/55881685/87149095-3adf0500-c2cd-11ea-87d9-0b64f3f038cc.png)

So we are procced to close this Ticket

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Master data uploaded, so closing this issue
