### ISSUE TITLE
MDU-Live Server Master Uploading - Finance - JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#298]

**Comment by basha123456** [comment]
COA uploading for MFG & Ziecon is same as it is in same company.
so, we can close this ticket.

**Comment by AkashGleen** [comment]
@raju-kurup Sir,

ZIECON OU Master Data Uploaded in Live Server Kindly Check the File & Move on Nxt Level

[ZIECO Live Uploaded File.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6820981/ZIECO.Live.Uploaded.File.zip)

Regards,
Akash

**Comment by raju-kurup** [comment]
[ZIECON Live Uploaded File.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6824275/ZIECON.Live.Uploaded.File.zip)

Master data uploaded, so closing the ticket.
