### ISSUE TITLE
MDU-Live Server Master Uploading - Fixed Asset - JCIPL_ZIECON_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#299]

**Comment by Dhanwandher** [comment]
Dear Team...

Upload of Fixed completed...

[Validation_ZIECON.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5619750/Validation_ZIECON.xlsx)

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
