### ISSUE TITLE
PMO - Process Production Scenario Check - Tool Tracking -  Tool Production

### ISSUE THREAD

**Issue by Duraisingam-G** [astpl1998/Jyoti-Ceramic#30]

**Comment by basha123456** [comment]
Tool Tracking in Production Scenario Modelling is completed and it is explained to Development team(Karthi)
Tool Tracking Scenario Modelling : [Tool Tracking Scenario Modelling.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3385435/Tool.Tracking.Scenario.Modelling.xlsx)

**Comment by basha123456** [comment]
Tool Production Draft SDD document is given to Srini in #35 and the flowcharts also.
