### ISSUE TITLE
MDU-Live Server Master Uploading - Pur & Subcon  - JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#302]

**Comment by Manimahat** [comment]
@raju Sir,

MDC - Live Server Master Collection - purchase Completed for GmbH OU.

Supplier Data received from the User.

Supplier Domestic: [00_JCIPL_Supplier_Master_Domestic_1.to.849-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762314/00_JCIPL_Supplier_Master_Domestic_1.to.849-C.xlsx)

Supplier Import: [01_JCIPL_Supplier_Master_Imports_1.to.46-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762317/01_JCIPL_Supplier_Master_Imports_1.to.46-C.xlsx)

Supplier Group Domestic: [01_JCIPL_Domestic_Supplier.Group_1.to.22-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762319/01_JCIPL_Domestic_Supplier.Group_1.to.22-C.xlsx)

Supplier Group Import: [01_JCIPL_Imports_Supplier.Group_1.to.10-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762324/01_JCIPL_Imports_Supplier.Group_1.to.10-C.xlsx)

Payterm: [01_JCIPL_Create.Payterm_1.to.39-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762325/01_JCIPL_Create.Payterm_1.to.39-C.xlsx)

Supplier TCD code: [TCD.Master.Data.-.To.Customer.07.05.2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762327/TCD.Master.Data.-.To.Customer.07.05.2020.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Details attached.  So closing this ticket.

**Comment by Manimahat** [comment]
@raju-kurup Sir,

We closed this uploading ticket instead of collection. So we are-open this ticket.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

We closed this uploading ticket instead of collection. So we are-open this ticket.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

This is the new file Which Was given by jyoti. So we will upload below Updated File.

Supplier Master : [01_JCIPL_Supplier_Master_GmbH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5564345/01_JCIPL_Supplier_Master_GmbH.xlsx)

Supplier Group : [01_SupplierGroup -Gmbh.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5564347/01_SupplierGroup.-Gmbh.xlsx)

Payterm : [01_JCIPL_Create.Payterm_1.to.39-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5564350/01_JCIPL_Create.Payterm_1.to.39-C.xlsx)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Purchase & subcontracting Gmbh OU has been Completed. So please close this Ticket.

regards,
Manivel A

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
