### ISSUE TITLE
MDU-Live Server Master Uploading - Process Prod  - JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#304]

**Comment by sujin1708** [comment]
[CreateProcessElement_InsertData1_P.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4440363/CreateProcessElement_InsertData1_P.xlsx)
[CreateProcessElement_InsertData1_E.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4440366/CreateProcessElement_InsertData1_E.xlsx)
[CreateProcessElement_InsertData1_D.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4440369/CreateProcessElement_InsertData1_D.xlsx)
[Warehouse_Creation_MDCF.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4440372/Warehouse_Creation_MDCF.xlsx)

**Comment by raju-kurup** [comment]
In GmbH OU, there is no Process Production module, so closing this ticket
