### ISSUE TITLE
MDU-Live Server Master Uploading - Sales & Shipping -JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#305]

**Comment by Manimahat** [comment]
@raju-kurup Sir,

We have Completed the uploading Process. So please close this ticket.

Customer Master : [01_JCIPL_Customer.Master_GmbH_Updated. 26June2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5658451/01_JCIPL_Customer.Master_GmbH_Updated.26June2020.xlsx)

Customer Group : [01_JCIPL_Customer.Group - GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5658455/01_JCIPL_Customer.Group.-.GMBH.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
