### ISSUE TITLE
MDU-Live Server Master Uploading - Finance - JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#306]

**Comment by basha123456** [comment]
clarification mail sent to joshi for RSH.

**Comment by AkashGleen** [comment]
@raju-kurup 

Fixed Asset GMBH Uploaded Completed File 

[GMBH FA Workings.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6315613/GMBH.FA.Workings.xlsx)

**Comment by raju-kurup** [comment]
[GMBH Live Uplaoded File_Jyoti.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6824272/GMBH.Live.Uplaoded.File_Jyoti.zip)

Master data uploaded, so closing this ticket.
