### ISSUE TITLE
MDU-Live Server Master Uploading - Fixed Asset - JC_GmbH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#307]

**Comment by Dhanwandher** [comment]
Dear Team...

Upload of Fixed completed...
[Validation of GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5619749/Validation.of.GMBH.xlsx)

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
