### ISSUE TITLE
PMO - Process Production Scenario Check - Rework Module

### ISSUE THREAD

**Issue by Duraisingam-G** [astpl1998/Jyoti-Ceramic#31]

**Comment by Duraisingam-G** [comment]
I have checked both "**Back Flushing With Confirmation" & "Hard Allocation Required From Production**", but Rejected Status Lot Not Showing in below activity.
User Defined Allocation.
Report Consumption

Back Flushing With Confirmation : 
Production Order : APO/1920/J007 (Kanam Server)

Hard Allocation Required From Production:
We already checked and addressed this issue to Ramco.

**Comment by srinivasanbaskaran** [comment]
Sir,

This is Duplicate ticket. Refer - #176 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
This is Duplicate ticket. Refer - #176
