### ISSUE TITLE
MDU-Live Server Master Uploading - Pur & Subcon  - UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#310]

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Purchase & subcontracting Uploading Completed for Unitech OU.Please Close this ticket.

Supplier Master: [01_Supplier_Master_17-12-20-MFG_.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759906/01_Supplier_Master_17-12-20-MFG_.xlsx)
Supplier group: [01_SupplierGroup - Revise3_18DEC2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759907/01_SupplierGroup.-.Revise3_18DEC2020.xlsx)
Supplier TCD:[TCD.Master.Data.-.To.Customer.07.05.2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759909/TCD.Master.Data.-.To.Customer.07.05.2020.xlsx)
Supplier Payterm:[01_JCIPL_Create.Payterm_1.to.39-C.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5759910/01_JCIPL_Create.Payterm_1.to.39-C.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
