### ISSUE TITLE
MDU-Live Server Master Uploading - Process Prod  - UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#312]

**Comment by sujin1708** [comment]
[Warehouse_Creation_MDCF.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4440338/Warehouse_Creation_MDCF.xlsx)
[CreateProcessElement_InsertData1_P.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4440343/CreateProcessElement_InsertData1_P.xlsx)
[CreateProcessElement_InsertData1_E.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4440344/CreateProcessElement_InsertData1_E.xlsx)
[CreateProcessElement_InsertData1_D.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4440355/CreateProcessElement_InsertData1_D.xlsx)

**Comment by sujin1708** [comment]
Stages created in live server manually.

**Comment by raju-kurup** [comment]
Master created manually in Live Server

**Comment by srinivasanbaskaran** [comment]
Sujin,

Need to create the Process Stages in UNITECH OU. 

Please do the needful 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@sujin1708 

Process Stage,Operation and Unit Class have been created in UNITECH OU.
Kindly check.

Regards,
Faisal

**Comment by sujin1708** [comment]
@raju-kurup kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this tickets.
