### ISSUE TITLE
MDU-Live Server Master Uploading - Sales & Shipping -UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#313]

**Comment by Manimahat** [comment]
@raju-kurup sir,

Unitech OU have only one customer that's jyoti ceramic pvt Ltd. india. they will create this customer manually from their end.
I have Attached the Mail Screen Shot for your reference.

Mail Screen Shot :  ![image](https://user-images.githubusercontent.com/55881685/87149095-3adf0500-c2cd-11ea-87d9-0b64f3f038cc.png)

So we are proceed to close this Ticket

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Master data uploaded, so closing this ticket
