### ISSUE TITLE
MDU-Live Server Master Uploading - Finance - UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#314]

**Comment by basha123456** [comment]
120 accounts uploaded in COA. for remaining clarification mail sent to joshi

**Comment by sujin1708** [comment]
@AkashGleen update the sttaus and move to raju sir

**Comment by AkashGleen** [comment]
@raju-kurup Sir,

UNITECH OU Master Data Uploaded in Live Server Kindly Check the File & Move on Nxt Level

[UNITECH Live Uploaded.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6820967/UNITECH.Live.Uploaded.zip)

Regards,
Akash
