### ISSUE TITLE
MDU-Live Server Master Uploading - Fixed Asset - UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#315]

**Comment by Dhanwandher** [comment]
Dear Team...

Upload of Fixed completed...

[Validation of Unitech.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5619746/Validation.of.Unitech.xlsx)

**Comment by raju-kurup** [comment]
Being upload done in live server, closing this ticket
