### ISSUE TITLE
MDU-Live Server Master Uploading - EAM - UNITECH_OU

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#316]

**Comment by srinivasanbaskaran** [comment]
Team,

Faizal is working under the guidence of Srinivasan. KT given, Documents are shared. 

Regards,
Srinivasan

**Comment by Manimahat** [comment]
@raju-kurup Sir,

EAM Uploading is completed. Please Close this ticket.

Planning & work group:[Planninng Group - as per UAT.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5768275/Planninng.Group.-.as.per.UAT.xlsx)

Location & Equipment: [EAM MASTERS12MAY20.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5768280/EAM.MASTERS12MAY20.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Being uploading done in live server, we are closing this ticket.
