### ISSUE TITLE
PPD : Daily production summary/ rejection report stage wise-Extrusion

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#318]

**Comment by sujin1708** [comment]
[PFS.Daily  Production summary report_V1.2 - Extrusion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4445672/PFS.Daily.Production.summary.report_V1.2.-.Extrusion.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please start the development, test data will be given by sujin today

**Comment by GayuSri** [comment]
Design has been completed. Rtrack raised for deliverables. Rtrack id : JCIE-250

**Comment by GayuSri** [comment]
Kindly share the updated PFS.

**Comment by sujin1708** [comment]
@raju-kurup please find the updated PFS..kindly review
[PFS.Daily  Production summary report_V1.2 - Extrusion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4523270/PFS.Daily.Production.summary.report_V1.2.-.Extrusion.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Please do the correction as per the PFS. Test data is attached in PFS itself

**Comment by GayuSri** [comment]
Deign changes has been done. Rtrack raised for deliverables. Rtrack id : JCIE-264

**Comment by GayuSri** [comment]
@sujin1708 Development has been completed.

![image](https://user-images.githubusercontent.com/47743592/80865295-f9672380-8ca5-11ea-91b4-94bd20d8ca6b.png)

**Comment by sujin1708** [comment]
@gayathri values not fetching properly
![image](https://user-images.githubusercontent.com/47313592/80934151-77c9df80-8de4-11ea-9abe-b556ac953a18.png)

**Comment by GayuSri** [comment]
@sujin1708  Kindly mention which values are coming wrong and also share the test data for that.

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Test data attached and sujin send the test data to Gayathri by skype also, please allocate to Gayathri
[PFS.Daily  Production summary report_V1.2 - Extrusion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4574219/PFS.Daily.Production.summary.report_V1.2.-.Extrusion.xlsx)

**Comment by GayuSri** [comment]
@sujin1708 

Issues have been resolved. Kindly check.
![image](https://user-images.githubusercontent.com/47743592/80962272-60154a00-8e2a-11ea-8b58-1c72aa988586.png)
[Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4574384/Report.pdf)

Thanks & Regards,
Gayathri P

**Comment by sujin1708** [comment]
@raju sir opening balance for green stage & Drying oven stage value fetching wrong

item description not fetching

[PFS.Daily  Production summary report_V1.2 - Extrusion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4584902/PFS.Daily.Production.summary.report_V1.2.-.Extrusion.xlsx)

![image](https://user-images.githubusercontent.com/47313592/81140459-0bd3ac80-8f87-11ea-8a27-7c01e4e685dc.png)

**Comment by raju-kurup** [comment]
@sujin1708 : As discussed in meeting you do the testing.

**Comment by sujin1708** [comment]
[Test Result_Extrusion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4594717/Test.Result_Extrusion.xlsx)
[PFS.Daily  Production summary report_V1.2 - Extrusion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4594721/PFS.Daily.Production.summary.report_V1.2.-.Extrusion.xlsx)

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly Start Testing 2 & Prepare the Testing Documents

Regards,
Srinivasan

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly Start Testing 2 & Prepare the Testing Documents

Regards,
Srinivasan

**Comment by basha123456** [comment]
Keeping this report on Hold as it in Awaited status from Customer end.

**Comment by basha123456** [comment]
@GayuSri 

Values are not coming correctly. attached test data & output. please check & resolve.
[Daily production summary - Extrusion - system output.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4746256/Daily.production.summary.-.Extrusion.-.system.output.xlsx)
[PFS.Daily.Production.summary.report_V1.2.-.Extrusion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4746258/PFS.Daily.Production.summary.report_V1.2.-.Extrusion.xlsx)
for test data refer sheet TD in the PFS file.

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction highlighted in yellow colour.  Test data is attached.  If test data is matched then transfer it to functional team for testing

**Comment by Jeyapriyat** [comment]
@sujin1708 

kindly provide the data for 2nd Rejection and 3rd Rejection column.

**Comment by sujin1708** [comment]
PO NO : E/PO/20-21/0043

**Comment by Jeyapriyat** [comment]
@sujin1708 
issue solved ,kindly check and revert.
i have attached latest deliverables and sample output.
[daily prod sum rej rpt stage rise ext - deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4798967/daily.prod.sum.rej.rpt.stage.rise.ext.-.deliverables.zip)
[daily prod sum rej rpt stage rise ext sample output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4798970/daily.prod.sum.rej.rpt.stage.rise.ext.sample.output.pdf)

**Comment by sujin1708** [comment]
@Jeyapriyat green production data not fetching
![image](https://user-images.githubusercontent.com/47313592/85248903-db30cf00-b46f-11ea-8c46-52a471aa06ee.png)

**Comment by Jeyapriyat** [comment]
@sujin1708 
green production value fetching .kinldy check and revert.
i have attached sample output .
[sample output 24-6-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4824517/sample.output.24-6-2020.pdf)

**Comment by sujin1708** [comment]
@Jeyapriyat values not fetching properly Check the EXDO_PS value
![image](https://user-images.githubusercontent.com/47313592/85812056-484ca900-b77d-11ea-8efc-8717d3f9e62b.png)

![image](https://user-images.githubusercontent.com/47313592/85812081-58fd1f00-b77d-11ea-9fe8-90216a8bc174.png)

**Comment by Jeyapriyat** [comment]
@sujin1708 
 EXDO_PS value fetching ,kindly check and revert.
latest deliverables and sample output attached.
[daily prod sum rej rpt stage rise ext - deli 29-6-2020.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4844021/daily.prod.sum.rej.rpt.stage.rise.ext.-.deli.29-6-2020.zip)
[sample output 29-6-2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4844023/sample.output.29-6-2020.pdf)

**Comment by sujin1708** [comment]
@srinivasanbaskaran 
Testing 2 complted.kindly check and move to next level
[Extrusion Test Result2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4846285/Extrusion.Test.Result2.pdf)

**Comment by srinivasanbaskaran** [comment]
Sir,

Daily Production Summary / Rejection Report - Extrusion testing has been completed. Herewith, I have attached the Testing Documents for future references

PFS: [PFS.Daily.Production.summary.report_V1.2_Extrusion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4885946/PFS.Daily.Production.summary.report_V1.2_Extrusion.xlsx)

DELIVERABLES: [daily.prod.sum.rej.rpt.stage.rise.ext.-.deli.29-6-2020.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4885947/daily.prod.sum.rej.rpt.stage.rise.ext.-.deli.29-6-2020.zip)

TESTCASE 1: [Extrusion_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4885949/Extrusion_TestCase1.xlsx)

TEST RESULT 1: [Test.Result_Extrusion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4885950/Test.Result_Extrusion.xlsx)

TESTCASE 2: [Extrusion_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4885957/Extrusion_TestCase2.xlsx)

TEST RESULT 2: [Extrusion.Test.Result2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4885951/Extrusion.Test.Result2.pdf)

**Comment by sujin1708** [comment]
@Jeyapriyat values not fetching properly for Extrusion please check on high priority

Date : 07.09.2020
![image](https://user-images.githubusercontent.com/47313592/92433647-50808600-f1bb-11ea-85de-fa4fb3a467a9.png)

**Comment by GayuSri** [comment]
Dear Sujin,

Reported issues has been resolved. Kindly check and revert back.

Sample output has been attached and also latest deliverable (sp) has been attached below.

[result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5202827/result.pdf)
[jcurtdpse_genera_grd1_gr.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5202833/jcurtdpse_genera_grd1_gr.zip)

**Comment by eafaisal** [comment]
@GayuSri 

Values are not fetched in Firing stage.
Please check.

Test Data : 
[test_data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5259212/test_data.xlsx)

Test Result : 
[test_result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5259214/test_result.pdf)

Regards,
Faisal

**Comment by GayuSri** [comment]
@eafaisal Changes has been done. Kindly check and revert back.

**Comment by eafaisal** [comment]
@GayuSri 

There is negative value coming in opening balance in In Furnace stage.(-3600).
Kindly check.

Test Result : 
[test_data.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5286416/test_data.pdf)

Regards,
Faisal

**Comment by GayuSri** [comment]
Kindly share the full test data.

Thanks & Regards,
Gayathri P

**Comment by eafaisal** [comment]
@GayuSri 

Please find the test data and result attached.

Test Data : 
[test_data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5286557/test_data.xlsx)

Test Result : 
[test_result.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5286563/test_result.pdf)

Regards,
Faisal

**Comment by sujin1708** [comment]
@raju-kurup please find  the attached revised pfs for your reference 
 [PFS.Daily  Production summary report_V1.3 - Extrusion.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5382578/PFS.Daily.Production.summary.report_V1.3.-.Extrusion.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per the PFS and Gayathri has done this report

**Comment by GayuSri** [comment]
@sujin1708 
Kindly attach full test data (for all columns).

**Comment by GayuSri** [comment]
@sujin1708 Changes have been done. Kindly check.
Sample output and latest deliverable have been attached here.
[Latest Deliverable_v1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5621143/Latest.Deliverable_v1.0.zip)
[sample output-extrusion.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5621144/sample.output-extrusion.pdf)

**Comment by GayuSri** [comment]
Latest Develiverables.
[Latest Deliverable_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5629056/Latest.Deliverable_v1.1.zip)

**Comment by GayuSri** [comment]
Latest Deliverables.
[Latest Deliverable_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5646649/Latest.Deliverable_v1.2.zip)

**Comment by sujin1708** [comment]
Testing 1 completed 

Test Result : [Extrusion Test Result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5650316/Extrusion.Test.Result.xlsx)

**Comment by sujin1708** [comment]
@Manimahat kindly do the testing2

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 2 completed. Please find the attached document for reference.

Test Case : [Extrusion_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5658297/Extrusion_TestCase2.xlsx)

Test Result : [Extrusion.Test.Result2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5658300/Extrusion.Test.Result2.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@GayuSri as discuss with jyoti team they want see the unitech stock in that report

![image](https://user-images.githubusercontent.com/47313592/101975288-4f9b3c80-3c61-11eb-9fe9-57e730ea23ed.png)

**Comment by GayuSri** [comment]
@sujin1708 Changes has been done. Kindly check and revert back.
Latest deliverables and sample output have been attached here.
[Latest Deliverable_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5719459/Latest.Deliverable_v1.3.zip)
[sample output.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5719462/sample.output.zip)

Thanks & Regards,
Gayathri P

**Comment by sujin1708** [comment]
@karthikeyanamitysoft Kindly deploy this in live server

**Comment by sujin1708** [comment]
@Nandhineedevi kindly deploy the report in live

**Comment by Nandhineedevi** [comment]
Completed moving into Live Server.

[Extrusion.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6607188/Extrusion.zip)

**Comment by raju-kurup** [comment]
Deployed in live server, so closing this ticket

**Comment by raju-kurup** [comment]
Check in live server and change the status

**Comment by sujin1708** [comment]
@raju-kurup Deployment Completed.Kindly Close the ticket

**Comment by raju-kurup** [comment]
Deployment Completed.Kindly Close the ticket
