### ISSUE TITLE
PMO - Inter Plant Transfer From WIP Modelling & Inter Company Transfer From WIP Modelling

### ISSUE THREAD

**Issue by Duraisingam-G** [astpl1998/Jyoti-Ceramic#32]

**Comment by astpl1998** [comment]
DueDate:<flask_table.columns.Col object at 0x00000164A0D209E8>
Remarks:<flask_table.columns.Col object at 0x00000164A0FA3B00>

**Comment by srinivasanbaskaran** [comment]
Sir,

This is Duplicate. Refer - #172 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
This is Duplicate. Refer - #172
