### ISSUE TITLE
PPD : Daily production summary/ rejection report stage wise-Dental

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#320]

**Comment by sujin1708** [comment]
[PFS.Daily  Production summary report_V1.2 - Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4445649/PFS.Daily.Production.summary.report_V1.2.-.Dental.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the development

**Comment by Narendiranath** [comment]
Hi Badam,

  DW design is completed. Report name is daily_prod_sum_rpt_dental. Kindly check.

**Comment by badamnarendra028** [comment]
kindly update pfs

**Comment by sujin1708** [comment]
@raju-kurup please find the attached pfs ..kindly review
[PFS.Daily  Production summary report_V1.2 - Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4533785/PFS.Daily.Production.summary.report_V1.2.-.Dental.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per PFS and test data attached in PFS itself

**Comment by badamnarendra028** [comment]
JCIE-269 rtrack raised

**Comment by badamnarendra028** [comment]
[dental.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4588030/dental.pdf)
completed kindly check

**Comment by sujin1708** [comment]
@badamnarendra028 values fetching wrong
![image](https://user-images.githubusercontent.com/47313592/81590796-0805b700-93d9-11ea-945c-81b93d1aec91.png)

**Comment by badamnarendra028** [comment]
[dental_pdf.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4689979/dental_pdf.pdf)
completd kindly check

**Comment by basha123456** [comment]
@badamnarendra028 

badam values are not fetching correctly. please correct.
[dental output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4705615/dental.output.pdf)
[PFS.Daily.Production.summary.report_V1.2.-.Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4705616/PFS.Daily.Production.summary.report_V1.2.-.Dental.xlsx)

**Comment by badamnarendra028** [comment]
completed check and revert

**Comment by sujin1708** [comment]
@srinivasanbaskaran Testing1 completed..kinldy move to testing next level
[Dental Test Result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4816474/Dental.Test.Result.xlsx)

**Comment by badamnarendra028** [comment]
[jcie-297 (2).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4901333/jcie-297.2.zip)

**Comment by srinivasanbaskaran** [comment]
@Sujin,

Kindly update the Testcase

**Comment by sujin1708** [comment]
@srinivasanbaskaran testing2 completed kindly move to next level
[Test Result _Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4938183/Test.Result._Dental.xlsx)
[PFS.Daily  Production summary report_V1.2 - Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4938195/PFS.Daily.Production.summary.report_V1.2.-.Dental.xlsx)
[TestCase - Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4938202/TestCase.-.Dental.xlsx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Daily Production Summary / Rejection Report - Dental report testing has been completed. Herewith I have attached the Testing documents for future references. 

PFS: [PFS.Daily  Production summary report_V1.2 - Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4938195/PFS.Daily.Production.summary.report_V1.2.-.Dental.xlsx)

DELIVERABLES: [jcie-297.2 (2).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4941457/jcie-297.2.2.zip)

TESTCASE1 & TEST RESULT1: [Dental.Test.Result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4941456/Dental.Test.Result.xlsx)

TESTCASE2: [TestCase - Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4938202/TestCase.-.Dental.xlsx)

TEST RESULT2 : [Test Result _Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4938183/Test.Result._Dental.xlsx)

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
Customer give feedback for values  mismatching

**Comment by Manimahat** [comment]
@AkashGleen ,

Kindly Start Testing 1 Prepare Test case as per our Format.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 Completed. Kindly check your side whether the values correct or not.

Test Case : [test Data for Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5236472/test.Data.for.Dental.xlsx)

Test Result : [Test Result for Dental Division.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5236475/Test.Result.for.Dental.Division.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@raju-kurup Please Find the attached revised PFS for your refernece..kindly review and move to next level
PFS : [PFS.Daily  Production summary report_V1.3 - Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5426806/PFS.Daily.Production.summary.report_V1.3.-.Dental.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as mentioned  in PFS.  contact sujin for more clarification

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per the PFS and contact sujin for more clarification.

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The report is completed. Kindly check and revert back.

[dpsr_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5547229/dpsr_v2.1.zip)

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
Testing 1 completed ..kindly do the testing 2

Test Result :[Test Result Dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5626769/Test.Result.Dental.xlsx)

**Comment by sujin1708** [comment]
@karthikeyanamitysoft Need to interchange one coloumn in summary-dental report

![image](https://user-images.githubusercontent.com/47313592/101443793-371ae180-3944-11eb-8637-c403189cff8e.png)

**Comment by Nandhineedevi** [comment]
completed

[dental.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5707317/dental.xlsx)
[dpsr_v2.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5707319/dpsr_v2.3.zip)

**Comment by sujin1708** [comment]
@AkashGleen kindly do the testing 1

**Comment by AkashGleen** [comment]
Dear Sujin 

Daily Production Summary / rejection report stage wise-dental Testing 1 Completed Kindly Check.

[Test Result v1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5747224/Test.Result.v1.pdf)

Regards,
Akash

**Comment by sujin1708** [comment]
@karthikeyanamitysoft kindly attach the lastest deliverables which is deployed in live

**Comment by sujin1708** [comment]
@Nandhineedevi kindly deploy the report in live

**Comment by Nandhineedevi** [comment]
Completed moving into Live Server.

[dpsr.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6606845/dpsr.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployment Completed .Kindly Close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
