### ISSUE TITLE
PPD : Daily production summary/ rejection report stage wise-Coating

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#321]

**Comment by sujin1708** [comment]
[PFS.Daily  Production summary report_V1.2 - Coating.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4445749/PFS.Daily.Production.summary.report_V1.2.-.Coating.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop this report, test case will be submitted by Sujin today

**Comment by karthikeyanamitysoft** [comment]
Dear Naren,

Kindly check with Badam and do the report.
Regards,
Karthi

**Comment by badamnarendra028** [comment]
completed kindly check and update me

**Comment by sujin1708** [comment]
Hold ..once completed press shop & exturiosn & sand & dental ..we ill take it as a last

**Comment by sujin1708** [comment]
@raju-kurup please find the attched PFS for your reference..kindly review
PFS : [PFS.Daily  Production summary report_V1.2 - Coating.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4666370/PFS.Daily.Production.summary.report_V1.2.-.Coating.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Test case and test data attached in this ticket as requested by Badam.. So please allocate to badam.

**Comment by badamnarendra028** [comment]
completed kindly check
[coating.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4694760/coating.pdf)

**Comment by basha123456** [comment]
@badamnarendra028 

1.In the Input screen, remove the Process Stage combo & Description.
2. In the report format remove the fields Green stock ist shift,Green stock iind shift,Green stock iiird shift.
3.Apply the logic of the formula correctly( refer data in the PFS).
4. please correct the Allignment also.

[PFS.Daily.Production.summary.report_V1.2.-.Coating.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4705364/PFS.Daily.Production.summary.report_V1.2.-.Coating.xlsx)

**Comment by badamnarendra028** [comment]
completed check and revert

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 Completed. Kindly Start Testing 2 Process.

Test Case : [Product Wise Dily Production Summary Coating.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4820959/Product.Wise.Dily.Production.Summary.Coating.xlsx)

Test Result : [Product Wise Daily Summary Coating Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4820961/Product.Wise.Daily.Summary.Coating.Report.pdf)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@sujin1708,

Please Start the Testing 2 Process

Regards,
Manivel A

**Comment by sujin1708** [comment]
@badamnarendra028 values not caluclating properly
![image](https://user-images.githubusercontent.com/47313592/85646308-7963a580-b6b9-11ea-88dc-d5bb5cfc2cfc.png)

**Comment by badamnarendra028** [comment]
[jcie-297 (2).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4901331/jcie-297.2.zip)

**Comment by sujin1708** [comment]
@srinivasan testing1 completed ..kindly check and move to next level

**Comment by srinivasanbaskaran** [comment]
Sujin,

Kindly start Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Daily Production Summary / Rejection Report - Coating testing has been completed. Herewith I have attached the Testing documents for the future references.

PFS: [PFS.Daily  Production summary report_V1.2 - Coating.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4922970/PFS.Daily.Production.summary.report_V1.2.-.Coating.xlsx)

DELIVERABLES: [jcie-297.2_Coating.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4929322/jcie-297.2_Coating.zip)

TESTCASE1: [Product Wise Dily Production Summary Coating.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4820959/Product.Wise.Dily.Production.Summary.Coating.xlsx)

TEST RESULT1: [Product Wise Daily Summary Coating Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4820961/Product.Wise.Daily.Summary.Coating.Report.pdf)

TESTCASE2: [Coating_TestCase.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4922963/Coating_TestCase.xlsx)

TEST RESULT2: [coating.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4922958/coating.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sujin,

Kindly get the clarification from Jyoti

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@raju-kurup Please Find the Attached Revised PFS for your refernce..
PFS : [PFS.Daily  Production summary report_V1.3 - Coating.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5427029/PFS.Daily.Production.summary.report_V1.3.-.Coating.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per the PFS and contact sujin for more clarification.

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The report is completed. Kindly check and revert back.

[dpsr_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5547229/dpsr_v2.1.zip)

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
Testing 1 completed

Test Result : [Coating Test Result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5620336/Coating.Test.Result.xlsx)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 2 Completed. please find the attached document for your reference.

Test case : 
[Coating_TestCase.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5658263/Coating_TestCase.xlsx)

Test Result: [coating.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5658264/coating.xlsx)

Regards,
Manivel A

**Comment by sujin1708** [comment]
Daily Production Summary / Rejection Report - Coating testing has been completed. Herewith I have attached the Testing documents for the future references.
PFS : [PFS.Daily.Production.summary.report_V1.2.-.Coating.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5682414/PFS.Daily.Production.summary.report_V1.2.-.Coating.xlsx)
Test Case : [Coating_TestCase.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5682416/Coating_TestCase.xlsx)
Test Result : [Coating.Test.Result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5682417/Coating.Test.Result.xlsx)

**Comment by sujin1708** [comment]
to be deploy in live server

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by karthikeyanamitysoft** [comment]
Dear Nandhinee,

Kindly move the deliverables into live server.

Regards,
Karthi

**Comment by sujin1708** [comment]
@Nandhineedevi Kindly update the status

**Comment by Nandhineedevi** [comment]
Completed moving into Live Server.

[dpsr.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6606845/dpsr.zip)

**Comment by sujin1708** [comment]
@raju-kurup Report Deployed Kindly Close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
