### ISSUE TITLE
IMP - Master Data Collection - ZIECON

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#322]
IMP - Master Data Collection - ZIECON

**Comment by Manimahat** [comment]
@raju-kurup sir,

There is no data provided for For Ziecon OU. If they need, they will copy Whichever data they need from MFG OU. Please close this ticket

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Being copying done from MFG OU, so closing this tickets.
