### ISSUE TITLE
IMP - Opening Balance Sign Off_Live Server - All OU's

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#323]
IMP - Opening Balance Sign Off - All OU's
--

**Comment by Manimahat** [comment]
@raju-kurup Sir,

All OU opening Balance Uploaded in All OU With customer Confirmation. please Find the file for your ref. please close this ticket

All OU file : [Openeing Balance For All OU.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6820389/Openeing.Balance.For.All.OU.zip)

![image](https://user-images.githubusercontent.com/55881685/125729672-ee7f7a7a-220b-4271-8a06-89d77ce06891.png)

![image](https://user-images.githubusercontent.com/55881685/125729687-cfe5b81e-d866-4320-84cb-edfca881a12a.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Opening balance uploaded and tested by Jyoti and starting creating transaction, so closing this tickets.
