### ISSUE TITLE
S&S : Hide Rate / Amount in reference Document 

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#324]
Team,

Need to create the Rtrack ticket for this requirements by the User

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@team 

Rtrack raised JCIE-321 on 04/09/2020 for the Hide rate / amount in the Reference document in Production order.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Ramco Provide Solution for the Above Mentioned Rtrack JCIE-321. Please find the Below Screen shot for your ref... So Please close this Ticket.

![image](https://user-images.githubusercontent.com/55881685/130394540-bb2f6a29-7f80-4081-884a-647b1dd08f94.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Ramco commented to update Service pack.
