### ISSUE TITLE
I&P : Restrict Import Export Data from Multiline 

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#325]
Team,

Need to raise a Rtrack for this requirements by the User

JCIE-272

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup sir,

Ramco provided their comment in the Ticket like " This is feature cannot be accommodated in the product. However, you could restrict the save task in task privilege in deployment". So please close this point.

Ramco commented image : 
![image](https://user-images.githubusercontent.com/55881685/125936325-878f4f33-07d4-4f89-981c-6be634880a1f.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Ramco has given their comment, so closing this ticket
