### ISSUE TITLE
I&P : Item Type wise User Wise access control 

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#326]
Dear Team,

Need to raise the Rtrack for this requirements by the User

JCIE-274

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup sir,

Ramco provided their comment in the Ticket like " This requirement cannot be accommodated in the product. Request you to take it up as customisation if required for the customer". So please close this point.

Ramco comment image : 
![image](https://user-images.githubusercontent.com/55881685/125935950-6d5e37f0-6200-4e5a-a58f-8331cd7b09c5.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Closing this issue as mentioned by Ramco
