### ISSUE TITLE
QLT : QC Request Number to be generated automatically based on the Division wise

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#327]
Dear Team,

QC Request Number to be generated automatically based on the Division wise .. Need to raise a Rtrack for this requirements 

JCIE-275

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup sir,

Ramco Provided the comment Like "This Requirement cannot be accommodated in the Product. Please close this point.

Ramco comment image : 
![image](https://user-images.githubusercontent.com/55881685/125935825-96724946-b6a2-4b13-99e8-ae6cf5b795be.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Ramco has given the solution "This requirement cannot be accommodated in the product"
