### ISSUE TITLE
S&S : Customer Name in Sales order list multiline

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#328]
Dear Team,

Customer   Name in Sales order list multiline [in blank search unable to predict which   So is of Which party]

Need to raise rtrack for this requirment

JCIE - 276

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup sir,

Customer name is included in the SO search screen in the multi line feature ramco developed & packaged in Res 6.2 version. released in april 2021.

Ramco commented Image : ![image](https://user-images.githubusercontent.com/55881685/125818380-aaa20f35-b02e-472c-93ad-6675bf57a911.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
After updating CU this facility will be fetched in search screen
