### ISSUE TITLE
PPD : Lot Number Logic based on Batch Code

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#329]
Dear Team,

Customer asking that, Lot Number logic ( Stage wise )  based on Stage Based Reporting Automation screen.

Customer given the confirmation through mail. 

Sujin needs to work on this

**Comment by sujin1708** [comment]
@raju-kurup Please Find the Attched PFS ..Kindly Review
[PFS. Lot No Logic -Batch Wise V1.0 -.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4695542/PFS.Lot.No.Logic.-Batch.Wise.V1.0.-.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please correct the Lot No logic and Sujin will contact you . Take this in priority

**Comment by karthikeyanamitysoft** [comment]
[pajsbr_jsbr_c_jsbr_g_gr.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4774859/pajsbr_jsbr_c_jsbr_g_gr.zip)
lot no logic completed..
REgards,
Karthi

**Comment by sujin1708** [comment]
@srinivasanbaskaran  Testing1 Completed .kindly move to next level

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly Start the Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2 completed.
[Lot.No.Test.Result2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4786449/Lot.No.Test.Result2.xlsx)

**Comment by srinivasanbaskaran** [comment]
Sir,

Lot Number Logic based on Batch Code testing has been completed. Herewith I have attached for the future references.

PFS: [PFS.Lot.No.Logic.-Batch.Wise.v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4791221/PFS.Lot.No.Logic.-Batch.Wise.v1.0.xlsx)

DELIVERABLES: [pajsbr_jsbr_c_jsbr_g_gr.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4791226/pajsbr_jsbr_c_jsbr_g_gr.zip)

TESTCASE1 & TEST RESULT1: [Lot.No.Test.Result1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4791229/Lot.No.Test.Result1.xlsx)

TESTCASE2 & TEST RESULT2: [Lot.No.Test.Result2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4791231/Lot.No.Test.Result2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customr gave the Confirmation to MOVE this point to GREEN. 

So, Kindly proceed furhter to close this ticket

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer Approved, so closing this ticket

**Comment by sujin1708** [comment]
kindly deploy in live server

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by karthikeyanamitysoft** [comment]
Completed deliverables attached with
[Uploading automation.zip…]()

**Comment by sujin1708** [comment]
@raju-kurup Deployed in live server ..kindly  close the ticket

**Comment by raju-kurup** [comment]
Being this automation is deployed in live server, so closing this ticket.
