### ISSUE TITLE
FIN-Process Document for Finance

### ISSUE THREAD

**Issue by Dhanwandher** [astpl1998/Jyoti-Ceramic#330]
Dear Team...

Need to prepare process document for Finance...

Regards.
S.Dhanwandher....

**Comment by Dhanwandher** [comment]
Dear Team....

Finance process document completed.....

Regards.
S.Dhanwandher.
[Process Document for Masters.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4901092/Process.Document.for.Masters.xlsx)
[Process Document for payables.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4901093/Process.Document.for.payables.xlsx)
[Process Document for recivables.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4901096/Process.Document.for.recivables.xlsx)

**Comment by srinivasanbaskaran** [comment]
Dhanwandher,

Please add the below points in the master document.

1. ARD 
2. COA 
3. Bank Cash Definition
4. Exchange Rate
5. NOTES ( Standard Notes )
6. Reason Definition
7. Quick Codes
8. Finance Book Processing ( If Applicable )

**Comment by srinivasanbaskaran** [comment]
Dhanwandher,

Please correct the below points in AR & AP

1. Errors & Solutions should be provide
2. Credit & Debit Note should be clearly given

Regards,
Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Dear Team....

Finance process document completed.....

Regards.
S.Dhanwandher.
[Process Document for Masters.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4951761/Process.Document.for.Masters.xlsx)
[Process Document for payables.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4951763/Process.Document.for.payables.xlsx)
[Process Document for recivables.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4951764/Process.Document.for.recivables.xlsx)

**Comment by raju-kurup** [comment]
Please send the document to Jyoti

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Process Document sent to jyoti at 23-07-2020

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Document send to Jyoti on 23.07.2020, so closing this ticket
