### ISSUE TITLE
S&S: Export Invoice with GST

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#331]
New scenario to be explore to jyoti

Export Invoice with GST ( Duty Payment Transaction )

Rtrack rsied for this. 

JCIE-302

**Comment by sujin1708** [comment]
@manivel kindly the explore this

**Comment by Manimahat** [comment]
@raju-kurup Sir,

We have configured Export invoice with GST (Duty Paid concept), User accepted As well deployed UAT & Live Server.

Duty Paid Transaction file : [Duty Paid Export.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6820468/Duty.Paid.Export.xlsx)
 
Regards,
Manivel A

**Comment by raju-kurup** [comment]
Document submitted to Jyoti, but confirmation not given. Anyhow we are closing this ticket.
