### ISSUE TITLE
S&S: Invoice to raised for IRAN & NEPAL in INR currency

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#332]
Team,

Invoice to raised   for IRAN & NEPAL in INR currency for the below mentioned Customer 

NEPAL - 14000050000
IRAN - 14000060000

**Comment by raju-kurup** [comment]
INR currency to be added in EXP ARD or Seperate Group for EXP_INR should be created and account code to be mapped in ARD.
