### ISSUE TITLE
PPD : Tool Trigger Stage base reporting validation

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#334]
@karthick please find the attachment 

[Tool Logic.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5564501/Tool.Logic.xlsx)

**Comment by Narendiranath** [comment]
Hi Sujin,

Development completed. Kindly check. PFA Latest Deliverable.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5566795/Deliverable.zip)

**Comment by sujin1708** [comment]
@Nandhineedevi kindly apply the logic in reporting screen

1. Loading   of tools in Stage based Reporting Screen --The tools Mapped in attach notes of process unit attach Notes will be fetched in Process Production --> Process production - Automation --> Stage Base reporting Multiple items --> Multi line Tool combo

**Comment by Nandhineedevi** [comment]
Hi Sujin,
I have handled only Tool combo logic in automation and trigger for PO creation tool updating.

[nand_po_create_tool_check_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5577768/nand_po_create_tool_check_v1.1.zip)

Regards
Nandhinee Devi

**Comment by sujin1708** [comment]
@manivel do the testing and prepare test document for tool validation

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 completed. kindly proceed testing 2 Process.

Test Case & Result : [Test Result - Tool Validation in proudction.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5708959/Test.Result.-.Tool.Validation.in.proudction.xlsx)

Regards,
Manivel A

**Comment by sujin1708** [comment]
Testing 2 completed ..customer agreed this logic its working fine 
PFS : [Test Result2 _Tool validation.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5718846/Test.Result2._Tool.validation.xlsx)
Deliverables : [nand_po_create_tool_check_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5718842/nand_po_create_tool_check_v1.1.zip)
Test Result 1 : [Test.Result.-.Tool.Validation.in.proudction.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5718843/Test.Result.-.Tool.Validation.in.proudction.xlsx)
Test Result 2 : 
[Test Result2 _Tool validation.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5718844/Test.Result2._Tool.validation.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server

**Comment by karthikeyanamitysoft** [comment]
Dear Naren, 

Get the latest deliverables from Nandhini and deploy it in live  server.

Regards,
Karthi

**Comment by Narendiranath** [comment]
Hi Sujin,

              Trigger deployed in live server. PFA Latest Deliverable.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5764196/Deliverable.zip)

**Comment by sujin1708** [comment]
deployment completed in live server kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live server so closing this ticket
