### ISSUE TITLE
S&S : Maintain Type Master-EDK

### ISSUE THREAD

**Issue by Manimahat** [astpl1998/Jyoti-Ceramic#336]
@raju-kurup Sir,

Need to be Deployed Maintain Type Master-EDK Screen in Live server. We do not have Ticket for this .

Please Refer below path : Sales & shipping --> Sales Master --> Maintain Type Master..

Regards,

Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server

**Comment by karthikeyanamitysoft** [comment]
Please check mani ticket will be there. Without ticket we will not work on New EDK screen.

We need to get the deliverables from GITHUB only..

REgards,
Karthi

**Comment by Narendiranath** [comment]
Hi,

             PFA Latest deliverables for your ref. Kindly check.

[Delivarables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6243815/Delivarables.zip)

**Comment by raju-kurup** [comment]
Taken this id in 65 itself
