### ISSUE TITLE
SMA - TOOL MANAGEMENT 

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#34]
![IMG_20190719_175003 1](https://user-images.githubusercontent.com/46194039/61534890-67f82f00-aa4e-11e9-8ebb-d810033df8e8.jpg)
![IMG_20190719_174924 1](https://user-images.githubusercontent.com/46194039/61534924-83633a00-aa4e-11e9-995a-61d1428ca29b.jpg)
![IMG_20190719_174906 1](https://user-images.githubusercontent.com/46194039/61534947-9970fa80-aa4e-11e9-8342-5c5e37bf9181.jpg)

**Comment by srinivasanbaskaran** [comment]
[SMA - Project Mgnt - Modeling Details.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3411210/SMA.-.Project.Mgnt.-.Modeling.Details.xlsx)

**Comment by basha123456** [comment]
Team,

Modeling has been completed.. And Scenario showcasing also completed.. 

Hence this ticket has been closed..
