### ISSUE TITLE
ISS : Packslip is not getting Issued due to Exchange Rate Process Parameter.

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#340]
While issuing Packslip is not getting Issued and throwing error of "Exchangerate type is not set in process params .. Set Exchange rate type to proceed"

![image](https://user-images.githubusercontent.com/38855314/132680364-7f4e0520-c4a3-480a-8658-1ed254a20e5d.png)

![image](https://user-images.githubusercontent.com/38855314/132680437-9cdef1e6-4f57-44e0-a341-bcaac2d61a8b.png)

**Comment by Narendiranath** [comment]
@raju-kurup Sir,

              Clarification given to you.

Regards,
Naren

**Comment by raju-kurup** [comment]
Issue resolved, so closing this ticket
