### ISSUE TITLE
IMP-SDD - TOOL MANAGEMENT 

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Jyoti-Ceramic#35]
SDD - Tool Management 

Basha,

Kindly update the SDD - Tool Management what ever you complete.. 

Regards,

Srinivasan Baskaran

**Comment by basha123456** [comment]
Srini,

PFA SDD for Tool management 

Tool management SDD : [JYOTI_SDD__Project Management_Ver 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3416788/JYOTI_SDD__Project.Management_Ver.1.0.docx)

**Comment by raju-kurup** [comment]
SDD issued waiting for Sign-off

**Comment by raju-kurup** [comment]
Please attach the latest SDD and close this issue

**Comment by maheshwaran-m** [comment]
Dear Sir,

Please find the attached updated Tool Management SDD for your reference.

Tool Management SDD : [02_JYOTI_SDD__Tool_Management_V1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3530203/02_JYOTI_SDD__Tool_Management_V1.1.docx)

Thanks and Regards,
M.Maheshwaran.
