### ISSUE TITLE
IMP-SDD-Process Production

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#36]
kindly create the SDD for Jyoti process production

**Comment by sujin1708** [comment]
SDD : [JCIPL_SDD__Process Production Ver_1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3477629/JCIPL_SDD__Process.Production.Ver_1.1.zip)

**Comment by raju-kurup** [comment]
SDD issued waiting for Sign-off

**Comment by raju-kurup** [comment]
Please attach the latest SDD version and close the issue

**Comment by sujin1708** [comment]
[JCIPL_SDD__Process Production Ver_1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3537411/JCIPL_SDD__Process.Production.Ver_1.2.zip)
