### ISSUE TITLE
IMP-Master Data Collection For UAT Server

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#37]
Master data collection for UAT & LIVE server

**Comment by maheshwaran-m** [comment]
Team ,

Purchase and Sub contracting , Inventory and PICC, Quality Management, Sales and shipping MDCF training has been completed.

Thanks and Regards,
M.Maheshwaran.

**Comment by maheshwaran-m** [comment]
Duplicate ticket. Ticket has been closed
