### ISSUE TITLE
P&S : Item based Consumption Report

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#39]
Dear Karthi,

Please find the attached **Item based Consumption_PFS V 1.0** for your reference.

PFS :

Note : Prabakaran Pls Attach PFS.

Thanks and Regards,
M.Maheshwaran

**Comment by Prabakaran92** [comment]
Dear Karthi,

Please find the attached Item based Consumption_PFS V 1.0 for your reference.
[01_JCIPL_Item Based Consuption report_PFS V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3549853/01_JCIPL_Item.Based.Consuption.report_PFS.V.1.0.xlsx)

Regards,
Prabakaran A

**Comment by maheshwaran-m** [comment]
Report Not required.
