### ISSUE TITLE
P&S : Insurance Report (Against PO Value)-Dcube

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#40]
Dear Karthi,

Please find the attached **Insurance Report_PFS V 1.0** for your reference.

**PFS :**[01_JCIPL_Insurance Report_PFS V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3544511/01_JCIPL_Insurance.Report_PFS.V.1.0.xlsx)

Thanks and Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Dear Karthi,

Please find the attached updated Insurance Report_PFS V 1.0 for your reference.

PFS : [01_JCIPL_Insurance Report_PFS V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3590832/01_JCIPL_Insurance.Report_PFS.V.1.0.xlsx)

@raju-kurup sir : Kindly review Updated PFS.

Thanks and Regards,
M.Maheshwaran

**Comment by raju-kurup** [comment]
Dear Karthi, Please start the development

**Comment by karthikeyanamitysoft** [comment]
Dear Nandinee,

Kindly start the new Dcube report.
Regards,
Karthi

**Comment by Nandhineedevi** [comment]
Hi Maheshwaran,
The report development has been completed. Kindly check and revert back

Regards
Nandhinee Devi

[Insurance Report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3620292/Insurance.Report.zip)

**Comment by maheshwaran-m** [comment]
Sujin,

Kindly start Testing 1 Process as per the PFS.

Regards,
M.Maheshwaran

**Comment by sujin1708** [comment]
Testing 1 completed ..kindly check and move to next level
[Insurance Report use case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3626192/Insurance.Report.use.case.xlsx)
[Insurance Test data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3626211/Insurance.Test.data.xlsx)

**Comment by maheshwaran-m** [comment]
Raju sir,

> Testing one is completed Please find the Below Attached files for your reference.

**PFS :** [01_JCIPL_Insurance Report_PFS V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3626287/01_JCIPL_Insurance.Report_PFS.V.1.0.xlsx)
**USE CASE :** [Insurance Report use case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3626192/Insurance.Report.use.case.xlsx)
**TEST DATA :** [Insurance Test data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3626211/Insurance.Test.data.xlsx)
**Deliverable :** [Insurance Report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3620292/Insurance.Report.zip)


**Regards,**
M.Maheshwaran

**Comment by srinivasanbaskaran** [comment]
Hi,

Kindly start Test this report & Prepare the Test cases & Test Results 

Regards,

Srinivasan Baskaran

**Comment by Ugeshkumar16** [comment]
@srinivasanbaskaran 
herewith attached the details for reference.
[Insurance_Report Test case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3710645/Insurance_Report.Test.case.xlsx)
[Insurance Report po no 93.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3710646/Insurance.Report.po.no.93.pdf)

Thanks & Regards,
S.Ugeshkumar

**Comment by srinivasanbaskaran** [comment]
Mahesh,

Test Case 1 is not proper. Kindly correct the Test Case & Revert back

Regards,

Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 

Testing 1 completed,
Kindly start Testing 2.
Test case : [Insurance.Report.use.case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3732521/Insurance.Report.use.case.xlsx)
Test Result : [Test result_ins.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3732529/Test.result_ins.xlsx)

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Sir,

Transportation Cost Report for month basis report testing has been completed.

Testing documents are attached for future references.

PFS: [01_JCIPL_Insurance.Report_PFS.V.1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794290/01_JCIPL_Insurance.Report_PFS.V.1.0.xlsx)

DELIVERABLES: [Insurance.Report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3794294/Insurance.Report.zip)

TEST CASE 1: [Insurance.Report.Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794312/Insurance.Report.Testcase1.xlsx)

TEST RESULT 1: [Test.result_ins.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794306/Test.result_ins.xlsx)

TEST CASE 2: [Insurance_Report_Testcase.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794300/Insurance_Report_Testcase.xlsx)

TEST RESULT 2: [Insurance.Report.po.no.93_Test Result2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3794317/Insurance.Report.po.no.93_Test.Result2.pdf)

Regards,

Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Srinivasan,
Report is correct and small modification to be done will be taken after training.

**Comment by maheshwaran-m** [comment]
@srinivasanbaskaran 

This is Insurance report not Transportation cost report.

**Comment by srinivasanbaskaran** [comment]
@maheshwaran-m,

I know that.. Then only I tested this report & Closed this. 

Regards,

Srinivasan Baskaran

**Comment by maheshwaran-m** [comment]
What you mean? Still contend is not changed for your reference.

![image](https://user-images.githubusercontent.com/38855450/68129680-f7fbaf00-ff3f-11e9-98f1-c4167aee3f81.png)

**Comment by srinivasanbaskaran** [comment]
@Mahesh..

I changes that description ... 

Thanks for finding my mistake.

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Above correction will take up after Training.

Regards,

Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Prabha - Please raise PFS for modification given by customer

**Comment by maheshwaran-m** [comment]
Dear Team, 

Please find the below mentioned UAT changes on this report for your reference.

**1. Insurance Report :Data should be fetching Open and Closed status data.**

Regards,
M.Maheshwaran.

**Comment by Nandhineedevi** [comment]
Hi Mahesh,
The UAT changes has been completed. Kindly check and revert back.

[generate_insurance_report_pop_v1.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4015080/generate_insurance_report_pop_v1.4.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Insurence Report for month basis report testing has been completed.

Testing documents are attached for future references.

PFS: [01_JCIPL_Insurance.Report_PFS.v_1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4029946/01_JCIPL_Insurance.Report_PFS.v_1.1.xlsx)

DELIVERABLES: [generate_insurance_report_pop_v1.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4029949/generate_insurance_report_pop_v1.4.zip)

TEST CASE 1: [Insurance.Report.Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794312/Insurance.Report.Testcase1.xlsx)

TEST RESULT 1: [Test.result_ins.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794306/Test.result_ins.xlsx)

TEST CASE 2: [Testcase2_Insurance_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4029975/Testcase2_Insurance_Report.xlsx)

TEST RESULT 2: [Test Result_2_Insurance Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4029978/Test.Result_2_Insurance.Report.xlsx)

Regards,

Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed so closing this ticket

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly show this Report & Close the Development from ourside

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly update the logic in this report & Close this development 

Regards,
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
This report Customer Accepted But some Changes Required From customer side
Point : 
1.Insured Amount Should sum of 10% .
2.PO Line No Field Not Needed Kindly Remove this field.

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly review the above changes & Assigned to the Developers.

Regards,
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@raju-kurup 
Kindly allocate to Developer 
Correction 
1.Insured Amount Should sum of 10% .
2.PO Line No Field Not Needed Kindly Remove this field.

Updated PFS : [01_JCIPL_Insurance.Report_PFS.v_1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4291092/01_JCIPL_Insurance.Report_PFS.v_1.2.xlsx)

Regards,
Prabakaran A

**Comment by raju-kurup** [comment]
Please do the correction (2 Nos)

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Testing 1 completed 
1.Insured Amount sum of 10% .
2.PO Line No Field Removed this field.
Kindly check and close this report 

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly updatet the Latest Deliverables 

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the attached deliverables.

[generate_insurance_report_pop_v1.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4323160/generate_insurance_report_pop_v1.5.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Insurance Report Testing has been completed. Herewith I have attached some Testing documents for future references

PFS: [01_JCIPL_Insurance.Report_PFS.v_1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334603/01_JCIPL_Insurance.Report_PFS.v_1.2.xlsx)

DELIVERABLES: [generate_insurance_report_pop_v1.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4334604/generate_insurance_report_pop_v1.5.zip)

PATH: Tools --> Drill Down --> Inquiries ( Insurance Report )

TESTCASE1: [Insurance_Report_Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334610/Insurance_Report_Testcase1.xlsx)

TEST RESULT1: [Insurance.Report.use.case (3).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334612/Insurance.Report.use.case.3.xlsx)

TESTCASE2: [Testcase2_Insurance_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334620/Testcase2_Insurance_Report.xlsx)

TEST RESULT2: [Test Result2_Insurance Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334625/Test.Result2_Insurance.Report_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Testing 2 completed, so closing this ticket

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Report Showing Total amount is Wrong ( Declare Amount ). So we re-open this ticket.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

I thoroughly Checked All the Points , Only Declaring amount Value is Wrong. Please Find the Excel sheet for your Reference. 
Kindly Allocated to developers .

Report : [Insurance PO Report Value.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5167202/Insurance.PO.Report.Value.xlsx)

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
completed.

[insurance.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5173154/insurance.xlsx)
[generate_insurance_report_pop_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5173155/generate_insurance_report_pop_v2.1.zip)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 completed. Kindly start the Testing 2 Process.

Test case : [Testcase1_Insurance_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5177505/Testcase1_Insurance_Report.xlsx)

Test Result : [insurance.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5177506/insurance.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start Testing 2 & Prepare the Testing Document

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Srinivasan will do Testing2

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 2 Completed. Herewith I have attached the Testing Documents 

TESTCASE2: [Testcase2_Insurance_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5196200/Testcase2_Insurance_Report.xlsx)

TEST RESULT2: [Test Result2_Insurance Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5196203/Test.Result2_Insurance.Report.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Insurance Report Against PO Value Report testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [01_JCIPL_Insurance.Report_PFS_V_1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5196225/01_JCIPL_Insurance.Report_PFS_V_1.2.xlsx)

DELIVERABLES: [generate_insurance_report_pop_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5196228/generate_insurance_report_pop_v2.1.zip)

TESTCASE1: [Testcase1_Insurance_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5177505/Testcase1_Insurance_Report.xlsx)

TEST RESULT1: [insurance.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5177506/insurance.xlsx)


TESTCASE2: [Testcase2_Insurance_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5196200/Testcase2_Insurance_Report.xlsx)

TEST RESULT2: [Test Result2_Insurance Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5196203/Test.Result2_Insurance.Report.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer given clearance, so closing this ticket

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Need to deploy this Report In Live Server.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by karthikeyanamitysoft** [comment]
Dear Gayatri,
kindly move the deliverables into live server and Do the dcube design.

Regards,
Karthi

**Comment by mohanaamity** [comment]
@Manimahat 

Deployment completed in live serever.
[Insurance report(Against PO value).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5790512/Insurance.report.Against.PO.value.zip)

Regards,
Mohana B

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Insurance Report deployed Successfully in Live server. Please close this ticket.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
