### ISSUE TITLE
P&S : Daily Communication Report-Dcube

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#41]
Dear Karthi,

Please find the attached **Daily Communication Report_PFS V 1.0** for your reference.

**PFS :**[01_JCIPL_Daily communication Report_PFS V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3544504/01_JCIPL_Daily.communication.Report_PFS.V.1.0.xlsx)

Thanks and Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Dear Karthi,

Please find the attached updated Daily Communication Report_PFS V 1.0 for your reference.

PFS : [01_JCIPL_Daily communication Report_PFS V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3590864/01_JCIPL_Daily.communication.Report_PFS.V.1.0.xlsx)

@raju-kurup  sir : Kindly review updated PFS

Thanks and Regards,
M.Maheshwaran

**Comment by raju-kurup** [comment]
Dear Karthi,  Please start the development.

**Comment by karthikeyanamitysoft** [comment]
Dear Arunachalam,

Kindly start new Dcube report.
Regards,
Karthi

**Comment by Arunachalamamitysoft** [comment]
Dear  Mahesh,
 Development is completed,kindly check and revert it back.

**Comment by Arunachalamamitysoft** [comment]
[Daily_communication_rpt_v1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3619754/Daily_communication_rpt_v1.0.zip)
updated sp_V1.0

**Comment by maheshwaran-m** [comment]
Prabakaran,

Kindly start Testing 1 process as per the PFS.

Regards,
M.Maheshwaran

**Comment by Arunachalamamitysoft** [comment]
Dear prabhakaran ,
Development is completed ,kindly provide test data and revert it back and also kindly update the PFS.

**Comment by Prabakaran92** [comment]
@Arunachalamamitysoft 

Ref Doc : Plz use **Report format Ref Sheet** as the PFS.
[01_JCIPL_Daily.communication.Report_PFS.V.1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3650787/01_JCIPL_Daily.communication.Report_PFS.V.1.0.xlsx)

Regards,
Prabakaran A

**Comment by maheshwaran-m** [comment]
Dear Arunachalam,

Please find the updated Daily communication report PFS V 1.3 for your reference.

PFS : [04_JCIPL_Daily Communication.Report_PFS V.1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3661209/04_JCIPL_Daily.Communication.Report_PFS.V.1.3.xlsx)

regards,
M.Maheshwaran

**Comment by Arunachalamamitysoft** [comment]
Dear prabakaran,
                   Development is completed. kindly check and revert it back.

**Comment by Arunachalamamitysoft** [comment]
[Daily_communication_rpt_pop.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3675401/Daily_communication_rpt_pop.zip)

**Comment by Arunachalamamitysoft** [comment]
[Daily_communication_rpt_pop (2).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3675417/Daily_communication_rpt_pop.2.zip)
updated

**Comment by Prabakaran92** [comment]
Dear srini,

Testing1 completed ,
Kindly start Testing 2.

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Hi,

Kindly update the below deliverables.
   1. Testcase 1
   2. Testdata 1
   3. Test Result 1

Without the proper deliverables, report will not be processed further.

Regards,

Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@Arunachalamamitysoft 
As we discus this report Received material field not working.
Kindly check and revert.
Regards,
Prabakaran A

**Comment by Prabakaran92** [comment]
Dear Team ,
PFA
Test case : [Daily communication Test case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3710783/Daily.communication.Test.case.xlsx)
Test Result : [Test Result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3710795/Test.Result.xlsx)
Regards,
Prabakaran A

**Comment by maheshwaran-m** [comment]
Arunachalam,

Please find the updated Daily communication PFS V 1.4 for your reference.

PFS : [04_JCIPL_Daily Communication.Report_PFS V.1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3710994/04_JCIPL_Daily.Communication.Report_PFS.V.1.4.xlsx)

Regards,
M.Maheshwaran

**Comment by Arunachalamamitysoft** [comment]
Dear prabakaran,
                         Development is completed,kindly check and revert it back.

**Comment by Prabakaran92** [comment]
Dear srini,

Testing 1 completed.
kindly start testing 2,
PFA 

**PFS** : [04_JCIPL_Daily.Communication.Report_PFS.V.1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3715809/04_JCIPL_Daily.Communication.Report_PFS.V.1.4.xlsx)
**Test case** : [Daily communication Test case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3715810/Daily.communication.Test.case.xlsx)
**Test Result** : [Test Result Daily communication.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3715811/Test.Result.Daily.communication.xlsx)


Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Praba,

We are changing the Test Case doucments. You are uploading a older version Testcase document. 

Kindly check with Suressh sir & Raju sir. 

Regards,

Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
Dear srini ,
As we discuss about this format Issue.
Kindly start testing 2
Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Hi Praba,

In this report, Previous Cost & New Basic Cost are the 2 feilds that are not properly fetched

**Comment by Prabakaran92** [comment]
Dear srini,
Report working normally check and revert 

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Sir,

Daily Communication Report Testing has been completed.

Herewith I have attached Testing Documents for future references.

PFS: [04_JCIPL_Daily.Communication.Report_PFS.v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3809072/04_JCIPL_Daily.Communication.Report_PFS.v1.4.xlsx)

DELIVERABLES: [Daily_communication_rpt_pop.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3809077/Daily_communication_rpt_pop.2.zip)

TEST CASE 1: [Daily.communication.Test Case1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3809079/Daily.communication.Test.Case1.xlsx)

TEST RESULT 1: [Daily.communication.Test.case1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3809098/Daily.communication.Test.case1.xlsx)

TEST CASE 2: [Daily Communication Report_Test Case2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3809104/Daily.Communication.Report_Test.Case2.xlsx)

TEST RESULT 2: [Daily Communication Report_Test Result2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3809106/Daily.Communication.Report_Test.Result2.xlsx)

Regards,

Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Remarks column heading to be changed

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly do the above changes & Revert 

Regards,

Srinivasan Baskaran

**Comment by maheshwaran-m** [comment]
@Arunachalamamitysoft 
 Kindly move in this report from Dcube to below mentioned Path.
**Purchase and Subcontracting-->Purchase Reports-->Daily Communication Report**

Regards,
M.Maheshwaran

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Issue resolved check and revert.

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Sir,

Daily Communication Report Testing has been completed.

Herewith I have attached Testing Documents for future references.

PFS: [04_JCIPL_Daily.Communication.Report_PFS.v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3809072/04_JCIPL_Daily.Communication.Report_PFS.v1.4.xlsx)

DELIVERABLES: [Daily_communication_rpt_pop.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3809077/Daily_communication_rpt_pop.2.zip)

TEST CASE 1: [Daily.communication.Test Case1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3809079/Daily.communication.Test.Case1.xlsx)

TEST RESULT 1: [Daily Communication Report_Test Result1_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3818203/Daily.Communication.Report_Test.Result1_v1.1.xlsx)

TEST CASE 2: [Daily Communication Report_Test Case2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3809104/Daily.Communication.Report_Test.Case2.xlsx)

TEST RESULT 2: [Daily Communication Report_Test Result2_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3818200/Daily.Communication.Report_Test.Result2_v1.1.xlsx)

Regards,

Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@Arunachalamamitysoft 
Need add some new fields in this report.
Pls Refer The updated PFS.
**PFS** : [05_JCIPL_Daily.Communication.Report_PFS.v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3819331/05_JCIPL_Daily.Communication.Report_PFS.v1.5.xlsx)
Regards,
Prabakaran A

**Comment by raju-kurup** [comment]
Report was tested and shown to customer. Customer needs more input in this report. so it should be incorporated

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the below attached UAT changes points for your reference.

**1. Daily Communication Report - Date From and To Input filter Required, Inventory Issue, Issue Status, Document status should be added in End of the report.**

Thanks and Regards,
M.Maheshwaran

**Comment by srinivasanbaskaran** [comment]
Dear Team, 

Please Find the attached updated PFS.

PFS: 
[05_JCIPL_Daily.Communication.Report_PFS.v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4015101/05_JCIPL_Daily.Communication.Report_PFS.v1.6.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Arunachalamamitysoft** [comment]
@srinivasanbaskaran 
Development is completed,Kindly check and revert it back.

Thanks&Regards
Arunachalam

**Comment by srinivasanbaskaran** [comment]
Arun,

Changes reflected.. Report working fine 

Regards,
Srinivasan Baskaran

**Comment by Arunachalamamitysoft** [comment]
updated Deliverables
[Daily_communication_report_pop_final1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4018301/Daily_communication_report_pop_final1.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

Daily Communication Report correction completed. 

Herewith I have attached Testing Documents for future references.

PFS: [05_JCIPL_Daily.Communication.Report_PFS.v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4029256/05_JCIPL_Daily.Communication.Report_PFS.v1.6.xlsx)

DELIVERABLES: [Daily_communication_report_pop_final1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4029260/Daily_communication_report_pop_final1.zip)

TEST CASE 1: [Daily.communication.Test Case1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3809079/Daily.communication.Test.Case1.xlsx)

TEST RESULT 1: [Daily Communication Report_Test Result1_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3818203/Daily.Communication.Report_Test.Result1_v1.1.xlsx)

TEST CASE 2: [Daily Communication Report_Test Case2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4029787/Daily.Communication.Report_Test.Case2.xlsx)

TEST RESULT 2: [TestResult 2 - Daily Communication Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4029804/TestResult.2.-.Daily.Communication.Report.xlsx)

Regards,

Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed, so closing this ticket

**Comment by Arunachalamamitysoft** [comment]
updated deliverables,
[Daily_communication_report_updated_final2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4122027/Daily_communication_report_updated_final2.zip)

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly show this Report & Close the Development from ourside

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Daily Communication Report has been shown to the Users & They are Accepting this Report.

Kindly proceed further on this report.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and user accepted, so closing this ticket.

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly chage the logic of taking the Report as per the User Requirements

Regards,
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@raju-kurup 
Daily communication Report should launch pur_user (Purchase User) All users report
Currently MR generated user only launch .
Kindly check & Allocate.

Regards,
Prabakaran A

**Comment by karthikeyanamitysoft** [comment]
Dear Badham,
Kindly do the above changes.

Note: The report will load only the data which is created for the login user.
now need to if user is purchase user then no need to give the where condition
Regards,
Karthi

**Comment by badamnarendra028** [comment]
completed kindly check

**Comment by Prabakaran92** [comment]
@raju-kurup 
If Ramcouser report launch 42 records fetch
if inventory user report launch 42 records fetch but only 2 records different user
if purchase user report launch 18 records only fetch
Kindly check and allocate Development rework
Regards,
Prabakaran A

**Comment by raju-kurup** [comment]
Now as mentioned report is working fine.

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Testing 1 competed 
Kindly start testing 2 

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Sir,

Daily Communication Report correction completed. 

Herewith I have attached Testing Documents for future references.

PFS: [05_JCIPL_Daily.Communication.Report_PFS.v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4029256/05_JCIPL_Daily.Communication.Report_PFS.v1.6.xlsx)

DELIVERABLES: 

TEST CASE 1: [Daily.communication.Test Case1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3809079/Daily.communication.Test.Case1.xlsx)

TEST RESULT 1: [Daily Communication Report_Test Result1_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3818203/Daily.Communication.Report_Test.Result1_v1.1.xlsx)

TEST CASE 2: [Daily Communication Report_Test Case2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4345087/Daily.Communication.Report_Test.Case2.xlsx)

TEST RESULT 2: [TestResult 2 - Daily Communication Report_Updated.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4345097/TestResult.2.-.Daily.Communication.Report_Updated.xlsx)

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Badam,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[daily_comm.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4347290/daily_comm.zip)

**Comment by badamnarendra028** [comment]
updated

**Comment by srinivasanbaskaran** [comment]
Sir,

Daily Communication Report correction completed. 

Herewith I have attached Testing Documents for future references.

PFS: [05_JCIPL_Daily.Communication.Report_PFS.v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4029256/05_JCIPL_Daily.Communication.Report_PFS.v1.6.xlsx)

DELIVERABLES: [daily_comm.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4347651/daily_comm.zip)

TEST CASE 1: [Daily.communication.Test Case1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3809079/Daily.communication.Test.Case1.xlsx)

TEST RESULT 1: [Daily Communication Report_Test Result1_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3818203/Daily.Communication.Report_Test.Result1_v1.1.xlsx)

TEST CASE 2: [Daily Communication Report_Test Case2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4345087/Daily.Communication.Report_Test.Case2.xlsx)

TEST RESULT 2: [TestResult 2 - Daily Communication Report_Updated.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4345097/TestResult.2.-.Daily.Communication.Report_Updated.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed, so closing this issue

**Comment by raju-kurup** [comment]
Development completed, so closing this issue

**Comment by Manimahat** [comment]
@raju-kurup Sir,

In this Report All MR is not fetched for Both Purchase & inventory User. So we are re-open this Ticket

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

In this Report All MR information Is not Fetched for Purchase & Inventory User. Please allocated this ticket to Developers.

Actual Report : [grddyn (5).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5187532/grddyn.5.xlsx)

Base Excel MR Info : [Base MR File.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5187561/Base.MR.File.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
This report was done by Badam.  But now the desired data is not coming

**Comment by karthikeyanamitysoft** [comment]
The codition is already handled all mr will launch for the login user inv_user, pur_user, so please mention the MR Number which is not comming in the report.

**Comment by karthikeyanamitysoft** [comment]
as discussed with raju sir, kindly provide clarification,
mr no is not availables it will not reflect in the rport..

**Comment by Manimahat** [comment]
@karthikeyanamitysoft ,

All MR No Should Load in the Report. Just now User Confirmed this point.

Regards,
Manivel A

**Comment by badamnarendra028** [comment]
[daily_communication_10-09.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5208660/daily_communication_10-09.zip)
copmleted kindly check and revert

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 Completed. Kindly proceed Testing 2 process.

Test Case : [Daily.communication.Test.Case1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5214789/Daily.communication.Test.Case1.xlsx)

Test Result: [Test Result For Daily Communication Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5214790/Test.Result.For.Daily.Communication.Report.xlsx)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@eafaisal,

Kindly Start Testing 2 process & attached the document as per format.

Regards,
Manivel A

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Kindly check

Test Case : 
[Daily.communication.Test.Case2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5225539/Daily.communication.Test.Case2.xlsx)

Test Result : 
[Test.Result.For.Daily.Communication.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5225551/Test.Result.For.Daily.Communication.Report.xlsx)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

PFS: [05_JCIPL_Daily.Communication.Report_PFS.v1.7.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5243399/05_JCIPL_Daily.Communication.Report_PFS.v1.7.xlsx)

DELIVERABLES: [daily_communication_10-09.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5243397/daily_communication_10-09.zip)

Test Case1 : [Daily.communication.Test.Case1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5214789/Daily.communication.Test.Case1.xlsx)

Test Result1 : [Test Result For Daily Communication Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5214790/Test.Result.For.Daily.Communication.Report.xlsx)

Test Case2 : [Daily.communication.Test.Case2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5225539/Daily.communication.Test.Case2.xlsx)

Test Result2 : [Test.Result.For.Daily.Communication.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5225551/Test.Result.For.Daily.Communication.Report.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer given clearance, so closing this ticket

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Need to Deploy this Report in Live server. Please allocate to Developers.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.
--

**Comment by Jeyapriyat** [comment]
@Manimahat 
deployment completed in live server,kindly check and revert.

**Comment by Jeyapriyat** [comment]
> @Manimahat
> deployment completed in live server,kindly check and revert.
i have attached latest deliverables .
[deliverables-8-01-2021.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5794063/deliverables-8-01-2021.zip)

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Daily Communication Report deployed Successfully. Please close this ticket.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
