### ISSUE TITLE
P&S : Quotation Comparison Print Item wise-RDW

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#42]
Dear Karthi,

Please find the attached **Quotation Comparison Print Item wise_PFS V 1.0** for your Reference.

PFS : [01_JCIPL_Quotation Comparision PFS_V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3610187/01_JCIPL_Quotation.Comparision.PFS_V.1.0.xlsx)

Thanks and Regards,
M.Maheshwaran

**Comment by karthikeyanamitysoft** [comment]
hi magesh 

Kindly attach the PFS

Regards,
Karthi

**Comment by maheshwaran-m** [comment]
hi karthi,

attached above

**Comment by raju-kurup** [comment]
Dear Karthi - please start development

**Comment by karthikeyanamitysoft** [comment]
[Purchase_Quotation.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3624856/Purchase_Quotation.zip)
object got from kannam

**Comment by maheshwaran-m** [comment]
Nandinee,

Please find the attached Quotation Comparison PFS V 1.1 for your reference.

PFS :  [02_JCIPL_Quotation Comparision PFS_V 1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3715796/02_JCIPL_Quotation.Comparision.PFS_V.1.1.xlsx)

regards,
M.Maheshwaran

**Comment by Nandhineedevi** [comment]
Hi,
UDS screen is not launching, so I raised ticket for Racmo. 
Please find the ticket details below.

https://rtrack.ramco.com/browse/JCIE-35

Regards
Nandhinee Devi

![Eror](https://user-images.githubusercontent.com/52193780/66741080-50381780-ee92-11e9-8c62-1641d480990f.jpg)

**Comment by Nandhineedevi** [comment]
Hi Mahesh,
Kindly Clarify the below details.

1. Warranty on Report Print
2. Last purchase date and price.

Regards
Nandhinee Devi

**Comment by Nandhineedevi** [comment]
Hi Mahesh,
As we discussed, other than warranty, last purchase price and date field, I have completed the development. Kindly check and revert back.

Regards
Nandhinee devi

**Comment by Nandhineedevi** [comment]
Hi Mahesh,
Find the latest deliverables for your reference.

Regards
Nandhinee Devi

[Quotation Comparison Report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3792630/Quotation.Comparison.Report.zip)

**Comment by Prabakaran92** [comment]
Dear srini, 
Testing 1 completed.
Kindly start testing 2.
PFA
Test case : [Quotation comparison Test case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3797715/Quotation.comparison.Test.case.xlsx)
Test output : [Quotation Test Output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3797717/Quotation.Test.Output.pdf)
Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Sir,

Quotation Comparison Report Tested completely.
While provide the value for Warrentyfeild, Got the below error...
Warrenty Error: ![image](https://user-images.githubusercontent.com/46194039/68071664-8d613c80-fda2-11e9-92ac-35669aa57946.png)

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Quotation Comparison Report Testing completed.
Testing Documents are attached for future references.

PFS:[02_JCIPL_Quotation.Comparision.PFS_V.1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3800548/02_JCIPL_Quotation.Comparision.PFS_V.1.1.xlsx)

DELIVERABLES: [Quotation.Comparison.Report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3800549/Quotation.Comparison.Report.zip)

TESTCASE1: [Quotation.comparison.Test.case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3800550/Quotation.comparison.Test.case.xlsx)

TEST RESULT1: [Quotation.Test.Result1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3800553/Quotation.Test.Result1.pdf)

TESTCASE2: [Quotation Comparison_Test Case2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3800555/Quotation.Comparison_Test.Case2.xlsx)

TEST RESULT 2: [Quotation Comparison Report_Test Result2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3800556/Quotation.Comparison.Report_Test.Result2.pdf)

Regards,

Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and comparism is coming for 3 supplier in 1 page

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Below points are not fetching the Values. Please Check & Correct the same.

1. Previuos Purchase Price
2. Previuos Purchase Date

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

[ptnkqcr_k_prin_grd1_gr_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4121567/ptnkqcr_k_prin_grd1_gr_v1.2.zip)

Regards
Nandhinee Devi

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The Rework has been completed. Kindly check and revert back.

[Kanam_QCR_v1.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4142264/Kanam_QCR_v1.4.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

Quotation Comparison Print Testing has been completed.

Testing Documents are attached for the future references.

PFS: [02_JCIPL_Quotation.Comparision.PFS_v 1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4143661/02_JCIPL_Quotation.Comparision.PFS_v.1.2.xlsx)

DELIVERABLES: [JYOTI_QCR_v1.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4143663/JYOTI_QCR_v1.4.zip)

TESTCASE 1:

TEST RESULT 1:

TESTCASE 2:

TEST RESULT 2: [Purchase Quotation Comparison_02_02_2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4143664/Purchase.Quotation.Comparison_02_02_2020.pdf)


Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly show this Report &  Close the Development from ourside

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Please do the below mentioned correction & Revert 

1. Warrenty Field to be Manual Entry 
2. Payterm Description to be fetched instead of Payterm code

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The corrections has been completed. Kindly check and revert back.

[Kanam_QCR_v1.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4184335/Kanam_QCR_v1.5.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

Quotation Comparison Print Testing has been completed.

Testing Documents are attached for the future references.

PFS: [02_JCIPL_Quotation.Comparision.PFS_v 1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4143661/02_JCIPL_Quotation.Comparision.PFS_v.1.2.xlsx)

DELIVERABLES: [Kanam_QCR_v1.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4184618/Kanam_QCR_v1.5.zip)

TESTCASE :

TEST RESULT 2: [Purchase Quotation Comparison_11_02_2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4184615/Purchase.Quotation.Comparison_11_02_2020.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We are shown this report to the Users. They were accepted.

Kindly proceed further in this report.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and user accepted, so closing this ticket

**Comment by raju-kurup** [comment]
please remove the waranty lable in top portion

**Comment by raju-kurup** [comment]
due to warranty field to be removed

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Testing 1 completed 
kindly check and close.

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Final Testing Need to be done 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee, 

Kindly update the Latest Deliverables 

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the attached deliverables.

[quotation_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4323269/quotation_v2.1.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

Quotation Comparison Print Testing has been completed.

Testing Documents are attached for the future references.

PFS: [02_JCIPL_Quotation.Comparision.PFS_v 1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4143661/02_JCIPL_Quotation.Comparision.PFS_v.1.2.xlsx)

DELIVERABLES: [quotation_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4334591/quotation_v2.1.zip)

TESTCASE 2: [Quotation Comparison_Test Case2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334589/Quotation.Comparison_Test.Case2.xlsx)

TEST RESULT 2: [Purchase Quotation Comparison_02_02_2020.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4143664/Purchase.Quotation.Comparison_02_02_2020.pdf)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Testing 2 completed, so closing this ticket

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Need to Deploy this Report in Live Server. Please Allocate to Developers.

**Comment by Nandhineedevi** [comment]
@Narendiranath 
DW Report Name: quotation_comparison_report

Kindly Move only the DW Report from UAT to Live Server.
All Back end and Front end Deployment had been completed.
Latest Deliverable has been attached below.

[Live_import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5918575/Live_import.zip)

**Comment by Narendiranath** [comment]
Hi Manivel,

         DW Report deployed in live server. Kindly check. PFA Latest Deliverables for your ref.

[Dw_ER_03Feb2021235339.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5920664/Dw_ER_03Feb2021235339.zip)

**Comment by Manimahat** [comment]
@raju-kurup sir,

Report has been Deployed successfully. Kindly close this ticket.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
