### ISSUE TITLE
I&P : Returnable & Non Returnable Screen - EDK

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#43]
Raju sir,

Please find the attached **Updated** **Returnable & Non Returnable Screen and Print_PFS V 1.0** for your Reference.

PFS : [01_JCIPL_RGP and NRGP_PFS_V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3631989/01_JCIPL_RGP.and.NRGP_PFS_V.1.0.xlsx)

Thanks and Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Raju sir,

Pls find the above attached updated RGP/NRGP PFS. Kindly Review and Proceed further.

Regards,
M.Maheshwaran

**Comment by raju-kurup** [comment]
PFS Reviewed, please proceed further for development

**Comment by maheshwaran-m** [comment]
Ezhil,

Please find the attached Updated Returnable & Non Returnable Screen and Print_PFS V 1.1 for your Reference.

PFS : [02_JCIPL_RGP and NRGP_PFS_V 1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3651874/02_JCIPL_RGP.and.NRGP_PFS_V.1.1.xlsx)

Thanks and Regards,
M.Maheshwaran

**Comment by karthikeyanamitysoft** [comment]
issue resolved edk screen fetching

**Comment by karthikeyanamitysoft** [comment]
Dear nandini kindly start the coding sp writing.

Regards,
Karthi

**Comment by Nandhineedevi** [comment]
Hi Mahesh,
Kindly share the jyoti logo.

Regards
Nandhinee Devi

**Comment by maheshwaran-m** [comment]
Nandhinee,

Please find the attached Jyoti Logo for your reference.

Jyoti Logo : ![Jyoti Logo final-01 CMYK-01](https://user-images.githubusercontent.com/38855450/66808498-fe05fd80-ef48-11e9-9c56-ab24bc06eb49.jpg)

**Comment by Nandhineedevi** [comment]
Hi Mahesh,
I have completed the Activity Create and Authorize RGP/NRGP. Kindly check and revert back.
There is ramco issue for other Two activity (Receipt and Return). 
Once Resolved I will let you know. 
Please find the deliverables attached below.

[Create and Authorize RGP and NRGP.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3804057/Create.and.Authorize.RGP.and.NRGP.zip)

Regards
Nandhinee Devi

**Comment by maheshwaran-m** [comment]
@srinivasanbaskaran 

Create RGP/NRGP  and Return RGP Smoke test, with reference document and without reference document testing has been completed.Check and Proceed further.

Regards,
M.Maheshwaran

**Comment by srinivasanbaskaran** [comment]
@maheshwaran-m

Kindly share the Testing 1 documents for the next level.

If its a smoke test also, need to update the Testing 1 documents.

Regards,
Srinivasan Baskaran

**Comment by maheshwaran-m** [comment]
@Nandhineedevi

Please find the attached Updated PFS for RGP/NRGP V 1.2 for your reference.

PFS : [02_JCIPL_RGP and NRGP_PFS_V 1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3844840/02_JCIPL_RGP.and.NRGP_PFS_V.1.2.xlsx)


Below points to be corrected in RGP/NRGP
1. Service item: HSN code & UOM should be fetch from Miscellaneous Item
2. Ref.Doc : Add Purchase Return and Sale Invoice
3. Receiver : Make Non Mandatory 

Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
@Nandhineedevi 

Any update?

**Comment by Nandhineedevi** [comment]
@maheshwaran-m 
I am going to start the RGP Receipt now, Once completed I will let you know.

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Updated Open Points 

Queries:
RGP   Scenario -  unitech NRGP

Scnerio checked.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly update the Latest deliverables 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

RGP / NRGP screen testing completed. Herewith, Testing documents are attached for future.

PFS: [02_JCIPL_RGP.and.NRGP_PFS_V.1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4087577/02_JCIPL_RGP.and.NRGP_PFS_V.1.2.xlsx)

NAVIGATION: Inventory & PICC --> Returnable / Non Returnable Pass --> Create RGP / NRGP

DELIVERABLES:

TESTCASE: [Returnable_Non_Returnable_Gate_Pass_Testcase.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4087583/Returnable_Non_Returnable_Gate_Pass_Testcase.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Kindly find the latest deliverables.

[RGP NRGP Deliverables v1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4089325/RGP.NRGP.Deliverables.v1.0.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

RGP / NRGP screen testing completed. Herewith, Testing documents are attached for future.

PFS: [02_JCIPL_RGP.and.NRGP_PFS_V.1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4087577/02_JCIPL_RGP.and.NRGP_PFS_V.1.2.xlsx)

NAVIGATION: Inventory & PICC --> Returnable / Non Returnable Pass --> Create RGP / NRGP

DELIVERABLES: [RGP.NRGP.Deliverables.v1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4089656/RGP.NRGP.Deliverables.v1.0.zip)

TESTCASE: [Returnable_Non_Returnable_Gate_Pass_Testcase.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4087583/Returnable_Non_Returnable_Gate_Pass_Testcase.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Holding for the Final documents

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

RGP / NRGP screen testing completed. Herewith, Testing documents are attached for future.

PFS: [02_JCIPL_RGP.and.NRGP_PFS_V.1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4087577/02_JCIPL_RGP.and.NRGP_PFS_V.1.2.xlsx)

NAVIGATION: Inventory & PICC --> Returnable / Non Returnable Pass --> Create RGP / NRGP

DELIVERABLES: [RGP.NRGP.Deliverables.v1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4089656/RGP.NRGP.Deliverables.v1.0.zip)

TESTCASE: [Returnable_Non_Returnable_Gate_Pass_Testcase.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4180474/Returnable_Non_Returnable_Gate_Pass_Testcase.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start Testing2 & Prepare the Testing Documents as per our format

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@raju-kurup 
Stage is not loading for production order reference doc.
![image](https://user-images.githubusercontent.com/47315921/77890018-6a24b580-728c-11ea-8f37-fa1863274096.png)

for other reference documents stage is loading
![image](https://user-images.githubusercontent.com/47315921/77890139-9fc99e80-728c-11ea-96d2-bf059cf5134c.png)
Please assign to developer sir

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : 1 correction to be done in this report, while clicking stage detail should appear when "Ref doc type : Process Production" only

At present Stage is not appearing for Process Production.

**Comment by mohanaamity** [comment]
Kindly check with new record.old records are deleted in base table

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2completed. documents attached.

Test case: [Returnable_Non_Returnable_Gate_Pass_Testcase.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4431743/Returnable_Non_Returnable_Gate_Pass_Testcase.xlsx)
Test Result: [RGP NRGP Test Result.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4431745/RGP.NRGP.Test.Result.docx)

**Comment by srinivasanbaskaran** [comment]
Srini have to do Testing 2

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 2 completed. 

Testcase2: [Returnable_Non_Returnable_Gate_Pass_Testcase_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4452309/Returnable_Non_Returnable_Gate_Pass_Testcase_v1.1.xlsx)

Test Result2: 

Regards,
Srinivasan

**Comment by srinivasanbaskaran** [comment]
@mohana,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan.B

**Comment by srinivasanbaskaran** [comment]
Team,

There is no changes in report. So, Existing Delvierables to be attached.

**Comment by srinivasanbaskaran** [comment]
Rajuj Sir,

RGP / NRGP screen testing completed. Herewith I have attached the Testing documents for future references.

PFS: [02_JCIPL_RGP.and.NRGP_PFS_V.1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4501285/02_JCIPL_RGP.and.NRGP_PFS_V.1.3.xlsx)

DELIVERABLES: [RGP.NRGP.Deliverables.v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4501305/RGP.NRGP.Deliverables.v1.1.zip)

TESTCASE 1: [Returnable_Non_Returnable_Gate_Pass_Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4501306/Returnable_Non_Returnable_Gate_Pass_Testcase1.xlsx)

TEST RESULT 1: [Test Result1_RGP_NRGP.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4501311/Test.Result1_RGP_NRGP.docx)

TESTCASE 2: [Returnable_Non_Returnable_Gate_Pass_Testcase_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4501312/Returnable_Non_Returnable_Gate_Pass_Testcase_v1.1.xlsx)

TEST RESULT 2: [Test Result2_RGP & NRGP.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4501313/Test.Result2_RGP.NRGP.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Re-Test again & Prepare the Testcase for All the OUs....

**Comment by srinivasanbaskaran** [comment]
Team,

Screen is properly working. So Testing 2 Completed.

**Comment by raju-kurup** [comment]
Development completed and tested., so closing this development

**Comment by Manimahat** [comment]
@raju-kurup Sir,

To be Deployed in this Screen in Live Server. Please Allocate to Developers.

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server

**Comment by Nandhineedevi** [comment]
Dear Naren, 
Kindly deploy the latest deliverables in Live Server.
I have deployed only JCIE-160 deliverables in Live Server Front End.

[JCIE-120.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5780458/JCIE-120.zip)
[JCIE-119.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5780468/JCIE-119.zip)
[JCIE-160.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5780478/JCIE-160.zip)

Regards
Nandhinee Devi

**Comment by Narendiranath** [comment]
Hi Manivel,

               RDW design deployed in live server. Kindly check. PFA Latest deliverable for your ref.

[Dw_ER_04Feb2021001913.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5969458/Dw_ER_04Feb2021001913.zip)

**Comment by Manimahat** [comment]
@raju-kurup sir,

EDK Screen has been Deployed successfully. Kindly close this ticket.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/AMITYS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/AMITYS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



43
--




</body>

</html>
