### ISSUE TITLE
INV : Raw Material Item wise Batch wise Stock report

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#44]
Dear Karthi,

Please find the attached **Raw Material Item wise Batch wise Stock report_PFS V 1.0** for your Reference.

PFS :

Thanks and Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Sujin,

Kindly Start PFS for raw material stock statement report batch wise.

Regards,
M.Maheshwaran.

**Comment by sujin1708** [comment]
As Discuss with report has been canceled..

**Comment by maheshwaran-m** [comment]
Report Not required . Ticket Has been closed
