### ISSUE TITLE
QLT : Quality Control Reports - UDS

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#45]
Dear Karthi,

Please find the attached **Quality Control Reports** for your Reference.

Thanks and Regards,
M.Maheshwaran

**Comment by srinivasanbaskaran** [comment]
Team,

Herewith, I have attached the PFS for the UDS screen for the Combined Reports. 

PFS: [01_Quality Control Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4142598/01_Quality.Control.Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Herewith I have attached the PFS for **Raw Material Test Report**. 

PFS: [01_Quality Control_Raw Material Inspection Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4142642/01_Quality.Control_Raw.Material.Inspection.Report_PFS_v1.0.xlsx)
 
Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Herewith I have attached the PFS for Receiving (Packing) Material Inspection Report

PFS: [01_Quality Receiving (Packing) Material Inspection Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4143558/01_Quality.Receiving.Packing.Material.Inspection.Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Please find the Updated PFS for Report UDS 

PFS: [00_Quality Control Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4167037/00_Quality.Control.Report_PFS_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Herewith I have attached the PFS for Raw Material Test Report.

PFS: [01_Quality Control_Raw Material Inspection Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4167165/01_Quality.Control_Raw.Material.Inspection.Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Kindly allocate this Report for Development

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Karthi,
Due to you absence I am allocating this EDK to Nandhinee.

**Comment by raju-kurup** [comment]
Dear Nandhinee,
Please start developing this EDK screen

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Kindly provide column level requirement and print format for Report.

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

If PRINT button is click means, Report will launch within the 7 reports 

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The 6 quality report development has been completed. Kindly check and revert back.
Please find the deliverables attached.

[jqcr_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4297589/jqcr_v1.1.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Quality Control Reports ( 6 Reports ) are developed & Tested completed. Herewith I have attached the Testing Documents for the future references.

PFS: [00_Quality Control Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4396585/00_Quality.Control.Report_PFS_v1.1.xlsx)

DELIVERABLES: [jqcr_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4396586/jqcr_v1.1.zip)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticket & Proceed further 

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed, so closing this issue
