### ISSUE TITLE
QLT : Shrinkage Report-RDW

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#46]
Dear Karthi,

Please find the attached **Spray Dried Batch Test Report_PFS V 1.0** for your Reference.

PFS :

Thanks and Regards,
M.Maheshwaran

**Comment by srinivasanbaskaran** [comment]
Hi Karthi,

Please find the PFS for Spary Dried Batch Test / Shrinkage Report.

Kindly start the DW Design & Will update the Column Level PFS later. 

Kindly do the needful

PFS: [01_Shrinkage_Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3994433/01_Shrinkage_Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Kindly update column level requirement in PFS, Then only I can start coding

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Please Find the Attched updated PFS & Kindly start the development 

Let me know if you have any doubts.

PFS: [01_Shrinkage_Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4022933/01_Shrinkage_Report_PFS_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Kindly update the path of the below data and test data

1. Green Date
2. Fired Date
3. Material

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Please find the below details. 

1. Green Date - User provide the Date in the UDS screen & Take the Print
2. Fired Date - User provide the Date in the UDS screen & Take the Print
3. Material - Data should fetched from Inventory & PICC --> Quality Mgnt --> View Inspection Request. Then refer Item Code field under Item detail tab

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Please find the updated PFS for Spary Dried Batch Test Report.

PFS: [01_Shrinkage_Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4033940/01_Shrinkage_Report_PFS_v1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The development has been completed. Kindly check and revert back.

[Shrinkage Report v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4044147/Shrinkage.Report.v1.1.zip)

Regards
Nandhinee Devi

**Comment by basha123456** [comment]
Srini,

need KT for this report.

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly the Create Attributes & Mapped to the Item code and then Test this Report.

File: [Attribute Needs to Create.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4090615/Attribute.Needs.to.Create.xlsx)

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Srini,

Above atributes are created.

please update the following codes in the PFS.

ISO.DIA - changed to ISO.DI due to length issue.

S.FINAL - changed to S.FNL due to length issue.(in diameter mm section)

In height(mm) section give any other code to S.FINAL . dont give S.FNL..

Testing1 is completed. PFA with the test data & test result.
[01_Shrinkage_Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4116166/01_Shrinkage_Report_PFS_v1.2.xlsx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Need to update the PRINT as per the Customer Requirements. 

On 16-02-2020 only, we received a format from Mr. Gaurav. 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

PFS updated as per the User Requirement. Kindly Review & Aloocate to Development.

PFS: [01_Shrinkage_Report_PFS_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4254355/01_Shrinkage_Report_PFS_v1.3.xlsx)

FORMULA: [Shrinkage Report - Fomula from Gaurav.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4254357/Shrinkage.Report.-.Fomula.from.Gaurav.docx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Karthi,
Please do the modification in this report and this should come in single A4 Sheet.  You can decrease the font as required.

**Comment by raju-kurup** [comment]
Please do the correction and contact Srinivasan for clarification

**Comment by badamnarendra028** [comment]
completed

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing & Prepare the Testing Documents as per our format.

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing 1 completed. found the following errors.

1. GRN No not fetched
2. Space unwanted came between the columns   and the multiline
3. In the multiline, lines are missing for   some columns
4. Data not fetched for shrinkage(%) green   to  pre fired, shrinkage(%) green   to  final fired in both height &   diameter. ISO pressed Dia.(mm) also.
5. Data not fetched in the column Pressure   kg/cm2

[01_Shrinkage_Report_PFS_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4298063/01_Shrinkage_Report_PFS_v1.3.xlsx)

**Comment by srinivasanbaskaran** [comment]
Basha,

If you found any errors, pls co-ordinates with Develpers & Correct that errors. 

Please follow this. I am assigning this report to you  & Proceed further.

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

For Pressure kg/cm2, It is stated as hard coded in PFS. 

The attribute description is not uniform, How I will filter for weight, height
example:-
Green Data **Weight** 
Final Fired **Wt**


![press](https://user-images.githubusercontent.com/52193780/76140770-aeed7000-6083-11ea-9e74-37d3b5a57160.jpg)

Regards
Nandhinee devi

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing after corrections

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 
Testing1 is completed...PFA of test result sheet
[01_Shrinkage_Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4312880/01_Shrinkage_Report_PFS_v1.2.xlsx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Below are the points to be corrected. 

1. Fired Date ( Pre-Fired & Final Fired )
2. Prepared By
3. Approved By
4. Density formula is wrongly calculated 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly Test & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly Start Testing2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

For your references, I have attached the Test Result 1. 

Test Result1: 
[Test_Result1_Shrinkage Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4378752/Test_Result1_Shrinkage.Report.pdf)

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2 completed. PFA

Test Case: [Test.Case.-.Shrinkage_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4380881/Test.Case.-.Shrinkage_Report.xlsx)
Test Result : [Shrinkage Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4380883/Shrinkage.Report.pdf)

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly attach the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Shrinkage Report Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [01_Shrinkage_Report_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389495/01_Shrinkage_Report_PFS_v1.6.xlsx)

FORMULA: [Shrinkage Report - Fomula_Srini_Workings.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389499/Shrinkage.Report.-.Fomula_Srini_Workings.docx)

PATH: Inventory & PICC --> Quality Managemet --> View Final Clearance Feedback Details 

DELIVERABLES: 

TESTCASE1: [Testcase1_Shrinkage_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389504/Testcase1_Shrinkage_Report.xlsx)

TEST RESULT1: [Test_Result1_Shrinkage Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4389506/Test_Result1_Shrinkage.Report.pdf)

TESTCASE2: [Testcase2_Shrinkage_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389508/Testcase2_Shrinkage_Report.xlsx)

TEST RESULT2: [Shrinkage.Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4389510/Shrinkage.Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The deliverables has been attached.

[SDBR_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4391505/SDBR_v1.2.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Shrinkage Report Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [01_Shrinkage_Report_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389495/01_Shrinkage_Report_PFS_v1.6.xlsx)

FORMULA: [Shrinkage Report - Fomula_Srini_Workings.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389499/Shrinkage.Report.-.Fomula_Srini_Workings.docx)

PATH: Inventory & PICC --> Quality Managemet --> View Final Clearance Feedback Details 

DELIVERABLES: [SDBR_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4391556/SDBR_v1.2.zip)

TESTCASE1: [Testcase1_Shrinkage_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389504/Testcase1_Shrinkage_Report.xlsx)

TEST RESULT1: [Test_Result1_Shrinkage Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4389506/Test_Result1_Shrinkage.Report.pdf)

TESTCASE2: [Testcase2_Shrinkage_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389508/Testcase2_Shrinkage_Report.xlsx)

TEST RESULT2: [Shrinkage.Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4389510/Shrinkage.Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the attached PFS as per the User's Requirements.

PFS: [01_Shrinkage_Report_PFS_v1.8.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4473411/01_Shrinkage_Report_PFS_v1.8.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@srinivasanbaskaran : we will wait for the confirmation from Mr. Deshmukh by mail and we will start the correction. And also please attach the test data along with PFS

**Comment by srinivasanbaskaran** [comment]
Team,

PFA of Latest Points 

![Shrinkage Report](https://user-images.githubusercontent.com/46194039/82190339-864ce680-990e-11ea-8ee6-e371a7e826f9.jpg)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : 3 points in report and 3 points in UDS to be changed which is highlighted in yellow colour in PFS.

**Comment by Nandhineedevi** [comment]
Rtrack raised for deliverables 
https://rtrack.ramco.com/browse/JCIE-278

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

[Sdbr_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4701563/Sdbr_v2.2.zip)
[shrink_test_output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4701566/shrink_test_output.pdf)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 1 Completed. Please find the attached Testing Documents 

TESTCASE1: [Testcase1_Shrinkage_Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4749992/Testcase1_Shrinkage_Report_v1.1.xlsx)

TEST RESULT1: 
[Test_Result1_Shrinkage Report_V1.1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4749994/Test_Result1_Shrinkage.Report_V1.1.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start Testing2 & Prepare the Testing Documents

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2 completed. 

[Test.Case.-.Shrinkage_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4750321/Test.Case.-.Shrinkage_Report.xlsx)
[Shrinkage report TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4750322/Shrinkage.report.TR.pdf)

**Comment by srinivasanbaskaran** [comment]
Sir,

Shrinkage Report Testing has been completed. Herewith I have attached Testing Documents for future references.

PFS: [01_Shrinkage_Report_PFS_v1.8.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762631/01_Shrinkage_Report_PFS_v1.8.xlsx)

DELIVERABLES: [Sdbr_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4762632/Sdbr_v2.2.zip)

TESTCASE1: [Testcase1_Shrinkage_Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762634/Testcase1_Shrinkage_Report_v1.1.xlsx)

TEST RESULT1: [Test_Result1_Shrinkage.Report_V1.1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4762636/Test_Result1_Shrinkage.Report_V1.1.pdf)

TESTCASE2: [Test.Case.-.Shrinkage_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4762637/Test.Case.-.Shrinkage_Report.xlsx)

TEST RESULT2: [Shrinkage.report.TR (1).pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4762638/Shrinkage.report.TR.1.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team, 

Sujin Need to update the PFS as per the Customer Requirements 

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@raju-kurup please find the updated pfs kinly review and move to next level
[01_Shrinkage_Report_PFS_v1.9.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5095945/01_Shrinkage_Report_PFS_v1.9.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the 1 correction as mentioned by PFS. Nandhinee has done this report and discussed about this.

**Comment by Nandhineedevi** [comment]
[mpqsdbr_sdbr_p_grd1_gr_v2.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5106855/mpqsdbr_sdbr_p_grd1_gr_v2.3.zip)
[shrinnk.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5106851/shrinnk.pdf)

**Comment by srinivasanbaskaran** [comment]
@Nandhineedevi ,

Please find the below screenshot .. Supplier Lot Number details are not fetched correctly.. 

![image](https://user-images.githubusercontent.com/46194039/91122549-3a050580-e6b8-11ea-8755-51b0b4624513.png)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Completed

[shrink1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5127825/shrink1.pdf)

[mpqsdbr_sdbr_p_grd1_gr_v2.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5127833/mpqsdbr_sdbr_p_grd1_gr_v2.4.zip)

**Comment by srinivasanbaskaran** [comment]
Team,

Shrinkage Report Testing Completed. Herewith I have attached the Testing Documents of the Testing 1. 

TESTCASE1: [Testcase1_Shrinkage_Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5188702/Testcase1_Shrinkage_Report_v1.2.xlsx)

TEST RESULT1: [Test_Result1_Shrinkage Report_V1.2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5188707/Test_Result1_Shrinkage.Report_V1.2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Report will have the Logic change of MATERIAL NAME. So, I HOLD this report testing 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start the Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srinivasanbaskaran,

Shrinkage Report Testing 2 Completed Kindly Check & Update.

[Testcase1_Shrinkage_Report_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5201372/Testcase1_Shrinkage_Report_v2.xlsx)

[Test Result For Shrinkage_Report v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5201373/Test.Result.For.Shrinkage_Report.v2.pdf)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Shrinkage Report Testing has been completed. Herewith I have attached the Testing Documents for the future references. 

PFS: 

DELIVERABLES: [mpqsdbr_sdbr_p_grd1_gr_v2.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5253648/mpqsdbr_sdbr_p_grd1_gr_v2.4.zip)

TESTCASE1: [Testcase1_Shrinkage_Report_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5188702/Testcase1_Shrinkage_Report_v1.2.xlsx)

TEST RESULT1: [Test_Result1_Shrinkage Report_V1.2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5188707/Test_Result1_Shrinkage.Report_V1.2.pdf)

TESTCASE2: [Testcase1_Shrinkage_Report_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5201372/Testcase1_Shrinkage_Report_v2.xlsx)

TEST RESULT2: [Test Result For Shrinkage_Report v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5201373/Test.Result.For.Shrinkage_Report.v2.pdf)

Regards,
Srinivasan Baskran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS as per the latest Requirements of the Customer. 

PFS: [01_Shrinkage_Report_PFS_v1.10.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5353085/01_Shrinkage_Report_PFS_v1.10.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as mentioned in PFS

**Comment by Nandhineedevi** [comment]
completed.

[p3.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5365252/p3.pdf)
[p1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5365253/p1.pdf)
[mpqsdbr_sdbr_p_grd1_gr_v2.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5365263/mpqsdbr_sdbr_p_grd1_gr_v2.5.zip)

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 1 Completed. Herewith I have attached the Testing Documents for the future references.

TESTCASE1: [Testcase1_Shrinkage_Report_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5369462/Testcase1_Shrinkage_Report_v1.3.xlsx)

TEST RESULT1: [Shrinkage Report_P3.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5369463/Shrinkage.Report_P3.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly Start Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@eafaisal 

Kindly Start Testing 2 & Prepare the Testing Documents

Regards,
Manivel A

**Comment by AkashGleen** [comment]
Dear Srinivasanbaskaran,

Shrinkage Report Testing 2 Completed Kindly Check & Update.

[Test Result For Shrinkage_Report v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5419903/Test.Result.For.Shrinkage_Report.v2.pdf)

[Testcase2_Shrinkage_Report_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5419904/Testcase2_Shrinkage_Report_v2.xlsx)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly update the Testcase & Test Result as we discussed

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srinivasanbaskaran,

Shrinkage Report Testing 2 Completed Kindly Check & Update.

[Test Result For Shrinkage Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5423201/Test.Result.For.Shrinkage.Report.pdf)

[Testcase2_Shrinkage_Report_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5423202/Testcase2_Shrinkage_Report_v2.xlsx)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Shrinkage Report testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [01_Shrinkage_Report_PFS_v1.10.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5423275/01_Shrinkage_Report_PFS_v1.10.xlsx)

DELIVERABLES: [mpqsdbr_sdbr_p_grd1_gr_v2.5.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5423290/mpqsdbr_sdbr_p_grd1_gr_v2.5.2.zip)

TESTCASE1: [Testcase1_Shrinkage_Report_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5369481/Testcase1_Shrinkage_Report_v1.3.xlsx)

TEST RESULT1: [Shrinkage Report_P3.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5369463/Shrinkage.Report_P3.pdf)

TESTCASE2: [Test Result For Shrinkage Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5423201/Test.Result.For.Shrinkage.Report.pdf)

TEST RESULT2: [Testcase2_Shrinkage_Report_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5423202/Testcase2_Shrinkage_Report_v2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer gave confirmation to move this report to GREEN on 18-10-2020 through mail confirmation.

Kindly proceed to close this report

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@raju-kurup plz close the ticket

**Comment by karthikeyanamitysoft** [comment]
Dear Nandhinee ,

Kindly deploy the latest deliverables into live server.

Regards,
Karthi

**Comment by Nandhineedevi** [comment]
Deployed in Live Server

[Live_import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5918691/Live_import.zip)

**Comment by Manimahat** [comment]
@raju-kurup sir,

Report has been Deployed successfully. Kindly close this ticket.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this tickets.
