### ISSUE TITLE
QLT : Machine Sample Inspection Report-RDW

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#47]
Dear Karthi,

Please find the attached **Machine Sample Inspection Report_PFS V 1.0** for your Reference.

PFS :

Thanks and Regards,
M.Maheshwaran

**Comment by srinivasanbaskaran** [comment]
Hi Karthi,

Please Find the Attached PFS for Machine Sample Report.

Kindly start the Design related work & Column level PFS will update later.

Please do the needful.

PFS: [Machine Sample Inspection Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3994459/Machine.Sample.Inspection.Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandinee,

Please Find the updated PFS ...

PFS: [Machine Sample Inspection Report_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3997330/Machine.Sample.Inspection.Report_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Please find the Update PFS for Machine Sample Inspection Report.

PFS: 
[Machine Sample Inspection Report_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4009487/Machine.Sample.Inspection.Report_PFS_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start Test this report & Prepare the Testing documents and revert 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Srini,

Testing1 is completed. Test case is attached. Test data is also given in the test data sheet.
[Machine sample inspection report - quality - Test Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4039232/Machine.sample.inspection.report.-.quality.-.Test.Case.xlsx)

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Please find the updated PFS for Machine Sample Inspection Report.

PFS: [Machine Sample Inspection Report_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4198347/Machine.Sample.Inspection.Report_PFS_v1.2.xlsx)

Please made the corrections & Revert

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Need to update the PFS as per the Customer Requirements 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

PFS updated as per the User Requirements. Kindly Review the PFS & Allocated to Development

PFS : [Machine Sample Inspection Report_PFS_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4254171/Machine.Sample.Inspection.Report_PFS_v1.3.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Karthi,
Change the format from landscape to portrait and give the maximum column possible.  Contact Srini for clarification

**Comment by raju-kurup** [comment]
Nandhinee - Please do the rework on this ticket

**Comment by raju-kurup** [comment]
Ezhil - please do the correction in this ticket

**Comment by srinivasanbaskaran** [comment]
Team,

Please Find the attached updated PFS. 

PFS: [Machine Sample Inspection Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4285266/Machine.Sample.Inspection.Report_PFS_v1.4.xlsx)

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
1. All obtained fields not clear logic
2. Detail part need clear clarification

**Comment by srinivasanbaskaran** [comment]
PFS updated. 

PFS: [Machine Sample Inspection Report_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4297733/Machine.Sample.Inspection.Report_PFS_v1.5.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Karthi,

Check the PFS & Proceed further 

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the signed copy of the changes of Machine Sample Inspection Report.

Machine Sample: ![1583814589327](https://user-images.githubusercontent.com/46194039/76282669-55bd5080-62be-11ea-9748-2aa7a6712896.JPEG)

Below are the points to be changed in this report

1. User required HORIZONTAL mode.
2. 1 Sample data having the following flow ( Green Data - Sintered Results in 1 line )

**NOTE**
Suggestion from Mr. Goutham, 
* Font size should be 12 or more
* 6 columns only available

After that only Mr. Goutham will confirm that format.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Please update the PFS

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find sample format of the report. Kindly check and revert back.

[qc_312.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4332368/qc_312.pdf)
[qc_227.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4332369/qc_227.pdf)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

QC_227 - Report format is OK... 

Let me confirm from the User

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
[mac_Sam_638.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4337511/mac_Sam_638.pdf)

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

In the multi line, Green data is fetching all the attributes. 

But, User wants that, below Attributes only.
1. Green Height
2. Green Weight
3. Green Step Height
4. Ratio

Kindly correct the report & Revert me 

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.
Please find the latest deliverables.

[msir_jyoti_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4354340/msir_jyoti_v2.2.zip)
[msir_227_p1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4354341/msir_227_p1.pdf)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

Machine Sample Inspection Report Testing 1 Completed. 

PFS: [Machine.Sample.Inspection.Report_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356780/Machine.Sample.Inspection.Report_PFS_v1.6.xlsx)

DELIVERABLES:

TESTCASE1: [TestCase2_Machine Sample Inspection Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356781/TestCase2_Machine.Sample.Inspection.Report.xlsx)

TEST RESULT1 (1): [Machine Sample Inspection Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4356783/Machine.Sample.Inspection.Report.pdf)

TEST RESULT1 (2): [Machine Sample Inspection Report-1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4356784/Machine.Sample.Inspection.Report-1.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start Testing 2 & Prepare the Testcase 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2 completed. PFA of test documents. please check.

Test Case: [TestCase-Machine.Sample.Inspection.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4359351/TestCase-Machine.Sample.Inspection.Report.xlsx)

Test Result : [Test Result - Machine Sample Inspection report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4359352/Test.Result.-.Machine.Sample.Inspection.report.pdf)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Below are the changes are to be made as per the Customer Requirements.

1. Fired Color - Changed to FFired Colour
2. Green related data to be in order ( Green Weight, Green Height, Green Ratio & Green Step Height )

Kindly Review the above points & Proceed to the Development

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Machine Sample Inspection Report Testing 1 Completed. 

PFS: [Machine.Sample.Inspection.Report_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356780/Machine.Sample.Inspection.Report_PFS_v1.6.xlsx)

DELIVERABLES:

TESTCASE1: [TestCase2_Machine Sample Inspection Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356781/TestCase2_Machine.Sample.Inspection.Report.xlsx)

TEST RESULT1: [06_Machine Sample Inspection Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4378711/06_Machine.Sample.Inspection.Report.pdf)

TESTCASE2: [TestCase-Machine.Sample.Inspection.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4378724/TestCase-Machine.Sample.Inspection.Report.xlsx)

TEST RESULT2: [Machine Sample_Test Result2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4378725/Machine.Sample_Test.Result2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly attach the Latest Deliverables ASAP.

REgards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the latest deliverables.

[msir_jyoti_v2.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4379068/msir_jyoti_v2.3.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

Machine Sample Inspection Report Testing 1 Completed. 

PFS: [Machine.Sample.Inspection.Report_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356780/Machine.Sample.Inspection.Report_PFS_v1.6.xlsx)

PATH: Inventory & PICC --> Quality Management --> View Final Clearance Feedback Details

DELIVERABLES: [msir_jyoti_v2.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4389515/msir_jyoti_v2.3.zip)

TESTCASE1: [TestCase2_Machine Sample Inspection Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356781/TestCase2_Machine.Sample.Inspection.Report.xlsx)

TEST RESULT1: [06_Machine Sample Inspection Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4378711/06_Machine.Sample.Inspection.Report.pdf)

TESTCASE2: [TestCase-Machine.Sample.Inspection.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4378724/TestCase-Machine.Sample.Inspection.Report.xlsx)

TEST RESULT2: [Machine Sample_Test Result2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4378725/Machine.Sample_Test.Result2.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

As per the User's Requirements, PFS updated & Kindly review & Move to the Development

**NOTE**
**New logic to be handled for Qualitative Attributes**

PFS: 
[Machine.Sample.Inspection.Report_PFS_v1.7.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4452287/Machine.Sample.Inspection.Report_PFS_v1.7.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As discussed with srini, please do the correction and allocate to nandhinee

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing1 & Prepare the Testing Document

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing1 completed...PFA..

[TestCase1_Machine.Sample.Inspection.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4470134/TestCase1_Machine.Sample.Inspection.Report.xlsx)
[TR Machine sample Inspection report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4470135/TR.Machine.sample.Inspection.report.pdf)

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 2 Completed. PFA

Testcase 2: [TestCase2_Machine Sample Inspection Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4498030/TestCase2_Machine.Sample.Inspection.Report_v1.1.xlsx)

Test Result 2: [Machine Sample_Test Result2_V1.1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4498033/Machine.Sample_Test.Result2_V1.1.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly update the Latest Deliverables ASAP

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The deliverables has been attached.

[msir_jyoti_v2.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4501281/msir_jyoti_v2.4.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Machine Sample Inspection Report Testing has been completed. Herewith I have attached Testing Documents for future references.

PFS: [Machine.Sample.Inspection.Report_PFS_v1.7.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4509680/Machine.Sample.Inspection.Report_PFS_v1.7.xlsx)

DELIVERABLES: [msir_jyoti_v2.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4509684/msir_jyoti_v2.4.zip)

TESTCASE1: [TestCase1_Machine.Sample.Inspection.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4509694/TestCase1_Machine.Sample.Inspection.Report.xlsx)

TEST RESULT1: [TR.Machine.sample.Inspection.report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4509695/TR.Machine.sample.Inspection.report.pdf)

TESTCASE2: [TestCase2_Machine.Sample.Inspection.Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4509697/TestCase2_Machine.Sample.Inspection.Report_v1.1.xlsx)

TEST RESULT2: [Machine.Sample_Test.Result2_V1.1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4509702/Machine.Sample_Test.Result2_V1.1.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

User given confirmation.. Attached the same

Doc: ![Machine Sample Inspection Report_Confirmation](https://user-images.githubusercontent.com/46194039/81582179-56ad5400-93cd-11ea-810d-7e303c5cd962.jpg)

Kindly close this ticket.

Regards,
Srinivasan

**Comment by raju-kurup** [comment]
Development completed, so closing this development

**Comment by sujin1708** [comment]
@Nandhineedevi Need to update the Req. Min. & Req. Max values in all the specified value fields

[Machine.Sample.Inspection.Report_PFS_v1.9.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5061369/Machine.Sample.Inspection.Report_PFS_v1.9.xlsx)

**Comment by Nandhineedevi** [comment]
Hi Sujin,
The rework has been completed.

[sample.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5062997/sample.pdf)
[mpqmsir_msir_p_grd1_gr_v2.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5063002/mpqmsir_msir_p_grd1_gr_v2.5.zip)

**Comment by sujin1708** [comment]
@eafaisal kindly update the PFS variant and move to  review

![image](https://user-images.githubusercontent.com/47313592/90097674-240c5200-dd54-11ea-94eb-77f182aa947e.png)

**Comment by srinivasanbaskaran** [comment]
@Nandhineedevi ,

Please find the below points, need to be corrected in this report.

* RATIO - Minimum & Maximum value not fetch

![image](https://user-images.githubusercontent.com/46194039/91518935-ed673780-e90e-11ea-91ad-253590bea5d1.png)


Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Completed.

[mpqmsir_msir_p_grd1_gr_v2.6.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5140071/mpqmsir_msir_p_grd1_gr_v2.6.zip)
[msir.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5140079/msir.pdf)

**Comment by srinivasanbaskaran** [comment]
Sujin,

Pls do the Testing 1 & Prepare the Testing Document

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the attached Design format of Machine Sample Report. Kindly review the same & allocate for the Development.

Template: [New Format_Machine Sample Inspection Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5157180/New.Format_Machine.Sample.Inspection.Report.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please allocate to Nandhinee for correction of Specified value to be added in header itself and remove of Heading for sample nos.

**Comment by Nandhineedevi** [comment]
Completed.

[without green data in sintered results.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5162936/without.green.data.in.sintered.results.pdf)
[with green data in sintered results.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5162937/with.green.data.in.sintered.results.pdf)
[mpqmsir_msir_p_grd1_gr-v2.7.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5162944/mpqmsir_msir_p_grd1_gr-v2.7.zip)

**Comment by srinivasanbaskaran** [comment]
Team,

Customer needs to confirm the Sintered Results ( Green Data required or not ) 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 1 Completed. Herewith I have attached the Testing Documents 

TESTCASE1:

TEST RESULT1 (a): [Machine Sample Inspection Report_TR1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5166011/Machine.Sample.Inspection.Report_TR1.pdf)

TEST RESULT1 (b): [Machine Sample Inspection Report_TR1_New.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5166012/Machine.Sample.Inspection.Report_TR1_New.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start Testing 2 & Prepare teh Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srinivasanbaskaran,

Machine Sample Inspection Report Testing 2 Completed Kindly Check & Update.

[Test Result For Machine Sample Inspection report v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5172583/Test.Result.For.Machine.Sample.Inspection.report.v2.pdf)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
please attach the document.

**Comment by srinivasanbaskaran** [comment]
Raju Sir, 

Machine Sample Inspection Report Testing has been completed. Herewith I have attached the Testing documents for the future references.

PFS: [Machine.Sample.Inspection.Report_PFS_v1.10.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5157257/Machine.Sample.Inspection.Report_PFS_v1.10.xlsx)

DELIVERABLES: [mpqmsir_msir_p_grd1_gr-v2.7.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5297118/mpqmsir_msir_p_grd1_gr-v2.7.zip)

TESTCASE1:

TEST RESULT1 (a): [Machine Sample Inspection Report_TR1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5166011/Machine.Sample.Inspection.Report_TR1.pdf)

TEST RESULT1 (b): [Machine Sample Inspection Report_TR1_New.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5166012/Machine.Sample.Inspection.Report_TR1_New.pdf)

TESTCASE2: [TestCase2_Machine.Sample.Inspection.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5172637/TestCase2_Machine.Sample.Inspection.Report.xlsx)

TEST RESULT2: [Test Result For Machine Sample Inspection report v2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5172583/Test.Result.For.Machine.Sample.Inspection.report.v2.pdf)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer confirmed the report, so closing this ticket

**Comment by sujin1708** [comment]
variant to be handled

**Comment by sujin1708** [comment]
Refer the below screen shot ..apply the material name logic as per the screen shot

![image](https://user-images.githubusercontent.com/47313592/102454145-87402500-4063-11eb-9619-9df6d08fb9ea.png)

**Comment by Nandhineedevi** [comment]
Completed.

[msir_jyoti_v3.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5709357/msir_jyoti_v3.1.zip)
[machine sample inspection report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5709359/machine.sample.inspection.report.pdf)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by Nandhineedevi** [comment]
Deployed in Live Server

[Live_import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5918677/Live_import.zip)

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Report has been Deployed successfully. Kindly close this ticket.

Regards,
Manivel A

**Comment by sujin1708** [comment]
@karthikeyanamitysoft please check the below error

1. Material name not showeing

![image](https://user-images.githubusercontent.com/47313592/125384802-1376b880-e3b7-11eb-952d-71c417e662f0.png)

**Comment by Jeyapriyat** [comment]
@sujin1708 
changes completed,kindlycheck and revert.
![image](https://user-images.githubusercontent.com/37791285/125921320-84e077ba-96b4-48d1-9b52-ab463b00ad47.png)
[new changes live sp 16-7-2021.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6829307/new.changes.live.sp.16-7-2021.zip)

**Comment by Manimahat** [comment]
@Jeyapriyat ,

Please deploy the same deliverable in UAT server.

Thanks,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup sir,

Need to deploy the same deliverable in UAT server.  Please allocate a developer to for this point.

Thanks,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy the same deliverables in UAT server also

**Comment by Jeyapriyat** [comment]
@Manimahat 
changes completed,kindly check and revert.
i have attached latest deliverables and sample output.
[msir_jyoti.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6855780/msir_jyoti.zip)
[sample report uat.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6855781/sample.report.uat.pdf)

**Comment by Manimahat** [comment]
@raju-kurup sir,

As per our new Requirement Material Name Logic Changed & other Issue has been Resolved. New Deliverable deployed & Tested Successfully in Both UAT & Live Server. Test Result has been attached Below.  Please close this Ticket.

Live Server Result : [Machine Sample Inspection report - Live.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6872221/Machine.Sample.Inspection.report.-.Live.pdf)

UAT Server Result : [Machine Sample Inspection Report - UAT.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6872222/Machine.Sample.Inspection.Report.-.UAT.pdf)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Report Developed and deployed in both Live and Test, so Closing this ticket.
