### ISSUE TITLE
EAM : Mobile Maintenance activity

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#48]
Dear Team.,

Through Mobile Maintenance activity process, Like PM, Work order approve etc.

Thanks and Regards,
M.Maheshwaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

As per discussed with Mr. Sunil, Maintenance Activity should not be maintained through mobiles. 

But, they need Trigger & SMS. Trigger we are provided. For SMS, Jyoti needs to provide SMS Gateway. 

So, Kindly request you to close this ticket.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Training completed, so closing the ticket
