### ISSUE TITLE
EAM : Trigger for Work Order Creation for the Equipement

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#49]
Dear Sir

Please find the attached **Trigger for Work Order reached Due date_PFS V 1.0** for your Reference. through SMS and Mail trigger should be come.

PFS : [01_JCIPL_Mail trigger for WO_CO PFS_V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3650736/01_JCIPL_Mail.trigger.for.WO_CO.PFS_V.1.0.xlsx)

Note : SMS is pending

Thanks and Regards,
M.Maheshwaran

**Comment by raju-kurup** [comment]
Karthi, please develop this trigger

**Comment by karthikeyanamitysoft** [comment]
Dear Nandini,

Kindly start the schedule.
regards,
Karthi

**Comment by maheshwaran-m** [comment]
Dear Karthi,

Ticket No : 49 and 50 both same development only.

Regards,
M.Maheshwaran

**Comment by Nandhineedevi** [comment]
Hi KarthiK Sr,
I have completed development for both 49 and 50 issues. 
Please find the attached deliverable for the report.

[Trigger for due day in work order.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3715685/Trigger.for.due.day.in.work.order.zip)

Regards
Nandhinee Devi

**Comment by maheshwaran-m** [comment]
Prabakaran,

Kindly start Testing 1 process.

regards,
M.Maheshwaran

**Comment by Prabakaran92** [comment]
Dear srini,

Testing1 competed.
Kindly start testing 2.
PFA

**PFS** : [01_JCIPL_Mail.trigger.for.WO_CO.PFS_V.1.0 (2).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3723156/01_JCIPL_Mail.trigger.for.WO_CO.PFS_V.1.0.2.xlsx)



**Test case** : [Trigger mail Due days in WO_CO  Test case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3723139/Trigger.mail.Due.days.in.WO_CO.Test.case.xlsx)

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Ugesh,

Kindly start the Testing 2. Prepare the Testcase & Test Results

Regards,

Srinivasan Baskaran

**Comment by Ugeshkumar16** [comment]
@Nandhineedevi,
Email not triggered.
Refer the no: PMWO/1920/0046, PMWO/1920/0045.

Regards,
S.Ugeshkumar

**Comment by Nandhineedevi** [comment]
Hi Ugesh,
Email is now triggering. Kindly check and revert back.

Regards
Nandhinee Devi N

**Comment by Nandhineedevi** [comment]
Hi ,
Please find the latest deliverables.

[Work_order_schedule_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3845772/Work_order_schedule_v1.2.zip)

Regards
Nandhinee Devi

**Comment by Ugeshkumar16** [comment]
Dear Srinivasan,
Testing 2 completed.
kindly find the attachments
[Test Cases for 49 (2).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3869141/Test.Cases.for.49.2.xlsx)
![wo 53 remainder 1](https://user-images.githubusercontent.com/48987324/69238597-671f0780-0bbe-11ea-81de-324bc89fb95f.png)
![wo 53 remainder 2](https://user-images.githubusercontent.com/48987324/69238609-6ab28e80-0bbe-11ea-8924-a18c0f888c69.png)
![Cwo remainder 1 09](https://user-images.githubusercontent.com/48987324/69238640-7736e700-0bbe-11ea-8aa2-4e86e5089a17.png)
![Cwo remainder 2 09](https://user-images.githubusercontent.com/48987324/69238651-7b630480-0bbe-11ea-9fb7-e644771d24fd.png)

Regards,
S.Ugeshkumar

**Comment by srinivasanbaskaran** [comment]
Sir,

Trigger for Work Order Testing has been completed. 

Herewith I have attached Testing documents for future references.

PFS:[01_JCIPL_Mail.trigger.for.WO_CO.PFS_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3885223/01_JCIPL_Mail.trigger.for.WO_CO.PFS_v2.xlsx)

DELIVERABLES: [Work_order_schedule_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3885229/Work_order_schedule_v1.2.zip)

TESTCASE 1: [Trigger.mail.Due.days.in.WO_CO.Test.case_V1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3885230/Trigger.mail.Due.days.in.WO_CO.Test.case_V1.xlsx)

TEST RESULT 1: ![Remainder2 - Test Result Rrigger mail](https://user-images.githubusercontent.com/46194039/69519739-c09d8280-0f80-11ea-9cd2-d71952f56538.JPG)

TESTCASE 2: [Test.Cases.for.49.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3885247/Test.Cases.for.49.xlsx)

TEST RESULT 2 (Remainder 1 ): ![Remainder1- PM WO](https://user-images.githubusercontent.com/46194039/69519811-f17db780-0f80-11ea-915c-586563cb2932.png)

TEST RESULT 2 (Remainder 2 ): ![Remainder2- PM WO](https://user-images.githubusercontent.com/46194039/69519814-f17db780-0f80-11ea-874f-20ef189222ee.png)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Trigger developed and tested, so closing this ticket.

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Explained to the EAM User & Accepted.

**Resolution Doc:** [01_Resolution Doc for EAM OpenPoint for 2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4179274/01_Resolution.Doc.for.EAM.OpenPoint.for.2.docx)

Kindly process further. 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and user accepted, so closing this ticket.
Srini - please attach the signed document

**Comment by srinivasanbaskaran** [comment]
Faizal,

Please do the PFS changes as per we discussed. 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@raju-kurup 

Sir,

The PFS is updated.
Kindly check.

PFS : 
[01_JCIPL_Mail.trigger.for.WO_CO.PFS_v2 (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5156786/01_JCIPL_Mail.trigger.for.WO_CO.PFS_v2.1.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction of Email ID given place as mentioned in PFS

**Comment by badamnarendra028** [comment]
[trigger_wo.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5161228/trigger_wo.zip)
completed kindly check and revert

**Comment by srinivasanbaskaran** [comment]
Faizal,

Kindly start Testing 1 & Prepare the Testing Document

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
[Work_order_schedule_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5181098/Work_order_schedule_v1.3.zip)

**Comment by srinivasanbaskaran** [comment]
Team,

Please find the User Requirement as below.

**OLD CONCEPT**
Mail Trigger happens at Work Order Reached Due Date

**NEW CONCEPT**
Mail Trigger happens at whenever Work Order Created

NOTE: Mr. Sunil asked this requirement on 08-09-2020

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

After getting the confirmation, PFS will be prepared.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS along with the Test Data that incorporated of Customer's recent requirements.

PFS: [01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5195435/01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.6.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction in the trigger (ie) previously we consider Preventive and Caliberation order but now all order should come in trigger.

**Comment by Manimahat** [comment]
@Nandhineedevi ,

Please make the Trigger As per PFS only.

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
Completed.

[Work_order_schedule_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5254457/Work_order_schedule_v2.1.zip)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Kindly Start Testing 1 Process.

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Team,

For Creation of Work Order, we got the Trigger as attached. 


TESTCASE1: 
TEST RESULT1: [WO_Creation Trigger.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5292054/WO_Creation.Trigger.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by AkashGleen** [comment]
Dear Srinivasanbaskaran,

Trigger For Work Order Creation For the Equipment Testing 2 Completed Kindly Check & Update.

[Test Case For Work Order v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5292461/Test.Case.For.Work.Order.v2.xlsx)

[Test Result For Work Order v2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5292462/Test.Result.For.Work.Order.v2.docx)

Regards,
Akash

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Trigger for Work Order Creation for the Equipment Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5195435/01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.6.xlsx)

DELIVERABLES: [Work_order_schedule_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5254457/Work_order_schedule_v2.1.zip)

TESTCASE1: [Testcase1_Trigger for Work Order Creation_V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5311038/Testcase1_Trigger.for.Work.Order.Creation_V1.1.xlsx)

TEST RESULT1: [WO_Creation Trigger.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5292054/WO_Creation.Trigger.docx)

TESTCASE2: [Test Case For Work Order v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5292461/Test.Case.For.Work.Order.v2.xlsx)

TEST RESULT2: [Test Result For Work Order v2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5292462/Test.Result.For.Work.Order.v2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Manivel,

Please do the PFS as per the Customer Requirements 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Kindly review the Updated PFS & allocated to Developers.

Updated PFS : [01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.7.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5416498/01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.7.xlsx)

Correction PDF : [Order Created.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5416504/Order.Created.pdf)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
please do the correction in mail subject and body of the mail. Contact Manivel for this issue

**Comment by mohanaamity** [comment]
@Manimahat 

Report completed.Kindly check and confirm

Regards,
Mohana B

**Comment by Manimahat** [comment]
@eafaisal ,

Testing 1 completed. Kindly start testing 2 Process.

Test Case : [Testcase1_Trigger.for.Work.Order.Creation_V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5508705/Testcase1_Trigger.for.Work.Order.Creation_V1.1.xlsx)

Test Result : [WO_Creation.Trigger.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5508709/WO_Creation.Trigger.docx)

Regards,
Manivel A

**Comment by mohanaamity** [comment]
@Manimahat 

I have attached the latest deliverables.
[EAM  Trigger for Work Order Creation for the Equipement.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5508740/EAM.Trigger.for.Work.Order.Creation.for.the.Equipement.zip)

Regards,
Mohana B

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Test case and result are attached.

Test Case: 
[Testcase2_Trigger.for.Work.Order.Creation_V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5510268/Testcase2_Trigger.for.Work.Order.Creation_V1.1.xlsx)

Test Result: 
[WO_Creation.Trigger.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5510269/WO_Creation.Trigger.2.docx)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Trigger for Work Order Creation for the Equipement testing has been completed, Herewith I have attached the Testing Documents for the future references.

PFS : [01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.7.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5416498/01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.7.xlsx)

DELIVERABLES: [EAM  Trigger for Work Order Creation for the Equipement.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5508740/EAM.Trigger.for.Work.Order.Creation.for.the.Equipement.zip)

TESTCASE1 : [Testcase1_Trigger.for.Work.Order.Creation_V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5508705/Testcase1_Trigger.for.Work.Order.Creation_V1.1.xlsx)

TEST RESULT1: [WO_Creation.Trigger.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5508709/WO_Creation.Trigger.docx)

TESTCASE2 : [Testcase2_Trigger.for.Work.Order.Creation_V1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5510268/Testcase2_Trigger.for.Work.Order.Creation_V1.1.xlsx)

TEST RESULT2: [WO_Creation.Trigger.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5510269/WO_Creation.Trigger.2.docx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by mohanaamity** [comment]
@Manimahat 

Deployment completed in live server

[Trigger for work order creation for the equipment.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5765108/Trigger.for.work.order.creation.for.the.equipment.zip)

Regards,
Mohana B

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Trigger for Work order creation trigger Deployed successfully in Live Server. Please Close this ticket.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
