### ISSUE TITLE
EAM : Trigger for Due days in Calibration ( 2 days before and after )-Trigger

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#50]
Dear Sir,

Please find the attached **Trigger for due days in Work Order_PFS V 1.0** for your Reference.
Due days Before two days and after two days system should trigger.

PFS : [01_JCIPL_Mail trigger for WO_CO PFS_V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3650749/01_JCIPL_Mail.trigger.for.WO_CO.PFS_V.1.0.xlsx)

Ticket No : #49 and #50 both PFS Same

Thanks and Regards,
M.Maheshwaran

**Comment by raju-kurup** [comment]
Karthi, please plan for the development

**Comment by karthikeyanamitysoft** [comment]
dear Nandini,

Kindly start the new schedule 
Regards,
Karthi

**Comment by Nandhineedevi** [comment]
Hi,
The coding has been completed. Waiting for mail configuration in database.

Regards
Nandhinee devi

**Comment by maheshwaran-m** [comment]
Dear Karthi,

Please find the attached Jyoti mail details for your reference.

mail id: donotreply@jyoticeramic.com
Profile Name : Ramco

Regards,
M.Maheshwaran

**Comment by karthikeyanamitysoft** [comment]
Completed kindly test

**Comment by Nandhineedevi** [comment]
Hi Mahesh,
The Development completed. Kindly check and revert back.
Please find the deliverable.

[Trigger for due day in work order.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3715696/Trigger.for.due.day.in.work.order.zip)


Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
Dear srini,

Testing1 competed.
Kindly start testing 2.
PFA

**PFS** : [Uploading 01_JCIPL_Mail.trigger.for.WO_CO.PFS_V.1.0 (1).xlsx…]()

**Test case** : 
**Test Result ** :

**Comment by srinivasanbaskaran** [comment]
Nova,

Kindly start Testing 2. Prepare the Testcase & Test Result

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start Testing 2 & Prepare the Testing Documents 

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Ugesh,

Kindy start the testing 2 & Prepare the Testing Documents

Regards,

Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi,
Kindly find the latest deliverables.

[Calibration_Order_Schedule.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3845792/Calibration_Order_Schedule.zip)

Regards
Nandhinee Devi

**Comment by Ugeshkumar16** [comment]
Dear Srinivasan,
Testing 2 is completed.
kindly find the attachments.
[Test Cases for 50.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3869149/Test.Cases.for.50.xlsx)
![wo 53 remainder 1](https://user-images.githubusercontent.com/48987324/69238796-d1d04300-0bbe-11ea-8c4c-46e01e93832c.png)
![wo 53 remainder 2](https://user-images.githubusercontent.com/48987324/69238807-d4cb3380-0bbe-11ea-848e-469a2f48e689.png)
![Cwo remainder 1 09](https://user-images.githubusercontent.com/48987324/69238815-d8f75100-0bbe-11ea-95ba-8e5daf791e60.png)
![Cwo remainder 2 09](https://user-images.githubusercontent.com/48987324/69238825-dd236e80-0bbe-11ea-91b3-19d1e1950c13.png)

Regards,
S.Ugeshkumar

**Comment by srinivasanbaskaran** [comment]
Sir,

Trigger for Calibration Work Order testing has been completed. 

Herewith, I have attached Testing Documents for future references.

PFS:[01_JCIPL_Mail.trigger.for.WO_CO.PFS_v1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3885138/01_JCIPL_Mail.trigger.for.WO_CO.PFS_v1.xlsx)

DELIVERABLES: [Calibration_Order_Schedule.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3885145/Calibration_Order_Schedule.zip)

TESTCASE 1: [Trigger.mail.Due.days.in.WO_CO.Test.case_updated.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3885147/Trigger.mail.Due.days.in.WO_CO.Test.case_updated.xlsx)

TEST RESULT 1: ![Remainder2 - Test Result Rrigger mail](https://user-images.githubusercontent.com/46194039/69518255-1a03b280-0f7d-11ea-9d83-3a9e8a50d80d.JPG)

TESTCASE 2: [Test.Cases.for.50.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3885164/Test.Cases.for.50.xlsx)

TEST RESULT 2 (Remainder 1) : ![Remainder1- CWO](https://user-images.githubusercontent.com/46194039/69518366-59ca9a00-0f7d-11ea-83e6-5250317350f9.png)

TEST RESULT 2 (Remainder 2) : ![Remainder2- CWO](https://user-images.githubusercontent.com/46194039/69518394-6b13a680-0f7d-11ea-86f1-ae8e6296201f.png)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Trigger developed and testing, so closing this issue

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Explained to the EAM Users & They accepted

**Resolution Doc:** 
[01_Resolution Doc for EAM OpenPoint for 3.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4179287/01_Resolution.Doc.for.EAM.OpenPoint.for.3.docx)

Kindly process further.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and user accepted, so closing this ticket.
Srini  - Please attach the signed document

**Comment by srinivasanbaskaran** [comment]
Faizal,

Please do the PFS changes as per we discussed. 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@raju-kurup 

Sir,

The PFS is updated.
Kindly check.

PFS : 
[01_JCIPL_Mail.trigger.for.WO_CO.PFS_v1 (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5156818/01_JCIPL_Mail.trigger.for.WO_CO.PFS_v1.1.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft :  please do the correction of Email ID given place as mentioned in PFS

**Comment by badamnarendra028** [comment]
[trigger_2days.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5160809/trigger_2days.zip)
completed kindly check and revert

**Comment by srinivasanbaskaran** [comment]
Faizal,

Kindly start Testing 1 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
[Calibration_Order_Schedule_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5181103/Calibration_Order_Schedule_v1.2.zip)

**Comment by srinivasanbaskaran** [comment]
Team,

Need to clarify some points with the Customer. After that only PFS to be updated

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS along with Test Data that incorporated of Customer's recent requirements

PFS: [01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5195824/01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.3.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as mentioned in PFS (ie) previously we considered Preventive and Callibration work orders only, but now we need trigger for all WO

**Comment by Manimahat** [comment]
@Nandhineedevi ,

Please make the Trigger as per PFS.

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
completed.

[Work_order_schedule_v2.1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5254462/Work_order_schedule_v2.1.1.zip)
[Calibration_Order_Schedule_v2.1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5254465/Calibration_Order_Schedule_v2.1.2.zip)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Kindly Start Testing 1 Process.

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
@Nandhinee, 

Please check Trigger mail is not come for the Scheduled Work Order.. 

WO No: PMWO/2021/0046 ... Scheduled Date: 26-09-2020

Kindly check & update ASAP... 

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

[Work_order_schedule_v3.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5290096/Work_order_schedule_v3.1.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 1 Completed. Herewith I have attached the Testing Documents. 

TESTCASE1:

TEST RESULT1: [Due Date 2 days before & after.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5292072/Due.Date.2.days.before.after.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Faizal,

Kindly start the Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Test result is attached.

Test Result : 
[Due.Date.2.days.before.after.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5321069/Due.Date.2.days.before.after.docx)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Trigger for Due days 2 days Before & After Trigger testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5195824/01_JCIPL_Mail.trigger.for.WO_CO.PFS_V1.3.xlsx)

DELIVERABLES1(a): [Work_order_schedule_v2.1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5254462/Work_order_schedule_v2.1.1.zip)

DELIVERABLES1(b):[Calibration_Order_Schedule_v2.1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5254465/Calibration_Order_Schedule_v2.1.2.zip)

TESTCASE1: [Testcase1_Trigger for Work Order Reached Due Date 2 days Before & After.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5333813/Testcase1_Trigger.for.Work.Order.Reached.Due.Date.2.days.Before.After.xlsx)

TEST RESULT1: [Due Date 2 days before & after.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5292072/Due.Date.2.days.before.after.docx)

TESTCASE2: [Trigger.mail.Due.days.in.WO_PMWO.Test.case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5333277/Trigger.mail.Due.days.in.WO_PMWO.Test.case.xlsx)

TEST RESULT2:[Due.Date.2.days.before.after.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5321069/Due.Date.2.days.before.after.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Manivel,

Please do the PFS as per the Customer Requirements 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Kindly review the Updated PFS & allocated to Developers.

Updated PFS : [01_JCIPL_Mail.trigger.for.WO_CO.-Remainder -PFS_V1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5416483/01_JCIPL_Mail.trigger.for.WO_CO.-Remainder.-PFS_V1.4.xlsx)

Correction PDF - 1 : [Prior_due_date.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5416484/Prior_due_date.pdf)

Correction PDF - 2 : [Due_Date_Pass.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5416490/Due_Date_Pass.pdf)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
please do the correction in mail subject and body of the mail. Contact Manivel for this issue

**Comment by Narendiranath** [comment]
Hi Manivel,

                  You are busy with some other work & call. Once you are free after that allocate this ticket to me.

**Comment by Narendiranath** [comment]
Hi Manivel,

                            Changes are done. Kindly check. PFA Latest Deliverable & Test Result.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5504345/Deliverable.zip)

![image](https://user-images.githubusercontent.com/59695578/98432765-9ab4b380-20e7-11eb-94fd-31f33cf89612.png)

**Comment by Manimahat** [comment]
@eafaisal ,

Testing 1 Completed. Kindly Start Testing 2 Process.

Test case : [Testcase1_Trigger.for.Work.Order.Reached.Due.Date.2.days.Before.After.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5509132/Testcase1_Trigger.for.Work.Order.Reached.Due.Date.2.days.Before.After.xlsx)

Test Result : [Due.Date.2.days.before.after.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5509134/Due.Date.2.days.before.after.docx)

Regards,
Manivel A

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Test case and result are attached.

Test Case: 
[Testcase2_Trigger.for.Work.Order.Reached.Due.Date.2.days.Before.After.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5521835/Testcase2_Trigger.for.Work.Order.Reached.Due.Date.2.days.Before.After.xlsx)


Test Result: 
[Due.Date.2.days.before.after.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5521837/Due.Date.2.days.before.after.docx)

Regards,
Faisal

**Comment by sujin1708** [comment]
@Narendiranath kidnly update the lastest deliverables

**Comment by sujin1708** [comment]
[Due.Date.2.days.before.after (1).docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5646544/Due.Date.2.days.before.after.1.docx)
[Testcase2_Trigger.for.Work.Order.Reached.Due.Date.2.days.Before.After.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5646546/Testcase2_Trigger.for.Work.Order.Reached.Due.Date.2.days.Before.After.xlsx)
[Due.Date.2.days.before.after.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5646547/Due.Date.2.days.before.after.docx)
[Uploading 01_JCIPL_Mail.trigger.for.WO_CO.PFS_v1.xlsx…]()
[Testcase1_Trigger.for.Work.Order.Reached.Due.Date.2.days.Before.After.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5646549/Testcase1_Trigger.for.Work.Order.Reached.Due.Date.2.days.Before.After.xlsx)
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5646550/Deliverable.zip)

**Comment by sujin1708** [comment]
@raju-kurup Development completed and user accepted, so closing this ticket.

**Comment by Manimahat** [comment]
@raju-kurup Sir,

to be Deployed in Live Server. please Allocate to Develoeprs.

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by Nandhineedevi** [comment]
Deployed in Live Server.

[Live_Final_import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5790518/Live_Final_import.zip)

**Comment by sujin1708** [comment]
kinldy close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
