### ISSUE TITLE
EAM : Trigger for Same issue Repeatedly-Trigger

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#51]
Dear sir,

Please find the attached **Trigger for Same issue repeatedly_PFS V 1.0** for your Reference.
In a six months 3rd time work order will be raised for same equipment system should be trigger at the time of work order creation.

**PFS :** [01_JCIPL_Mail trigger for Equipment Repeated issue_PFS V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3725137/01_JCIPL_Mail.trigger.for.Equipment.Repeated.issue_PFS.V.1.0.xlsx)

Thanks and Regards,
**M.Maheshwaran**

**Comment by raju-kurup** [comment]
Karthi - Please start the development

**Comment by badamnarendra028** [comment]
[equiptment_repeat_issue.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3890262/equiptment_repeat_issue.zip)

**Comment by maheshwaran-m** [comment]
@Nandhineedevi 

keep this ticket in your name, As discussed once sales invoice UDS development is completed. You can start Advance license Master.

Regards,
M.Maheshwaran

**Comment by badamnarendra028** [comment]
[equiptment_repeat_issue--28.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3901921/equiptment_repeat_issue--28.zip)
completed

**Comment by badamnarendra028** [comment]
[equiptment_repeat_issue--28-updated.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3901930/equiptment_repeat_issue--28-updated.zip)

**Comment by maheshwaran-m** [comment]
@badamnarendra028 

Am Created Three Work Request , against Work request Am generated Three Work order , For that three work order am received 9 mail trigger. We Required only one mail for Third work order in a 6 month gap. Please find the attached screen shots for your reference.

![Work order details](https://user-images.githubusercontent.com/38855450/69824205-1435f780-1231-11ea-8771-1330fc6e18c2.JPG)

![mail triggered](https://user-images.githubusercontent.com/38855450/69824229-2152e680-1231-11ea-8673-3a57e02c9d31.JPG)

Regards,
M.Maheshwaran

**Comment by badamnarendra028** [comment]
[equiptment_repeat_issue--28-updated.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3905182/equiptment_repeat_issue--28-updated.zip)

**Comment by maheshwaran-m** [comment]
@badamnarendra028 

Again Am received Three mail triggered for Three work order please check the attached screen shot for your reference.

![Capture](https://user-images.githubusercontent.com/38855450/69877063-2f633e80-12e7-11ea-8b53-37480221a7d7.JPG)

**Comment by badamnarendra028** [comment]
completed  kindly check

**Comment by maheshwaran-m** [comment]
@Prabakaran92 

Kindly test the Repeated issue mail trigger and prepare test case and test result for further process.

Regards,
M.Maheshwaran

**Comment by Prabakaran92** [comment]
@badamnarendra028 
Trigger mail not working praperly While generate Work order Same equipment at 3rd time work order generation time i get mail but 2nd Work order number fetching in trigger 
kindly check and revert .

Regards,
Prabakaran A

**Comment by badamnarendra028** [comment]
[equiptment_repeat_issue_trigger_jyothi--06.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3931269/equiptment_repeat_issue_trigger_jyothi--06.zip)
completed check and revert me

**Comment by maheshwaran-m** [comment]
@Prabakaran92 

Kindly start testing 1 for this ticket and attached all necessary documents for testing 2 purpose.

Regards,
M.Maheshwaran

**Comment by Prabakaran92** [comment]
@badamnarendra028 
Plz check this issue 
Test Result : ![image](https://user-images.githubusercontent.com/46194613/70885941-55cfec00-2000-11ea-92b4-41f6efb9600b.png)
Test Data : WR/1920/0113/P1
At the time of Approved/Generate WO 3rd Work request get this error 
Kindly check and close this issue.
 
Regards,
Prabakaran A

**Comment by badamnarendra028** [comment]
completed
[@equiptment_repeat.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3967879/%40equiptment_repeat.zip)

**Comment by Prabakaran92** [comment]
@badamnarendra028 
![image](https://user-images.githubusercontent.com/46194613/71065200-c1e45880-2196-11ea-91e6-19bf0a751f32.png)

Plz check this issue

**Comment by badamnarendra028** [comment]
![trigger1](https://user-images.githubusercontent.com/46923845/71171517-f8e46800-2283-11ea-9c12-adda1ac6e3fa.JPG)
kindly check

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Testing 1 completed
kindly start testing 2
Test case1 : [Trigger mail Repeted issue Test case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4004741/Trigger.mail.Repeted.issue.Test.case.xlsx)
Test output : ![image](https://user-images.githubusercontent.com/46194613/71509003-b3d9ba80-28af-11ea-8224-135b2bb5b55f.png)

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Trigger for the Repeated issues for the same Equipement testing completed. 

Testing Documents are attached for the future references.

PFS: [01_JCIPL_Mail.trigger.for.Equipment.Repeated.issue_PFS_v.1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4082368/01_JCIPL_Mail.trigger.for.Equipment.Repeated.issue_PFS_v.1.0.xlsx)

DELIVERABLES:

TESTCASE1: [Trigger Mail for Repeated Issue_Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4082369/Trigger.Mail.for.Repeated.Issue_Testcase1.xlsx)

TEST RESULT1: [Repeated Trigger Mail_Test_Result1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4082370/Repeated.Trigger.Mail_Test_Result1.docx)

TESTCASE2: [Trigger Mail for Repeated Issue_Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4082371/Trigger.Mail.for.Repeated.Issue_Testcase2.xlsx)

TEST RESULT2: [Repeated Trigger Mail_Test_Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4082372/Repeated.Trigger.Mail_Test_Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Badam,

Kindly update the Latest Deliverabels for this Trigger Report.

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[@equiptment_repeat1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4084667/%40equiptment_repeat1.zip)

**Comment by badamnarendra028** [comment]
updated

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Trigger for the Repeated issues for the same Equipement testing completed. 

Testing Documents are attached for the future references.

PFS: [01_JCIPL_Mail.trigger.for.Equipment.Repeated.issue_PFS_v.1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4082368/01_JCIPL_Mail.trigger.for.Equipment.Repeated.issue_PFS_v.1.0.xlsx)

DELIVERABLES: [@equiptment_repeat1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4085985/%40equiptment_repeat1.zip)

TESTCASE1: [Trigger Mail for Repeated Issue_Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4082369/Trigger.Mail.for.Repeated.Issue_Testcase1.xlsx)

TEST RESULT1: [Repeated Trigger Mail_Test_Result1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4082370/Repeated.Trigger.Mail_Test_Result1.docx)

TESTCASE2: [Trigger Mail for Repeated Issue_Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4082371/Trigger.Mail.for.Repeated.Issue_Testcase2.xlsx)

TEST RESULT2: [Repeated Trigger Mail_Test_Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4082372/Repeated.Trigger.Mail_Test_Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Explain to the EAM Users & They have accepted.

**Resolution Doc:**[01_Resolution Doc for EAM OpenPoint for 4.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4179293/01_Resolution.Doc.for.EAM.OpenPoint.for.4.docx)

Kindly proceed further.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

We have discussed this point with the Users. They were accepted. 

Kindly proceed further on this point.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and user accepted, so closing this ticket
Srini - Please attach the signed copy

**Comment by srinivasanbaskaran** [comment]
Faizal,

Please do the PFS changes as per we discussed. 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@raju-kurup 

Sir,

The PFS is updated.
Kindly check.

PFS : 
[01_JCIPL_Mail.trigger.for.Equipment.Repeated.issue_PFS_v.1.0 (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5156849/01_JCIPL_Mail.trigger.for.Equipment.Repeated.issue_PFS_v.1.0.1.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft :  please do the correction of Email ID given place as mentioned in PFS

**Comment by badamnarendra028** [comment]
[trigger_repeat.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5160819/trigger_repeat.zip)
completed kindly check and revert

**Comment by srinivasanbaskaran** [comment]
Faizal,

Kindly start Testing1 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 1 is completed.
Kindly proceed with testing 2.

Test Case : 
[Trigger.Mail.for.Repeated.Issue_Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5161951/Trigger.Mail.for.Repeated.Issue_Testcase1.xlsx)

Test Result : 
![Repeated Trigger Mail_Test_Result](https://user-images.githubusercontent.com/65998153/91976332-6535c780-ed3e-11ea-87d8-e26bd2d6c3c6.png)



Regards,
Faisal

**Comment by badamnarendra028** [comment]
[trigger_repeat (2).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5174641/trigger_repeat.2.zip)
completed check and revert

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 2 Completed. Herewith I have attached the Testing documents.

TESTCASE2: [Trigger.Mail.for.Repeated.Issue_Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5193031/Trigger.Mail.for.Repeated.Issue_Testcase2.xlsx)

TEST RESULT2: [Test Result2_Repeated Issue.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5193034/Test.Result2_Repeated.Issue.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Repeated Trigger for the same issue Trigger testing has been completed. Herewith I have attached the

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly Prepare the PFS as per Customer Requirement. 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup Ssir,

Kindly review the Updated PFS & allocated to Developers.

Updated PFS : [PFS_Trigger.for.Repeated.Issue_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5416455/PFS_Trigger.for.Repeated.Issue_V1.2.xlsx)

Correction PDF : [6Month3rd.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5416460/6Month3rd.pdf)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction in mail subject and body of the mail. Contact Manivel for this issue

**Comment by Narendiranath** [comment]
Hi Manivel,

                  You are busy with some other work & call. Once you are free after that allocate this ticket to me.

**Comment by mohanaamity** [comment]
@Manimahat 

Report completed.Kindly check and confirm

Regards,
Mohana B

**Comment by mohanaamity** [comment]
@Manimahat 

I have attached the latest deliverables for your reference.
[EAM-Trigger for same issue Repeatedly.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5508761/EAM-Trigger.for.same.issue.Repeatedly.zip)

Regards,
Mohana B

**Comment by Manimahat** [comment]
@eafaisal ,

Testing 1 Completed. Kindly Process Testing 2 process.

Test Case : [Trigger.Mail.for.Repeated.Issue_Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5508807/Trigger.Mail.for.Repeated.Issue_Testcase1.xlsx)

Test Result : [Test.Result1_Repeated.Issue.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5508810/Test.Result1_Repeated.Issue.docx)

Regards,
Manivel A

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Test case and result are attched.

Test  Case: 
[Trigger.Mail.for.Repeated.Issue_Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5510718/Trigger.Mail.for.Repeated.Issue_Testcase2.xlsx)


Test Result: 
[Test.Result2_Repeated.Issue.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5510720/Test.Result2_Repeated.Issue.docx)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Trigger for the Same Issues repeatedly occurs in a 6 months trigger testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS : [PFS_Trigger.for.Repeated.Issue_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5416455/PFS_Trigger.for.Repeated.Issue_V1.2.xlsx)

DELIVERABLES: [EAM-Trigger for same issue Repeatedly.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5508761/EAM-Trigger.for.same.issue.Repeatedly.zip)

TESTCASE1: [Trigger.Mail.for.Repeated.Issue_Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5508807/Trigger.Mail.for.Repeated.Issue_Testcase1.xlsx)

TEST RESULT1 : [Test.Result1_Repeated.Issue.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5508810/Test.Result1_Repeated.Issue.docx)

TESTCASE2: [Trigger.Mail.for.Repeated.Issue_Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5510718/Trigger.Mail.for.Repeated.Issue_Testcase2.xlsx)

TEST RESULT2: [Test.Result2_Repeated.Issue.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5510720/Test.Result2_Repeated.Issue.docx)

Regards,
Srinivasan Baskaran

**Comment by mohanaamity** [comment]
Kindly find the latest deliverables

[equiptment_repeat_issue_trigger_jyothi.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5544380/equiptment_repeat_issue_trigger_jyothi.zip)
Regards,
Mohana B

**Comment by Manimahat** [comment]
@raju-kurup Sir,

to be Deployed this report in Liver Server. please allocate to Developers.

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by mohanaamity** [comment]
@Manimahat 

Deployment completed in live server

[Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5765080/Deliverables.zip)

Regards,
Mohana B

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Trigger for same Issue repeatedly trigger Deployed successfully in Live Server. Please Close this ticket.

Regards,
Manivel A

**Comment by mohanaamity** [comment]
Latest Deliverables.
[Trigger for same issue repeately.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5796046/Trigger.for.same.issue.repeately.zip)

Regards,
Mohana B

**Comment by raju-kurup** [comment]
Trigger deployed in live server so ticket is closed
