### ISSUE TITLE
TOOL : Tool Production Quantity Report-Dcube

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#52]
Dear Karthi,

Please find the attached **Tool production quantity report_PFS V 1.0** for your Reference.

PFS :

Thanks and Regards,
M.Maheshwaran

**Comment by sujin1708** [comment]
@basha123456 kindly create the PFS

[Doc-1141.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3650693/Doc-1141.pdf)

**Comment by basha123456** [comment]
Dear Sujin,

As discussed, write in the Remarks field in the PFS..PFA
[PFS.Tool production Quantity report v1.0. Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3656462/PFS.Tool.production.Quantity.report.v1.0.Dcube.xlsx)

**Comment by basha123456** [comment]
Sujin,

AS discussd,PFA of updated PFS


Updated PFS:[PFS.Tool production Quantity report v2.0. Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3662488/PFS.Tool.production.Quantity.report.v2.0.Dcube.xlsx)

**Comment by basha123456** [comment]
Dear Raju Sir,

PFA of PFS..please review

[PFS.Tool production Quantity report v2.0. Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3676048/PFS.Tool.production.Quantity.report.v2.0.Dcube.xlsx)

**Comment by raju-kurup** [comment]
Please furnish test case

**Comment by basha123456** [comment]
Dear Raju Sir,

PFA of the PFS..Please review...Test case is prepared.
Jothi Server is Down now..so test data will be prepared when the server is working.

[PFS.Tool production Quantity report v2.0. Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3701580/PFS.Tool.production.Quantity.report.v2.0.Dcube.xlsx)

Regards,
Basha

**Comment by sujin1708** [comment]
@basha123456 Attach test data

**Comment by basha123456** [comment]
@sujin1708 ...once server works properly i will attach data..before that we can complete PFS review with Raju sir...

**Comment by basha123456** [comment]
Dear Raju Sir,

Test data is attached in the PFS..please review.

[PFS.Tool production Quantity report v2.0. Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3715913/PFS.Tool.production.Quantity.report.v2.0.Dcube.xlsx)

**Comment by sujin1708** [comment]
@basha Attach  Test Case & Test data

**Comment by basha123456** [comment]
Dear Raju sir,

I am attaching separate excel for the test case. please review.
[PFS.Tool production Quantity report v2.0. Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3717428/PFS.Tool.production.Quantity.report.v2.0.Dcube.xlsx)
[Test Case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3717429/Test.Case.xlsx)

**Comment by basha123456** [comment]
Dear Raju Sir,

PFA of tool production quantity PFS. please review and send for development.
[PFS.Tool production Quantity report v2.0. Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3755405/PFS.Tool.production.Quantity.report.v2.0.Dcube.xlsx)

**Comment by karthikeyanamitysoft** [comment]
Allocated to Anand

**Comment by karthikeyanamitysoft** [comment]
Development completed , test and confirm with multiple data

REgards,
Karthi

**Comment by karthikeyanamitysoft** [comment]
[Tool_Production_Quantity_Report_pop.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3789221/Tool_Production_Quantity_Report_pop.zip)

**Comment by basha123456** [comment]
Dear Karthi,

As Discussed, production qty is not fetching correctly. please correct it.

**Comment by karthikeyanamitysoft** [comment]
Dear Bhasha,

Productin Qty logic is handled now kindly check and give me the multiple test data.

Regards,
Karthi

**Comment by basha123456** [comment]
Dear Karthi,

In the report data in the fields  M/C, modification date, reason , work done columns are not fethed. they are showing blank. please notice.
Production order qty is fetching. i will again prepare sample data meanwhile.

![image](https://user-images.githubusercontent.com/47315921/68270554-96445d80-0083-11ea-827f-7eba3944ad66.png)

**Comment by karthikeyanamitysoft** [comment]
completed.

**Comment by basha123456** [comment]
Dear Karthi,

please do the following changes in the report
In the input, i have given from date as 10/10/2019 & to date as 22/10/2019 . 
1. but in the report generating for 04/08/2019 & 05/08/2019(old data) please correct.
2. Tool manufacturing date is not fethed.
3. In the remaining fields data duplication is there. In the production quantity also data is duplicating.
cells has to merge.
All the blue boxes in the below screenshot has to merge.
red boxes - unwanted data.
for clarifications, please call.
![image](https://user-images.githubusercontent.com/47315921/68483756-1f18f000-0262-11ea-8750-af35c6caef2e.png)

**Comment by basha123456** [comment]
In the work done field, we need the Description of task from the multiline, but equipment code it is fetching. please check.

**Comment by karthikeyanamitysoft** [comment]
Dear Bhasha,

Kindly mention the which field need to filter with input date.

**Comment by karthikeyanamitysoft** [comment]
Dear Basha ,

i completed the mentioned issue.
![image](https://user-images.githubusercontent.com/40713407/68557245-4090fc00-045b-11ea-87b3-cdd539eb3c66.png)

Check and confirm

**Comment by basha123456** [comment]
Dear Karthi,

Please correct these in the below report.
1. Sr.No  field - In the report for each tool one Sr.No is enough. cells should be merged.
2. Tool Description - for each tool one cell is enough. cells should be merged.
3. Tool manufacturing date - cells should be merged and show only one date for each tool.
4. M/C - Tool will be attached for one tool. it should be displayed in one cell.
5. Modification date - word order date as per PFS.
6. Reason - in this field unwanted data is fetching. kindly remove it.
7. Work done - in this field as per PFS data should be fetched. but Tool code is fetching .kindly correct it.
8. Production Qty - the value in this field fetching is not correct.

I have created test data and tested the report. the new data is not fetching.
I have attached PFS for your reference with the new test data. 

![image](https://user-images.githubusercontent.com/47315921/70308496-69759880-1831-11ea-9d09-d64a452b461e.png)
 
[PFS.Tool production Quantity report v2.0. Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3931153/PFS.Tool.production.Quantity.report.v2.0.Dcube.xlsx)

**Comment by basha123456** [comment]
Dear Raju Sir,

PFA of the updated PFS..please review.
[PFS.Tool.production.Quantity.report.v1.3.Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3944133/PFS.Tool.production.Quantity.report.v1.3.Dcube.xlsx)

**Comment by basha123456** [comment]
Dear Karthi,

Please find the updated PFS for Tool Production quantity. kindly do the development.
[PFS.Tool.production.Quantity.report.v1.3.Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3945696/PFS.Tool.production.Quantity.report.v1.3.Dcube.xlsx)

**Comment by karthikeyanamitysoft** [comment]
Dear Basha,

kindly mention the link for the below mentioned point with tool

completion date:
go to Project management and Accounting -> project detailing -> Maintain Project/Subproject -> in the optional links, go to task mapping -> refer tab "Task mapping" -> in the multiline refer field "%completed". -> for all the tasks, if the % completed is 100 -> refer filed  Planned End date -> in the list of dates, fetch the most recent date.

Condition : if the %completed value is not 100 for any task in the list of tasks, then dont fetch the date and dont consider the project.

**Comment by karthikeyanamitysoft** [comment]
![image](https://user-images.githubusercontent.com/40713407/70843310-35fcc480-1e56-11ea-82ca-66cbdc30aba0.png)

searching for the data

**Comment by basha123456** [comment]
Dear karthi,

please take this data.
![image](https://user-images.githubusercontent.com/47315921/70880287-6f683800-1fee-11ea-8475-69d7b48a0304.png)

The path for completion date is 
Project management and Accounting -> project detailing -> Maintain Project/Subproject -> in the links go to task mapping
Tool: ALS-6

**Comment by karthikeyanamitysoft** [comment]
Please show me the ALS-6 is 100 percent completed.

**Comment by basha123456** [comment]
PLease find the below project with 100% completed.

![image](https://user-images.githubusercontent.com/47315921/70930711-d96af680-205b-11ea-9c23-40abce7b7861.png)
![image](https://user-images.githubusercontent.com/47315921/70930811-12a36680-205c-11ea-9ecb-0bf3fa84cf3c.png)

**Comment by basha123456** [comment]
Dear Karthi,

PLease find the updated PFS.
[PFS.Tool.production.Quantity.report.v1.4.Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3979683/PFS.Tool.production.Quantity.report.v1.4.Dcube.xlsx)

**Comment by srinivasanbaskaran** [comment]
Karthi,

Please Find the Attached updated PFS for your references and do the needful at ASAP

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
development completed

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start the Testing 1 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
Dear Karthi,

PFA..please refer sheet Test dat..

[PFS.Tool.production.Quantity.report.v1.4.Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3992186/PFS.Tool.production.Quantity.report.v1.4.Dcube.xlsx)

**Comment by basha123456** [comment]
Dear karthi,

In the above sheet, Please find the corrected tool manufacturing date & production qty Logic. need to generate report as per the logic.

**Comment by karthikeyanamitysoft** [comment]
Kindly check the logic and tell me the difference.

Regards,
Karthi

**Comment by basha123456** [comment]
Srini,

Tool manufacturing date - we were taking thi from the Planned end date in the task before. Now we are taking it from the reported date of the PPR.
Production qty - we were taking qty based on the meter reset logic before . now with reference to the WO date & time we are taking this qty.
PFS logic is updated. please review and assign for the development
[PFS.Tool.production.Quantity.report.v1.4.Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4015256/PFS.Tool.production.Quantity.report.v1.4.Dcube.xlsx)

**Comment by srinivasanbaskaran** [comment]
Hi Karthi,

Please made the changes as per the updated PFS below.

Pls let me know at the time of start the changes, I will explain the context

PFS: [Tool_Production_Qty_Report_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4018223/Tool_Production_Qty_Report_PFS_v1.4.xlsx)

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
assigned to Naredranath.

Regards,
Karthi

**Comment by basha123456** [comment]
Dear Naren,

PFA of updated PFS
[PFS.Tool.production.Quantity.report.v1.5.Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4045347/PFS.Tool.production.Quantity.report.v1.5.Dcube.xlsx)

**Comment by basha123456** [comment]
Dear Naren,

After discussion with raju sir, i have done some corretions in the PFS..kindly consider this and do development.
[PFS.Tool.production.Quantity.report.v1.6.Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4095944/PFS.Tool.production.Quantity.report.v1.6.Dcube.xlsx)

**Comment by Narendiranath** [comment]
Dear Basha,

Toll production quantity report is completed. Kindly check and revert back.

**Comment by basha123456** [comment]
Dear Naren,

Dcube lens search is not working.
Production quantity is not coming correctly.please check

**Comment by Narendiranath** [comment]
Dear Basha,

Toll production quantity report is completed. Kindly check and revert back.

**Comment by basha123456** [comment]
Dear Naren,

PFA updated PFS.
conditions needs to be done.

[PFS.Tool.production.Quantity.report.v1.6.Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4142332/PFS.Tool.production.Quantity.report.v1.6.Dcube.xlsx)

**Comment by basha123456** [comment]
@srinivasanbaskaran : testing1 is completed. please move to testing2.
[PFS.Tool.production.Quantity.report.v1.6.Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4165439/PFS.Tool.production.Quantity.report.v1.6.Dcube.xlsx)

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start testing 2 & Prepare the Testing Documents

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly allocate this report to Developers to correct the Report

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@ Raju Sir,
 
The Report Doesn't have New tool Info. Kindly Allocate this report to Developer.

Tool Code : 
1.TLM005
2. T/PS/HEX

Ragards,
Manivel A

**Comment by Narendiranath** [comment]
Hi Basha,

                Development completed. Kindly check.

**Comment by basha123456** [comment]
Dear Raju Sir,

PFA ..refer validations sheet. this needs to b
[PFS.Tool.production.Quantity.report.v1.6.Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4306972/PFS.Tool.production.Quantity.report.v1.6.Dcube.xlsx)
e development rework

**Comment by basha123456** [comment]
[PFS.Tool.production.Quantity.report.v1.6.Dcube.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4324053/PFS.Tool.production.Quantity.report.v1.6.Dcube.xlsx)
@Narendiranath : PFA..refer data sheet

**Comment by Narendiranath** [comment]
[Tool_Produ_Qty_System_Generated_Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4328955/Tool_Produ_Qty_System_Generated_Report.xlsx)
@basha123456 : I attached System generated Tool production quantity report. Kindly check with your test data and revert back.

**Comment by Narendiranath** [comment]
PFA for 
[Tool Production Quantity Report - System Generated As On 16-03-2020.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4336918/Tool.Production.Quantity.Report.-.System.Generated.As.On.16-03-2020.xlsx)

Updated Tool Production Quantity Report

**Comment by basha123456** [comment]
@raju-kurup 
Sir,
As discussed, customer has agreed for the following changes.
1. Modification date to be changed as Work order date.
2. Work Order number required insted of columns Reason & Work Done.
Signed document is attached for your reference. 
PFS is updated.
![Tool Prodution qty changes](https://user-images.githubusercontent.com/47315921/76742518-367b6300-6797-11ea-8ef6-1f69471538c2.jpg)
[PFS.Tool.production.Quantity.report.v1.6.Dcub.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4337329/PFS.Tool.production.Quantity.report.v1.6.Dcub.xlsx)

**Comment by raju-kurup** [comment]
@ Naren : please do the correection as mentioned.

**Comment by badamnarendra028** [comment]
Hi Basha,

            Changes are done. Kindly check.

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start Testing2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@raju-kurup 
Sir, we are facing the below errors while testing.
1. when i generate report only for the tool. manufacturing date is coming. minimum date in the parameter log history is picking. for this tool manufaturing date is not there.
![image](https://user-images.githubusercontent.com/47315921/77551048-dba0e480-6ed7-11ea-88dd-35ac5b872c4d.png)
2. when i generate report for all tools manufacturing date is not fetching. 
3. Work order number duplication is happening.  work order number is fetching.
![image](https://user-images.githubusercontent.com/47315921/77551551-80232680-6ed8-11ea-9878-702f94890123.png)
i have included conditions in PFS and marked in yelllow.
please assign to developer for these corrections.

**Comment by Narendiranath** [comment]
Hi Basha,

                Changes are done. Kindly check

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing1 completed. PFA of testing documents.

Test case1: [Test.Case - Tool Production Qty.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4398516/Test.Case.-.Tool.Production.Qty.xlsx)
Test Result1: [Test Result. Tool Production Qty report.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4398515/Test.Result.Tool.Production.Qty.report.docx)

**Comment by srinivasanbaskaran** [comment]
Manivel, 

Kindly start the Testing 2 & Prepare the Testcase as per our format

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 2 Completed. Please Find the Attached Document.

Test Case : [Test case _ Tool Production Qty DCUBE.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4406982/Test.case._.Tool.Production.Qty.DCUBE.xlsx)

Test Result : [Tool Production Qty Dcube Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4407005/Tool.Production.Qty.Dcube.Report.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Naren,

Kindly update the :atest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by Narendiranath** [comment]
Srini,

I attaached Deliverables for Tool Production Quantity Report. Kindly check.
[Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4413254/Deliverables.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

Tool Production Quantity Report testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [PFS.Tool.production.Quantity.report.v1.6.Dcub.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414619/PFS.Tool.production.Quantity.report.v1.6.Dcub.xlsx)

DELIVERABLES: [Tool Production Quantity_Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4414626/Tool.Production.Quantity_Deliverables.zip)

TESTCASE1: [Test.Case.-.Tool.Production.Qty.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414655/Test.Case.-.Tool.Production.Qty.xlsx)

TEST RESULT1: [Test.Result.Tool.Production.Qty.report.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414660/Test.Result.Tool.Production.Qty.report.docx)

TESTCASE2: [Test.case._.Tool.Production.Qty.DCUBE.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414661/Test.case._.Tool.Production.Qty.DCUBE.xlsx)

TEST RESULT2: [Tool.Production.Qty.Dcube.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414664/Tool.Production.Qty.Dcube.Report.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the Signed Copy of the Toll Production Quantity Rpeort

Signed Copy: 
![Tool Production Qty - Signed Copy](https://user-images.githubusercontent.com/46194039/78131095-19ea5680-7438-11ea-8a4d-c2ac98daed1d.jpg)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Developed completed, tested and deliverables attached, so closing this issue.

**Comment by basha123456** [comment]
@raju-kurup 

Sir, in the Dcube Input Screen, when we select ALL in the Parameter values and execute the report..below error is coming.
![image](https://user-images.githubusercontent.com/47315921/81895004-cb9bac00-95ce-11ea-9cbf-7980ee7384d5.png)
In the Parameter values lens search Equipments are also showing..we need only tools as per PFS..
![image](https://user-images.githubusercontent.com/47315921/81896300-f89d8e00-95d1-11ea-9175-a990bdb13f46.png)

**Comment by basha123456** [comment]
@raju-kurup 

in the input screen we need Description of the Tools, but it is showing Tool codes. need to assign developer to do this correction. highlighted with yellow colour.

[PFS.Tool.production.Quantity.report.v1.6.Dcub.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4661162/PFS.Tool.production.Quantity.report.v1.6.Dcub.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : In the Parameter values lens search now Tool code is coming, we need Tool description, please do this correction. Naren has done this report.

**Comment by karthikeyanamitysoft** [comment]
Dear naren ,

Solve the issue and attach the deliverables

**Comment by Narendiranath** [comment]
Hi Basha,

Changes are done. Kindly check.


![image](https://user-images.githubusercontent.com/59695578/82725762-e7a0fb00-9cfc-11ea-8327-8da9dafb701d.png)
[Latest Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4671406/Latest.Deliverable.zip)

**Comment by basha123456** [comment]
@raju-kurup 

only for some Tools data is fetching in the report. please assign to Naren for checking this issue.

**Comment by basha123456** [comment]
@raju-kurup 

Sir, now report is generating for all tools.

**Comment by srinivasanbaskaran** [comment]
@Manimahat,

Kindly do Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup ,

sir..we have hardcoded parameter decription as TOOL CONSUMPTION for parameter log value updation..but system is updating for other parameter description also.
and the Parameter value calculation is also wrong..please assign to developer

Updated PFS : [PFS.Tool.production.Quantity.report.v1.6.Dcub.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4715049/PFS.Tool.production.Quantity.report.v1.6.Dcub.xlsx)

Result : [TLM005 value wrongly updated.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4715053/TLM005.value.wrongly.updated.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do 1 correction mentioned above by Mani and Naren has done this report

**Comment by Narendiranath** [comment]
Hi Manivel,

                Changes are Done. Kindly check and revert back. PFA for your reference
![TLM005_Query](https://user-images.githubusercontent.com/59695578/83723472-63d00280-a65c-11ea-9914-dc7c98b08512.jpg)
[TLM005_Test_Data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4728022/TLM005_Test_Data.xlsx)

**Comment by Manimahat** [comment]
Hi srinivasan,

Testing 2 Completed. kidly check & move.now report is generating for all tools

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly update the Testcase1 ASAP

**Comment by srinivasanbaskaran** [comment]
Sir,

Tool Production Quantity Report testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [PFS.Tool.production.Quantity.report.v1.6.Dcub.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414619/PFS.Tool.production.Quantity.report.v1.6.Dcub.xlsx)

DELIVERABLES: [Tool Production Quantity_Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4414626/Tool.Production.Quantity_Deliverables.zip)

TESTCASE1: [Test.Case.-.Tool.Production.Qty.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414655/Test.Case.-.Tool.Production.Qty.xlsx)

TEST RESULT1: [Test.Result.Tool.Production.Qty.report.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414660/Test.Result.Tool.Production.Qty.report.docx)

TESTCASE2: [Test.case._.Tool.Production.Qty.DCUBE.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414661/Test.case._.Tool.Production.Qty.DCUBE.xlsx)

TEST RESULT2: [Tool.Production.Qty.Dcube.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4414664/Tool.Production.Qty.Dcube.Report.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested.  Delivered and acccepted by customer

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft   : please deploy this in live server.

**Comment by Narendiranath** [comment]
Hi Srinivasan Baskaran,

     Report deployed in live server. PFA Latest Deliverable.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5764357/Deliverable.zip)

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Tool production Quantity Report Deployed Successfully in Live Server.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
