### ISSUE TITLE
S&S : Dispatch Schedule report

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#54]
Dear Karthi,

Please find the  **Dispatch Schedule Report PFS V 1.0** for your reference.

PFS :

Thanks and Regards,
M. Maheshwaran

**Comment by maheshwaran-m** [comment]
This report is not required.

Regards,
M.Maheshwaran.

**Comment by raju-kurup** [comment]
Customer needs this report so we are developing

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Please provide format to prepare PFS

**Comment by srinivasanbaskaran** [comment]
Sir,

Dispatch Schedule Report PFS has been completed. Kindly Review the same & Proceed to further development

PFS: [01_Dispatch Schedule_PFS_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4452732/01_Dispatch.Schedule_PFS_v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Dispatch Schedule Report PFS has been completed. Kindly Review the same & Proceed to further development

PFS: [01_Dispatch Schedule_PFS_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4464857/01_Dispatch.Schedule_PFS_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please develop this new report.  Test case will be given by Srini today

**Comment by GayuSri** [comment]
Design has been completed. Rtrack raised for deliverables. Rtrack id : JCIE-254

**Comment by srinivasanbaskaran** [comment]
Gayathri,

Please find the Test Data..

TD: [Test Data - Dispatch Schedule Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4501332/Test.Data.-.Dispatch.Schedule.Report.xlsx)

**Comment by GayuSri** [comment]
Development has been completed. Kindly check. 
Here by, I have been attached the deliverables also.

[01_Dispatch.Schedule_Deliverables_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4509621/01_Dispatch.Schedule_Deliverables_v1.1.zip)

**Comment by srinivasanbaskaran** [comment]
Testing 1 will be done by Srinivasan

**Comment by srinivasanbaskaran** [comment]
HOLD.... Due to Other Sales Reports

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS. 

PFS: [01_Dispatch Schedule_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4614802/01_Dispatch.Schedule_PFS_v1.2.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do 1 correction, SO Status Authorized to be added.  Please take in high priority.  Test data attached

**Comment by karthikeyanamitysoft** [comment]
nandini,

Only only correction SO status should be authorized , Not in Open status.
Please changes the status from open to authorized.

Regards,
Karthi

**Comment by karthikeyanamitysoft** [comment]
@Nandhineedevi 

status should be in both Open and authorized
REgards,
Karthi

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The below changes has been done in addition to above said point.

1. Variant "##" has been replaced
2. Null values has been handled
3. Hardcoded company name has been replaced with OU based company name
4. Carrier code description has been fetched instead of carrier code
5. City and state against shipping Id has been fetched instead of Shipping ID
6. Transport mode description has been fetched instead of Transport mode code and checklist condition also been handled for all OU except GmbH

[dispatch test output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4615406/dispatch.test.output.pdf)
[disschrpt_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4615408/disschrpt_v2.1.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

PFA of Latest open poiints

![IMG_20200514_141903_20200514_142017934](https://user-images.githubusercontent.com/46194039/82199515-67a11c80-991b-11ea-9ba2-d05ba2ea9342.jpg)

**Comment by srinivasanbaskaran** [comment]
Basha,

Start testing 1 & Prepare the testcase 

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

PFS is updated as per the customer requirement. kindly review.

In the Existing report output, need to correct the following.
1. for 0 qty also report is generating.
2. In GmbH OU, need to deploy the screen.

[01_Dispatch.Schedule_PFS_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4688890/01_Dispatch.Schedule_PFS_v1.2.xlsx)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

PFA of updated PFS.

PFS: [01_Dispatch.Schedule_PFS_v1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4695916/01_Dispatch.Schedule_PFS_v1.3.xlsx)

Test Data: 
[Test.Data.-.Dispatch.Schedule.Report_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4695919/Test.Data.-.Dispatch.Schedule.Report_v1.1.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per the PFS and test data is also attached.

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

[schedule_test_output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4701859/schedule_test_output.pdf)
[disschrpt_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4701867/disschrpt_v2.2.zip)

Regards
Nandhinee Devi

**Comment by basha123456** [comment]
@srinivasanbaskaran 

1. The number of data generating as on 3105 & 0106 is different. 
2. SO done on 0106 but it is appearing in the 3105 report.

Attaching both the o/p report for ur ref. please check & move.
[as on 0106.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4712191/as.on.0106.pdf)
[ason 3105.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4712193/ason.3105.pdf)

**Comment by srinivasanbaskaran** [comment]
@Raju Sir,

Please refer above msg from Basha.. 

Need to Review..

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : this report has some variation in no of sale order fetching betn 31/05 and 01/06.  Test data upto 01.06.2020 is attached, Nandhinee has done this report lastly.

**Comment by Nandhineedevi** [comment]
Hi Basha,
The rework has been completed. Kindly check and revert back.

[as on 02_06.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4722069/as.on.02_06.pdf)
[as on 31_05.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4722071/as.on.31_05.pdf)
[srpdsr_print__grd1_gr_v2.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4722077/srpdsr_print__grd1_gr_v2.4.zip)

Regards
Nandhinee Devi

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing1 completed. please check & move.

[as on 0406 - dev.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4729310/as.on.0406.-.dev.xlsx)
[as on 0406 - sys.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4729311/as.on.0406.-.sys.xlsx)
[as on 3105 - dev.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4729312/as.on.3105.-.dev.xlsx)
[as on 3105 - sys.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4729316/as.on.3105.-.sys.xlsx)
[Test case - dispatch schedule report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4729318/Test.case.-.dispatch.schedule.report.xlsx)

**Comment by srinivasanbaskaran** [comment]
@Manimahat,

Kindly start the Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@Basha,

Please Check the Mode of transportation Field Value.

Regards,
Manivel A

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Please check the testing 1 test results and confirm the logic of mode of transport field.

**Comment by basha123456** [comment]
@raju-kurup 

PFS is updated. kindly assign developer for these changes.
[Daily.dispatch.report_PFS.V.1.2 (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4763465/Daily.dispatch.report_PFS.V.1.2.1.xlsx)

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Kindly review the updated PFS & allocated to Developers.

Updated PFS: [01_Dispatch.Schedule_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5102471/01_Dispatch.Schedule_PFS_v1.4.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as mentioned in  PFS.  Previously we have taken it from Sale order now it should be taken from Packslip.

**Comment by Nandhineedevi** [comment]
[srpdsr_print__grd1_gr_v2.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5107341/srpdsr_print__grd1_gr_v2.3.zip)
[daily1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5107343/daily1.pdf)

**Comment by Manimahat** [comment]
@Nandhineedevi ,

Variant Code Column missing in this report & Increase the size of the company Name. Other logic working correctly.

![image](https://user-images.githubusercontent.com/55881685/91009694-c05d1100-e5fe-11ea-9de1-1b9c4cc5e062.png)

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
Completed

[daily1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5116859/daily1.pdf)
[srpdsr_print__grd1_gr_v2.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5116873/srpdsr_print__grd1_gr_v2.4.zip)

**Comment by Manimahat** [comment]
@Nandhineedevi ,

1. The product description is not fetching fully for Some Variant combination - Refer this So in the report SO/1920/0360/P1.
2. Product Group & Product Description Column Size to be increased Because of The Name feched more than two or three lines it is touching both upper & Lower Column Line. 

![image](https://user-images.githubusercontent.com/55881685/91108360-7bd08480-e695-11ea-96c2-774602136c9a.png)

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
Hi Mani,
check now

[srpdsr_print__grd1_gr_v2.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5121971/srpdsr_print__grd1_gr_v2.5.zip)
[daily1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5121974/daily1.pdf)

**Comment by Manimahat** [comment]
@Nandhineedevi ,

Please remove the Variant column in this report.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 Completed. Kindly proceed Testing 2 process.

Test Case : [Test Case _ Dispatch Schedule Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5136506/Test.Case._.Dispatch.Schedule.Report.xlsx)

Test Result : [Dispatch Scedule Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5136510/Dispatch.Scedule.Report.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Faizal, 

Kindly Start Testing 2 & Prepare the Testing Documents

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Kindly check.

Test Case : 
[Test.Case._.Dispatch.Schedule.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5141664/Test.Case._.Dispatch.Schedule.Report.xlsx)

Test Result : 
[Dispatch.Scedule.Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5141666/Dispatch.Scedule.Report.pdf)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Daily Dispatch Schedule Report Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [01_Dispatch.Schedule_PFS_v1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145062/01_Dispatch.Schedule_PFS_v1.4.xlsx)

DELIVERABLES: [srpdsr_print__grd1_gr_v2.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5145065/srpdsr_print__grd1_gr_v2.5.zip)

TESTCASE1: [Testcase1_.Dispatch.Schedule.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145053/Testcase1_.Dispatch.Schedule.Report.xlsx)

TEST RESULT1: [TestResutl1_Dispatch_Scedule_Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5145056/TestResutl1_Dispatch_Scedule_Report.pdf)

TESTCASE2: [Test.Case._.Dispatch.Schedule.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5145047/Test.Case._.Dispatch.Schedule.Report.xlsx)

TEST RESULT2: [Dispatch.Scedule.Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5145048/Dispatch.Scedule.Report.pdf)

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Kindly add two Columns for Pack Slip No. & Shipping Date in the Report & make other Changes like below Screen Shot 

Test Case: [01_Dispatch.Schedule_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5161112/01_Dispatch.Schedule_PFS_v1.5.xlsx)

Refer Screenshot : ![image](https://user-images.githubusercontent.com/55881685/91960682-d61db500-ed27-11ea-8d5d-e0d94a5cf044.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction of inserting Column of packslip no and Shipping date.  And also please do correction in qty and page no.

**Comment by badamnarendra028** [comment]
[dispatched_shedule-03-09.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5168290/dispatched_shedule-03-09.zip)
completed kindly check and revert

**Comment by Manimahat** [comment]
@badamnarendra028 ,

As discussed please Make the Changes in Page No. & Created By .

Regards,
Manivel A

**Comment by badamnarendra028** [comment]
[dispatch.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5169006/dispatch.pdf)
completed kindly check and revert

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 completed. Kindly Start the Testing 2 Process.

Test Case : [Test Case _ Dispatch Schedule Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5174949/Test.Case._.Dispatch.Schedule.Report.xlsx)

Test Result : [Dispatch Schedule_Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5174951/Dispatch.Schedule_Report.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Faizal, 

Kindly start Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@srinivasanbaskaran 

Testing 2 is completed.
Kindly check.

Test Case : 
[Test.Case 2._.Dispatch.Schedule.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5201694/Test.Case.2._.Dispatch.Schedule.Report.xlsx)

Test Result : 
[Dispatch.Scedule.Report.2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5201697/Dispatch.Scedule.Report.2.pdf)

Regards,
Faisal

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Dispatch Schedule Report testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [01_Dispatch.Schedule_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5243757/01_Dispatch.Schedule_PFS_v1.5.xlsx)

DELIVERABLES: [dispatched_shedule-03-09.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5243762/dispatched_shedule-03-09.zip)

TESTCASE1: [Test Case _ Dispatch Schedule Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5174949/Test.Case._.Dispatch.Schedule.Report.xlsx)

TEST RESULT1: [Dispatch Schedule_Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5174951/Dispatch.Schedule_Report.pdf)

TESTCASE2: [Test.Case 2._.Dispatch.Schedule.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5201694/Test.Case.2._.Dispatch.Schedule.Report.xlsx)

TEST RESULT2: [Dispatch.Scedule.Report.2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5201697/Dispatch.Scedule.Report.2.pdf)

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[Uploading dispatched_shedule-03-09 (2).zip…]()

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer gave the Confirmation to close this ticket.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Customer gave the confirmation dt 11.10.2020, so closing this development

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Item- Variant to be Handled in this Report

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Please review the Updated PFS & allocated to Developers.

Updated PFS: [01_Dispatch.Schedule_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5752903/01_Dispatch.Schedule_PFS_v1.6.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per PFS.

**Comment by Nandhineedevi** [comment]
Completed.

[disschrpt_v2.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5800879/disschrpt_v2.3.zip)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 Completed. Kindly start the Testing 2 Process.

Test Case 1: [Test.Case._.Dispatch.Schedule.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5833003/Test.Case._.Dispatch.Schedule.Report.xlsx)

Test Result : [Dispatch schedule Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5833006/Dispatch.schedule.Report.pdf)

Regards,
Mnaivel A

**Comment by Manimahat** [comment]
@AkashGleen ,

Kindly Do testing 2 & prepare the Test case As per our Format.

Regards,
Manivel A

**Comment by AkashGleen** [comment]
Dear Sujin,

Dispatch Schedule Report Testing 2 Completed.

[Test Result Dispatch.schedule.Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5864383/Test.Result.Dispatch.schedule.Report.pdf)

[Test.Case.v2_.Dispatch.Schedule.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5864384/Test.Case.v2_.Dispatch.Schedule.Report.xlsx)

Regards,
Akash

**Comment by sujin1708** [comment]
@raju-kurup Testing 2 Conpleted ..kindly check and move to next level
Deliverables : [disschrpt_v2.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6252187/disschrpt_v2.3.zip)
Test Result 2 : [Test.Result.Dispatch.schedule.Report.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6252185/Test.Result.Dispatch.schedule.Report.pdf)
Test case 2 : [Test.Case.v2_.Dispatch.Schedule.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6252186/Test.Case.v2_.Dispatch.Schedule.Report.xlsx)

**Comment by raju-kurup** [comment]
Pl deploy this in   live server
--

**Comment by Nandhineedevi** [comment]
Completed

[Live Final Import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6269764/Live.Final.Import.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployment completed kindly close the ticket

**Comment by Manimahat** [comment]
@karthikeyanamitysoft ,

Need to Re-deploy the Latest Deliverables in the Live server. due to report not deployed properly.. Now we click the Print button dispatch schedule report it is showing " The report file dispatch_schedule_rpt is not deployed in Ramco DecisionWorks Application"

![image](https://user-images.githubusercontent.com/55881685/125932636-c2bdf13e-285d-4bda-ab4c-e43c20cf9a69.png)

Regards,
Manivel A

**Comment by karthikeyanamitysoft** [comment]
dont allocate to me directly, allocate to raju sir, Raju sir will consolidate and allocate to me.

**Comment by Manimahat** [comment]
@raju-kurup sir,

Need to Re-deploy the Latest Deliverables in the Live server. due to report not deployed properly.. Now we click the Print button dispatch schedule report it is showing " The report file dispatch_schedule_rpt is not deployed in Ramco DecisionWorks Application"

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Dispatch Schedule report has been deployed in Live Server Successfully. Please close this Ticket.

![image](https://user-images.githubusercontent.com/55881685/126155725-d6a8dc7d-2117-42fb-b829-1d14af270dee.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Report Developed and deployed in both Live and Test, so Closing this ticket.
