### ISSUE TITLE
S&S : Reminder Mail to Trigger For Quotation -Trigger

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#56]
Dear sir,

Please find the **Reminder mail trigger for QUO and Proforma PFS V 1.0** for your reference.

PFS : [01_JCIPL_Sales Quotation Mail trigger_PFS V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3696714/01_JCIPL_Sales.Quotation.Mail.trigger_PFS.V.1.0.xlsx)

Thanks and Regards,
M. Maheshwaran

**Comment by raju-kurup** [comment]
Karthi - Please start developing

**Comment by Nandhineedevi** [comment]
Hi Mahesh,
I have scheduled the mail trigger at 1:30AM in the morning everyday. 
For the Transaction SQT/1920/0013/P1, the customer "1403131"(AMOD INDUSTRIES) has no email ID.
Kindly update the mail id, so that mail will trigger. 
Kindly check and revert back. Please find the deliverables attached.

[jyoti_quo_schedule.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3890346/jyoti_quo_schedule.zip)

Regards
Nandhinee devi

**Comment by Prabakaran92** [comment]
@Nandhineedevi 
![image](https://user-images.githubusercontent.com/46194613/70205178-47085000-1749-11ea-8b83-b25296a04d89.png)

RFQ Number not fetching.

**Comment by Nandhineedevi** [comment]
Hi Prabakaran,
The Rework has been completed. Kindly check and revert back.
Please find the latest deliverables.

![mail](https://user-images.githubusercontent.com/52193780/70206517-d283e000-174d-11ea-9e9b-8b914817973c.jpg)
![mail1](https://user-images.githubusercontent.com/52193780/70206518-d283e000-174d-11ea-8adc-9c8f41feb7e3.jpg)

[jyoti_quo_schedule_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3925250/jyoti_quo_schedule_v1.1.zip)

Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Testing 1 completed kindly start testing 2.

**Comment by srinivasanbaskaran** [comment]
Akash,

Kindly start Testing 2 & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the below attached UAT changes points for your reference.

**1. Reminder   mail logic change as per Customer.**

Thanks and Regards,
M.Maheshwaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Please find the updated PFS for based on the Customer Requirements. 

PFS: [02_JCIPL_Sales Quotation Mail trigger_PFS V 1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4015461/02_JCIPL_Sales.Quotation.Mail.trigger_PFS.V.1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The UAT changes have been completed. Kindly check and revert back.

Regards
Nandhinee Devi

[jyoti_quo_schedule_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4018263/jyoti_quo_schedule_v1.2.zip)

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Remainder Mail came. But, 10 mins later only mail came.

Can you please reduce the mail timings.

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
If server is fast mean, the mail will trigger at once. We can't do anything with mail sending time.

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Remainder mail to Trigger for Sales Quotation testing has been completed.

Herewith, I have attached Testing Documents for future references.

PFS:[01_JCIPL_Sales.Quotation.Mail.trigger_PFS.V.1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4033744/01_JCIPL_Sales.Quotation.Mail.trigger_PFS.V.1.0.xlsx)

DELIVERABLES: [jyoti_quo_schedule_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4033759/jyoti_quo_schedule_v1.2.zip)

TESTCASE1:
TEST RESULT1:
TESTCASE2: [Remainder Trigger for Sale Quotation_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4033769/Remainder.Trigger.for.Sale.Quotation_TestCase2.xlsx)

TEST RESULT2: [Remainder Trigger for Sale Quotation_Test Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4033771/Remainder.Trigger.for.Sale.Quotation_Test.Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Prabakaran,

Kindly update the Testing 1 Documents & Revert 

Regards, 
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Testing 1 completed
Test case 1 : [Remainder Trigger for Sale Quotation_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4039262/Remainder.Trigger.for.Sale.Quotation_TestCase1.xlsx)

Test output : ![image](https://user-images.githubusercontent.com/46194613/72048720-716aa180-32e3-11ea-96c0-7077894a1291.png)

Kindly attach updated PFS 

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Remainder mail to Trigger for Sales Quotation testing has been completed.

Herewith, I have attached Testing Documents for future references.

PFS:[01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4050275/01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.1.xlsx)

DELIVERABLES: [jyoti_quo_schedule_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4033759/jyoti_quo_schedule_v1.2.zip)

TESTCASE1:[Remainder.Trigger.for.Sale.Quotation_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4050278/Remainder.Trigger.for.Sale.Quotation_TestCase1.xlsx)

TEST RESULT1: ![Remainder Trigger for Sale Quotation_Test Result1](https://user-images.githubusercontent.com/46194039/72214985-d536d980-3532-11ea-853e-f63317676d62.png)

TESTCASE2: [Remainder Trigger for Sale Quotation_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4033769/Remainder.Trigger.for.Sale.Quotation_TestCase2.xlsx)

TEST RESULT2: [Remainder Trigger for Sale Quotation_Test Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4033771/Remainder.Trigger.for.Sale.Quotation_Test.Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Remainder Mail Trigger Original requirement developed & Shown to the Users. They are Accepted. But they are asking a new format of Remainder. **This will be taken as the New Requirement & This will be deliver after UAT Sign Off. ** 

**Resolution Doc:** [01_Resolution Doc for Sales & Shipping OpenPoint 42.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4180202/01_Resolution.Doc.for.Sales.Shipping.OpenPoint.42.docx)

Kindly proceed further on this 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Please find the updated content as per the Customer;s Requirements

**

Date : 09/01/2020

Dear Sir / Madam, [ please see if we can use customer contact person Name]
Greetings from Jyoti Ceramic Ind. Pvt Ltd

In response to your enquiry dated 04/01/2020 we have submitted  our best offer No. SQT/1920/0055/P1 under cover of  our  emailed dated 04/01/2020
For your ready reference, our offer is reproduced as under:

Tabular column of the Item details will come

**

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@srinivasanbaskaran : First acknowledge the mail which you received this as New requirement, then update the PFS, then send it for review.

**Comment by srinivasanbaskaran** [comment]
Team,

PFA of latest poiints

![IMG_20200514_144219_20200514_144249806](https://user-images.githubusercontent.com/46194039/82198929-a1bdee80-991a-11ea-808e-9c619819ae1d.jpg)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Customer Acknowledged this... 

Kindly review this report & proceed further for Development.

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS for Remainder Mail Trigger for Sales Quotation

PFS: [01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4655119/01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Please do 1 correction in the report as discussed.

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

![image](https://user-images.githubusercontent.com/52193780/82530669-7a099900-9b5b-11ea-8420-99145c56c2e8.png)
![image](https://user-images.githubusercontent.com/52193780/82530704-8beb3c00-9b5b-11ea-8643-d08250ae845d.png)
[jyoti_quo_schedule_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4660923/jyoti_quo_schedule_v1.3.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Rate column to be added into the tabular column

**Comment by srinivasanbaskaran** [comment]
Raju Sir,  

Pleas find the attached updated PFS as per the User's requirement. 

This point was missed by amity from the begining itself. Now Sunil wants that point ( RATE ) to be include in the content of the mail. 

Based on that PFS updated.

PFS: [01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4667303/01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.3.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS along with Test Data.

PFS: [01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4709394/01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.4.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Rate column to be introduced.

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

![image](https://user-images.githubusercontent.com/52193780/83613593-a08af380-a5a1-11ea-81f5-ab7b0997b31e.png)
[jyoti_quo_schedule_v1.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4721904/jyoti_quo_schedule_v1.4.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
@Nandhineedevi,

Please find the attached image of the User regarding the column interchange. 

Please do the needful

IMG: 
![image_2020_06_03T10_09_30_776Z](https://user-images.githubusercontent.com/46194039/83790258-880bfd80-a6b5-11ea-84e7-0e7463f23085.png)

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

![image](https://user-images.githubusercontent.com/52193780/83842221-04d3c180-a720-11ea-8bc6-19bf4436c5a6.png)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 1 Completed. Please find the Testing Documents

PFS: [01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.4_Updated.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4739329/01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.4_Updated.xlsx)

TESTCASE1: [Remainder.Trigger.for.Sale.Quotation_TestCase1_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4739331/Remainder.Trigger.for.Sale.Quotation_TestCase1_v1.1.xlsx)

TEST RESULT1: ![image](https://user-images.githubusercontent.com/46194039/83935533-25f7e900-a7d8-11ea-8939-8080a13c6f98.png)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start the Testing 2

**Comment by Manimahat** [comment]
@srinivasanbaskaran,

Testing 2 Completed. please Find the Attached Document For your Reference.

Test Case : [Remainder.Trigger.for.Sale.Quotation_TestCase_2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4741538/Remainder.Trigger.for.Sale.Quotation_TestCase_2.xlsx)

Test Result : 
![image](https://user-images.githubusercontent.com/55881685/83963215-dd1c5f00-a8c1-11ea-8d58-624a3cf9854b.png)

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
Latest Delierables...

[jyoti_quo_schedule-v1.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4743923/jyoti_quo_schedule-v1.5.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

Trigger for Sales Quotation Testing has been completed. Herewith I have attached Testing documents for future references.

PFS: [01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.4_Updated_New.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4744062/01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.4_Updated_New.xlsx)

DELIVERABLES: [jyoti_quo_schedule-v1.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4744063/jyoti_quo_schedule-v1.5.zip)

TESTCASE1: [Remainder.Trigger.for.Sale.Quotation_TestCase1_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4744067/Remainder.Trigger.for.Sale.Quotation_TestCase1_v1.1.xlsx)

TEST RESULT1: ![Remainder Trigger for Sale Quotation_Test Result1_v1 1](https://user-images.githubusercontent.com/46194039/83996180-16fc6c80-a979-11ea-9313-6516c75b6771.png)

TESTCASE2: [Remainder.Trigger.for.Sale.Quotation_TestCase_2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4744070/Remainder.Trigger.for.Sale.Quotation_TestCase_2.xlsx)

TEST RESULT2: ![Remainder Trigger for Sale Quotation_Test Result2_v1 1](https://user-images.githubusercontent.com/46194039/83996203-27144c00-a979-11ea-8a8f-4f849efe78a7.png)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
I have modified the changes as given in the mail. 

For Customer name,
If you have provided in Customer->Contact Person-> First Name or Name, It will take otherwise Sir/Madam only will come. Kindly convey it to the user.

![image](https://user-images.githubusercontent.com/52193780/84469220-298ae480-ac9e-11ea-82e3-ff41682bf7b9.png)
[jyoti_quo_schedule_v1.6.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4768970/jyoti_quo_schedule_v1.6.zip)

Regards
Nandhinee Devi

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Quotaation Mail Trigger done. 

[Remainder.Trigger.for.Sale.Quotation_TestCase.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4777875/Remainder.Trigger.for.Sale.Quotation_TestCase.xlsx)
![image](https://user-images.githubusercontent.com/47315921/84614877-0b62f580-aee5-11ea-8612-74b9696d38db.png)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Need to "remove bold and under line for under cover of " in the content of the mail. 

Kindly do the needful 

Regards,
Srinivasan

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Need to remove bold and under line for "under cover of " in the content of the mail.

**Comment by Nandhineedevi** [comment]
[jyoti_quo_schedule_v1.7.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4792133/jyoti_quo_schedule_v1.7.zip)

**Comment by srinivasanbaskaran** [comment]
Mani,

Kindly Start the Testing 1 & Prepare the Testing Document

**Comment by Manimahat** [comment]
@srinivasan,

Testing 1 Completed. Trigger Mail has been Received.

Test Case : [Remainder.Trigger.for.Sale.Quotation_TestCase_1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4798024/Remainder.Trigger.for.Sale.Quotation_TestCase_1.xlsx)

Test Result : 
![image](https://user-images.githubusercontent.com/55881685/85011056-a75b5e00-b17e-11ea-91f1-ff38e5b0964d.png)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Team,

Remainder Mail Trigger for Sales Quotation Testing 2 completed.

TESTCASE2: [Remainder.Trigger.for.Sale.Quotation_TestCase2_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4803842/Remainder.Trigger.for.Sale.Quotation_TestCase2_v1.2.xlsx)

TEST RESULT2: [Remainder Trigger for Sale Quotation_Test Result2_v1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4803846/Remainder.Trigger.for.Sale.Quotation_Test.Result2_v1.2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir, 

Remainder Mail Trigger for Sales Quotation testing has been completed. Herewith I have attached testing documents for future references.

PFS: [01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.4_Updated_New.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4744062/01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.4_Updated_New.xlsx)

DELIVERABLES: [jyoti_quo_schedule_v1.7.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4803860/jyoti_quo_schedule_v1.7.zip)

TESTCASE1 : [Remainder.Trigger.for.Sale.Quotation_TestCase_1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4798024/Remainder.Trigger.for.Sale.Quotation_TestCase_1.xlsx)

TEST RESULT1: ![image](https://user-images.githubusercontent.com/55881685/85011056-a75b5e00-b17e-11ea-91f1-ff38e5b0964d.png)

TESTCASE2: [Remainder.Trigger.for.Sale.Quotation_TestCase2_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4803842/Remainder.Trigger.for.Sale.Quotation_TestCase2_v1.2.xlsx)

TEST RESULT2: [Remainder Trigger for Sale Quotation_Test Result2_v1.2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4803846/Remainder.Trigger.for.Sale.Quotation_Test.Result2_v1.2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir, 

As per Sunil confirmation through mail, we will proceed on this report. 

![image](https://user-images.githubusercontent.com/46194039/87430759-4c911700-c603-11ea-8c6c-1d46ae614cca.png)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Report developed, tested and accepted by Jyoti team

**Comment by raju-kurup** [comment]
Pl do the correction of Variant logic as per PFS

**Comment by Manimahat** [comment]
@Nandhineedevi ,

Please find the below Attached PFS for your reference.

Updated PFS: [01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5773597/01_JCIPL_Sales.Quotation.Mail.trigger_PFS.v.1.5.xlsx)

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
Completed.

![mail](https://user-images.githubusercontent.com/52193780/104116253-e2042e00-533c-11eb-9876-7ccb74eb66d1.jpg)
[jyoti_quo_schedule_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5792337/jyoti_quo_schedule_v2.1.zip)

**Comment by Manimahat** [comment]
@Nandhineedevi ,

Trigger is not Generated while Click the Print button in View Quotation. Please check & Resolve.

Test data : SQT/2021/0036/P1

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
Completed.

![trigger](https://user-images.githubusercontent.com/52193780/104876649-22d3f680-597e-11eb-9e02-d4b60cabc86b.png)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 completed. Kindly start testing 2 Process.

Test case : [Remainder.Trigger.for.Sale.Quotation_TestCase1_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5832977/Remainder.Trigger.for.Sale.Quotation_TestCase1_v1.1.xlsx)

Test Result:
![image](https://user-images.githubusercontent.com/55881685/104975550-f4f3be00-5a20-11eb-9a8d-26f71f9fd89a.png)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@AkashGleen kindly do the testing 2

**Comment by Manimahat** [comment]
@Nandhineedevi ,

 Kindly Remove the below Logic in the Coding. Remaining things is Ok. 

If Sale UOM is PER100 means Quantity should multiplied with 100 & Rate divided by 100.

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
@Manimahat 

PER100 Logic has been removed

[jyoti_quo_schedule_v2.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5956356/jyoti_quo_schedule_v2.3.zip)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 completed. Kindly start testing 2 Process.

Test case : [Remainder.Trigger.for.Sale.Quotation_TestCase1_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6240457/Remainder.Trigger.for.Sale.Quotation_TestCase1_v1.0.xlsx)

Test Result: [jyoti_quo_schedule_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5828102/jyoti_quo_schedule_v2.2.zip)
![trigger](https://user-images.githubusercontent.com/52193780/104877430-d093d500-597f-11eb-8b47-25904cdf4e8d.png)

Regards,
Manivel A

**Comment by sujin1708** [comment]
Testing 2 completed ..kindly check and move to next level
Test Case : [Remainder.Trigger.for.Sale.Quotation_TestCase2_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6241601/Remainder.Trigger.for.Sale.Quotation_TestCase2_v1.0.xlsx)
Deliverables : [jyoti_quo_schedule_v2.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6241603/jyoti_quo_schedule_v2.3.zip)

![Image](https://user-images.githubusercontent.com/47313592/113256166-6d5ee100-92e6-11eb-8d84-144ba34f3fbb.png)

**Comment by raju-kurup** [comment]
Pl deploy this in   live server
--

**Comment by Nandhineedevi** [comment]
Completed.

[Live Final Import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6283378/Live.Final.Import.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployment completed kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
