### ISSUE TITLE
S&S : Transportation cost Report for Month Basis - GmbH-Dcube

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#57]
Dear Karthi,

Please find the **Transportation cost Report for Month Basis Updated PFS V 1.0** for your reference.

**PFS :** [01_GmbH_Transportation cost list _PFS V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3624782/01_GmbH_Transportation.cost.list._PFS.V.1.0.xlsx)

**Ref.Doc.No :** 

Thanks and Regards,
M. Maheshwaran

**Comment by maheshwaran-m** [comment]
Prabakaran,

Kindly Start the PFS for Transportation cost report.

Regards,
M.Maheshwaran

**Comment by Prabakaran92** [comment]
Dear Team,

Please find the Transportation cost Report  PFS V 1.0 for your reference.

[01_GmbH_Transportation cost list _PFS V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3558904/01_GmbH_Transportation.cost.list._PFS.V.1.0.xlsx)

Regards,
Prabakaran A

**Comment by raju-kurup** [comment]
Dear Karthi,

Please start development

**Comment by karthikeyanamitysoft** [comment]
HRMS team working on that guidence with me and  Arunachalam

**Comment by Prabakaran92** [comment]
@Arunachalamamitysoft 

Please find the Updated Transportation cost Report for Month Basis  PFS V 1.1 for your reference.

PFS : [01_GmbH_Transportation cost list _PFS V 1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3645782/01_GmbH_Transportation.cost.list._PFS.V.1.1.xlsx)

Ref.Doc.No : COI/1920/0020/P1
Regards,
Prabakaran A

**Comment by Arunachalamamitysoft** [comment]
Dear prabakaran,
Development is completed ,kindly check and provide test data.

**Comment by Prabakaran92** [comment]
@Arunachalamamitysoft 

Plz change the correction.

Regards,
Prabakaran A

**Comment by Arunachalamamitysoft** [comment]
Dear Prabakaran,
Development completed,check and revert it back.

**Comment by Prabakaran92** [comment]
Dear Team,

Testing 1 completed.
Kindly Start Testing 2.

PFA

**PFS**                      : [02_GmbH_Transportation cost list _PFS V 1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3660978/02_GmbH_Transportation.cost.list._PFS.V.1.1.xlsx)

**Test Case**             : [Transportation cost Report Test case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3660979/Transportation.cost.Report.Test.case.xlsx)

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Hi,

Kindly start Test this report & Prepare the Test cases & Test Results 

Regards,

Srinivasan Baskaran

**Comment by Arunachalamamitysoft** [comment]
[Transportation_cost_rpt.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3675427/Transportation_cost_rpt.zip)

**Comment by knovakaspar** [comment]
Dear Srinivasan

                        Testing 2 completed.kindly check and update any issues.


Regards,
Nova
[transportation cost for monthly basis.test case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3676066/transportation.cost.for.monthly.basis.test.case.xlsx)
[transportation cost for monthly basis.test result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3676067/transportation.cost.for.monthly.basis.test.result.xlsx)
[transportation cost monthly base.test data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3676068/transportation.cost.monthly.base.test.data.xlsx)

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly update the Test Result for Testing 1

Regards,

Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Transportation cost report Test result format not support in Github
I shared in Skype Jyoti group.
Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
TEST RESULT 1:[Jyoti_Transporation Cost Report for month Basis_Test Result_1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3712879/Jyoti_Transporation.Cost.Report.for.month.Basis_Test.Result_1.xlsx)

**Comment by raju-kurup** [comment]
Developed completed.

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly show this report User ( Sunil ) & Confirm me to Close the development

Regards,
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
This Report customer( Sunil )  Accepted But some change required
Point 
1. Manual fields need data save some where and fetch the report at the time of print.
Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Sir,

Kindly Review the above changes & Allocate to Developers 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Already show this to User ( Mr.Sunil ). Waiting for his confirmation

Regards,
Srinivasan Basakaran

**Comment by srinivasanbaskaran** [comment]
Team,

Mr. Sunil confirmed the Same & We can Close this ticket

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@srini :  please update the documents needed

**Comment by srinivasanbaskaran** [comment]
Sir,

Transportation Cost Report for month basis report testing has been completed.

Testing documents are attached for future references.

PFS: [02_GmbH_Transportation.cost.list._PFS.v.1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794198/02_GmbH_Transportation.cost.list._PFS.v.1.1.xlsx)

DELIVERABLES: [Transportation_cost_rpt.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3794326/Transportation_cost_rpt.zip)

TEST CASE 1: [Transportation_Cost_Report_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794221/Transportation_Cost_Report_TestCase1.xlsx)

TEST RESULT 1: [Jyoti_Transporation.Cost.Report.for.month.Basis_Test.Result_1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794224/Jyoti_Transporation.Cost.Report.for.month.Basis_Test.Result_1.xlsx)

TEST DATA 2: [transportation.cost.monthly.base.test.data.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794230/transportation.cost.monthly.base.test.data.xlsx)

TEST CASE 2: [transportation.cost.for.monthly.basis.test.case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794232/transportation.cost.for.monthly.basis.test.case.xlsx)

TEST RESULT 2: [transportation.cost.for.monthly.basis.test.result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3794236/transportation.cost.for.monthly.basis.test.result.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed, so closing this issue

**Comment by raju-kurup** [comment]
Development completed, so closing this issue

**Comment by raju-kurup** [comment]
Customer accepted and waiting for signature

**Comment by raju-kurup** [comment]
Customer accepted and waiting for signature

**Comment by srinivasanbaskaran** [comment]
Team,

PFA of Latest Open Points 

![IMG_20200514_170346_20200514_170403047](https://user-images.githubusercontent.com/46194039/82200000-15143000-991c-11ea-97a1-885add67e5ce.jpg)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS for Transporatation Cost Report for month basis - GmbH

PFS: 
[02_GmbH_Transportation.cost.list._PFS.v.1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4655427/02_GmbH_Transportation.cost.list._PFS.v.1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction of 2 field of 1 logic which is mentioned in PFS..

**Comment by Narendiranath** [comment]
Hi Srini,

              Changes are done. Kindly check.PFA
[Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4666456/Deliverables.zip)

[Transportation Cost Report - Result.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4666466/Transportation.Cost.Report.-.Result.xlsx)

**Comment by srinivasanbaskaran** [comment]
Basha,

Start Testing 1 & Prepare Testcase

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing1 completed. please check & move.
[TC1 TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4688115/TC1.TR.pdf)
[TC2 TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4688116/TC2.TR.pdf)
[Test.Case.-Transportation cost Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4688122/Test.Case.-Transportation.cost.Report.xlsx)

**Comment by srinivasanbaskaran** [comment]
Manivel,

Start Testing 2 & Prepare Testcase

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 2 Completed. PFA of Testing Documents

Testcase2: [Transportation Cost Report_Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4716351/Transportation.Cost.Report_Testcase2.xlsx)

Test Result2: [Transportation Cost Report_TR2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4716352/Transportation.Cost.Report_TR2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly update the Testing Documents properly

**Comment by basha123456** [comment]
@srinivasanbaskaran 

PFA of Test case.
[Test.Case1-Transportation cost Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4716729/Test.Case1-Transportation.cost.Report.xlsx)

**Comment by srinivasanbaskaran** [comment]
Sir,

Transportation Cost Report for Month Basis - GmbH Testing has been completed. Herewith I have attached Testing Documents for future referecnes.

PFS: [02_GmbH_Transportation.cost.list._PFS.v.1.2 (1).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4731625/02_GmbH_Transportation.cost.list._PFS.v.1.2.1.xlsx)

DELIVERABLES: [Deliverables_Transportation Cost Report.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4731629/Deliverables_Transportation.Cost.Report.zip)

TESTCASE1: [Test.Case1-Transportation.cost.Report.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4731633/Test.Case1-Transportation.cost.Report.xlsx)

TEST RESULT1: [TC1_TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4731634/TC1_TR.pdf)

TESTCASE2: [Transportation.Cost.Report_Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4731636/Transportation.Cost.Report_Testcase2.xlsx)

TEST RESULT2: [Transportation.Cost.Report_TR2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4731638/Transportation.Cost.Report_TR2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Kindly close this ticekt. Customer gave confirmation through mail dated on 18-09-2020.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Being customer given clearance, we are closing this ticket

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by karthikeyanamitysoft** [comment]
Dear Mohana,

Kindly get the latest deliverables and deploy the same into live server.

Regards,
Karthi

**Comment by mohanaamity** [comment]
@raju-kurup Sir

Deployment completed in live server.

Regards,
Mohana B

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Transportation Cost Report Deployed Successfully in Live server. Please Close this ticket.

Regards,
Manivel A

**Comment by mohanaamity** [comment]
Latest Deliverables.

[Transportation_cost_rpt.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5796033/Transportation_cost_rpt.zip)

Regards,
Mohana B

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
