### ISSUE TITLE
S&S : Packing Note Print Domestic and Exports for Gmbh & JCIPL-RDW

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#60]
Dear Karthi,

Please find the ** **Packing Note Print Domestic and Exports for Gmbh & JCIPL** PFS V 1.0** for your reference.

PFS : [01_Packing List_PFS V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3890589/01_Packing.List_PFS.V.1.0.xlsx)

Thanks and Regards,
M. Maheshwaran

**Comment by maheshwaran-m** [comment]
Prabakaran,

Kindly start Packing list PFS for development process.

Regards,
M.Maheshwaran

**Comment by Prabakaran92** [comment]
@raju-kurup 
Dear sir,
Pcacking slip PFS completed,
Kindly check and revert.
Regards,
Prabakaran A

**Comment by karthikeyanamitysoft** [comment]
allocated to Narendaranath.
EDK completed by Bhadam.

**Comment by badamnarendra028** [comment]
[JCIE - 126new.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3910923/JCIE.-.126new.zip)

**Comment by karthikeyanamitysoft** [comment]
Dear Bhadam,

Report logic completed by Naren Rao, SAve button newly added, kindly do the Coding for the SAve button.
Regards,
Karthi

**Comment by badamnarendra028** [comment]
save button logic done

**Comment by maheshwaran-m** [comment]
@Prabakaran92 

Kindly Start Packing list Testing 1 process and attached all required document for Testing 2 process.
Before starting UAT we need to complete.

Regards,
M.Maheshwaran

**Comment by Prabakaran92** [comment]
@karthikeyanamitysoft 
PF Above Points In Pack slip Print.
1.Item Duplication
2.Create Not Fetching
3.Packed in not fetching
4. Item category wise Not fetching
5. UOM duplication
6. Item description duplication
7. Total Qty,Net Wt,Gross Wt  value Wrong
8.S.No Line missing
9. Border Alignment check
10.All decimal value Two zeros enough

Packslip UDS
1. Ref No field changed (Packslip)

Kindly check the above points 
Regards,
Prabakaran A

**Comment by karthikeyanamitysoft** [comment]
Dear Prabha,

Take call with Narendranath, and close all the issues.

Regards,
Karthi

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
As we discussed kindly follow this report.

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the below attached UAT changes points for your reference.

**1. Attach   note not fetching.
2. Pack slip   UDS( Ref No field changed SO number)
3. Customer   Order is not fetching.
4. All the   Manual entry fields should be in Alphanumeric.**

Thanks and Regards,
M.Maheshwaran.

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Please find the Attached PFS for Packing List

PFS: [01_Packing.List_PFS.v.1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4025262/01_Packing.List_PFS.v.1.2.xlsx)

**NOTE: At the time of starting the development, Kindly call me, Need to discuss on this changes**

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Naren,

PFA of Updated PFS.

PFS: [01_Packing.List_PFS.v.1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4029093/01_Packing.List_PFS.v.1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Naren,

Pls find the above attached PFS 

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
Dear Srini,

kindly update the complete logic and attached the updated PFS.

Regards,
Karthi

**Comment by srinivasanbaskaran** [comment]
Karthi,

Please Find the attached updated PFS.

PFS: [01_Packing.List_PFS.v.1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4045061/01_Packing.List_PFS.v.1.3.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Narendiranath** [comment]
Hi Srini,

            In packing list report Mode of Transport & Destination is completed. Kindly check and revert back.

**Comment by srinivasanbaskaran** [comment]
Naren,

Please Change the below mentioned correction.

1. Packslip column name to be changed to Sale Order

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
how many time need to inform you,
dont allocate directly to developers
allocate to raju sir.

Regards,
Karthi

**Comment by srinivasanbaskaran** [comment]
Raju sir,

As discussed with you, Kindly do the needful 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju sir,

Please inform to the Developers to do the below mentioned changes.

1. Packslip column name to be changed to Sale Order
2. Numeric values are changed to Alphanumberic for Net weight & Gross weight columns

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Please do the correction as mentioned for sl.no: 1

**Comment by badamnarendra028** [comment]
packslip name changed to sale order no

**Comment by srinivasanbaskaran** [comment]
Need to do the changes.. PFS will update later

Regards,
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
Dear Team,
Kindly Refer the updated pack slip PFS
PFS : [01_Packing.List_PFS.v.1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4255194/01_Packing.List_PFS.v.1.4.xlsx)
Please do needful..

Regards,
Prabakaran A

**Comment by Nandhineedevi** [comment]
Hi Prabakaran,
The rework has been completed. Kindly check and revert back.

[Packinglist_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4269990/Packinglist_v2.1.zip)

Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
@Nandhineedevi 
Export benefit not fetching.
end line not close properly
Regards,
Prabakaran A

**Comment by Nandhineedevi** [comment]
Hi Prabakaran,
The rework has been completed. Kindly check and revert back.

[Packinglist_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4285230/Packinglist_v2.2.zip)

Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
@raju-kurup 
Kindly allocate Developer...
Regards,
Prabakaran A

**Comment by raju-kurup** [comment]
Nandhinee - Please do the correction

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Testing 1 completed Kindly start Testing 2
Test case : [Pack slip_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4291372/Pack.slip_TestCase1.xlsx)
Test output : [Pack slip Test output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4291379/Pack.slip.Test.output.pdf)

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly update the Latest Deliverables 

Regards,
Srinivasan Bakaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the attached deliverables.

[Packinglist_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4323254/Packinglist_v2.1.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Packslip Report Testing has been completed. Herewith I have attached Testing documents for future references.

PFS: [01_Packing.List_PFS.v.1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333902/01_Packing.List_PFS.v.1.4.xlsx)

PATH: Sales & Shipping --> Packslip --> View Packslip ( Packing List UDS ) 

DELIVERABLES: [Packinglist_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4333903/Packinglist_v2.1.zip)

TESTCASE1: [Pack.slip_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333910/Pack.slip_TestCase1.xlsx)

TEST RESULT1: [Pack.slip.Test.output.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4333911/Pack.slip.Test.output.pdf)

TESTCASE2: [Pack.slip_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4333923/Pack.slip_TestCase2.xlsx)

TEST RESULT2: [Test Result_Packslip.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4333926/Test.Result_Packslip.pdf)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Prabhakaran,
As per discussion, I have done validation for Export Scheme for splitting items. Kindly check and revert back.

[Packinglist_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4343356/Packinglist_v2.2.zip)

Regards
Nandhinee Devi

**Comment by Manimahat** [comment]
@raju-kurup Sir,

 We got Duplication records in UDS Screen. Kindly Allocate to developers.

Error Screen Shot : 
![image](https://user-images.githubusercontent.com/55881685/77390980-8bcdfa80-6dbd-11ea-8723-50edea714501.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@srinivasanbaskaran & @Manimahat : Issue now facing in packslip is due to Item code - variant combination introduction, please confirm with customer whether variant is needed or not, if needed whether it is to be reflected in packslip and Invoice print out.  Please confirm and update the PFS accordingly and check whether this was mentioned in SDD also.

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Please review the Updated PFS & Allocated to Developers.

Error Found : Email Id Is not fetching For customer Address as well Consignee adress. 

Screen Shot : 
![image](https://user-images.githubusercontent.com/55881685/77511338-e25b3780-6e96-11ea-872c-08f45df7519d.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please add email address in customer address and consignee address column, this is only correction

**Comment by Nandhineedevi** [comment]
Hi Mani,
The email has been added in the customer and consignee. Kindly check and revert back.

[ps_1920_0261_p1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4384992/ps_1920_0261_p1.pdf)
[Packinglist_v2.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4384993/Packinglist_v2.3.zip)

Regards
Nandhinee Devi

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Kindly Review the Update PFS & Allocated to Developers.

Updated PFS : [01_Packing.List_PFS.v.1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4399439/01_Packing.List_PFS.v.1.6.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Correction to be done in packslip
1. Logo to be added in Ziecon OU
2. Company name in signature column should come as per the OU Company name (for all Jyoti Ceramic Industries Pvt Ltd is coming)

**Comment by Nandhineedevi** [comment]
Hi Mani,
The rework has been completed. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by Manimahat** [comment]
@raju Sir,

Kindly Review the Updated PFS & Allocated To developers.

Updated PFS : [01_Packing.List_PFS.v.1.7.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4420428/01_Packing.List_PFS.v.1.7.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : Transportation mode is not coming and ODT format report taking to be needed.  Nandhini has done this report

**Comment by Manimahat** [comment]
Hi Srinivasan,

Testing 1 Completed. Kindly Proceed the Testing 2 Process.

Test Case : [Test Case_Pack Slip Print For MFG & GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4438791/Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx)

Test Result For MFG OU : [packing note print Ouput For MFG OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4438792/packing.note.print.Ouput.For.MFG.OU.pdf)

Test Result For GMBH OU : [Packing Note Print For GMBH OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4438797/Packing.Note.Print.For.GMBH.OU.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
@raju Sir,

Kinldy Review the Updated PFS & Allocated To developers.

Updated PFS : [01_Packing.List_PFS.v.1.8.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4468306/01_Packing.List_PFS.v.1.8.xlsx)

Regards,
Mnaivel A

**Comment by srinivasanbaskaran** [comment]
@raju-kurup,

kindly Review the Updated PFS & Allocated to developers.

Updated PFS : [01_Packing.List_PFS.v.1.9.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4486926/01_Packing.List_PFS.v.1.9.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : for this report only contact person should be added.  Please discuss with me while assigning

**Comment by karthikeyanamitysoft** [comment]
Dear Naren,

Only one New changes, "Contact Person" field should add in Report header , refer the attached PFS.
Please contact with Raju sir before start.

Dont Touch the existing coding at end of the coding you update the table with new field.
Regards,
Karthi

**Comment by Narendiranath** [comment]
Hi Manivel,

     "Contact Person" field is added in Report header. Kindly check. PFA
[PACKSLIP.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4491771/PACKSLIP.pdf)

**Comment by srinivasanbaskaran** [comment]
Hi Srinivasan,
Testing 1 completed. Kindly Proceed Testing 2 Process.

Test Case : [Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4496552/Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx)

Test Result for MFG : [PACKING LIST PRINT FOR MFG.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4496560/PACKING.LIST.PRINT.FOR.MFG.pdf)
 Test Result For GMBH :[PACKING LIST PRINT FOR GMBH.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4496561/PACKING.LIST.PRINT.FOR.GMBH.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start testing 2 & Prepare the Testing Documents

**Comment by basha123456** [comment]
@srinivasanbaskaran 

[PACKING NOTE GMBH OU TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4501874/PACKING.NOTE.GMBH.OU.TR.pdf)
[PACKING NOTE MFG OU TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4501875/PACKING.NOTE.MFG.OU.TR.pdf)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

PFS: [01_Packing.List_PFS.v.1.10.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4537963/01_Packing.List_PFS.v.1.10.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction, corrected point given in Notes.  Please allocate and do it in first priority

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS for the changes. 

PFS: [01_Packing.List_PFS.v.1.11.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4588612/01_Packing.List_PFS.v.1.11.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

PFA of Latest Open Points 

![1589456835912](https://user-images.githubusercontent.com/46194039/82200542-c4510700-991c-11ea-9a1c-5f3510f0813a.JPEG)

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Kindly review the Updated PFS & Allocated to Developers.

Updated PFS : [01_Packing.List_PFS.v.1.12.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4686432/01_Packing.List_PFS.v.1.12.xlsx)

Test Data : [test data For Pack Slip.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4686435/test.data.For.Pack.Slip.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction of alignment and signatory part and after doing correction ask technical to contact manivel and then transfer it to him.

**Comment by karthikeyanamitysoft** [comment]
Dear naren,

Kindly do the allignment changes.
note : please take backup of DW report.

Regards,
Karthi

**Comment by Narendiranath** [comment]
Hi Manivel,

  Changes are done. Kindly check. PFA Deliverables
[Latest Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4739952/Latest.Deliverables.zip)

**Comment by Manimahat** [comment]
@srinivasan,

Testing 1 Completed.  Kindly Start the Testing 2 Process.

Test case : [Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4745466/Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx)

Test Result For MFG OU: [Packing note Print_MFG OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4745470/Packing.note.Print_MFG.OU.pdf)

Test Result GMBH OU: [Packing note Print _ GMBH OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4745471/Packing.note.Print._.GMBH.OU.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly start Testing 2 & Prepare the Testing Documents

Regards,
Srinivasan Baskaran

**Comment by basha123456** [comment]
@Narendiranath 

In the UDS screen we are facing the below error in all the combo's. please resolve ASAP.
![image](https://user-images.githubusercontent.com/47315921/84055016-db41c100-a9d1-11ea-95ec-4c484c8311de.png)

**Comment by Narendiranath** [comment]
Hi Basha,

   Changes are done. Kindly check and revert back.
[Latest Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4749903/Latest.Deliverables.zip)

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing2 done. 

[Packing List MFG OU TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4750023/Packing.List.MFG.OU.TR.pdf)
[Packing List GMBH OU TR.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4750024/Packing.List.GMBH.OU.TR.pdf)

**Comment by Narendiranath** [comment]
Hi Srini,

              PFA Latest Deliverables.
[Latest Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4750122/Latest.Deliverables.zip)

**Comment by srinivasanbaskaran** [comment]
Pls handle Variant into the UDS screen

**Comment by srinivasanbaskaran** [comment]
Sir,

Packslip Report Testing has been completed. Herewith I have attached Testing Documents for future references.

PFS: [01_Packing.List_PFS.v.1.12.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4766828/01_Packing.List_PFS.v.1.12.xlsx)

DELIVERABLES: [Latest.Deliverables.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4766849/Latest.Deliverables.zip)

TESTCASE1: [Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4766850/Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx)

TEST RESULT1: [TR1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4766873/TR1.zip)

TESTCASE2: 

TEST RESULT2: [TR2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4766874/TR2.zip)

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju Sir,

As per user Requirement, Name & Designation Point will add in the MFG OU. I have updated the PFS As per the Requirement.

Already we Add the Employee Name Field in UDS Screen, Only need to Load the Data in that Field & Name & Designation will come in the Report.

Updated PFS : [01_Packing.List_PFS.v.1.13.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4916332/01_Packing.List_PFS.v.1.13.xlsx)


Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please add the name and designation in report only in MFG ou

**Comment by Narendiranath** [comment]
Hi Manivel,

          Changes are done. Kindly check and revert back. PFA Deliverables.
[Latest Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4936429/Latest.Deliverable.zip)

**Comment by Manimahat** [comment]
@srinivasanbaskaran,

Testing 1 completed. Kindly Move to testing 2 process.

Test Case : [Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4941014/Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx)

Test Result For GMBH : [Packing List print _MFG OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4941016/Packing.List.print._MFG.OU.pdf)

Test Result for GMBH : [Packing List print _GMBH OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4941017/Packing.List.print._GMBH.OU.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Team,

Srinivasan will do Testing 2

**Comment by Narendiranath** [comment]
Hi,

    PFA Latest deliverable for your referance.
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5298485/Deliverable.zip)

**Comment by sujin1708** [comment]
Packing note print  testing has been completed. Herewith I have attached the Testing documents for the future references.

PFS : 
[Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5656899/Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx)
Test Result1 : [Packing.List.print._MFG.OU.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5656903/Packing.List.print._MFG.OU.pdf)

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Please review the Updated PFS & allocated to Developers.

Updated PFS: [01_Packing.List_PFS.v.1.14.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5753085/01_Packing.List_PFS.v.1.14.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Please do the correction of Variant logic as per the PFS

**Comment by karthikeyanamitysoft** [comment]
Dear Naren,

KIndly do the changes mentioned above.

Regards,
Karthi

**Comment by Narendiranath** [comment]
Hi Manivel,

you are busy on some other work. Once you complete your work entire work after that assign this ticket to me.

**Comment by Manimahat** [comment]
@Narendiranath ,

Now I am Free. We will Take a call & close the Ticket. 

Regards,
Manivel A

**Comment by Narendiranath** [comment]
Hi Manivel,

                Development completed. Kindly check. PFA Latest Deliverable for your ref.
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5809681/Deliverable.zip)

**Comment by Manimahat** [comment]
Testing 1 completed. Kindly Move to testing 2 process.

Test Case : [Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5839351/Test.Case_Pack.Slip.Print.For.MFG.GMBH.xlsx)

Test Result For MFG : [Packing Note print-MFG.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5839357/Packing.Note.print-MFG.pdf)

Test Result for GMBH : [Packing Note Print-GMBH.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5839359/Packing.Note.Print-GMBH.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@AkashGleen kindly do the testing 2

**Comment by Manimahat** [comment]
@Narendiranath ,

 Kindly Remove the below Logic in the Coding. Remaining things is Ok. 

If Sale UOM is PER100 means Quantity should multiplied with 100 & Rate divided by 100.

Regards,
Manivel A

**Comment by Narendiranath** [comment]
Hi Manivel,

Changes are done. Kindly check. PFA Latest deliverable for your ref.

[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5943540/Deliverable.zip)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 Completed. Kindly Start the Testing 2 Process.

Test Case: [Test.Case_Pack.Slip.Print.For.MFG.GMBH_1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6240405/Test.Case_Pack.Slip.Print.For.MFG.GMBH_1.xlsx)

Test Result For MFG: [Packing.Note.print-MFG.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6240409/Packing.Note.print-MFG.pdf)

Test Result For GMBH: [Packing.Note.Print-GMBH.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6240411/Packing.Note.Print-GMBH.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@raju-kurup Testing 2 Completed ..kindly check and move to next level

Test Case 2 : [Test.Case_Pack.Slip.Print.For.MFG.GMBH_2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6252088/Test.Case_Pack.Slip.Print.For.MFG.GMBH_2.xlsx)
Test Result 2 MFG: [Packing.Note.print-MFG.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6252089/Packing.Note.print-MFG.pdf)
Test Result 2 GMBH : [Packing.Note.Print-GMBH.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6252091/Packing.Note.Print-GMBH.pdf)
Deliverables : [Deliverable (2).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6252092/Deliverable.2.zip)

**Comment by raju-kurup** [comment]
Pl deploy this in   live server
--

**Comment by Narendiranath** [comment]
Hi,

    Deliverables deployed in Live server. Kindly check. PFA Latest Deliverable for your ref.

[Packing_list.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6285015/Packing_list.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployment completed kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
