### ISSUE TITLE
S&S : Commercial Invoice Print-RDW

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#62]
Dear Karthi,

Please find the **Commercial Invoice Print V 1.0** for your reference.

PFS : [01_Commercial invoice_PFS_V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3915455/01_Commercial.invoice_PFS_V.1.0.xlsx)

Thanks and Regards,
Prabakaran A

**Comment by Prabakaran92** [comment]
@raju-kurup 
Dear sir
Commercial invoice print PFS completed 
kindly once check and revert.

Regards,
Prabakaran A

**Comment by raju-kurup** [comment]
Please start the development, field for "PreCarraige by" and "Place of Receipt by Pre-carrier" having some issue in ramco.  other than that everything is ok.

**Comment by karthikeyanamitysoft** [comment]
EDK Desing completed by Ezhil
coding and DW desing work is pending

**Comment by Nandhineedevi** [comment]
Hi Prabakaran,
The development has been completed. Kindly check and revert back.

[Commercial_invoice_print_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3948802/Commercial_invoice_print_v1.1.zip)

Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
@Nandhineedevi 
PFA 
Test Output : [Commercial Invoice.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/3960340/Commercial.Invoice.pdf)

Test Data : COI/1920/0055/P1
 Points
1.Vessel/Flight No. Not fetching
2. AEO-T1 CERTIFICATE NO : (Need Space)
3. Multiple Items There mean Print Not Properly 

Regards,
Prabakaran

**Comment by Nandhineedevi** [comment]
Hi prabakaran,
The rework has been completed. Kindly check and revert back.

Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
@Nandhineedevi 
As we discuses Changes plz do needful
1.Page wise total
2. hardcore Data in page wise properly

Regards,
Prabakaran A

**Comment by Prabakaran92** [comment]
@Nandhineedevi 
PF Updated PFS
PFS : [02_Commercial invoice_PFS_V 1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4030263/02_Commercial.invoice_PFS_V.1.1.xlsx)
Test Data 1 : SO/1920/0001/P2
Test Data 2 : COI/1920/0057/P1

Kindly update the changes as per PFS

Regards,
Prabakaran A

**Comment by Nandhineedevi** [comment]
Hi Praba,
The rework has been completed. Kindly check and revert back.

[Commerial invoice v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4044086/Commerial.invoice.v1.3.zip)

Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
@Nandhineedevi 
PF Changes 
Points:
1. Vessel/Flight No.(Not fetching)
2. Final Destination(Logic as per descussed)
3.No. & Kind of
Packages (Space required)
4.Amount of Chargeable
(in words) currency 
5. Item category wise Fetching
6.Export benefit not fetching

Test data1: COI/1920/0075/P1
 Test data2: COI/1920/0073/P1

Regards,
Prabakaran A

**Comment by Nandhineedevi** [comment]
Hi Prabakaran,
The Rework has been completed. Kindly check and revert back.

Points: 6 you have to map
Points: 7 data has to be given

Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
@Nandhineedevi 
PF Changesee
Export benifit details not fetching,

Regards,
Prabakaran A

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

[Commercial_invoice_print_v1.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4101514/Commercial_invoice_print_v1.4.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly made the changes as per the Customer Requirements. 

Regards,
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@Nandhineedevi 
Kindly check the updated PFS 
PFS : [04_Commercial invoice_PFS_V 1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4229228/04_Commercial.invoice_PFS_V.1.3.xlsx)
Start the rework ..

Regards,
Prabakaran A

**Comment by Nandhineedevi** [comment]
Hi Prabakaran,
The rework has been completed. Kindly check and revert back.

[commercial_invoice_print_v1.5.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4254210/commercial_invoice_print_v1.5.zip)

Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
Dear srini,
Testing 1 Completed Kindly Start Test 2
Kindly give the priority of emergency Testing 2  
This report need to show customer so Please test Asap.
Regards,
Prabakaran A

**Comment by Prabakaran92** [comment]
@raju-kurup 
Commercial invoice not working properly 
Kindly check the invoice
Invoice : COI/1920/0135/P1
Packslip : PS/1920/0201/P1
Free sample not fetching properly

Regards,
Prabakaran a

**Comment by raju-kurup** [comment]
@ prabha : please prepare the full set of correction and submit to me as discussed

**Comment by Prabakaran92** [comment]
@raju-kurup 
Kindly Allocate Development Rework 
Correction : [New Doc 2020-03-17 11.54.58.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4342221/New.Doc.2020-03-17.11.54.58.pdf)
Points : 
1.Export Scheme Not fetching properly
2. Marks, & Nos./ containers No
3.Quantity not proper
4.Attach not Line space not proper
5.Free sample not proper
6.Data format should be like so print

Note :  Some document working fine but some document not working properly 
Test data1 : COI/1920/0135/P1 (Working good)
Test data2 : COI/1920/0124/P1 (working currently Wrong but 23rd Feb working normal)
Test data3 : COI/1920/0003/P2 (Working Wrong)

Regards,
Prabakaran A

**Comment by Nandhineedevi** [comment]
Hi Prabakaran,
The rework has been completed. Kindly check and revert back.

[Commercial_124_p1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4347766/Commercial_124_p1.pdf)
[Commercial_003_p2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4347768/Commercial_003_p2.pdf)

Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
@raju-kurup 
Sir Kindly check these  commercial invoice Testing.
COI/1920/0135/P1
COI/1920/0124/P1
COI/1920/0003/P2
COI/1920/0140/P1

Regards,
Prabakaran A

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Testing 1 completed.
kindly start Testing 2.
Test Output : [Output1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4360017/Output1.pdf)
[Output4.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4360026/Output4.pdf)
[Output2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4360022/Output2.pdf)
[Output3.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4360023/Output3.pdf)
Test Case : [Commercial Invoice_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4360068/Commercial.Invoice_TestCase1.xlsx)
Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Praba, 

Kindly check the below points in the Output1 file.

* Page total is woringly calculated. ( Sum of total is correctly fetched. But Sum of the Individual total is wrongly calculated.)

Kindly check & Revet the same 

Regards,
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@raju-kurup 
Kindly Allocate development Rework 
1.Page wise Total not Working Properly.
2.Attachment Alignment Not proper.
![image](https://user-images.githubusercontent.com/46194613/77220849-4c5ba000-6b6a-11ea-9527-f4a31fc3d6b3.png)
Test output : [Output1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4362513/Output1.pdf)

Regards,
Prabakaran A

**Comment by raju-kurup** [comment]
@karthi : only previous page issue is there

**Comment by raju-kurup** [comment]
Previous page total issue to be spoken to Lakshmi

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As mentioned in skype please allocate Nandhinee to do this correction.

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
As per discussed points, I have completed the development.

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Sir,

Please find the updated PFS & Testcase for the Commercial Invoice. Need to correct the report 

PFS: [04_Commercial.invoice_PFS_v1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4556289/04_Commercial.invoice_PFS_v1.5.xlsx)

TESTCASE1: [Commercial_Invoice_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4556291/Commercial_Invoice_TestCase1.xlsx)

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as discussed.

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Please find the test result and deliverables attached.

[comm_test1.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4557861/comm_test1.pdf)
[comm_test2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4557862/comm_test2.pdf)
[comm_test3.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4557863/comm_test3.pdf)
[comm_test4.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4557864/comm_test4.pdf)
[comm_test5.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4557865/comm_test5.pdf)
[commercial_invoice_print-v1.7.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4557883/commercial_invoice_print-v1.7.zip)

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the attached PFS as per the latest changes. 

PFS: [04_Commercial.invoice_PFS_v1.6.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4588491/04_Commercial.invoice_PFS_v1.6.xlsx)

IMAGE: ![IMG-20200506-WA0008_20200506_112419401](https://user-images.githubusercontent.com/46194039/81210837-1aa27980-8ff0-11ea-9af4-8f60ce3b7be5.jpg)

**Comment by raju-kurup** [comment]
@srinivasanbaskaran : after getting confirmation from customer we will review this ticket

**Comment by srinivasanbaskaran** [comment]
Team, 

PFA of Latest Open Points 

![IMG_20200514_171229_20200514_171253217](https://user-images.githubusercontent.com/46194039/82201004-56f1a600-991d-11ea-874d-2be1db868784.jpg)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the attached updated PFS.

PFS: [04_Commercial.invoice_PFS_v1.7.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4658432/04_Commercial.invoice_PFS_v1.7.xlsx)

NOTE: Test data is attached along with PFS

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the attached updated PFS for Commercial Invoice

PFS: [04_Commercial.invoice_PFS_v1.8.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4766067/04_Commercial.invoice_PFS_v1.8.xlsx)

Kindly remove the PFS & Allocate to Development

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per the colour highlighted in PFS.  Test data is also attached

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
Kindlly provide new test data.

Regards
Nandhinee Devi

**Comment by srinivasanbaskaran** [comment]
@Nandhineedevi,

Please find the attached updated PFS along with New Test Data 

PFS: [04_Commercial.invoice_PFS_v1.9.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4784543/04_Commercial.invoice_PFS_v1.9.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The Rework has been completed. Kindly check and revert back.

[commercial_test__data.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4799055/commercial_test__data.pdf)
[commercial_invoice_print_v1.8.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4799072/commercial_invoice_print_v1.8.zip)

Regards
Nandhinee Devi

**Comment by Manimahat** [comment]
@Nandhineedevi ,

Attach notes not fetch in the Report.  i have provided in Sale order but it is not reflect.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@srinivasanbaskaran,

Testing 1 Completed. Kindly Proceed testing 2 Process.

Test case : [Commercial_Invoice_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4880272/Commercial_Invoice_TestCase1.xlsx)

Test Result : [Commercial Invoice.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4880276/Commercial.Invoice.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Team,

Commercial Invoice Testing 2 Completed. Please find the Testing Documents 

TESTCASE2: [Commercial_Invoice_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886352/Commercial_Invoice_TestCase2.xlsx)

TEST RESULT2: [TR_2_Commercial Invoice.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4886353/TR_2_Commercial.Invoice.pdf)

Regards,
Srinivasan

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

 Commercial Invoice testing has been completed. Herewith I have attached the Testing documents for the future references.

PFS: [04_Commercial.invoice_PFS_v1.9.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886370/04_Commercial.invoice_PFS_v1.9.xlsx)

DELIVERABLES: [commercial_invoice_print_v1.8.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4886374/commercial_invoice_print_v1.8.zip)

TESTCASE1 : [Commercial_Invoice_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4880272/Commercial_Invoice_TestCase1.xlsx)

TEST RESULT1 : [Commercial Invoice.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4880276/Commercial.Invoice.pdf)

TESTCASE2: [Commercial_Invoice_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4886352/Commercial_Invoice_TestCase2.xlsx)

TEST RESULT2: [TR_2_Commercial Invoice.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4886353/TR_2_Commercial.Invoice.pdf)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
@Manimahat,

Please cross check the PFS & Transaction ( Functionality )

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Below points need to Change In the report.
1.  UOM
2. Qty
3.  Rate
4.  Value
5.  freight Charges

Updated PFS : [04_Commercial.invoice_PFS_v1.10.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4919735/04_Commercial.invoice_PFS_v1.10.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per the PFS mentioned.

**Comment by Nandhineedevi** [comment]
[commercial.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4952256/commercial.pdf)
[commercial_invoice_print_v1.9.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4952261/commercial_invoice_print_v1.9.zip)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 completed. Kindly proceed to testing 2 process.

Test Case : [Commercial_Invoice_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4959306/Commercial_Invoice_TestCase1.xlsx)

Test Result : [Commercial Invoice.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4959313/Commercial.Invoice.pdf)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@eafaisal,

Kindly start the Testing 2 Process & prepare the test case As per our format.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@Nandhineedevi ,

As discussed with raju sir,  Report has fetched incorrect Qty from Commercial Invoice tab to Report. Kindly Check & resolve the Issue.

Herewith I have Attached Customer sent Copy. They also facing the same Issue.

Customer Print : [BASCO-INV-0043- Customer Copy.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/4989998/BASCO-INV-0043-.Customer.Copy.pdf)

Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
Hi Mani,
The rework has been completed. Kindly check and revert back.

[comm.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5001523/comm.pdf)
[commercial_invoice_print_v2.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5001529/commercial_invoice_print_v2.0.zip)

Regards
Nandhinee Devi

**Comment by Manimahat** [comment]
@Nandhineedevi ,

1. Marking Description Is not fully Fetched. Kindly Check & Resolved.

![image](https://user-images.githubusercontent.com/55881685/88955326-62683280-d2b9-11ea-989a-2d69c6f91af7.png)


Regards,
Manivel A

**Comment by Nandhineedevi** [comment]
[commercial_invoice_print_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5006495/commercial_invoice_print_v2.1.zip)
[Commercial Invoice - JCIPL.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5006498/Commercial.Invoice.-.JCIPL.pdf)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 Completed. Kindly Proceed the testing 2 process.

Test Case : [Commercial_Invoice_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5011640/Commercial_Invoice_TestCase1.xlsx)

Test Result : [Commercial Invoice.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5011641/Commercial.Invoice.pdf)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Commercial Invoice Testing has been completed. Herewith I have attached the Testing Documents for the future references.

PFS: [04_Commercial.invoice_PFS_v1.10.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5052512/04_Commercial.invoice_PFS_v1.10.xlsx)

DELIVERABLES: [commercial_invoice_print_v2.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5052515/commercial_invoice_print_v2.1.zip)

TESTCASE1: [Commercial_Invoice - TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5052518/Commercial_Invoice.-.TestCase1.xlsx)

TEST RESULT1: [Commercial Invoice.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5052522/Commercial.Invoice.pdf)

TESTCASE2: [Commercial_Invoice_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5052523/Commercial_Invoice_TestCase2.xlsx)

TEST RESULT2: [Commercial_Invoice_Test_Result2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5052524/Commercial_Invoice_Test_Result2.pdf)

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup ,

Please find the Updated PFS allocated to Developers.

Updated pfs : [04_Commercial.invoice_PFS_v1.11.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5067684/04_Commercial.invoice_PFS_v1.11.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction for 2 points which is mentioned in PFS and test data also in PFS.

**Comment by Nandhineedevi** [comment]
[poshpcmi_c_prin_grd1_gr_v2.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5084035/poshpcmi_c_prin_grd1_gr_v2.3.zip)
[comm.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5084036/comm.pdf)

**Comment by Manimahat** [comment]
@srinivasanbaskaran ,

Testing 1 completed. Please find the attached document for your reference.

Test Case : [Commercial_Invoice_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5094148/Commercial_Invoice_TestCase1.xlsx)

Test Result : [Commercial Invoice Print_Ins.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5094150/Commercial.Invoice.Print_Ins.pdf)

Regards,
Manivel A

**Comment by Narendiranath** [comment]
Hi,

PFA Latest deliverable for your referance.
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5298360/Deliverable.zip)

**Comment by sujin1708** [comment]
PFS : [04_Commercial.invoice_PFS_v1.9.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5656804/04_Commercial.invoice_PFS_v1.9.xlsx)
[Commercial_Invoice_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5656805/Commercial_Invoice_TestCase1.xlsx)
[Commercial.Invoice.Print_Ins.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5656807/Commercial.Invoice.Print_Ins.pdf)
[Commercial_Invoice_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Test Ceramic/files/5656809/Commercial_Invoice_TestCase2.xlsx)
[TR_2_Commercial.Invoice.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5656810/TR_2_Commercial.Invoice.pdf)

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Please review the Updated PFS & allocated to Developers.

Updated PFS: [04_Commercial.invoice_PFS_v1.12.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5752898/04_Commercial.invoice_PFS_v1.12.xlsx)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction as per PFS.

**Comment by karthikeyanamitysoft** [comment]
Dear Nandhinee,

Check the attached PFS and do the changes.

REgards,
Karthi

**Comment by Nandhineedevi** [comment]
Completed.

[comm.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5792305/comm.pdf)
[commercial_invoice_print_v2.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5792306/commercial_invoice_print_v2.2.zip)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 Completed. Kindly Start Testing 2 Process.

Test Case 1: [Commercial_Invoice_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5827489/Commercial_Invoice_TestCase1.xlsx)

Test Result : [comm.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5827492/comm.pdf)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@AkashGleen ,

Kindly Do testing 2 & prepare the Test case As per our Format.

Regards,
Manivel A

**Comment by AkashGleen** [comment]
Dear Sujin,

Commercial Invoice Print Testing 2 Completed.
[Commercial Invoice Print.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/5835789/Commercial.Invoice.Print.pdf)
[Commercial_Invoice_TestCase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5835799/Commercial_Invoice_TestCase1.xlsx)

Regards,
Akash

**Comment by Nandhineedevi** [comment]
@Manimahat 

PER100 Logic has been removed

[commercial_invoice_print_v2..zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5956349/commercial_invoice_print_v2.zip)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 Completed. Kindly Start the Testing 2 Process.

Test case : [Commercial_Invoice_TestCase_1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6240373/Commercial_Invoice_TestCase_1.xlsx)

Test Result : [comm.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6240376/comm.pdf)

Regards,
Manivel A

**Comment by sujin1708** [comment]
[commercial_invoice_print_v2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6252021/commercial_invoice_print_v2.zip)
[comm_2.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6252022/comm_2.pdf)
[Commercial_Invoice_TestCase_2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/6252023/Commercial_Invoice_TestCase_2.xlsx)

**Comment by raju-kurup** [comment]
Pl deploy this in   live server
--

**Comment by Nandhineedevi** [comment]
Completed.

[Live Final Import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6283560/Live.Final.Import.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployemnt completed kindly close the ticket

**Comment by Manimahat** [comment]
@raju-kurup sir,

As per Ramco Suggestion we need Generate new Deliverbales & deploy both UAT & Live server for UDS
For any Clarification Please Refer Rtrack JCIE - 391.

![image](https://user-images.githubusercontent.com/55881685/124713048-a928c880-df1d-11eb-897f-ff5cbe7cf488.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please redeploy the UDS as mentioned in RTrack #JCIE-391 and inform us, we will test.

**Comment by mohanaamity** [comment]
@Manimahat 

Now the UDS screen link is working  in Jyoti uat server after deploying the new fixes .

Regards,
Mohana B

**Comment by Manimahat** [comment]
@mohanaamity ,

Now both server Commercial invoice UDS Link is showing & working perfectly. but we are launching the report in Live server the report is showing blank only. I think select statement is not removed in that Live server report. Please Check & resolve asap.

UAT report is launching perfectly with data.

Live server report : 
![image](https://user-images.githubusercontent.com/55881685/128971470-11399702-66ca-47f3-b8e9-ec48bda5fb3c.png)


Regards,
Manivel A

**Comment by mohanaamity** [comment]
@Manimahat 

Values are fetching in live server.
[RAMCOUSER__40111028_b46c913f-a432-4940-a16d-7734f059f3af.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/6967058/RAMCOUSER__40111028_b46c913f-a432-4940-a16d-7734f059f3af.pdf)


Regards,
Mohana B

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Commercial invoice UDS screen deployed Successfully in both UAT & Live server. So please close this ticket.

UAT UDS screen: 
![image](https://user-images.githubusercontent.com/55881685/129193960-44d29310-421b-42ca-9437-7200c2eab13f.png)

UAT Report : 
![image](https://user-images.githubusercontent.com/55881685/129194055-13169cda-0898-4ce8-b431-d4e0391616f5.png)

Live Server UDS screen ;  
![image](https://user-images.githubusercontent.com/55881685/129194377-b7f09e1a-7a2e-4878-983b-253e0f124799.png)

Live server report : 
![image](https://user-images.githubusercontent.com/55881685/129194479-68f5497c-0099-4a0a-a51a-7d755ad4993a.png)

Regards,
Maniivel A

**Comment by raju-kurup** [comment]
Being development completed and deployed in live and test server, we are closing this ticket.

**Comment by Manimahat** [comment]
@raju-kurup Sir,

While Saving multi line data in the Commercial invoice UDS screen, Data was Vanished if we save more than one time in the Live Server but UAT server it is working Perfectly. Please route this ticket to developers for Re-work.

Please find the Below Screen Shot for your Ref....

Original Data in  Live Server UDS Screen:  ![image](https://user-images.githubusercontent.com/55881685/130450002-13bda1a4-5dfb-42f4-aebe-78644ec5d73d.png)

Editing data in the Live server UDS Screen : ![image](https://user-images.githubusercontent.com/55881685/130450152-38515e6b-ddde-40ea-9ea9-fc0eaff3f99d.png)

Edited Data in the Live Server UDS Screen : 
![image](https://user-images.githubusercontent.com/55881685/130450251-ef9b6d29-7f91-457d-8aeb-3ce34fc65f68.png)

Original Data in UAT Sever UDS Screen : ![image](https://user-images.githubusercontent.com/55881685/130448877-ccbaef1d-986a-40c0-837a-f2dcb0872c9c.png)

Edited Data in UAT Server UDS Screen: ![image](https://user-images.githubusercontent.com/55881685/130449033-940a6604-eb17-40bb-8cd1-0fc97fd12185.png)

Regards,
Manivel A

**Comment by Manimahat** [comment]
@raju-kurup Sir,

While Saving multi line data in the Commercial invoice UDS screen, Data was Vanished if we save more than one time in the Live Server but UAT server it is working Perfectly. Please route this ticket to developers for Re-work.

Please find the Below Screen Shot for your Ref....

Original Data in  Live Server UDS Screen:  ![image](https://user-images.githubusercontent.com/55881685/130450002-13bda1a4-5dfb-42f4-aebe-78644ec5d73d.png)

Editing data in the Live server UDS Screen : ![image](https://user-images.githubusercontent.com/55881685/130450152-38515e6b-ddde-40ea-9ea9-fc0eaff3f99d.png)

Edited Data in the Live Server UDS Screen : 
![image](https://user-images.githubusercontent.com/55881685/130450251-ef9b6d29-7f91-457d-8aeb-3ce34fc65f68.png)

Original Data in UAT Sever UDS Screen : ![image](https://user-images.githubusercontent.com/55881685/130448877-ccbaef1d-986a-40c0-837a-f2dcb0872c9c.png)

Edited Data in UAT Server UDS Screen: ![image](https://user-images.githubusercontent.com/55881685/130449033-940a6604-eb17-40bb-8cd1-0fc97fd12185.png)

We will Re-open this ticket for development re-work

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction (ie) Variant is handled in live server as discussed

**Comment by mohanaamity** [comment]
@Manimahat ,

As discussed with Raju Sir, variant code is handled in both live and uat server. Now we are able to save the changes. Kindly check and confirm.

Regards,
Mohana B

**Comment by Manimahat** [comment]
@raju-kurup sir,

Now we are able to Edit & save the Data Successfully in both UAT & Live server. Please find the PDF for your Ref... Kindly close this ticket

Live server UDS Original Data : ![image](https://user-images.githubusercontent.com/55881685/130719235-815c61fd-0581-41d6-a4f7-4a4c1fb85935.png)

Live server UDS Edited Data :  ![image](https://user-images.githubusercontent.com/55881685/130719283-916620c5-2f54-48db-9744-c2a78c27595a.png)


PDF 1: [Commercial Invoice_HSN & END Use code.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/7043280/Commercial.Invoice_HSN.END.Use.code.pdf)

PDF 2: [Commercial Invoice -220001.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/7043283/Commercial.Invoice.-220001.pdf)

PDF 3: [Commercial Invoice -220007.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/7043292/Commercial.Invoice.-220007.pdf)

PDF 4 : [Commercial Invoice -220003.pdf](https://github.com/astpl1998/Jyoti-Ceramic/files/7043295/Commercial.Invoice.-220003.pdf)

Regards,
Manivel A

**Comment by mohanaamity** [comment]
@Manimahat 

Latest deliverables attached.
[Live.Final.Import.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/7088310/Live.Final.Import.zip)

Regards,
Mohana B

**Comment by raju-kurup** [comment]
Report developed and deployed in Live and UAT server so closing this ticket
