### ISSUE TITLE
S&S : Exports Benefits Scheme Master-EDK

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#65]
Dear Sir,

Please find the **Exports Benefits Scheme Master PFS V 1.0** for your reference.

PFS : [01_JCIPL_Exports Benifits Master_V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3724316/01_JCIPL_Exports.Benifits.Master_V.1.0.xlsx)

Thanks and Regards,
M. Maheshwaran

**Comment by raju-kurup** [comment]
Karthi - Please start the development in  IEDK/EDK

**Comment by karthikeyanamitysoft** [comment]
Dear Badham,

Kindly start new EDK screen development.

Regards,
Karthi

**Comment by Arunachalamamitysoft** [comment]
Dear mahesh,
               Maintain type master activity  development is completed  ,kindly check and revert it back.

**Comment by Arunachalamamitysoft** [comment]
[Maintain Type Master V1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3900859/Maintain.Type.Master.V1.0.zip)
Updated deliverables for Maintain type Master Activity.

**Comment by maheshwaran-m** [comment]
@Arunachalamamitysoft 

As discussed Type master screen, while clicking Maintain Button record has been disappear, and Edit Type master is working not properly.

Regards,
M.Maheshwaran

**Comment by Arunachalamamitysoft** [comment]
Dear Mahesh,
         Export benefits master  Development is completed  ,kindly check and revert it back.

**Comment by Arunachalamamitysoft** [comment]
Updated Deliverables
[Exp Ben Master V1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3914865/Exp.Ben.Master.V1.0.zip)

**Comment by maheshwaran-m** [comment]
@Prabakaran92 

Kindly start Testing for this Exports benefits Master.

M.Maheshwaran.

**Comment by Prabakaran92** [comment]
@Arunachalamamitysoft 
PFA 
** Test Case**  : [Export Benifit Master_Test.case_V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3916294/Export.Benifit.Master_Test.case_V.1.0.xlsx)

Points : 
1.Group code
2.Scheme Type
3.Heading
The above fields mandatery.
Currently No Validation above fields.
Kindly check and revert.

Regards,
Prabakaran A

**Comment by Arunachalamamitysoft** [comment]
Dear Prabakaran,
          Development is completed,kindly check and revert it back.

**Comment by Arunachalamamitysoft** [comment]
updated Deliverables for exports benefits scheme master
[Exp Ben Master V2.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3926576/Exp.Ben.Master.V2.0.zip)

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Testing 1 Completed.
kindly start Testing 2

**Comment by srinivasanbaskaran** [comment]
Ugesh,

Kindly start the Testing & Prepare the Testing Documents 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Arun,

Please find the below point & Made the correction & Revert.

While Removing the multi line data, System throws an error like "Scheme type should not be Blank"

Kindly call me once you have started this work.

Regards,
Srinivasan Baskaran

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the below attached UAT changes points for your reference.

1. Removed Some data in multi line but again data will be fetching at the time of maintain, its only in 1001 group. Remaining group at the time of removing "Scheme type should not be Blank error will be come".

Thanks and Regards,
M.Maheshwaran

**Comment by Arunachalamamitysoft** [comment]
Dear Mahesh,
Development is completed,corrections are done.

Thanks& Regards,
S.Arunachalam

**Comment by srinivasanbaskaran** [comment]
@Arun, 

Issue Resolved. 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
@Prabakaran92,

Kindly update the Testing 1 documents for this report

Regards,
Srinivasan Baskaran

**Comment by Arunachalamamitysoft** [comment]
updated deliverables,
[Exp Ben Master V3.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4011980/Exp.Ben.Master.V3.0.zip)

**Comment by Prabakaran92** [comment]
@basha123456 
Kindly start Testing 1 and update the testing 1 documents.

Regards.
Prabakaran A

**Comment by basha123456** [comment]
Srini,

Testing1 is completed.
Export benefits master screen is working as per the PFS.
In the packing list print, heading is not coming. kindly check.
[Export benefits master test case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4038866/Export.benefits.master.test.case.xlsx)
Test data: 
Sale Order: SO/1920/0191/P1
Packslip: PS/1920/0111/P1


--



--

**Comment by srinivasanbaskaran** [comment]
Raju sir,

Export Benefits Scheme Master screen Testing completed. Some of the Testing documents are attached for future references.

PFS:[01_JCIPL_Exports.Benifits.Master_V.1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4044436/01_JCIPL_Exports.Benifits.Master_V.1.0.xlsx)

DELIVERABLES: [Exp.Ben.Master.V3.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4044437/Exp.Ben.Master.V3.0.zip)

TESTCASE 1: [Export.benefits.master.test.case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4044443/Export.benefits.master.test.case.xlsx)

TEST RESULT 1: [Export Benefit Master Test Result1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4044444/Export.Benefit.Master.Test.Result1.docx)

TESTCASE 2: [Export Benefit Master Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4044514/Export.Benefit.Master.Testcase2.xlsx)

TEST RESULT 2: [Exports Scheme Master_Test Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4044683/Exports.Scheme.Master_Test.Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
As per the user requirements, need to change the screen design..

PFS will update later

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

PFS updated as per the Customer Requirements.

PFS: [01_JCIPL_Exports Benifits Scheme Master_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4142303/01_JCIPL_Exports.Benifits.Scheme.Master_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
As already discussed kindly provide clear requirement, impact of the given changes.

Regards,
Karthi

**Comment by srinivasanbaskaran** [comment]
Karthi,

As we discussed earlier, Kindly REMOVE the DEEC Title to be Remove from the screen.

If there is any logic for the DEEC Title means, Kindly remove that also. Because, we are not using that Field anywhere 

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
Srini,

Please, you need to mention what are the list of logic need to remove.

REgards,
Karthi

**Comment by srinivasanbaskaran** [comment]
Karthi,

As discussed with the User / Customer, Kindly remove the DEEC Title from the Screen.

PFS updated & attached. 

Regards,
Srinivasan Baskaran

**Comment by Arunachalamamitysoft** [comment]
@srinivasanbaskaran 
Development is completed ,kindly check and revert it back.

**Comment by badamnarendra028** [comment]
changes completed kindly check

**Comment by srinivasanbaskaran** [comment]
Raju Sir,
Export Benefits Scheme Master developed & Testing Completed. Herewith, I have attached the Testing Documents for future references. 

PFS:

DELIVERABLES:

TESTCASE 1:

TEST RESULT1:

TESTCASE2:

TEST RESULT2:

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Badam,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[jcie-210.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4197985/jcie-210.zip)

**Comment by badamnarendra028** [comment]
updated

**Comment by srinivasanbaskaran** [comment]
Raju Sir,
Export Benefits Scheme Master developed & Testing Completed. Herewith, I have attached the Testing Documents for future references. 

PFS: [Export Benefit Master Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4196533/Export.Benefit.Master.Testcase2.xlsx)

DELIVERABLES: [jcie-210.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4198194/jcie-210.zip)

TESTCASE 1: [Export.benefits.master.test.case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4196537/Export.benefits.master.test.case.xlsx)

TEST RESULT1: [Export Benefit Master Test Result1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4196538/Export.Benefit.Master.Test.Result1.docx)

TESTCASE2: [Export Benefit Master Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4196540/Export.Benefit.Master.Testcase2.xlsx)

TEST RESULT2: [Exports Scheme Master_Test Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4196541/Exports.Scheme.Master_Test.Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team, 

Please find the attached PFS as per the Customer Requirements.

PFS: [01_JCIPL_Exports.Benifits.Scheme.Master_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4218400/01_JCIPL_Exports.Benifits.Scheme.Master_v1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

Kindly review & Allocate for Development

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Dear Karthi,

Please do the correction as mentioned in the PFS - 1 Point.

**Comment by karthikeyanamitysoft** [comment]
Completed

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly show this screen to User & close this ASAP

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,
Export Benefits Scheme Master developed & Testing Completed. Herewith, I have attached the Testing Documents for future references. 

PFS: [01_JCIPL_Exports.Benifits.Scheme.Master_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334631/01_JCIPL_Exports.Benifits.Scheme.Master_v1.2.xlsx)
 
DELIVERABLES: 

TESTCASE 1: [Export.benefits.master.test.case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4196537/Export.benefits.master.test.case.xlsx)

TEST RESULT1: [Export Benefit Master Test Result1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4196538/Export.Benefit.Master.Test.Result1.docx)

TESTCASE2: [Export Benefit Master Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334639/Export.Benefit.Master.Testcase2.xlsx)

TEST RESULT2: [Exports Scheme Master_Test Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334640/Exports.Scheme.Master_Test.Result2.docx)
 
Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Karthi,

Kindlly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[jcie-210.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4337887/jcie-210.zip)

**Comment by badamnarendra028** [comment]
attached

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Export Benefits Scheme Master developed & Testing Completed. Herewith, I have attached the Testing Documents for future references. 

PFS: [01_JCIPL_Exports.Benifits.Scheme.Master_v1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334631/01_JCIPL_Exports.Benifits.Scheme.Master_v1.2.xlsx)
 
DELIVERABLES: [jcie-210.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4341960/jcie-210.zip)

TESTCASE 1: [Export.benefits.master.test.case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4196537/Export.benefits.master.test.case.xlsx)

TEST RESULT1: [Export Benefit Master Test Result1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4196538/Export.Benefit.Master.Test.Result1.docx)

TESTCASE2: [Export Benefit Master Testcase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334639/Export.Benefit.Master.Testcase2.xlsx)

TEST RESULT2: [Exports Scheme Master_Test Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4334640/Exports.Scheme.Master_Test.Result2.docx)
 
Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Testing 2 completed, so closing this ticket

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by karthikeyanamitysoft** [comment]
Dear Gayatri,

Kindly get the latest deliverables and deploy the same into live server.

Regards,
Karthi

**Comment by Narendiranath** [comment]
Hi Srinivasan,
 
               deployment completed in live server. Kindly check. PFA Latest Deliverable for your ref.

[jcie-210.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5897889/jcie-210.zip)

**Comment by sujin1708** [comment]
@raju-kurup Deployment completed kindly close the ticket

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket.
