### ISSUE TITLE
S&S : Advance license Master-EDK

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#66]
Dear Sir,

Please find the **Advance License Master PFS V 1.0** for your reference.

PFS : [01_JCIPL_Advance License Master_V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3733292/01_JCIPL_Advance.License.Master_V.1.0.xlsx)

Thanks and Regards,
M. Maheshwaran

**Comment by raju-kurup** [comment]
Karthi- Please start the development in IEDK/EDK

**Comment by karthikeyanamitysoft** [comment]
Dear Nandinee,

Kindly start the new EDK screen desing.

Regards,
Karthi

**Comment by Nandhineedevi** [comment]
Hi Mahesh,
The development has been hold since the dependence screen(Sale Invoice) is not yet completed. 

Regards
Nandhinee Devi

**Comment by maheshwaran-m** [comment]
@Nandhineedevi

keep this ticket in your name, As discussed once sales invoice UDS development is completed. You can start Advance license Master.

Regards,
M.Maheshwaran

**Comment by Nandhineedevi** [comment]
Hi Mahesh,
The design and coding has been completed. Kindly check and revert back.

[adv_lic_master.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3904995/adv_lic_master.zip)

Regards
Nandhinee Devi

**Comment by Nandhineedevi** [comment]
Hi Mahesh,
Please find the new deliverables attached.

[adv_lic_master_v1.1.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3915140/adv_lic_master_v1.1.zip)

Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
@Nandhineedevi 
PF Points: 
1.Serial No Help screen No validation and error msg
2.Advance licence No do not editable.
3.Serial no incresing 
4.Maintain button no validation
5.Get invoice working but not properly
6.Save button no validation
7.Line no not working properly

The above points need to modify the screen.

Regards,
Prabakaran A

**Comment by Nandhineedevi** [comment]
Hi Prabakaran,
The Rework has been completed. Kindly check and revert back.

[Adv_lic_master_v1.2.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/3931877/Adv_lic_master_v1.2.zip)

Regards
Nandhinee Devi

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Testing 1 Completed.
kindly start Testing 2

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly do the corrections as per the document which is attached. Call me once at the time of start looking into this error

DOC: 
[Advance License Master_Error.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3997974/Advance.License.Master_Error.docx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

For date error, I have taken filter for policy date, so I showing correct only

Regards
Nandhinee devi

**Comment by srinivasanbaskaran** [comment]
Prabakaran,

Kindly update the Testing 1 documents for process further on this report

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Advance License Master EDK report testing has been completed.
Testing related documents are attached for future references.

PFS: [01_JCIPL_Advance.License.Master_PFS_v.1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4000389/01_JCIPL_Advance.License.Master_PFS_v.1.0.xlsx)

Deliverables:
Testcase1:
Test Result1:
Testcase2: [Advance License Master_EDK_Testcase2_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4000391/Advance.License.Master_EDK_Testcase2_v1.0.xlsx)

Test Result2: [Advance License Master_Test Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4000396/Advance.License.Master_Test.Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nandhinee,

Kindly update the Latest Updated Deliverables for this report

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi,
Please find the latest deliverables.

[adv_lic_master_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4001320/adv_lic_master_v1.3.zip)

Regards
Nandhinee devi

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
Testing 1 completed
Test Case 1 : [Advance license Masteest.case_V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4038808/Advance.license.Masteest.case_V.1.0.xlsx)

Test data : AL/001

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Advance License Master EDK report testing has been completed.
Testing related documents are attached for future references.

PFS: [01_JCIPL_Advance.License.Master_PFS_v.1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4000389/01_JCIPL_Advance.License.Master_PFS_v.1.0.xlsx)

Deliverables: [adv_lic_master_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4015231/adv_lic_master_v1.3.zip)

Testcase1:[Advance.license.Masteest.case_V.1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4040349/Advance.license.Masteest.case_V.1.0.xlsx)

Test Result1: 
[Advance License Master Test Result1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4040351/Advance.License.Master.Test.Result1.docx)


Testcase2: [Advance License Master_EDK_Testcase2_v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4000391/Advance.License.Master_EDK_Testcase2_v1.0.xlsx)

Test Result2: [Advance License Master_Test Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4000396/Advance.License.Master_Test.Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
As per the user requirements, need to change this screen.

PFS will be update later

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

PFS update as per the Customer Requirements. 

PFS: [01_JCIPL_Advance License Master_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4142295/01_JCIPL_Advance.License.Master_v1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by Nandhineedevi** [comment]
Hi Srinivasan,
The rework has been completed. Kindly check and revert back.

[adv_lic_master_v1.4.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4153201/adv_lic_master_v1.4.zip)

Regards
Nandhinee devi

**Comment by srinivasanbaskaran** [comment]
Team,

Advance License Master working correctly as per the Customer Requirements 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Advance License Master EDK report testing has been completed.
Testing related documents are attached for future references.

PFS: 

Deliverables: [adv_lic_master_v1.3.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4015231/adv_lic_master_v1.3.zip)

Testcase1:[Advance.license.Masteest.case_V.1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4040349/Advance.license.Masteest.case_V.1.0.xlsx)

Test Result1: 
[Advance License Master Test Result1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4040351/Advance.License.Master.Test.Result1.docx)

Testcase2: 

Test Result2: 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Advance License Master Screen completed & Shown to the Users. 

**Document:** [01_Resolution Doc for Sales & Shipping OpenPoint 12.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4180148/01_Resolution.Doc.for.Sales.Shipping.OpenPoint.12.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

This development has been completed. 

Kindly proceed further on this Development

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed  so closing this issue.
Srini - Please attach the signed copy

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by karthikeyanamitysoft** [comment]
Dear Nandinee,

Kindly deploy the deliverables into live server.

Regards,
Karthi

**Comment by Nandhineedevi** [comment]
Deployed in Live Server.

[adv_lic_master_final_live.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5768488/adv_lic_master_final_live.zip)

**Comment by sujin1708** [comment]
kinldy close the ticket

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Advance License Master Deployed Successfully in Live Server.

Regards,
Manivel A

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket
