### ISSUE TITLE
S&S : Insurance Policy Master-EDK

### ISSUE THREAD

**Issue by maheshwaran-m** [astpl1998/Jyoti-Ceramic#67]
Dear Sir,

Please find the **Insurance Policy Master PFS V 1.0** for your reference.

PFS : [01_JCIPL_Insurance Policy Master_V 1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3728334/01_JCIPL_Insurance.Policy.Master_V.1.0.xlsx)

Thanks and Regards,
M. Maheshwaran

**Comment by raju-kurup** [comment]
Karthi - Please start development in IEDK/EDK

**Comment by badamnarendra028** [comment]
completed kindly check the report and revert me

**Comment by badamnarendra028** [comment]
![insuimg](https://user-images.githubusercontent.com/46923845/70137535-1f1add00-16b4-11ea-9e96-b6e41731773e.JPG)
![insimg2](https://user-images.githubusercontent.com/46923845/70137539-2215cd80-16b4-11ea-80a4-ae5c00398f4e.JPG)

**Comment by maheshwaran-m** [comment]
@badamnarendra028 

As discussed we need to check Total enhancement amount, closing balance, and Enhancement amount multi-line details disappearing. please check and close this ASAP.

**Comment by badamnarendra028** [comment]
completed

**Comment by maheshwaran-m** [comment]
@Prabakaran92 

Kindly start Testing for Insurance policy master.

Regards,
M.Maheshwaran

**Comment by Prabakaran92** [comment]
@badamnarendra028 
PF Above points
1.Serial No Leans search From date as Financial year start date and to Date System date Need to Fetch.
2 .Sl.No Field not needed remove that
3. Total Insured Amount not fetching
4.Policy no duplication
5.Serial No not in order
6.Maintain Policy Button no validation
7. Enhancement Records not store in multi line
8. Policy Type Duplication Leans search 
9.Unwanted activity Need to Remove

Regards,
Prabakaran A

**Comment by badamnarendra028** [comment]
completed check and revert

**Comment by maheshwaran-m** [comment]
Dear Team,

Please find the below attached UAT changes points for your reference.

**1. In UDS unwanted Insurance activity will be there kindly remove that activity.
2.  Insurance Policy in help variant from and to date functionality Is not working.
3. In Insurance search screen so many duplicate values are there need to check.
4. I   cant add enhancement amount.
5. After adding enhancement amount data keep it save some times data is disappear.
6. Need to add New fields in insurance policy master invoice details screen. BL/NO, BL/Date, Customer Name, Currency,Country.**

Thanks and Regards,
M.Maheshwaran.

**Comment by Prabakaran92** [comment]
@badamnarendra028 
PF Changes : 
![image](https://user-images.githubusercontent.com/46194613/71571071-8a629e00-2afe-11ea-8678-ac4453c13e16.png)
Points :
1. Serial No manual allowed need validation
2. If serial no on enter function not working
3. Get invoice details not fetching
4. this transaction not working properly
Plz do needful 

Regards,
Prabakaran A

**Comment by badamnarendra028** [comment]
validation completed kindly check

**Comment by srinivasanbaskaran** [comment]
Dear Team,

PFA the UAT changes. 
1. In   UDS unwanted Insurance activity will be there kinldy remove that activity.
2. Need to add New fields in insurance policy master invoice   details screen. BL/NO, BL/Date, Customer Name, Currency,Country.

**NOTE: Praba, Please update the PFS which should be incorporate the Customer Changes **

Regards,
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
As we discussed Kindly update the PFS

**Comment by srinivasanbaskaran** [comment]
Dear Team, 

Please find the updated PFS.

PFS: [01_JCIPL_Insurance.Policy.Master_v.1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4025054/01_JCIPL_Insurance.Policy.Master_v.1.1.xlsx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Karthi,

Kindly start the changes &Revert

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
completed

**Comment by srinivasanbaskaran** [comment]
Badam,

Kindly made the changes as per our discussion.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju sir,

Insurance Policy Master EDK screen testing completed. 

Herewith, I have attached Testing Documents for future purposes.

PFS:[01_JCIPL_Insurance.Policy.Master_v.1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4038990/01_JCIPL_Insurance.Policy.Master_v.1.1.xlsx)

DELIVERABLES: 

TESTCASE1:

TEST RESULT1:

TESTCASE 2: [Insurance Policy Master_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4039010/Insurance.Policy.Master_TestCase2.xlsx)

TEST RESULT 2: [Insurance Policy Master_Test Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4039013/Insurance.Policy.Master_Test.Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Prabakaran,

Kindly update the Testing 2 documents 

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Badam,

Kindly update the Latest Deliverables 

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
[BE.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4039318/BE.zip)

**Comment by srinivasanbaskaran** [comment]
Badam,

Kindly made the changes in below points. 

1. Serial Number manual entry not allowed
2. Insured Amount is not fetched in the Invoice
3. In multi line, S.No is fetched blank.  - How many numbers are in the multi line, that much numbers will come

Please revert after completion

Regards,
Srinivasan Baskaran

**Comment by badamnarendra028** [comment]
completed

**Comment by srinivasanbaskaran** [comment]
Praba,

Kindly update the Testing 1 documents

Regards,
Srinivasan Baskaran

**Comment by Prabakaran92** [comment]
@srinivasanbaskaran 
PFA
Test case 1: [Insurance policy Master Test case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4084875/Insurance.policy.Master.Test.case.xlsx)

Test Data : IP/004

Regards,
Prabakaran A

**Comment by srinivasanbaskaran** [comment]
Raju sir,

Insurance Policy Master EDK screen testing completed. 

Herewith, I have attached Testing Documents for future purposes.

PFS:[01_JCIPL_Insurance.Policy.Master_v.1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4038990/01_JCIPL_Insurance.Policy.Master_v.1.1.xlsx)

DELIVERABLES: [BE_v1.0.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4040372/BE_v1.0.zip)

TESTCASE1: [Insurance.policy.Master.Test.case.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4085976/Insurance.policy.Master.Test.case.xlsx)

TEST RESULT1: [Insurance Policy Master_Test Result1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4085977/Insurance.Policy.Master_Test.Result1.docx)

TESTCASE 2: [Insurance Policy Master_TestCase2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4039010/Insurance.Policy.Master_TestCase2.xlsx)

TEST RESULT 2: [Insurance Policy Master_Test Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4039013/Insurance.Policy.Master_Test.Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

EDK Screen completed. User accepeted to do the transactions with this screen.

Kindly close this ticket from your side. All the Deliverables are attached.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Being accepted by user, this ticket is getting closed

**Comment by raju-kurup** [comment]
Opening balance to be added

**Comment by srinivasanbaskaran** [comment]
Sir,

Updated PFS attached. Kindly review the PFS & Allocate to Development 

PFS: 
[01_JCIPL_Insurance.Policy.Master_v.1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4389742/01_JCIPL_Insurance.Policy.Master_v.1.2.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please add column of "Opening balance" in the UDS Screen, data will be manually entered by the user itself by replacing the column "Max Bal Reqd"

**Comment by karthikeyanamitysoft** [comment]
Hi
1. EDK change : Need to change the "max bal Reqd" to "Opening Balance"
2. Back end change: Remove all logic for Max bal Reqd
3. User only give value for opening balance so just save the value in BE table.

REgards,
Karthi

**Comment by badamnarendra028** [comment]
patnersandbox not wrking

**Comment by raju-kurup** [comment]
Now the partnersandbox server is working

**Comment by karthikeyanamitysoft** [comment]
Dear Badham,

kindly mention the Deliverables Rtrack id.
Regards,
karthi

**Comment by badamnarendra028** [comment]
completed kindly check opening balance in replace of max balance

**Comment by srinivasanbaskaran** [comment]
Manivel, 

Kindly start the Testing 1 & Prepare the Testing documents 

Regards,
Srinivasan Baskaran

**Comment by Manimahat** [comment]
@raju-kurup Sir,

Kindly Review the Updated PFS with Test Data & Allocated to Developers.

1. The Opening Balance amount Should Reflect  in the Total Enhancement Amount.

**Condition 1**: If we add the Enhancement Amount it will have added in the Total Enhancement Amount 

**Condition 2** :  row needs to be delete, users should be select the row and click delete button, that row should be remove from that table and value has been reduced from Total enhancement amount.

Updated PFS : [01_JCIPL_Insurance.Policy.Master_v.1.3.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4445596/01_JCIPL_Insurance.Policy.Master_v.1.3.xlsx)

Test Data : [Test data for Insurance Policy Master.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4445601/Test.data.for.Insurance.Policy.Master.xlsx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS of Insurance Policy Master. Kindly Review & Proceed to the Development.

PFS: 
[01_JCIPL_Insurance.Policy.Master_v.1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4455675/01_JCIPL_Insurance.Policy.Master_v.1.4.xlsx)

REgards,
Srinivasan.B

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As discussed with srini, please do the correction for "Total Enchanment Amount" = Opening balance + Enchancement Amount (sum all the rows of this column"

**Comment by badamnarendra028** [comment]
Total Enchanment Amount" = Opening balance + Enchancement Amount
change have been completed kindly check

**Comment by srinivasanbaskaran** [comment]
Badam,

Kindly attach the Testing Result of the development

**Comment by badamnarendra028** [comment]
![insurance](https://user-images.githubusercontent.com/46923845/79188688-5dcc5b00-7e3d-11ea-8c50-224aa352f83c.JPG)

**Comment by badamnarendra028** [comment]
attached check

**Comment by srinivasanbaskaran** [comment]
Sir,

Please check the below attached word document for your referecnes

DOC: 
[Insurance Policy Master_Testing Error.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4473522/Insurance.Policy.Master_Testing.Error.docx)

As per this only we want that screen

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please do the correction, we will explain this to you. Issue is when we create only opening balance it is not updating in the "Total Enchancement Amount".  Badam has done this so we will explain this to him

**Comment by Narendiranath** [comment]
Hi Srini,

                   Changes are done.  I attach the test data also. Kindly check.
[Insurance_Policy_Masters.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4485754/Insurance_Policy_Masters.xlsx)

**Comment by srinivasanbaskaran** [comment]
Team,

Testing 1 Completed. 

Testcase 1: [Insurance Policy Master_TestCase2_v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4498057/Insurance.Policy.Master_TestCase2_v1.1.xlsx)

Test Result 1: [Insurance Policy Master - Test Result 1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4498058/Insurance.Policy.Master.-.Test.Result.1.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start  Testing 2 & Prepare Testing Documents

**Comment by srinivasanbaskaran** [comment]
@raju-kurup sir,

I have Provided different amount , it added in the total enhancement amount column.  If I provide same amount in the Enhancement tab, it has vanished. please refer the below screen shot for your reference. Kinldy allocate this ticket to developers.

![image](https://user-images.githubusercontent.com/46194039/79864282-d52e5b80-83f6-11ea-8899-4bba62b49ace.png)

Regards,
Manivel A

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : As discussed please do the correction

**Comment by Narendiranath** [comment]
Hi Manivel,

                Changes are done. Kindly check.

**Comment by srinivasanbaskaran** [comment]
Hi Srinivasan,

Testing 1 Completed. Kinldy start the Testing 2 process.

Test Case 1 : [Insurance Policy Master.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4536214/Insurance.Policy.Master.xlsx)

Test Result : [Insurance Policy Master Result.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4536215/Insurance.Policy.Master.Result.docx)

Regards,
Manivel A

**Comment by srinivasanbaskaran** [comment]
Team,

Insurance Policy Master testing2 completed. 

TESTCASE2 : [Insurance Policy Master_TestCase2_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4545226/Insurance.Policy.Master_TestCase2_v2.xlsx)

TEST RESULT2 : [Insurance Policy Master_Test Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4545229/Insurance.Policy.Master_Test.Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Naren,

Kindly update the Latest Deliverables ASAP

**Comment by Narendiranath** [comment]
Hi Srini,

Please find the updated deliverables.
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4549853/Deliverable.zip)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Insurance Policy Master Testing has been completed. Herewith I have attached the Testing documents for future references. 

PFS: 
[01_JCIPL_Insurance.Policy.Master_v.1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4558355/01_JCIPL_Insurance.Policy.Master_v.1.4.xlsx)

DELIVERABLES: [Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4558357/Deliverable.zip)

TESTCASE1: [Insurance.Policy.Master_Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4558361/Insurance.Policy.Master_Testcase1.xlsx)

TEST RESULT1: [Insurance.Policy.Master.Result1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4558363/Insurance.Policy.Master.Result1.docx)

TESTCASE2: [Insurance.Policy.Master_TestCase2_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4558364/Insurance.Policy.Master_TestCase2_v2.xlsx)

TEST RESULT2: [Insurance.Policy.Master_Test.Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4558365/Insurance.Policy.Master_Test.Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Team,

PFA of Latest Open Points 

![IMG_20200514_171956867_20200514_171958058](https://user-images.githubusercontent.com/46194039/82201278-bf408780-991d-11ea-9e88-a53d2a045d5d.jpg)

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Please find the updated PFS or Insurance Policy Master 

PFS: 
[01_JCIPL_Insurance.Policy.Master_v.1.5.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4655161/01_JCIPL_Insurance.Policy.Master_v.1.5.xlsx)

**Comment by raju-kurup** [comment]
@srinivasanbaskaran : As discussed, there is no changes in this EDK Screen.

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

Insurance Policy Master Testing has been completed. Herewith I have attached the Testing documents for future references. 

PFS: 
[01_JCIPL_Insurance.Policy.Master_v.1.4.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4558355/01_JCIPL_Insurance.Policy.Master_v.1.4.xlsx)

DELIVERABLES: [Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4558357/Deliverable.zip)

TESTCASE1: [Insurance.Policy.Master_Testcase1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4558361/Insurance.Policy.Master_Testcase1.xlsx)

TEST RESULT1: [Insurance.Policy.Master.Result1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4558363/Insurance.Policy.Master.Result1.docx)

TESTCASE2: [Insurance.Policy.Master_TestCase2_v2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4558364/Insurance.Policy.Master_TestCase2_v2.xlsx)

TEST RESULT2: [Insurance.Policy.Master_Test.Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/4558365/Insurance.Policy.Master_Test.Result2.docx)

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Raju Sir,

EDK working as per the User Requirement. '
Kindly proceed further to close this ticket

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested. Delivered to customer and accepted.  So closing this issue

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please deploy this in live server.

**Comment by karthikeyanamitysoft** [comment]
Dear Gayatri ,

Kindy deploy the latest deliverables into live server.

Regards,
Karthi

**Comment by Manimahat** [comment]
@mohanaamity,

Kindly hold the Deployment Process due to face some issue in the EDK master.

Regards,
Manivel A

**Comment by Manimahat** [comment]
@Narendiranath ,

As Discussed through Skype, Total Enhancement is not Working for Newly Created Serial No. & policy Type. Kindly check & close this issue on high priority.

Regards,
Manivel A

**Comment by Narendiranath** [comment]
Hi Manivel,

             Changes are done. Kindly check. PFA Latest deliverable.
[Deliverable.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/5830311/Deliverable.zip)

**Comment by Manimahat** [comment]
@sujin1708 ,

Testing 1 completed. Kindly start the Testing 2 process.

Test Case 1: [Insurance.Policy.Master.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5832959/Insurance.Policy.Master.xlsx)
Test Result: [Insurance.Policy.Master.Result.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5832962/Insurance.Policy.Master.Result.docx)

Regards,
Manivel A

**Comment by sujin1708** [comment]
@AkashGleen kindly do the testing 2

**Comment by AkashGleen** [comment]
Dear Sujin,

Insurance Policy Master Testing 2 Completed.

[Insurance.Policy.Master.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/5864340/Insurance.Policy.Master.xlsx)
[Insurance.Policy.Test.Result.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/5864341/Insurance.Policy.Test.Result.docx)

Regards,
Akash

**Comment by sujin1708** [comment]
@raju-kurup Testing 2 completed ..kindly check and move to next level
Test result : [Insurance.Policy.Test.Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/6252095/Insurance.Policy.Test.Result2.docx)
Deliverables : [Deliverable (3).zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6252097/Deliverable.3.zip)
Test Case : [Insurance.Policy.Test.Result2.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/6252099/Insurance.Policy.Test.Result2.docx)

**Comment by raju-kurup** [comment]
Deployed in Live Server, so closing this ticket

**Comment by srinivasanbaskaran** [comment]
Naren, 

Kindly update the latest deliverables ( Live Deliverables ) for cosing this ticket

Regards,
Srinivasan Baskaran

**Comment by Narendiranath** [comment]
Srinivasan,

          Already attached Latest Deliverables only. Please refer that.

Regards,
Naren
