### ISSUE TITLE
PPD : Report Production Stage Based Car No Based Fire no logic Testing in UAT

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#69]
Dear Karthick,

Kindly create the logic as discussed on 10-09-2019 car no based fired no logic
[FireNo Logic.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3599187/FireNo.Logic.xlsx)

regards,
Sujin.M

**Comment by karthikeyanamitysoft** [comment]
Dear Sujin,

Please provide more detail.

Regards,
Karthi

**Comment by sujin1708** [comment]
@ raju sir fire no logic trigger file attached ..kindly check

[Fire No Trigger Logic.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3730289/Fire.No.Trigger.Logic.xlsx)

**Comment by sujin1708** [comment]
@karthick please start the trigger for fire no logic
 [Car No Logic - Jyoti.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3800371/Car.No.Logic.-.Jyoti.xlsx)

**Comment by sujin1708** [comment]
@raju-kurup please find the attached fire no trigger PFS for your refernce..kindly review
PFS : [Car Base Fire No Trigger.PFS.v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3804652/Car.Base.Fire.No.Trigger.PFS.v1.0.xlsx)

**Comment by sujin1708** [comment]
@Anand as Discuss kindly change PFS input ..please refer the PFS
[PFS.Car.wise.infurnance.report_V1.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3814433/PFS.Car.wise.infurnance.report_V1.2.xlsx)

**Comment by sujin1708** [comment]
@raju sir rule logic has been applied ...kindly move to next level
PFS : [Car Base Fire No Trigger.PFS.v1.1.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3827020/Car.Base.Fire.No.Trigger.PFS.v1.1.xlsx)

**Comment by raju-kurup** [comment]
Karthi - Please start the development

**Comment by sujin1708** [comment]
logic to be change by customer...consider as a open point

**Comment by sujin1708** [comment]
please find the revised PFS for your refernce
PFS : [Car.Base.Fire.No.Trigger.PFS.v1.2 (2).xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4123252/Car.Base.Fire.No.Trigger.PFS.v1.2.2.xlsx)

**Comment by karthikeyanamitysoft** [comment]
completed

**Comment by sujin1708** [comment]
@basha123456 test the fire no logic and prepare document

**Comment by srinivasanbaskaran** [comment]
Basha, 

Kindly update the status of this Report

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Basha,

Kindly update the Status of this report

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
test the fire no logic with multiple division wise

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Testing 2 completed..kindly check & m
[Car.Base.Fire.No.Trigger.PFS.v1.2.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4275052/Car.Base.Fire.No.Trigger.PFS.v1.2.2.xlsx)
ove.

**Comment by srinivasanbaskaran** [comment]
Sujin / Basha,

Kindly update the Testing Document as per our format. After that only we need to close this report

Regards,
Srinivasan Baskaran

**Comment by sujin1708** [comment]
@basha123456 prepare test case

**Comment by basha123456** [comment]
@srinivasanbaskaran 

Test Case: [Test.Case.-.Report Production Stage Based Car No Based Fire no logic Testing in UAT v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4355414/Test.Case.-.Report.Production.Stage.Based.Car.No.Based.Fire.no.logic.Testing.in.UAT.v1.0.xlsx)

**Comment by srinivasanbaskaran** [comment]
Karthi,

Kindly update the Latest Deliverables ASAP

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Sir,

This report testing has been completed. Herewith I have attached the Testing documents for future references.

PFS: [Car.Base.Fire.No.Trigger.PFS_v1.2.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356665/Car.Base.Fire.No.Trigger.PFS_v1.2.2.xlsx)

DELIVERABLES:

TESTCASE1 & TEST RESULT1: [Car.Base.Fire.No.Trigger_v1.2.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356669/Car.Base.Fire.No.Trigger_v1.2.2.xlsx)

TESTCASE2 & TEST RESULT2: [Uploading Test.Case.-.Report.Production.Stage.Based.Car.No.Based.Fire.no.logic.Testing.in.UAT.v1.0.xlsx…]()

Regards,
Srinivasan Baskaran

**Comment by karthikeyanamitysoft** [comment]
No deliverables available for this

**Comment by karthikeyanamitysoft** [comment]
[pajsbrjsbr_a_jsbr_g_gs.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4358020/pajsbrjsbr_a_jsbr_g_gs.zip)

**Comment by srinivasanbaskaran** [comment]
Sir,

This report testing has been completed. Herewith I have attached the Testing documents for future references.

PFS: [Car.Base.Fire.No.Trigger.PFS_v1.2.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356665/Car.Base.Fire.No.Trigger.PFS_v1.2.2.xlsx)

DELIVERABLES: [pajsbrjsbr_a_jsbr_g_gs.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/4358075/pajsbrjsbr_a_jsbr_g_gs.zip)

TESTCASE1 & TEST RESULT1: [Car.Base.Fire.No.Trigger_v1.2.2.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356669/Car.Base.Fire.No.Trigger_v1.2.2.xlsx)

TESTCASE2 & TEST RESULT2: 
[Test.Case.-.Report.Production.Stage.Based.Car.No.Based.Fire.no.logic.Testing.in.UAT.v1.0.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/4356673/Test.Case.-.Report.Production.Stage.Based.Car.No.Based.Fire.no.logic.Testing.in.UAT.v1.0.xlsx)

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Development completed and tested, so closing this issue

**Comment by srinivasanbaskaran** [comment]
WCA

**Comment by sujin1708** [comment]
@karthikeyanamitysoft kindly attach the latest deliverables

**Comment by karthikeyanamitysoft** [comment]
![image](https://user-images.githubusercontent.com/40713407/123633130-6fc5ce00-d836-11eb-99c0-d62edbb4b45d.png)

**Comment by sujin1708** [comment]
@raju-kurup Document Shared to customer.kindly close the ticket

**Comment by raju-kurup** [comment]
Document shared, so closing this ticket
