### ISSUE TITLE
IMP-Sales & Distribution Business Process Study Discussion

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#7]
Sales and Shipping process study

**Comment by maheshwaran-m** [comment]
Dear sir,

Sales and shipping Business process study discussion in in progress.

Thanks and Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Dear Team,

Sales and Shipping Business process study has been completed.

**MOM:**


MOM : [01_JCIPL_MOM_SAL&SHIP_DOM_24.06.2019_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3337935/01_JCIPL_MOM_SAL.SHIP_DOM_24.06.2019_V.1.0.docx)
MOM : [01_JCIPL_MOM_SAL&SHIP_DOM_26.06.2019_V 1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3337936/01_JCIPL_MOM_SAL.SHIP_DOM_26.06.2019_V.1.1.docx)
MOM : [02_JCIPL_MOM_SAL&SHIP_EXP_24.06.2019_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3337941/02_JCIPL_MOM_SAL.SHIP_EXP_24.06.2019_V.1.0.docx)
MOM : [03_JCIPL_MOM_SAL&SHIP_EXP_25.06.2019_V 1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3337944/03_JCIPL_MOM_SAL.SHIP_EXP_25.06.2019_V.1.1.docx)
MOM : [04_JCIPL_MOM_SAL&SHIP_GmbH_25.06.2019_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3337945/04_JCIPL_MOM_SAL.SHIP_GmbH_25.06.2019_V.1.0.docx)

Regatds,
M.Maheshwaran
