### ISSUE TITLE
GEN - Multiple OU configuration

### ISSUE THREAD

**Issue by Prabakaran92** [astpl1998/Jyoti-Ceramic#70]
Dear Team,

Need to configure Multiple OU for Training Purpose.

Thanks and Regards,
Prabakaran. A

**Comment by Prabakaran92** [comment]
@Dhanwandher @basha123456 
1.Need to Tax configuration on Unitech OU and GmbH OU.
2.Need to Fixed asset setup to Ziecon ,Unitech OU.

Regards, 
Prabakaran A

**Comment by Prabakaran92** [comment]
Unitech OU
1.PR-GR(Movement) completed.
2.PO-GR(Movement) completed.
3.Capital Purchase completed.

**Comment by Prabakaran92** [comment]
@Dhanwandher @basha123456 

Plz Do Needful OU Configuration for Ziecon,Unitech,GmbH.

1.Financial related setup.
2.Cost center setup.
3.AC/CC Usage 
4.Invoice related setup.
5.Invoice reverse setup.

Regards,
Prabakaran A

**Comment by sujin1708** [comment]
@raju-kurup kindly create the WIP account for Unitech

**Comment by basha123456** [comment]
PFA the entire configuration for Tool Management.
[List of activities Project Management.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3993696/List.of.activities.Project.Management.xlsx)

**Comment by Prabakaran92** [comment]
Test server Configuration completed. 

Hence this ticket is closed
