### ISSUE TITLE
IMP - Test server readiness for Training - Tools Management

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#78]
IMP - Test server readiness for Training -   Tools Management
--

**Comment by basha123456** [comment]
Dear Raju Sir,

PFA of the scenarios of all modules in Project management.

[List of activities Project Management.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3938326/List.of.activities.Project.Management.xlsx)

Regrads,
Basha

**Comment by raju-kurup** [comment]
OK. Proceed further
