### ISSUE TITLE
IMP - Training and UAT - Purchase 

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#79]
IMP - Training and UAT - Purchase
--

**Comment by maheshwaran-m** [comment]
Dear Team,

As Per the schedule Purchase and Subcontracting Training has been completed, UAT has been In progress.

@raju-kurup sir, Need Label for **Open_Gen_Completed** 

Regards,
M.Maheshewaran

**Comment by maheshwaran-m** [comment]
Dear Team,

Training and UAT completed. Sign off sheet still not provide.

Regards,
M.Maheshwaran.

**Comment by srinivasanbaskaran** [comment]
Dear Sir,

Training has been completed from 04-11-2019 to 07-11-2019 to Purchase Users.

UAT completed by the Users. But they need below Type of Transactions once again as a training

1. Blanket purchase 
2. Subcontract
3. Adhoc Purchase 

**NOTE: We are planning for provide those Transactions by 10-01-2020**

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Training completed, so closing this ticket
