### ISSUE TITLE
IMP-SDD-Production Process study discussion

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#8]
Production process study

**Comment by Duraisingam-G** [comment]
Process Production Process study  has been completed for below department
1. Press shop
2. Sand
3. Igniter
4. Extrusion
5. Dental
6. Coating
7. Uni-tech

**Comment by Duraisingam-G** [comment]
Report discussion also completed for all dept, but in press shot 3 reports pending to be clarified from Jyoti team.

**Comment by raju-kurup** [comment]
Process Study completed
