### ISSUE TITLE
IMP - Training and UAT - Inventory

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#80]
IMP - Training and UAT - Inventory
--

**Comment by maheshwaran-m** [comment]
Dear Team,

Training and UAT completed. Sign off sheet still not provide.

Regards,
M.Maheshwaran.

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Training has been completed from  08-11-2019 to 13-11-2019 for Inventory Users.

Still Sign Off is pending.

Kindly proceed further on this ticket.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Training completed, so closing this ticket
