### ISSUE TITLE
IMP - Training and UAT - Sales & Shipping

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#81]
IMP - Training and UAT - Sales & Shipping
--

**Comment by maheshwaran-m** [comment]
Dear Team,

Training completed and UAT In progress. Sign off sheet still not provide.

Regards,
M.Maheshwaran.

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Training has been completed from 06-12-2019 to 12-12-2019.

User doing UAT. User awiting for Reports, then only they aill provide the Sign off.

Kindly proceed further on this ticket.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,

For GmbH User Training In-Progress. Reports are shown to the User.

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Dear Team,

For GmbH User Training has been completed on 22-01-2020.

Regards,
Srinivasan Baskaran
