### ISSUE TITLE
IMP - Training and UAT - Production

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#82]
IMP - Training and UAT - Production
--

**Comment by sujin1708** [comment]
Following activity UAT training has been completed
1. Time   Table
2. Maintain   Calendar
3. Maintain User   Defined Category Values
4. Select Usage   for Template
5. Maintain   Reason Code
6. Create   Physical Element
7. Create Process   Element
8. Create Process   Element - Physical Element Association
9. Create Formula
10. Create Master   Recipe
11. Associate Lot   Templates
12. Maintain   Formula Access Rights
13. Create   Production Order - Multiple Item
Regards,
Sujin. M

**Comment by sujin1708** [comment]
follow the topic uat training has been completed on 16.12.2019 to 24.12.2019
14. Report   Production - Stage Based
15 .Generate QC Clearance Request
16. Report   Activities & Resources
17. Report consumption
18. Material   Movement
