### ISSUE TITLE
IMP - Training and UAT - EAM

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#84]
IMP - Training and UAT - EAM
--

**Comment by maheshwaran-m** [comment]
Training completed UAT in progress, sign off still not provide.

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Training has been completed from 29-11-2019 to 04-12-2019 to EAM users.

User doing UAT.

Kindly proceed further on this ticket.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Training completed, so closing this ticket
