### ISSUE TITLE
IMP - Training and UAT - Tools Management

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#85]
IMP - Training and UAT - Tools Management
--

**Comment by basha123456** [comment]
UAT & Training schedule for Project management.


UAT & Training schedule : [04_JCIPL_Training_and_UAT PLAN.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3638423/04_JCIPL_Training_and_UAT.PLAN.xlsx)

**Comment by basha123456** [comment]
PFA for the training & UAT dates for Tools Management

[09_JCIPL_Training_and_UAT PLAN_V 1.8.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3987258/09_JCIPL_Training_and_UAT.PLAN_V.1.8.xlsx)

**Comment by basha123456** [comment]
PFA for the training & UAT dates for Tool Management
[09_JCIPL_Training_and_UAT PLAN_V 1.8.xlsx](https://github.com/astpl1998/Jyoti-Ceramic/files/3993688/09_JCIPL_Training_and_UAT.PLAN_V.1.8.xlsx)

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Training has been completed on 19-12-2019 to the Tool Room users.

User doing UAT.

Kindly proceed further on this ticket.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Training completed, so closing the ticket
