### ISSUE TITLE
IMP - Rtrack (ITS -Incidence Tracking System) Training

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#87]
IMP - Rtrack (ITS   -Incidence Tracking System) Training
--

**Comment by srinivasanbaskaran** [comment]
Dear Team,

Admin & Rtrack Training has been completed on 05-01-2020 to Sunil

Kindly proceed further on this ticket.

Regards,
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
Training provided, so closing this ticket
