### ISSUE TITLE
IMP-Maintenance Management Process Study Discussion

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#9]
Maintenance Management

**Comment by maheshwaran-m** [comment]
Dear Team,

Maintenance Business study process is completed.

MOM : [02_JCIPL_MOM_EAM_03.07.2019_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3356166/02_JCIPL_MOM_EAM_03.07.2019_V.1.0.docx)
MOM : [01_JCIPL_MOM_EAM_28.06.2019_V 1.0.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3356167/01_JCIPL_MOM_EAM_28.06.2019_V.1.0.docx)
 
Regards,
M.Maheshwaran

**Comment by maheshwaran-m** [comment]
Dear Team,

Reviewed Updated MOM for Maintenance V 1.1

MOM : [01_JCIPL_MOM_EAM_28.06.2019_V 1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3375718/01_JCIPL_MOM_EAM_28.06.2019_V.1.1.docx)
MOM : [02_JCIPL_MOM_EAM_03.07.2019_V 1.1.docx](https://github.com/astpl1998/Jyoti-Ceramic/files/3375719/02_JCIPL_MOM_EAM_03.07.2019_V.1.1.docx)

Regrads,
M.Maheshwaran
