### ISSUE TITLE
IMP - Master Data Collection - GmbH

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Jyoti-Ceramic#94]
Master   Data Collection
--
Please furnish the details of   master data

**Comment by srinivasanbaskaran** [comment]
Manivel,

Kindly start the Validation of Inventory & PICC module

NOTE: Kindly collect the Data from me & Confirm the same with Mr. Sunil

Regards
Srinivasan Baskaran

**Comment by raju-kurup** [comment]
[GMBH Live Uplaoded File_Jyoti.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6824105/GMBH.Live.Uplaoded.File_Jyoti.zip)

Master Data collected, so closing this ticket.
